### ISSUE TITLE
[Proposal] Remove python 3.6 and add Jax as a core dependancy

### ISSUE THREAD

**Issue by pseudo-rnd-thoughts** [Farama-Foundation/Gymnasium#10]
Python 3.6 is no longer being supported by the python foundation despite critical bugs
As a result, a number of project we rely on not longer provide python 3.6 releases: pytest, mujoco, jax

Therefore, I propose after the v26 release, we remove support for python 3.6.
At the same time, we can add jax as a core dependency for the project that will be used in the updated wrappers and envs

**Comment by gianlucadecola** [comment]
I agree with the proposal :+1:

**Comment by pseudo-rnd-thoughts** [comment]
Python 3.6 has been removed for v0.27 and jumpy has been updated to have jax as an optional dependency so jax will be an optional dependency
