### ISSUE TITLE
[Question] Multitple render modes

### ISSUE THREAD

**Issue by araffin** [Farama-Foundation/Gymnasium#100]
### Question

Hello,

is it possible to enable multiple render modes at the same time? (apparently no, see below)

For instance, if you want to take a look at the env and record a video at the same time.

In gym 0.21 you could do:
```python
# Retrieve the image
image = env.render(mode="rgb_array")
# Show the GUI
env.render(mode="human")
```

but now with gym 0.26+, `render_mode` passed to the constructor can only be a string, no?

**Comment by pseudo-rnd-thoughts** [comment]
Yes you can't do this anymore.
It might be possible to use the `VideoRecord` and `HumanRendering` wrappers together for recording the video and showing the RGB array to users
If it is not possible, I think this is a feature we should add

**Comment by araffin** [comment]
thanks for the swift answer =)

> Yes you can't do this anymore.

was there a particular reason to not allow more than one render mode?

I guess the solution is good enough (although I didn't test it) until the user would like to have a viewer like the one provided by MuJoCo/Pybullet.
