### ISSUE TITLE
[Proposal] Add metadata field to VectorEnv

### ISSUE THREAD

**Issue by TimSchneider42** [Farama-Foundation/Gymnasium#1005]
### Proposal

Hi,

I noticed that `VectorEnv` currently does not have a field `metadata` like `Env` does. Is there a particular reason for this? If not, I propose adding it since, currently, there is no way of specifying, e.g., rendering FPS for `VectorEnv` instances.

Best,
Tim

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Good point, I thought that we did include one, thanks for spotting that
