### ISSUE TITLE
Rendering of CartPoleVectorEnv is broken

### ISSUE THREAD

**Issue by TimSchneider42** [Farama-Foundation/Gymnasium#1007]
### Describe the bug

Hi,

the rendering of `CartPoleVectorEnv` is broken in two places:
1. In line 548, `self.clock` is assigned instead of `self.clocks` 
2. In line 561, `self.state` is used instead of `state`

Because of these two bugs, `CartPoleVectorEnv.render()` throws exceptions. I will create a PR in a moment.

Best,
Tim

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by TimSchneider42** [comment]
Just noticed that I overlooked #872, which addresses this issue already but still needs a pull request. Apologies for the duplication! Should I close this issue in favor of #872?

**Comment by pseudo-rnd-thoughts** [comment]
Thanks, for the issue. My proposal was to actually not contain "human" rendering in the custom vector environment as this is difficult to maintain. 
Rather, we should have a `wrappers.vector.HumanRendering` for which all "human" vector rendering is computed through. 
This still requires rgb array rendering in the vector environment but this feels like a simpler solution for most vector environments.

Thoughts @TimSchneider42 and maybe @Kallinteris-Andreas  or @RedTachyon

**Comment by TimSchneider42** [comment]
I like the idea of solving human rendering with a wrapper. At least in this case, I expect it to be easier to implement and maintain, since the rgb_array image simply gets rendered by pygame.

**Comment by pseudo-rnd-thoughts** [comment]
Agreed. I have been thinking about how to implement the vector human rendering but I haven't come to a satisfactory general solution. 
If you have any idea, I would love to hear them

**Comment by TimSchneider42** [comment]
I think for most environments we could simply render in "rgb_array" mode and then have the wrapper you proposed render all of them side by side in a single window with pygame. For more sophisticated environments, [like this one](https://github.com/NVIDIA-Omniverse/IsaacGymEnvs/blob/main/docs/rl_examples.md), though, there should still be an option for custom rendering solutions, like just showing the simulator interface without having to render RGB images.

In general, I think that human rendering should be detached from RGB rendering in the API. I just wrote a small proposal about that in #1010.

**Comment by RogerJL** [comment]
Can this be closed now?

**Comment by TimSchneider42** [comment]
Yes, it is fixed
