### ISSUE TITLE
How to record video with updated <site> objects?

### ISSUE THREAD

**Issue by nicehiro** [Farama-Foundation/Gymnasium#1016]
### Question

 Hi,

I'm trying to record a video with some goals,

```
<site name="goal" pos="0. 0.74 0.05" size="0.02" rgba="0 0.8 0 0.8"/>
```

I updated the position of the goal, it worked when I set `render_mode="human"`. but it didn't work for `rgb_array` when recording.
To reproduce,

```
import gymnasium as gym
import numpy as np
import mujoco

from metaworld.envs import (
    ALL_V2_ENVIRONMENTS_GOAL_OBSERVABLE,
)


env_cls = ALL_V2_ENVIRONMENTS_GOAL_OBSERVABLE.get("drawer-open-v2-goal-observable")
env = env_cls(render_mode="human")

env = gym.wrappers.RecordVideo(
    env, video_folder="results/videos", video_length=50, name_prefix="test"
)
obs, _ = env.reset()  # Reset environment
t = 0

while True:
    t += 1

    # update goal position
    _id = mujoco.mj_name2id(env.model, mujoco.mjtObj.mjOBJ_SITE, "goal")
    env.data.site_xpos[_id] = np.array((0.5, 0.5, 0.1))

    env.render()
    a = env.action_space.sample()
    obs, reward, terminal, truncated, info = env.step(a)
    print(t)

    if terminal or truncated:
        obs, _ = env.reset()
        t = 0
```

How to record the video with updated `<site>` objects? Thanks!

**Comment by Kallinteris-Andreas** [comment]
rendering for mujoco 3 does not work with gymnasium 0.29, either upgrade to gymnasium==1.0.0a1 or downgrade mujoco

**Comment by Kallinteris-Andreas** [comment]
What error do you get and does it work without recording video?

**Comment by nicehiro** [comment]
Thanks for your reply.

No error occured. It works well without recording video.

Rendering with human, the green dot position is updated.
![Screenshot 2024-04-15 171440](https://github.com/Farama-Foundation/Gymnasium/assets/17773634/2114e0ba-e0eb-4a2e-8f35-caf0fbd45387)

Rendering with rgb_array, the green dot position is not updated.
![Screenshot 2024-04-15 171540](https://github.com/Farama-Foundation/Gymnasium/assets/17773634/73a39f8d-50b6-4c5d-99bf-e058e5a541e8)

**Comment by Kallinteris-Andreas** [comment]
1)Have you verified which is the correct version?
2) Does this also happen when you update the `qpos`

**Comment by nicehiro** [comment]
1) Yes. I verified rendering with "human" is the correct version.
2) No. The recorded video updated when I updated the `qpos`.

Rendering with `human`, `qpos` and `site_xpos` all updated correctly.
![image](https://github.com/Farama-Foundation/Gymnasium/assets/17773634/ca16a5ac-eb71-4248-b322-b2653ced22fb)

Rendering with `rgb_array`, `qpos` correctly updated, but `site_xpos` didn't updated.
![image](https://github.com/Farama-Foundation/Gymnasium/assets/17773634/912c4cf7-13af-419e-ab86-526fa1ab3fb3)

**Comment by pseudo-rnd-thoughts** [comment]
@Kallinteris-Andreas or @nicehiro Can we test if this is an issue with Metaworld, Gymnasium mujoco rendering or mujoco itself?

**Comment by nicehiro** [comment]
Finally I figure out it was the record video wrapper didn't capture the updated site frame.
 
I need to update `site` position inside the `env.step` function and the record video wrapper worked.

**Comment by pseudo-rnd-thoughts** [comment]
Ahh that makes sense now, yeah, `VideoRecorder` will capture the frame during `reset` and `step` not `render`. Meaning that the changes must happen "within" these functions before the functions reach video recorder

An alternative approach that is more complex is using `record_video` function where a sequence of rendering must be passed to the function
