### ISSUE TITLE
[Bug Report] wrappers.vector.RecordEpisodeStatistics computes episode length incorrectly

### ISSUE THREAD

**Issue by TimSchneider42** [Farama-Foundation/Gymnasium#1017]
### Describe the bug

Hi,

`wrappers.vector.RecordEpisodeStatistics` computes the episode lengths incorrectly. It still adheres to the old API, in which the final observations of episodes were never returned. This causes the wrapper to be off by one in all episodes except for the first one.

For example in this case:
```python
import gymnasium as gym

env = gym.wrappers.vector.RecordEpisodeStatistics(gym.make_vec(id="CartPole-v1", num_envs=1, max_episode_steps=3))
env.reset(seed=0)

for i in range(15):
    print(f"Step {i}")
    *_, info = env.step(env.action_space.sample())
    if "episode" in info:
        print(f"Length: {info['episode']['l'][0]}")
```

`max_episode_steps` is set to 3, so we would expect all episodes to be exactly 3 steps long (it is not possible to end the episode faster than that in CartPole-v1). However, the output of this script is
```
Step 0
Step 1
Step 2
Length: 3.0
Step 3
Step 4
Step 5
Step 6
Length: 4.0
Step 7
Step 8
Step 9
Step 10
Length: 4.0
Step 11
Step 12
Step 13
Step 14
Length: 4.0
```

It is easy to get confused here, as the first step of each episode is not a real step but the output of the reset function and, thus, does not count as a step.

Best,
Tim

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Very good point, thanks for finding this and for the PR, I'll review it now
