### ISSUE TITLE
[Question] Reward calculation in HalfCheetah environment

### ISSUE THREAD

**Issue by EmiliyanGospodinov** [Farama-Foundation/Gymnasium#1021]
### Question

The reward in HalfCheetah environment is the forward velocity. It is calculated using finite differences of the positions according to: https://github.com/Farama-Foundation/Gymnasium/blob/94a7909042e846c496bcf54f375a5d0963da2b31/gymnasium/envs/mujoco/half_cheetah_v5.py#L229.

**My question** is why do you calculate the velocity like that when we have already the velocity information, e.g., from self.data.qvel[0].  My intuition is that the second way might be more accurate (e.g., due to numerical precisions we might make more errors using finite differences), can you please confirm if this might be true? 
**I need this information**, because I'm currently working on creating multiple HalfCheetah versions of the environment for non-stationary reinforcement learning.

This is the code for comparison of the two above-mentioned velocity calculation types:

```
x_position_before = self.data.qpos[0]
x_vel_before = self.data.qvel[0]
self.do_simulation(action, self.frame_skip)
x_vel_after = self.data.qvel[0]
x_position_after = self.data.qpos[0]
x_finite_diff_velocity = (x_position_after - x_position_before) / self.dt
```

and a few print outputs: 

```
X_FINITE_DIFF_VELOCITY: -0.27844318503837673, X_VELOCITY_Before: -0.14655024986970253, X_VELOCITY_After: -0.3722569079481009
X_FINITE_DIFF_VELOCITY: -0.43189010320381555, X_VELOCITY_Before: -0.3722569079481009, X_VELOCITY_After: -0.43215418807794126
X_FINITE_DIFF_VELOCITY: -0.41981896928124135, X_VELOCITY_Before: -0.43215418807794126, X_VELOCITY_After: -0.36869545997831343
X_FINITE_DIFF_VELOCITY: -0.45157499115245925, X_VELOCITY_Before: -0.36869545997831343, X_VELOCITY_After: -0.47635906396144095
X_FINITE_DIFF_VELOCITY: -0.17437418836084073, X_VELOCITY_Before: -0.47635906396144095, X_VELOCITY_After: -0.12613146629369046
X_FINITE_DIFF_VELOCITY: -0.27943251249703094, X_VELOCITY_Before: -0.12613146629369046, X_VELOCITY_After: -0.3595211671191295
X_FINITE_DIFF_VELOCITY: 0.07323414068928363, X_VELOCITY_Before: -0.3595211671191295, X_VELOCITY_After: 0.28493006496506756
X_FINITE_DIFF_VELOCITY: 0.242224738577905, X_VELOCITY_Before: 0.28493006496506756, X_VELOCITY_After: 0.12877526599448122
X_FINITE_DIFF_VELOCITY: -0.7683600366076095, X_VELOCITY_Before: 0.12877526599448122, X_VELOCITY_After: -1.2581178585834096
X_FINITE_DIFF_VELOCITY: -1.096763321771295, X_VELOCITY_Before: -1.2581178585834096, X_VELOCITY_After: -0.900686330882273
X_FINITE_DIFF_VELOCITY: 0.08276173479650761, X_VELOCITY_Before: -0.900686330882273, X_VELOCITY_After: 0.5090917084895409
X_FINITE_DIFF_VELOCITY: 0.37271081155531127, X_VELOCITY_Before: 0.5090917084895409, X_VELOCITY_After: -0.053138290354835194
X_FINITE_DIFF_VELOCITY: -0.06285459359084977, X_VELOCITY_Before: -0.053138290354835194, X_VELOCITY_After: 0.020683708118854255
```

When I print the two ways of velocity calculations, they are always different, probably due to when exactly I take the velocity information from self.data.qvel[0]. 

Any thoughts on this are appreciated! Thank you in advance!

**Comment by Kallinteris-Andreas** [comment]
The existing implementation uses the actual displacement of the robot In order to calculate the reward forward

Your suggestion approximates displacement by assuming that the velocity would be identical throughout the simulation of the environment step

**Comment by EmiliyanGospodinov** [comment]
@Kallinteris-Andreas Thanks for the quick response. 

Unfortunately, I don't think I understand. So, why when I take the velocity information directly, e.g. immediately after the simulation step using self.data.qvel[0], means that I assume the velocity is constant during the simulation step? 

You are probably right because this will explain why I get different velocity values(e.g. X_FINITE_DIFF_VELOCITY != X_VELOCITY_AFTER), but I would expect to receive similar velocity values when I just take the velocity information immediately after the simulation step? 

Thanks in advance!

**Comment by EmiliyanGospodinov** [comment]
Thanks, I will directly start reading the docu more extensively.
