### ISSUE TITLE
[Bug Report] Promote `PYGAME_HIDE_SUPPORT_PROMPT` to suppress pygame startup message

### ISSUE THREAD

**Issue by chnyutao** [Farama-Foundation/Gymnasium#1024]
### Describe the bug

I am using `gymnasium` with `minigrid`, which relies on `pygame`. When importing, `pygame` will print this message which is sometimes undesirable:
```sh
> python -c 'import gymnasium'
pygame 2.5.2 (SDL 2.28.3, Python 3.10.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
```
I can see that `gymnasium` actually tries to suppress this message https://github.com/Farama-Foundation/Gymnasium/blob/43ce95b1419fb0bdafeb48bd089e1c870482ebe4/gymnasium/__init__.py#L69
However, this is not currently working. I believe we need to promote this environment variable at least above `envs.__init__` https://github.com/Farama-Foundation/Gymnasium/blob/43ce95b1419fb0bdafeb48bd089e1c870482ebe4/gymnasium/__init__.py#L23-L24

### Code example

```shell
> pip install gymnasium==0.29.1 minigrid==2.3.1
...
> python -c 'import gymnasium'
pygame 2.5.2 (SDL 2.28.3, Python 3.10.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
```

### System info

```
python=3.10.0
gymnasium=0.29.1
minigird=2.3.1
```

### Additional context

This should be an easy fix imo. I am happy to submit a PR if you like :)

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Could this be added to minigrid separately?

**Comment by chnyutao** [comment]
Well I think it could. Should I move this ticket to minigrid repo instead?
