### ISSUE TITLE
Can Gymnasium be used on the aarch64 architecture?

### ISSUE THREAD

**Issue by zhoujingyu13687306871** [Farama-Foundation/Gymnasium#1025]
### Question

I ran pip install "gymnasium[all]" on an aarch64 computer, and the installation seemed to go smoothly. However, when I ran pip list to check the installed modules, I noticed that the result seemed off.
`(gymnasium0.29.1_py39) [scx6001@paraai-n32-h-01-ccs-master-1 gym]$ pip list
Package    Version
---------- -------
gymnasium  0.0.1
pip        24.0
setuptools 69.5.1
wheel      0.43.0
`
In contrast, I get a completely different result when running the same command on an x86 machine. Does this mean that Gymnasium currently does not support the aarch64 architecture? Is there a solution to this issue?
`(gymnasium0.29.1_py39) [scz0002@ln01 ~]$ pip list
Package                  Version
------------------------ -----------
absl-py                  2.1.0
ale-py                   0.8.1
box2d-py                 2.3.5
certifi                  2024.2.2
cffi                     1.16.0
charset-normalizer       3.3.2
cloudpickle              3.0.0
contourpy                1.2.1
cycler                   0.12.1
Cython                   0.29.37
decorator                4.4.2
etils                    1.5.2
Farama-Notifications     0.0.4
fasteners                0.19
filelock                 3.13.4
fonttools                4.51.0
fsspec                   2024.3.1
glfw                     2.7.0
gymnasium                0.29.1
idna                     3.7
imageio                  2.34.0
imageio-ffmpeg           0.4.9
importlib_metadata       7.1.0
importlib_resources      6.4.0
jax                      0.4.26
jaxlib                   0.4.26
Jinja2                   3.1.3
kiwisolver               1.4.5
lz4                      4.3.3
MarkupSafe               2.1.5
matplotlib               3.8.4
ml-dtypes                0.4.0
moviepy                  1.0.3
mpmath                   1.3.0
mujoco                   3.1.4
mujoco-py                2.1.2.14
networkx                 3.2.1
numpy                    1.26.4
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.19.3
nvidia-nvjitlink-cu12    12.4.127
nvidia-nvtx-cu12         12.1.105
opencv-python            4.9.0.80
opt-einsum               3.3.0
packaging                24.0
pillow                   10.3.0
pip                      23.3.1
proglog                  0.1.10
pycparser                2.22
pygame                   2.5.2
PyOpenGL                 3.1.7
pyparsing                3.1.2
python-dateutil          2.9.0.post0
requests                 2.31.0
scipy                    1.13.0
setuptools               68.2.2
Shimmy                   0.2.1
six                      1.16.0
swig                     4.2.1
sympy                    1.12
torch                    2.2.2
tqdm                     4.66.2
triton                   2.2.0
typing_extensions        4.11.0
urllib3                  2.2.1
wheel                    0.41.2
zipp                     3.18.1
`

**Comment by Kallinteris-Andreas** [comment]
From my testing With my phone (aarch V8) the core api works fine, but not all environmnets May work since they rely on third party libraries (mujoco worked fine)

Also there are users with apple macs running gymnasium with no issues

As with your particular case, for some reason you appear to have installed gymnasium version 0.0.1

Try pip install `gymnasium==1.0.0a1`
