### ISSUE TITLE
[Question] Discrepancy between Humanoid-v3 and Humanoid-v4

### ISSUE THREAD

**Issue by jjyyxx** [Farama-Foundation/Gymnasium#1041]
### Question

The Humanoid-v4 environment uses  the official mujoco binding, which offers simplicity in usage. However, in our reinforcement learning (RL) experiments, we've encountered notable differences in simulation performance compared to Humanoid-v3.

![image](https://github.com/Farama-Foundation/Gymnasium/assets/13808089/343aa0e1-7ac2-4354-b52e-74dbbacfd323)

Comparison between Blue - V3 and Orange - V4, with all settings identical

When testing these two environments side by side, I found that even though they share the same mujoco model, random seed and initial qpos and qvel, their initial observations upon reset diverge. So, I wonder if it is caused by different mujoco version (2.1.0 vs 3.1.4)? Is it possible to change certain simulation config to match the original environment?

**Comment by Kallinteris-Andreas** [comment]
Identical behavior is not guaranteed across different gymnasium environment versions, in fact that is the point of environment versions, that being said if you want closer performance, you could try using an earlier version of  `mujoco`

**Comment by Kallinteris-Andreas** [comment]
Humanoid version 3 and humanoid version 4 are definitely not identical, They have different reward functions because version 4 contact cost is always 0, (due to a bug)
