### ISSUE TITLE
The dynamics for Toy text environments

### ISSUE THREAD

**Issue by FarnazAdib** [Farama-Foundation/Gymnasium#1043]
### Question

How can one access to the transition probability model for the toy text environments, i.e. P[s^{prime}| s, a]. In gym, we could access via `env.P`.

**Comment by Kallinteris-Andreas** [comment]
env.unwrapped.P

**Comment by FarnazAdib** [comment]
Thanks but it is not defined for the blackjack environment. I checked other environments. All others work fine.
`AttributeError: 'BlackjackEnv' object has no attribute 'P'`

**Comment by pseudo-rnd-thoughts** [comment]
The probability of a card being drawn is constant as it draws from an "infinite desk" therefore it doesn't contain a `P` table
