### ISSUE TITLE
[Bug Report] Code examples in Vector API documentation use deprecated "gym.vector.make" instead of "gym.make_vec"

### ISSUE THREAD

**Issue by LetteraUnica** [Farama-Foundation/Gymnasium#1047]
### Describe the bug

I found that code examples in the vector API documentation, at https://gymnasium.farama.org/api/vector/examples use the deprecated method `gym.vector.make` instead of the method `gym.make_vec`.

If this is intended feel free to close this issue, otherwise I would be glad to work on this since it seems like a simple change.

### Code example

```shell
## Current example for creating a vector env on the documentation
import gymnasium as gym
envs = gym.vector.make("CartPole-v1", num_envs=3)
envs.reset(seed=42)
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Could you check if this is still an issue on the main version of the website?

**Comment by LetteraUnica** [comment]
If you mean the documentation present on the main branch, I've just built it and the issue with `gym.make_vec` seems to not be present

**Comment by pseudo-rnd-thoughts** [comment]
Ok, perfect, then I don't think there is an issue then I will close
