### ISSUE TITLE
[Question] Rough timeline for Atari (ALE) support for gymnasium>=1.0.

### ISSUE THREAD

**Issue by sven1977** [Farama-Foundation/Gymnasium#1049]
### Question

Hey all, really awesome work on the new gymnasium version and congrats for the 1.0 release! This is super exciting.

The RLlib team has been adopting the vector Env API of gymnasium for some time now ([for RLlib's new API stack](https://github.com/ray-project/ray/blob/master/rllib/env/single_agent_env_runner.py#L700), which is using `gym.vector.Env` natively) and we would like to also switch to supporting 1.0 very soon. There are bug fixes in 1.0 that are helpful for us as well (related to vectorization and async vectorization).
I think the only thing that keeps us from already merging [this PR here](https://github.com/ray-project/ray/pull/45328) is the lack of Atari support (and other env types?) on 1.0.0a1.

Currently ...
```
import ale_py
import gymnasium as gym

gym.register_envs(ale_py)  # optional

env = gym.make("ALE/Pong-v5")
# env = gym.make("ale_py:ALE/Pong-v5")
```

... fails with:

```
Traceback (most recent call last):
  File "/Users/sven/anaconda3/envs/ray/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 688, in make
    env_spec = _find_spec(id)
  File "/Users/sven/anaconda3/envs/ray/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 532, in _find_spec
    _check_version_exists(ns, name, version)
  File "/Users/sven/anaconda3/envs/ray/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 398, in _check_version_exists
    _check_name_exists(ns, name)
  File "/Users/sven/anaconda3/envs/ray/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 361, in _check_name_exists
    _check_namespace_exists(ns)
  File "/Users/sven/anaconda3/envs/ray/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 355, in _check_namespace_exists
    raise error.NamespaceNotFound(f"Namespace {ns} not found. {suggestion_msg}")
gymnasium.error.NamespaceNotFound: Namespace ALE not found. Have you installed the proper package for ALE?
```

Do you have a rough estimate on when a new `ale_py` will be available that supports gymnasium>=1.0?

**Comment by pseudo-rnd-thoughts** [comment]
This weekend, the code is written and on ale-py main, the only job I need to do is add some testing that the wheels work as expected and for the wheels to be built and pushed on cutting a release.

**Comment by sven1977** [comment]
Awesome! Thanks for the quick response @pseudo-rnd-thoughts ! :) This is such great news.

**Comment by pseudo-rnd-thoughts** [comment]
@sven1977 Ale-py 0.9.0 was released yesterday and Gymnasium alpha 2 today, let me know if you run into any issues. You can find me on discord if you want to DM as well
