### ISSUE TITLE
[Question] Is there any reason to add epsilon to action mean?

### ISSUE THREAD

**Issue by tyfkda** [Farama-Foundation/Gymnasium#1064]
### Question

I read [Training using REINFORCE for Mujoco](https://gymnasium.farama.org/tutorials/training_agents/reinforce_invpend_gym_v26/).
In `REINFORCE#sample_action` method, `self.eps` is added to the first argument for `Normal`.
I have no knowledge about REINFORCE, but is it intentional?

https://github.com/Farama-Foundation/Gymnasium/blob/596bdcc94d068ad494ff4347612df25c6ebec62c/docs/tutorials/training_agents/reinforce_invpend_gym_v26.py#L183

**Comment by pseudo-rnd-thoughts** [comment]
Could you find the original specification of REINFORCE to confirm either way what the correct implementation would be?

**Comment by tyfkda** [comment]
I think I misled you. Actually, the part I'm wondering about is that we sample according to the probability distribution (normal distribution) obtained by the REINFORCE algorithm.

It makes sense to add a small epsilon to the standard deviation to increase numerical stability, but adding it to the mean seems strange.

**Comment by tyfkda** [comment]
I want to ask original committer,
@siddarth-c If you have time, could you please check it? Thanks.

**Comment by siddarth-c** [comment]
> I want to ask original committer, @siddarth-c If you have time, could you please check it? Thanks.

I am not sure why I added `eps` to the mean. But it should not affect the final performance of the agent. 
I believe it should even learn w/o the `eps` added to the mean.
