### ISSUE TITLE
[Bug Report] Wrong information about the beginning observation in InvertedDoublePendulum-v4 

### ISSUE THREAD

**Issue by SebastianBayerle** [Farama-Foundation/Gymnasium#1073]
### Describe the bug

In the commented section of the environment and on the website it states that the starting state of all observations is (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0) with a uniform noise in the range of [-0.1, 0.1] added on top of it. But in reality it is (0.0, 0.0, 1.0,1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0). Which makes sense because they represent the cosines of the angle and therefore have to be 1 if the angle is equal to zero. This may be a pedantic issue but I just wanted to share the error I found. 

### Code example

```shell
import gymnasium as gym 
env_name = "InvertedDoublePendulum-v4"
env = gym.make(env_name)
obs = env.reset()
print(obs)
```

### System info

gymnasium.0.29.1

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Kallinteris-Andreas** [comment]
```
$ py
Python 3.12.3 (main, Apr 23 2024, 09:16:07) [GCC 13.2.1 20240417] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gymnasium as gym 
>>> env_name = "InvertedDoublePendulum-v4"
>>> env_name = "InvertedDoublePendulum-v4"
>>> env = gym.make(env_name)
/home/master-andreas/.local/lib/python3.12/site-packages/gymnasium/envs/registration.py:518: DeprecationWarning: WARN: The environment InvertedDoublePendulum-v4 is out of date. You should consider upgrading to version `v5`.
  logger.deprecation(
>>> env.unwrapped.init_qpos
array([0., 0., 0.])
>>> env.unwrapped.init_qvel
array([0., 0., 0.])
```
The Starting state is zero, the documentation was wrong, it said that the "initial observation is zero" instead of "the initial state is zero" 

This has been fixed in the 1.0 branch https://gymnasium.farama.org/v1.0.0a2/environments/mujoco/inverted_pendulum/#starting-state

Thanks for pointing it our regardless
