### ISSUE TITLE
[Proposal] Change `np.finfo(np.float32).max` in CartPole to `np.inf`

### ISSUE THREAD

**Issue by TimSchneider42** [Farama-Foundation/Gymnasium#1092]
### Proposal

Hey,

I noticed that in CartPole, the unboundedness of the velocity state components is expressed by setting their bounds to `np.finfo(np.float32).max` (see [cartepole.py](https://github.com/Farama-Foundation/Gymnasium/blob/3b7f39850887c349a611075629db200d801505c3/gymnasium/envs/classic_control/cartpole.py#L143)). However, this seems to be the only environment for which it is done this way, as other environments simply resort to `np.inf`. Unless there is a specific reason to avoid using `np.inf` in this case, I think CartPole should be adapted as it otherwise requires special handling on the user side.

Best,
Tim

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by RedTachyon** [comment]
I think this makes sense. We explicitly support `np.inf` in box spaces, and this is a clear use-case of that. Can you make a PR?
