### ISSUE TITLE
[Bug Report] Final observation missing in vector env on autoreset.

### ISSUE THREAD

**Issue by jjshoots** [Farama-Foundation/Gymnasium#1103]
### Describe the bug

`_final_observation`, `final_observation`, `_final_infos`, and `final_infos` are missing in VectorEnv's autoreset feature.

It doesn't appear anywhere [here](https://github.com/jjshoots/Gymnasium/blob/a1f83d38faac50d19b68c76ba8e10fb563b7d027/gymnasium/vector/sync_vector_env.py#L114-L155) and doing a repo-wide grep for `final_observation` returns nothing tangible that points at the observation being included.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
This is an intentional change in Gymnasium v1.0, see the release notes for the changes
