### ISSUE TITLE
[Bug Report] `torch_to_numpy` fails when tensors are not on cpu

### ISSUE THREAD

**Issue by mantasu** [Farama-Foundation/Gymnasium#1108]
### Describe the bug

[torch_to_numpy](https://github.com/Farama-Foundation/Gymnasium/blob/57136fbaeec340c023ae6939348ac2e7cfe3b3cb/gymnasium/wrappers/numpy_to_torch.py#L31) fails when `torch.Tensor` is on a _non-cpu_ device or has `requires_grad` set to `True`. 

> [!note]
> Calling [torch_to_jax](https://github.com/Farama-Foundation/Gymnasium/blob/57136fbaeec340c023ae6939348ac2e7cfe3b3cb/gymnasium/wrappers/jax_to_torch.py#L47) does not cause these problems when `jax` is installed with GPU support - otherwise it also throws an error but informs the user that `jax` should be installed with GPU support.

### Code example

```shell
import torch
from gymnasium.wrappers.numpy_to_torch import torch_to_numpy

t = torch.tensor(0.0, device="cuda")
torch_to_numpy(t) # throws error
```

### System info

`python=3.11`, `gymnasium=1.0.0a2`

### Additional context

Error traceback from the example script:

```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "anaconda/envs/sddl/lib/python3.11/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "anaconda/envs/sddl/lib/python3.11/site-packages/gymnasium/wrappers/numpy_to_torch.py", line 51, in _number_torch_to_numpy
    return np.array(value)
           ^^^^^^^^^^^^^^^
  File "anaconda/envs/sddl/lib/python3.11/site-packages/torch/_tensor.py", line 1087, in __array__
    return self.numpy()
           ^^^^^^^^^^^^
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for the PR and issue again, looks all good
