### ISSUE TITLE
[To investigate] Check that the new autoreset order works correctly in vectorized jax envs

### ISSUE THREAD

**Issue by RedTachyon** [Farama-Foundation/Gymnasium#1122]
I don't have time to debug properly right now, but I'm running some experiments with 1.0.0a2 and vectorized `phys2d/Pendulum-v0`.

The loop is roughly:

```python
for t in trange(200 * 5):

    actions = ...

    next_obs, reward, term, trunc, info = env.step(actions)

    done = np.logical_or(term, trunc).any()

    replay_buffer.add(obs, actions[:, jnp.newaxis], next_obs)


    obs = next_obs
    print(t, done)

    # This is the questionable code
    if done:
        obs, *_ = env.step(actions)
        obs, *_ = env.step(actions)
```

The time limit is set to 200, so I'm trying to set it up so that I get a consistent 200 samples for each episode. 
So steps 0-199 (inclusive) should be from episode 1, steps 200-399 from episode 2, and so on.

There's no termination condition, so all sub-environments will truncate in sync.

In the "questionable" part, if I don't have any additional `step`s, I get two consecutive steps with `done==True`. With one additional `step`, I get a single `done==True`, but there seems to be a misalignment after the first episode, since `done`s occur at steps 199, 400, 601, etc.

When I switch to a sync vector env implementation of the regular Pendulum, I get the "aligned" behavior with only one extra `step` (as opposed to two in the code above), which is consistent with my understanding of how the new autoreset order should work. So it's likely that FunctionalJaxVectorEnv isn't properly adapted. Quite possibly my fault, as off-by-one-errors are still my personal nemesis.

**Comment by amiii123malviya** [comment]
Hello,

Is this issue still active?
I would like to work on this.

Best Regards.

**Comment by pseudo-rnd-thoughts** [comment]
Hey @amiii123malviya, #1130 should have fixed this

**Comment by amiii123malviya** [comment]
Okay, Thankyou so much for your time .

Best Regards
