### ISSUE TITLE
[Bug] info dictionary in `env.step()` does not include all claimed terms

### ISSUE THREAD

**Issue by manuelhaussmann** [Farama-Foundation/Gymnasium#1123]
### Describe the bug

The documentation for mujoco environments claims several terms to be in the returned info dictionary that are not actually present. For [Hopper](https://gymnasium.farama.org/environments/mujoco/hopper/), it states 
> info will also contain the individual reward terms
which is not the case.

Instead, info only contains `x_position` and `x_velocity` (see [here](https://github.com/Farama-Foundation/Gymnasium/blob/a01d94d70242062fd8407855997797e5fb76c00b/gymnasium/envs/mujoco/hopper_v4.py#L148)). 

(I know that one of the reward terms is constant, i.e., it is rather useless to include it, but still...)

For others, such as Ant it includes them.

### Code example

```shell
import gymnasium as gym


env = gym.make("Hopper-v4")
act = env.action_space.sample()
next_state, reward, terminated, truncated, info = env.step(action)
print(info)
```

### System info

`gym.__version__ == 0.29.1`

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Kallinteris-Andreas** [comment]
https://github.com/Farama-Foundation/Gymnasium/blob/a01d94d70242062fd8407855997797e5fb76c00b/gymnasium/envs/mujoco/hopper_v5.py#L315-L319
this is fixed in `Hopper-v5`

note:I believe the documentation in `Hopper-v2` was copied and pasted from `Ant-v2` without validating it, and was kept till `v4`

**Comment by manuelhaussmann** [comment]
Perfect, thanks.
