### ISSUE TITLE
[Bug Report] The description of the observation space of "half cheetah" is not correct on the documentation website. 

### ISSUE THREAD

**Issue by chawuchen** [Farama-Foundation/Gymnasium#1124]
### Describe the bug

[https://gymnasium.farama.org/environments/mujoco/half_cheetah/](https://gymnasium.farama.org/environments/mujoco/half_cheetah/)
The table of observation space description is not correct. For example, "angle of the second rotor" and "x-coordinate of the front tip" appear repetitively. Some of the names are obviously mismatched with the Unit.

**Comment by pseudo-rnd-thoughts** [comment]
Please see the updated website https://gymnasium.farama.org/main/environments/mujoco/half_cheetah/
This appears to be fixed
