### ISSUE TITLE
[Question] Automated planning over simulators support

### ISSUE THREAD

**Issue by MFaisalZaki** [Farama-Foundation/Gymnasium#1125]
### Question

Hi, I would like to know if Gymnasium supports the functionality of simulating actions in a given state. For example, the agent is in a state and wants to perform a simulation five steps ahead. The agent then picks the best action based on a given policy, applies this action to the environment, and keeps repeating this until the agent reaches its goal.

**Comment by pseudo-rnd-thoughts** [comment]
Well sort of, if you are talking about Model-based planning like MuZero, PlaNet, Dreamer etc, yes as these don't interact with the environment to achieve this. 
Or if you mean that you want to step through the environment to trial the actions, then in some environment yes but only through hacking them, you can deepcopy an environment then mess with the deepcopied version

**Comment by MFaisalZaki** [comment]
Thanks, @pseudo-rnd-thoughts, for your reply. My goal is to step through the environment to trial actions, but I can't find any example of how to achieve this. Can you guide me on how to see some examples?

**Comment by pseudo-rnd-thoughts** [comment]
https://github.com/FragileTech/plangym

**Comment by MFaisalZaki** [comment]
Thank you so much. Do you want me to close the issue?
