### ISSUE TITLE
ERROR: Failed building wheel for box2d-py

### ISSUE THREAD

**Issue by Amanda051107** [Farama-Foundation/Gymnasium#1127]
### Describe the bug

(gym) C:\Users\Lenovo>pip install gymnasium[box2d]
Requirement already satisfied: gymnasium[box2d] in c:\users\lenovo\.conda\envs\gym\lib\site-packages (0.28.1)
Requirement already satisfied: numpy>=1.21.0 in c:\users\lenovo\.conda\envs\gym\lib\site-packages (from gymnasium[box2d]) (1.26.4)
Requirement already satisfied: jax-jumpy>=1.0.0 in c:\users\lenovo\.conda\envs\gym\lib\site-packages (from gymnasium[box2d]) (1.0.0)
Requirement already satisfied: cloudpickle>=1.2.0 in c:\users\lenovo\.conda\envs\gym\lib\site-packages (from gymnasium[box2d]) (3.0.0)
Requirement already satisfied: typing-extensions>=4.3.0 in c:\users\lenovo\.conda\envs\gym\lib\site-packages (from gymnasium[box2d]) (4.11.0)
Requirement already satisfied: farama-notifications>=0.0.1 in c:\users\lenovo\.conda\envs\gym\lib\site-packages (from gymnasium[box2d]) (0.0.4)
Requirement already satisfied: importlib-metadata>=4.8.0 in c:\users\lenovo\.conda\envs\gym\lib\site-packages (from gymnasium[box2d]) (7.0.1)
Collecting box2d-py==2.3.5 (from gymnasium[box2d])
  Using cached box2d-py-2.3.5.tar.gz (374 kB)
  Preparing metadata (setup.py) ... done
Collecting pygame==2.1.3 (from gymnasium[box2d])
  Using cached pygame-2.1.3-cp39-cp39-win_amd64.whl.metadata (9.6 kB)
Requirement already satisfied: swig==4.* in c:\users\lenovo\.conda\envs\gym\lib\site-packages (from gymnasium[box2d]) (4.2.1)
Requirement already satisfied: zipp>=0.5 in c:\users\lenovo\.conda\envs\gym\lib\site-packages (from importlib-metadata>=4.8.0->gymnasium[box2d]) (3.17.0)
Using cached pygame-2.1.3-cp39-cp39-win_amd64.whl (10.4 MB)
Building wheels for collected packages: box2d-py
  Building wheel for box2d-py (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      Using setuptools (version 71.1.0).
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-39
      creating build\lib.win-amd64-cpython-39\Box2D
      copying library\Box2D\Box2D.py -> build\lib.win-amd64-cpython-39\Box2D
      copying library\Box2D\__init__.py -> build\lib.win-amd64-cpython-39\Box2D
      creating build\lib.win-amd64-cpython-39\Box2D\b2
      copying library\Box2D\b2\__init__.py -> build\lib.win-amd64-cpython-39\Box2D\b2
      running build_ext
      building 'Box2D._Box2D' extension
      swigging Box2D\Box2D.i to Box2D\Box2D_wrap.cpp
      swig.exe -python -c++ -IBox2D -small -O -includeall -ignoremissing -w201 -globals b2Globals -outdir library\Box2D -keyword -w511 -D_SWIG_KWARGS -o Box2D\Box2D_wrap.cpp Box2D\Box2D.i
      Box2D\Common\b2Math.h(67) : Warning 302: Identifier 'b2Vec2' redefined by %extend (ignored),
      Box2D\Box2D_math.i(47) : Warning 302: %extend definition of 'b2Vec2'.
      Box2D\Common\b2Math.h(158) : Warning 302: Identifier 'b2Vec3' redefined by %extend (ignored),
      Box2D\Box2D_math.i(168) : Warning 302: %extend definition of 'b2Vec3'.
      Box2D\Common\b2Math.h(197) : Warning 302: Identifier 'b2Mat22' redefined by %extend (ignored),
      Box2D\Box2D_math.i(301) : Warning 302: %extend definition of 'b2Mat22'.
      Box2D\Common\b2Math.h(271) : Warning 302: Identifier 'b2Mat33' redefined by %extend (ignored),
      Box2D\Box2D_math.i(372) : Warning 302: %extend definition of 'b2Mat33'.
      Box2D\Collision\b2DynamicTree.h(44) : Warning 312: Nested union not currently supported (ignored).
      Box2D\Common\b2Settings.h(144) : Warning 506: Can't wrap varargs with keyword arguments enabled
      Box2D\Common\b2Math.h(91) : Warning 509: Overloaded method b2Vec2::operator ()(int32) effectively ignored,
      Box2D\Common\b2Math.h(85) : Warning 509: as it is shadowed by b2Vec2::operator ()(int32) const.
      creating build\temp.win-amd64-cpython-39
      creating build\temp.win-amd64-cpython-39\Release
      creating build\temp.win-amd64-cpython-39\Release\Box2D
      creating build\temp.win-amd64-cpython-39\Release\Box2D\Collision
      creating build\temp.win-amd64-cpython-39\Release\Box2D\Collision\Shapes
      creating build\temp.win-amd64-cpython-39\Release\Box2D\Common
      creating build\temp.win-amd64-cpython-39\Release\Box2D\Dynamics
      creating build\temp.win-amd64-cpython-39\Release\Box2D\Dynamics\Contacts
      creating build\temp.win-amd64-cpython-39\Release\Box2D\Dynamics\Joints
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Lenovo\.conda\envs\gym\include -IC:\Users\Lenovo\.conda\envs\gym\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" /EHsc /TpBox2D\Box2D_wrap.cpp /Fobuild\temp.win-amd64-cpython-39\Release\Box2D\Box2D_wrap.obj -I.
      Box2D_wrap.cpp
      C:\Users\Lenovo\.conda\envs\gym\include\pyconfig.h(59): fatal error C1083: 无法打开包括文件: “io.h”: No such file or directory
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for box2d-py
  Running setup.py clean for box2d-py
Failed to build box2d-py
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (box2d-py)

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by sryu1** [comment]
Try
```
pip install swig
```
before installing gymnasium with box2d.
