### ISSUE TITLE
[Bug Report] truncated is commented out

### ISSUE THREAD

**Issue by qelloman** [Farama-Foundation/Gymnasium#1131]
### Describe the bug

NOTE: This is my first issue report, so the format might be wrong.
There is a discrepancy in `Mountain Car` environment between documentation and code implementation.

According to the gymnasium documentation, `Mountain Car` env is supposed to be truncated when the elapsed step exceeds 200.
However, the code comments out the truncatation part and guides users to use `TimeLimit` wrapper.

The documentation is needed to be updated.

### Code example

```shell
# truncation=False as the time limit is handled by the `TimeLimit` wrapper added during `make`
        return np.array(self.state, dtype=np.float32), reward, terminated, False, {}
```

### System info

gymnasium is installed via pip.
gymnasium==0.29.1
MacOS 14.5
Python==3.8.19

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for the issue, could you clarify what the problem with the documentation is
Do you want a link to TimeLimit or the part of the make function that allows?
