### ISSUE TITLE
[Bug Report] Wrapper type hints seem to be specified incorrectly?

### ISSUE THREAD

**Issue by Katze2664** [Farama-Foundation/Gymnasium#1137]
### Describe the bug

In [core.py](https://github.com/Farama-Foundation/Gymnasium/blob/main/gymnasium/core.py) the type hints for some of the classes seem to be incorrect (possibly due to a typo?). Apologies if the type hints are correct and I have just misunderstood how they work.

Line 521:
`class ObservationWrapper(Wrapper[WrapperObsType, ActType, ObsType, ActType]):`
Proposed correction:
`class ObservationWrapper(Wrapper[WrapperObsType, WrapperActType, ObsType, ActType]):`

Line 565:
`class RewardWrapper(Wrapper[ObsType, ActType, ObsType, ActType]):`
Proposed correction:
`class RewardWrapper(Wrapper[WrapperObsType, WrapperActType, ObsType, ActType]):`

Line 602:
`class ActionWrapper(Wrapper[ObsType, WrapperActType, ObsType, ActType]):`
Proposed correction:
`class ActionWrapper(Wrapper[WrapperObsType, WrapperActType, ObsType, ActType]):`

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
This was intentional as the `ObservationWrapper` and `ActionWrapper` don't change the `ActType` or the `ObsType` respectively. 
Therefore, rather than having a `WrapperActType` or `WrapperObsType` that is different from the `ActType` or the `ObsType`. I have kept them the same as the base `ActType` / `ObsType`.

I hope that makes sense, let me know if you believe their is an issue with this

**Comment by Katze2664** [comment]
Yes, that makes sense.

I was looking at some of the other wrappers today and I noticed that some wrappers (e.g. `DelayObservation`, `TimeAwareObservation`, ...) only specify 3 types, even though they are inheriting from wrappers that specify 4 types (e.g. `ObservationWrapper`).

[core.py](https://github.com/Farama-Foundation/Gymnasium/blob/main/gymnasium/core.py)
Line 531:
`class ObservationWrapper(Wrapper[WrapperObsType, ActType, ObsType, ActType]):`

[stateful_observation.py](https://github.com/Farama-Foundation/Gymnasium/blob/main/gymnasium/wrappers/stateful_observation.py)
Line 35:
```
class DelayObservation(
    gym.ObservationWrapper[ObsType, ActType, ObsType], gym.utils.RecordConstructorArgs
):
```
Line 106:
```
class TimeAwareObservation(
    gym.ObservationWrapper[WrapperObsType, ActType, ObsType],
    gym.utils.RecordConstructorArgs,
):
```

I'm not very familiar with type hinting conventions, but I wondered whether the number of type hints should match the class it is inheriting from?
e.g.
class TimeAwareObservation(
    gym.ObservationWrapper[WrapperObsType, ActType, ObsType, **ActType**],
    gym.utils.RecordConstructorArgs,
):

**Comment by Katze2664** [comment]
I've read a bit more about inheriting from Generic base classes ([https://typing.python.org/en/latest/spec/generics.html#generic-base-classes](https://typing.python.org/en/latest/spec/generics.html#generic-base-classes)) and I think I understand now why it is correct for `TransformAction` to only specify 3 types.
