### ISSUE TITLE
[Bug Report] The last 84 dimensions of Humanoid-v4 are always zero.

### ISSUE THREAD

**Issue by Altriaex** [Farama-Foundation/Gymnasium#114]
### Describe the bug

The documentation of Humanoid-v4 says it no longer has the contact force issue. But I still find that the last 84 dimensions of states in Humanoid-v4 are always zero.
<img width="592" alt="截屏2022-11-06 17 16 15" src="https://user-images.githubusercontent.com/10769261/200160946-da863b30-1ec9-4e0b-b8a3-a2e4c1090e04.png">

### Code example

```shell
import mujoco
import gymnasium
env = gymnasium.make("Humanoid-v4")
s, _ = env.reset()
for i in range(3):
    action = env.action_space.sample()
    next_state, reward, done, truncated, _ = env.step(action)
print(next_state[-84:])
```

### System info

gymnasium_ver: 0.26.3
mujoco_ver 2.2.0
Ubuntu

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by rodrigodelazcano** [comment]
In this environment the `humanoid` is spawned in mid-air. Thus it won't touch the ground and there will be no external contact forces detected.
If you step the simulation a little longer until the humanoid touches the ground, contact forces should appear.

![image](https://user-images.githubusercontent.com/60633730/200186244-3d638f57-bbe6-4a14-904e-e626aad88994.png)
