### ISSUE TITLE
[Bug Report] Custom environment documentation example gif missing

### ISSUE THREAD

**Issue by SandSnip3r** [Farama-Foundation/Gymnasium#1143]
### Describe the bug

In the tutorial for creating a new environment, the gif is missing.

On this page: https://gymnasium.farama.org/tutorials/gymnasium_basics/environment_creation/#subclassing-gymnasium-env

There should be a video playing in this text:
```
An episode in this environment (with size=5) might look like this:

where the blue dot is the agent and the red square represents the target.

Let us look at the source code of GridWorldEnv piece by piece:
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Kallinteris-Andreas** [comment]
has been fixed:

https://gymnasium.farama.org/v1.0.0a2/tutorials/gymnasium_basics/environment_creation/#subclassing-gymnasium-env

**Comment by SandSnip3r** [comment]
Thanks. It seems like the documentation defaults to v0.29.0 (latest)? Can that be updated to v1+?
