### ISSUE TITLE
[Question] Wiki / Leaderboards?

### ISSUE THREAD

**Issue by vacant-observer** [Farama-Foundation/Gymnasium#1146]
### Question

I have this script which can solve CartPole in 0 episodes without any kind of custom CartPole heuristics and such. Gym had a leaderboard here https://github.com/openai/gym/wiki/Leaderboard and I was wondering if there is some other place this is hosted now?

I think it can also solve the Acrobot environment as well very efficiently.

Here is the script for reference

https://github.com/vacant-observer/QuantumInspiredIntelligence/blob/main/quantum_system.py

In this example 50 elements are used but I think maybe 2-4 could be fine.  In this example only 1 iteration was needed with only 1 sample Maybe with 2-4 elements consider trying 5-10 samples. This is a very simplified version.

I added a comparative analysis with sb3 PPO & DQN: https://github.com/vacant-observer/QuantumInspiredIntelligence/blob/main/quantum_system_compare_sb3.py

![LunarLander_Compare](https://github.com/user-attachments/assets/f04ef80b-0f86-4d32-8538-241c7cabf316)
![Acrobot_Compare](https://github.com/user-attachments/assets/582a970c-90ed-4d31-96e5-0d16d39c2515)
![CartPole_Compare](https://github.com/user-attachments/assets/c8d91373-c45e-4597-847c-7413e39c480c)

**Comment by pseudo-rnd-thoughts** [comment]
Hi, we don't have any plans to include this sadly due to verification and making sure that the links work would be too much work as the team is solely volunteers
