### ISSUE TITLE
[Bug Report] CarRacing car_dynamics.py TypeError

### ISSUE THREAD

**Issue by tjayada** [Farama-Foundation/Gymnasium#1151]
### Describe the bug

Simply running the CarRacing-v2 environment will result in a TypeError for me.

The problem arises because in gymnasium/envs/box2d/car_dynamics.py line 177 causes : 
`w.joint.motorSpeed = dir * min(50.0 * val, 3.0)
TypeError: in method 'b2RevoluteJoint___SetMotorSpeed', argument 2 of type 'float32'`

So just casting it all to the same type, eg. 
`w.joint.motorSpeed = float(dir * min(50.0 * val, 3.0))`
fixes it for me. 

Same (?) for line 261 with 
```
w.ApplyForceToCenter( 
                (
                    p_force * side[0] + f_force * forw[0],
                    p_force * side[1] + f_force * forw[1],
                ),
                True,
            )
```

I just use float again, and it works, eg.

```
w.ApplyForceToCenter( 
                (
                    float(p_force * side[0] + f_force * forw[0]),
                    float(p_force * side[1] + f_force * forw[1]),
                ),
                True,
            )
```

After applying float to these three lines, the environment works again. 
As I have no deeper understanding of what is happening in the code, this is the simplest solution I could think of, but the real issue probably lies somewhere deeper. 

### Code example

```shell
import gymnasium as gym

env = gym.make("CarRacing-v2", render_mode="human")

observation = env.reset(seed=42)

for _ in range(1000):
    action = env.action_space.sample()
    observation, reward, terminated, truncated, info = env.step(action)

    if terminated or truncated:
        observation, info = env.reset()
        print("Done!")
        break
        
env.close()
```

### System info

macOS Sonoma Version 14.6.1

python 3.9.13

pip list : 
box2d-py             2.3.5
cloudpickle          3.0.0
Farama-Notifications 0.0.4
gymnasium            0.29.1
importlib_metadata   8.4.0
numpy                2.0.2
pip                  22.0.4
pygame               2.6.0
setuptools           58.1.0
swig                 4.2.1
typing_extensions    4.12.2
zipp                 3.20.1

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Downgrade numpy to 1.24, it is a NumPy 2.0 related issues

**Comment by aduluu** [comment]
thank you for telling me that!i stucked in this problem for the entire afternoon!
