### ISSUE TITLE
[Bug Report] TransformObservation not backward compatible due to extra parameter

### ISSUE THREAD

**Issue by kinalmehta** [Farama-Foundation/Gymnasium#1155]
### Describe the bug

TransformObservation not backward compatible due to extra parameter

### Code example

```shell
# old call
env = gym.wrappers.TransformObservation(env, lambda obs: np.clip(obs, -10, 10))


# new call
env = gym.wrappers.TransformObservation(env, lambda obs: np.clip(obs, -10, 10), None)
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
This isn't a bug, this is intentional.
`TransformObservation` will generally change the observation space of the wrapper that might affect other wrappers / algorithms. 
Why should this be changed to allow `None`?

**Comment by kinalmehta** [comment]
The change in observation only happens when the given function does it. But for tasks like clipping as shown in the example, it doesn't necessarily change. 

Moreover when I went through the documentation, it was mentioned that `None` is a valid parameter in which case the observation space of the passed env is used.

So why not just make it a default setting where if the `observation_space `param is not provided, then its `None` by default and uses the `observation_space` of the passed `env`

**Comment by pseudo-rnd-thoughts** [comment]
> So why not just make it a default setting where if the observation_space param is not provided, then its None by default and uses the observation_space of the passed env

Because the wrapper cannot know if the function changes the observation space, therefore, this needs to be done by the user
