### ISSUE TITLE
[Bug Report] No reward threshold for Walker2d-v4

### ISSUE THREAD

**Issue by modanesh** [Farama-Foundation/Gymnasium#1157]
### Describe the bug

All MuJoCo envs have reward  threshold except for Walker2d-v4:

```shell
>>> import gymnasium as gym
>>> gym.__version__
'0.29.1'
>>> gym.make("Ant-v4").spec.reward_threshold
6000.0
>>> gym.make("Walker2d-v4").spec.reward_threshold
>>> 
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Reward threshold are not used by anthing so this shouldn't effect anything.

**Comment by modanesh** [comment]
I need it for my research, and that's why I created this issue. For some other envs, there are reward thresholds.

**Comment by pseudo-rnd-thoughts** [comment]
@Kallinteris-Andreas does a reward threshold exist? Otherwise, I don't think there is an upper bound
From the looks of it, agents can achieve around 3500 mean reward though this might not be max

**Comment by Kallinteris-Andreas** [comment]
From what I can understand reward threshold is being used to indicate that the environment is solved when the episodic is return is reached.

I am not sure how the reward threshold values were given.
In particular the Reward thresholds for MuJoCo environments is:
Reacher -3.75, Seems about right.
Pusher 0, unreachble / Impossible.
Inverted pendulum 950, should be 1000
Inverted double pendulum 9100, Should be 9500 
Half cheetah 4800, Should be around 12K
Hopper 3800, 
swimmer 360, Is correct
Ant 6000, While hard it is possible to get higher.

The other MuJoCo environments do not have A reward threshold

**Comment by modanesh** [comment]
Thanks @Kallinteris-Andreas and @pseudo-rnd-thoughts
