### ISSUE TITLE
[Bug Report] pip remove ale-py==0.8.1

### ISSUE THREAD

**Issue by Hananel-Hazan** [Farama-Foundation/Gymnasium#1160]
### Describe the bug

I'm attempting to install the release version of Gymnasium using pypi , which requires ale-py==0.8.1. However, when I try to install it using:

`pip install ale-py==0.8.1`

I receive the following error:

```
ERROR: Could not find a version that satisfies the requirement ale-py==0.8.1 (from versions: 0.9.0, 0.9.1)
ERROR: No matching distribution found for ale-py==0.8.1
```

I'm aware that Gymnasium version 1 is in development, but at the moment, installing the release (pypi) version v0.29.1 seems to be problematic due to this issue.

Is there a workaround or solution available to resolve this?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
What python version are you using? Gymnasium v0.29 doesn't support 3.12

**Comment by Hananel-Hazan** [comment]
You are right, I was on python 3.12. 
Switch to 3.11 and I can install Gymnasium v0.29.

Thanks!
