### ISSUE TITLE
[Bug Report] website defaults to the oldest version

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [Farama-Foundation/Gymnasium#1174]
### Describe the bug

When I go to https://gymnasium.farama.org/ it defaults to the earliest available version

![image](https://github.com/user-attachments/assets/7e71c2c7-40bd-430c-8dce-227fc22a26c3)
Probably something to do with how it compares strings
@mgoulao 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Kallinteris-Andreas** [comment]
does not seem to be fixed

**Comment by Kallinteris-Andreas** [comment]
still not fixed https://gymnasium.farama.org/

**Comment by pseudo-rnd-thoughts** [comment]
@mgoulao

**Comment by pseudo-rnd-thoughts** [comment]
@mgoulao updated Celshest yesterday so I rebuild the website so it now works. The only problem is that it doesn't ignore alphas but I don't think that should matter in a couple of days
