### ISSUE TITLE
[Question] How to record video when render_mode is "Human"?

### ISSUE THREAD

**Issue by TatsukiNishimura** [Farama-Foundation/Gymnasium#1182]
### Question

Hello.
I move the robot using remote control using the keyboard in a gym environment with render_mode "Human".
I would like to record a video of the environment I am currently controlling remotely, but when render_mode is Human, I cannot obtain the video using ```env.render()```.
How do we get the video when render_mode is Human?

**Comment by Kallinteris-Andreas** [comment]
You can record your window with a program like OBS, there is nothing built-in to the Gymnasium to record ` render_mode=human`

**Comment by TatsukiNishimura** [comment]
OK! Thanks! @Kallinteris-Andreas
