### ISSUE TITLE
[Proposal] New environments

### ISSUE THREAD

**Issue by sparisi** [Farama-Foundation/Gymnasium#1184]
### Proposal

I would like to know what's the policy/procedure to add new environments or to be referenced in the [third-party environments page](https://gymnasium.farama.org/environments/third_party_environments/). The page says to reach out on Discord, but the link is broken (it says "invite invalid"). 

I made [this collection of gridworlds](https://github.com/sparisi/gym_gridworlds) based on Gymnasium. The environments are fully discrete and are a nice easy benchmark (even though some are more challenging) before moving to pixel-based or continuous environments. AFAIK, there are no popular gridworld implementations, and MiniGrid does not have native `spaces.Discrete` observations (so, to use tabular methods once have to implement some workarounds). 

These gridworld environments have been used in AAMAS 2024 and NeurIPS 2024 papers, and I plan to use for future work. I would really like to have them either integrated in Gymnasium, or referenced in the third-party environment page. 

### Motivation

No common gridworld repository exists, AFAIK. Mine has been used in AAMAS and NeurIPS paper, and I'd like to make it more popular.

### Pitch

Have it referenced in the third-party page, or make it integrated by default in Gymnasium.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
We would be happy to include your project within the third-party page, just make a PR adding the project.
