### ISSUE TITLE
[Bug Report] Installing gymnasium[atari]

### ISSUE THREAD

**Issue by D-A-N-1-3-6** [Farama-Foundation/Gymnasium#1193]
### Describe the bug

To be precise pip is having an issue with checking the compatibility of the three versions with other requirements.
![Screenshot 2024-10-05 092704](https://github.com/user-attachments/assets/cbf27047-0fd5-470d-9ce0-eab0ed66b2da)

### System info

pip install gymnasium[atari]

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by JDRanpariya** [comment]
I was able to reproduce the issue. Similar issue exists at #1081, try solutions mentioned there and close the issue if solved.
