### ISSUE TITLE
[Bug Report] Wrong migration guide (?)

### ISSUE THREAD

**Issue by strakam** [Farama-Foundation/Gymnasium#1198]
### Describe the bug

At the gymnasium website (https://gymnasium.farama.org/introduction/migration_guide/) there is a migration guide named `Migration Guide - v0.21 to v1.0.0` but it looks like it describes migration from `v0.21` to `v0.26`. Is this correct behavior? 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Kallinteris-Andreas** [comment]
The core API was not changed from 0.26 to 1.0

**Comment by strakam** [comment]
I suggest making it clearer that the API was not changed, maybe give rename sections like this:
- `Example code for v0.26` -> `Example code for v0.26/v1.0.0`

I can create a PR if something like this is welcome.
