### ISSUE TITLE
[Proposal] Clarify practice when using `env.reset(seed=None)`

### ISSUE THREAD

**Issue by strakam** [Farama-Foundation/Gymnasium#1207]
### Proposal

Set a best practice on how to handle `seed` deterministicity when `env.reset(seed=None)`.

Some ideas:
- Explain in the [example](https://gymnasium.farama.org/introduction/create_custom_env/#reset-function) how to resolve the situation when `env.reset(seed=None)` as I think even this example wouldn't pass `check_env`.
- Make `self.np_random_seed` serve as "automatic fallback" (meaning that something like `seed=self.np_random_seed` is set when `seed=None`). However, I don't know how I would go about this right now. Happy to submit a PR if I get a hint.

### Motivation

Assume this code:
```python
def reset(self, seed: int | None = None, ...)-> something:
    grid = self.grid_factory.generate_grid(seed=seed)
    ...
```
When running `env_checker` since `v1.0.0`, the following error occurs:
```
AssertionError: Using `env.reset(seed=123)` then `env.reset()` is non-deterministic as the observations are not equivalent.
```
It is unclear how to resolve this problem. One solution looks like this:
```python
def reset(self, seed: int | None = None, ...)-> something:
    if seed is None:
        seed = self.np_random_seed
    grid = self.grid_factory.generate_grid(seed=seed)
    ...
```
but this workaround was deduced from the release notes. It would be better if this was handled implicitly, or
documented in `Create a Custom Environment` guide.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
You should have `super().reset(seed=seed)` on the first line of the reset function. 
See https://gymnasium.farama.org/introduction/create_custom_env/#reset-function for more detail, let me know if there anything missing or unclear

**Comment by strakam** [comment]
In the motivation example I need to pass the `seed` to a function that creates a grid. There are 2 cases:

1. We provide `seed=None`. In this case, `super().reset(seed=seed)` runs this:
```python
if seed is not None:
    self._np_random, self._np_random_seed = seeding.np_random(seed)
```
but the `seed` in the calling function (the one that is passed to `grid_factory.generate_grid(seed=seed)`) is still `None`. However the error from `check_env` (see motivation example above) says that when `reset()` is called, the last previous `seed` should be used in the rest of the function. But the current implementation of `super().reset(seed=seed)` doesn't set the `seed` to previous value. Something like this should work:
```python
if seed is not None:
    self._np_random, self._np_random_seed = seeding.np_random(seed)
    seed = self._np_random_seed
```

**Comment by strakam** [comment]
Also, in release notes, it is mentioned that:

>Additionally, for environments, we have added a new `np_random_seed` attribute that will store the most recent
>`np_random` seed value from `reset(seed=seed)`.

Perhaps it should be `_np_random_seed` ? Should we use `_np_random_seed` or `seed` in the function when `reset()` is run?

**Comment by pseudo-rnd-thoughts** [comment]
I'm a tad confused as `seed` is not returned from `super().reset` so the change you are suggesting wouldn't work I believe. 

My suggestion would be to use `grid_factory.generate_grid(seed=self.np_random_seed)` or pass `np_random` directly to the `generate_grid` function

**Comment by strakam** [comment]
> I'm a tad confused as seed is not returned from `super().reset` so the change you are suggesting wouldn't work I believe.

That's right, sorry for the confusion.

> My suggestion would be to use `grid_factory.generate_grid(seed=self.np_random_seed)` or pass `np_random` directly to the generate_grid function

This way, if `seed` is not `None`, `super.reset()` will do nothing and the passed `seed` will not be passed to `grid_factory.generate_grid`. Instead, old `seed` will be used via `self.np_random_seed`.

What I'm trying to say is that the current implementation of `reset()` is that you should use `seed` if it is not `None` and if it is, use `self.np_random_seed` - this way you will pass `env_checker`.

**Comment by strakam** [comment]
Current `env_checker` checks for this:
```python3
obs1, _ = env.reset(seed=123)
obs2,_ = env.reset()
assert obs1 == obs2 # should be the same
```

Consider this code:
```python
def reset(seed: int | None = None):
    super().reset(seed=seed)
    obs, info = self.grid_factory.generate_grid(seed=seed)
    return obs, info
```
This code will fail, as first seed is `123` and the second one is `None` (grids are different).

Possible workaround:
```python
def reset(seed: int | None = None):
    super().reset(seed=seed)
    if seed is None:
        seed = self.np_random_seed
    obs, info = self.grid_factory.generate_grid(seed=seed)
    return obs, info
```
This code passes the checker, because if we pass `seed=None` in the second `reset`, the previous `seed=123` is reused via `self.np_random_seed`.

Is this a good approach? It feels like it should be done differently, or at least explained in more detail.

**Comment by pseudo-rnd-thoughts** [comment]
Ahh, ok I understand the problem. 
If we have environment determinism, I.e. you pass a seed to the environment, given the same sequence of actions, this should always result in the same sequence of outputs. 

So for the first example, this is not right. We check that if we reset with a seed, reset without a seed then restart the process then we can the same respective observations. 

For your example, you should use 'self.np_random' not seed or 'np_random_seed'. In short, you want to use the internal random number generator, 'np_random' for all randomness in your environment.

**Comment by strakam** [comment]
I understand it now, makes a lot of sense :) Thanks for your patience.
