### ISSUE TITLE
[Bug Report] Discrete has incorrect shape

### ISSUE THREAD

**Issue by nathanhack** [Farama-Foundation/Gymnasium#1208]
### Describe the bug

Looks like the shape for Descrete isn't set.
See the first parameter is an empty tuple instead of the actual shape.
https://github.com/Farama-Foundation/Gymnasium/blob/d571ed63017fb0bf1a9022960a3798b8d7c8b409/gymnasium/spaces/discrete.py#L52

### Code example

```shell
from gymnasium import spaces
action_space = spaces.Discrete(3)
print(action_space.shape)
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Kallinteris-Andreas** [comment]
```py
>>> from gymnasium.spaces import Discrete
>>> observation_space = Discrete(500, seed=42)
>>> observation_space.sample()
np.int64(44)
>>> observation_space.sample()
np.int64(386)
>>> observation_space.sample()
np.int64(327)
>>> 
```

It is correct, `shape==()` represents scalars

**Comment by nathanhack** [comment]
I would never had thought 
`
observation_space = Discrete(500, seed=42)
observation_space.shape == shape(observation_space.sample()) 
`
Good to know.
