### ISSUE TITLE
[Question] Best way to use Gymnasium with another prorgramming language.

### ISSUE THREAD

**Issue by Tudyx** [Farama-Foundation/Gymnasium#122]
### Question

I want to test an algorithm written in another language that Python. I want to ask you what is the best way to interact with Gymnasium from another language currently?
I know that back in a day, gym had a REST API I wonder if you have something similar or a foreign function interface.

**Comment by pseudo-rnd-thoughts** [comment]
This depends on what language you want to convert it to
It would be possible to use a REST API, however this will be very slow so we would recommend to not do that

**Comment by Tudyx** [comment]
Thank you for your reply, my algorithm is in the Rust Programming language.

**Comment by pseudo-rnd-thoughts** [comment]
You can call python from rust https://github.com/PyO3/pyo3
But depending on your problem, it might be worth rewrite some of the base code

**Comment by Tudyx** [comment]
That's what I thought. Thank you for your time and your help!
