### ISSUE TITLE
[Question] Is the Conda version able to be updated to 1.0.0?

### ISSUE THREAD

**Issue by MittelmanDaniel** [Farama-Foundation/Gymnasium#1223]
### Question

The conda download of gymnasium is still in 0.29 is it possible to update it to the most recent version?

https://github.com/conda-forge/gymnasium-feedstock?tab=readme-ov-file

**Comment by Kallinteris-Andreas** [comment]
wip : https://github.com/conda-forge/gymnasium-feedstock/pull/41#issuecomment-2425917958

**Comment by traversaro** [comment]
> wip : [conda-forge/gymnasium-feedstock#41 (comment)](https://github.com/conda-forge/gymnasium-feedstock/pull/41#issuecomment-2425917958)

Just for alignment, that question was a nice to have, it is not blocking the PR (as we are skipping those tests at the moment).

**Comment by traversaro** [comment]
The conda-forge packages have been released, can you check if they work as you expect!

**Comment by MittelmanDaniel** [comment]
Yes! thank you! @traversaro
