### ISSUE TITLE
[Proposal] Add the width and height check of the `OffScreenViewer`

### ISSUE THREAD

**Issue by Beanpow** [Farama-Foundation/Gymnasium#1225]
### Proposal

The `width` and `height` of `OffScreenViewer` cannot be None otherwise, it will cause the error. Adding a type check before creating the opengl_context could provide more information for debugging, at least the glfw backend.

### Motivation

I used the `MujocoRenderer` to render a MuJoCo model outside the gymnasium project. And I forgot to set the `width` and `height` because the `gymnasium==0.29.1` has the default value.

```
self.renderer = MujocoRenderer(self.model, self.data, CAMERA_CONFIG)
```

So the following error occurs.
```
Exception ignored in: <function GLContext.__del__ at 0x111d33c70>
Traceback (most recent call last):
  File "envs/vis/lib/python3.10/site-packages/mujoco/glfw/__init__.py", line 45, in __del__
    self.free()
  File "envs/vis/lib/python3.10/site-packages/mujoco/glfw/__init__.py", line 38, in free
    if self._context:
AttributeError: 'GLContext' object has no attribute '_context'
RuntimeError: No OpenGL backend could be imported. Attempting to create a rendering context will result in a RuntimeError.
Exception ignored in: <function OffScreenViewer.__del__ at 0x1101436d0>
Traceback (most recent call last):
  File "envs/vis/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 202, in __del__
    self.free()
  File "envs/vis/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 199, in free
    self.opengl_context.free()
AttributeError: 'OffScreenViewer' object has no attribute 'opengl_context'
```

The traceback info is not straightforward for debugging, maybe adding a type check is better.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for reporting the problem, could you make a PR to fix the issue?

**Comment by Beanpow** [comment]
Sure

**Comment by Kallinteris-Andreas** [comment]
The check should be in `MujocoRenderer.__init__()`

**Comment by Beanpow** [comment]
The `WindowViewer` supports the None value of the width and height. Why not add this check inside the `OffScreenViewer`? Or maybe we can do the same thing as `WindowViewer`. If the value of width or height is None, set the width and height to the default value.

https://github.com/Farama-Foundation/Gymnasium/blob/02f829872270505f063ef6c3292321f640aaf677/gymnasium/envs/mujoco/mujoco_rendering.py#L325-L326

**Comment by Kallinteris-Andreas** [comment]
1) Honestly, I have no idea why the window viewer accepts `None` input.
2) I would prefer it if all the checks were in the init of `MujocoRender` (the class that manges thes renderers)

**Comment by Beanpow** [comment]
How about adding the default value for `OffScreenViewer`?

**Comment by Kallinteris-Andreas** [comment]
There's no benefit to the off-screen viewer handling `witdh=none`

Also you now Introduce the problem of defining what the default is, Which may not be the same for all environments

**Comment by Beanpow** [comment]
The `WindowViewer` accepts the None value, and the default of the width and height is quite reasonable and convenient. If we add the check in the `MujocoRenderer.__init__()` and raise an error, we cannot use the default setting of `WindowViewer`. Maybe we can raise a warning or add the check in `MujocoRenderer._get_viewer()`.

**Comment by Kallinteris-Andreas** [comment]
```py
if render_mode != "human"
    # do your checks
```
