### ISSUE TITLE
Vectorized FrameSkip Wrapper

### ISSUE THREAD

**Issue by jarbus** [Farama-Foundation/Gymnasium#1238]
The v1.0.0 release notes said to raise a feature request if there's a vectorized wrapper we'd like but isn't available. I'm looking to use a vectorized version of the frameskip wrapper

**Comment by pseudo-rnd-thoughts** [comment]
Hi, we don't include that currently. 
Could you create a PR to add this or if you are using Async or Sync then you should be able to use it within the sub environment rather than outside with a vector wrapper

**Comment by jarbus** [comment]
Somehow, I missed the fact that you can apply wrappers within a sub environment for sync/async vectorized envs, that seems to be exactly what I need. Thanks!
