### ISSUE TITLE
It says it will update after each episode, but looking at the code it updates after each move

### ISSUE THREAD

**Issue by worthy7** [Farama-Foundation/Gymnasium#1252]
https://github.com/Farama-Foundation/Gymnasium/blame/ebe70a1aebcbf00f5f137e98da250b089ce7ad74/docs/introduction/train_agent.md#L108

Am I mistaken?

**Comment by pseudo-rnd-thoughts** [comment]
Your right that the policy is updated every observation and is trained for a limited number of episodes. @worthy7 Would you be able to make a PR to correct it?
