### ISSUE TITLE
Calling play() from gymnasium.utils.play will error if render_mode is not in ["rgb_array", "rgb_array_list]"

### ISSUE THREAD

**Issue by axb2035** [Farama-Foundation/Gymnasium#126]
### Describe the bug

I had made an assumption that from gymnasium.utils.play import play would support text rendering. Seems that was a bad assumption and that only pygame rendering is supported i.e. render_mode in ["rgb_array", "rgb_array_list]". 

However, if you pass a mode not in that list e.g. render_mode="human", it is captured and sends a message to the logger. However, it the script doesn't exit and it crashes shortly after when it tries to obtain the video size with `assert rendered is not None and isinstance(rendered, np.ndarray)`

### Code example

```shell
import gymnasium as gym
from gymnasium.utils.play import play

mapping = {"2": 1,  # Down.
           "4": 0,  # Left.
           "6": 2,  # Right.
           "8": 3,  # Up.
           }

play(gym.make('FrozenLake-v1', render_mode='human'), keys_to_action=mapping)
```

### System info

Gymnasium installed with pip
gymnasium.__version__ '0.26.3'
Python 3.10.6
Windows 10.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Markus28** [comment]
I'll look into it

**Comment by axb2035** [comment]
Thanks @RedTachyon and @Markus28.
