### ISSUE TITLE
[Bug Report] rgb_array rendering in mujoco environments upside down

### ISSUE THREAD

**Issue by Sebastian-Griesbach** [Farama-Foundation/Gymnasium#1261]
### Describe the bug

Hi, I'm not sure about this one as I just recently noticed this behavior and can't remember seeing it before.
Render Mujoco environments as an RGB array renders the image upside down.

The code itself even mentions that the image is upside down (**mujoco_rendering.py line 262**) and already flips it but only in the render modes "depth_array" and "rgbd_tuple" and not for "rgb_array" even though the rgb_array image is also upside down. 

Adding 
```
rgb_img = rgb_img[::-1, :]
```
as **line 266** fixes this issue but I don't think this is the right way as for render mode "rgbd_tuple" the image would be flipped twice in this case. I lack the understanding of this code to propose a pull request I am afraid but It seems to me that something does not work as intended here. 

### Code example

```shell
# run in a jupyter notebook
import gymnasium as gym
import matplotlib.pyplot as plt

env = gym.make('HalfCheetah-v5', render_mode='rgb_array')
env.reset()
image = env.render()
plt.imshow(image)
```

### System info

Source installation from the repository via pip. Current main branch.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Sebastian-Griesbach** [comment]
> works fine locally

Thank you for checking!
I assumed it must be something with my installation then, so I tried it again in a clean installation but the behavior persisted.

These are the steps I did to install the environment in my local gymnasium repository directory:
```
python -m venv env
source env/bin/activate
pip install -e .[all]
pip install jupyter matplotlib
jupyter notebook
```
The commit I am on is: **13230f4a120336b45c880b644585056d31f4c956**
My python version: **3.12.3**
My pip version: **24.0**

This is the result I see in the notebook.

![Screenshot from 2024-11-27 11-29-08](https://github.com/user-attachments/assets/2240206c-c05e-4e2b-8c3d-d6171c7eaccf)

I am a bit clueless as to why this behavior would appear in my installation but not in yours. Are there maybe some other affecting dependencies I am not aware of?

**Comment by pseudo-rnd-thoughts** [comment]
@Sebastian-Griesbach Thanks for the raising this. 
There is more to this an I expected at first. 

```python

**Comment by Sebastian-Griesbach** [comment]
What is also weird is how I noticed this. I build a logger which sometimes renders episodes and hands the frames (which I create the same way how I create the image here) to wandb for logging. I have done this several times before without changing anything about the underlying code but at some point (I think after installing gymnasium from source) the videos were all upside down which they weren't before. And now, for some reason, I don't understand, the Mujoco videos are the right side around again and I don't know what changed. Also, I used to log videos of Atari games as well, which were always the right way up. 

Now I have two virtual environments in both of which the same gymnasium 1.0.0 version is installed and in one of them the images are upside down and in the other, they are not. The only obvious difference I see right now is that the latter environment used Python version 3.9.20 instead of 3.12.3. But that could also be a fluke as I have been using this environment for a while. Not sure if any of this is helpful. But thank you for looking into this. Maybe If I have some spare time I'll try to pinpoint what exactly is the difference between those two environments.

**Comment by pseudo-rnd-thoughts** [comment]
@Kallinteris-Andreas The bug is real and only on main due to #1229 

https://github.com/Farama-Foundation/Gymnasium/blob/13230f4a120336b45c880b644585056d31f4c956/gymnasium/envs/mujoco/mujoco_rendering.py#L285

Was added which flips the image for some reason. 

I think we just need to revert this line and everything should work. @Kallinteris-Andreas Could you double check this is the only issue before we fix it

**Comment by Kallinteris-Andreas** [comment]
No, this behavior was before rgbd

**Comment by pseudo-rnd-thoughts** [comment]
See this from before #1229, the flip was done on the return
https://github.com/Farama-Foundation/Gymnasium/blame/0e94c46b44873a23f85e635d552c74e2755f8473/gymnasium/envs/mujoco/mujoco_rendering.py#L285
