### ISSUE TITLE
[Question] make_vec() prevent reset behaviour from happening when enviroment returnes done = True

### ISSUE THREAD

**Issue by BN7002** [Farama-Foundation/Gymnasium#1265]
### Question

Hello, I am training a policy using gymnaiusm api with use of ```gymnasium.make_vec()```  set to sync mode but it is not aligned to being a sync mode. When my enviroment returnes ```done = True``` then the next step it will restart enviroment that returned that ``` done = True```. 
So in this situation is there a way to prevent this behaviour?

**Comment by pseudo-rnd-thoughts** [comment]
Yes, we have merged https://github.com/Farama-Foundation/Gymnasium/pull/1227 that adds support for different autoreset modes and will be released in v1.1
