### ISSUE TITLE
[Proposal] Seed for `generate_random_map()` in FrozenLake?

### ISSUE THREAD

**Issue by kir0ul** [Farama-Foundation/Gymnasium#127]
### Proposal

Could be useful to be able to pass a seed to the `generate_random_map()` function in FrozenLake.

### Motivation

Being able to get reproducible generated maps.

### Pitch

Being able to call `generate_random_map(size=8, seed=123)`.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
This seems like a critical issue, could you make a PR that solves this. 
Not sure, if we want the `__init__` to contain a `map_seed` parameter or for the map data to be set in `reset` and use the `seed` value
