### ISSUE TITLE
[Question] Normalize Environment Termination Status for Consistent Success/Failure Semantics

### ISSUE THREAD

**Issue by ekomlenovic** [Farama-Foundation/Gymnasium#1273]
### Question

I noticed that the interpretation of `terminated` and `truncated` in environments can vary significantly. For example, in the CartPole environment, a `terminated` state indicates failure, while in the Acrobot environment, `terminated` corresponds to success.  

This inconsistency makes it difficult to determine whether the end of an episode represents a success or failure across different environments.  

Would it make sense to standardize this behavior? Specifically:  
- Is there currently any metadata or signal in the environments that clearly indicates whether an episode ended in success or failure?  
- If not, would it be more intuitive to replace `terminated` and `truncated` with explicit labels like `success` or `failure` to better convey the outcome of an episode?  

This change could improve clarity and make it easier to build general-purpose agents that rely on consistent end-state semantics.

**Comment by pseudo-rnd-thoughts** [comment]
This is part of the semantics of reinforcement learning. The agent must learn to act optimally however only in binary situations will success or failure exist. 
Ironically, the two environments you note are not binary situations. 
Agents must survive for as longer as possible (cartpole) or finish the environment as quickly as possible (acrobot), therefore, success or failure doesn't make sense unlike a game of chess of exist (ignoring a draw)

**Comment by ekomlenovic** [comment]
In my project, I am working on generating reward functions and do not rely on the default rewards provided by the environments. My initial idea was to use success or failure as a metric to evaluate the quality of my generated reward functions.  

Given this context, what metrics would you recommend to evaluate the performance of my reward functions ? Any insights or suggestions would be greatly appreciated!

**Comment by pseudo-rnd-thoughts** [comment]
If you are working on enviornments like MetaWorld where agents need to complete a goal, then success or failure could be a valid metric to assess training performance.

**Comment by Kallinteris-Andreas** [comment]
In environments where determination can be a result of either a success or a failure state.
