### ISSUE TITLE
[Bug Report] deque_size error

### ISSUE THREAD

**Issue by ArshiaIlaty** [Farama-Foundation/Gymnasium#1275]
### Describe the bug

I came across an issue while running the Blackjack agent and the other agents as well—it raised a deque_size error.

### Code example

```shell
Upon investigation, I modified it to use buffer_length, which resolved the issue.
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for reporting but this has already been solved
