### ISSUE TITLE
[Proposal] FrameStackObservation wrapper for vector env

### ISSUE THREAD

**Issue by li-plus** [Farama-Foundation/Gymnasium#1279]
### Proposal

FrameStackObservation is implemented only for single env currently. It would be great if vector env supports this helpful wrapper. Is there any concern that it is not implemented for vector env?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
You can use `FrameStackObsrvation` within a vectorised environment, e.g.,`gymnasium.make_vec("ALE/Pong-v5", wrappers=(FrameStackObservation,))` just not on the "outside" of the vector enviornment. 
Do you have a custom environment that needs the wrapper on the outside?

**Comment by li-plus** [comment]
Thanks! I was wrapping outside so it wasn't working. It works by passing `wrappers` into `make_vec`.
