### ISSUE TITLE
[Proposal] Documentation Frozen Lake

### ISSUE THREAD

**Issue by MarionJS** [Farama-Foundation/Gymnasium#135]
### Proposal

Get the is_slippery parameter infos more visible in the documentation

### Motivation

When running Frozen Lake for the fisrt time, is_slippery add a default parameter set at true.
It's not explained in the documentation but only in the repository Github.
Can induce some difficulties when learning.
Also the info about this boolean are not easily readable on the documentation page.

### Pitch

Get a bigger policy or a title to separate the paragrah to the other ones.
Precise in the description that this parameter is set at true by default.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Would you be happy to make the PR? You should just need to update docstring in the `FrozenLake` environment

**Comment by MarionJS** [comment]
I just opened a [PR](https://github.com/Farama-Foundation/Gymnasium/pull/136)! :)

**Comment by pseudo-rnd-thoughts** [comment]
Addressed in #136
