### ISSUE TITLE
[Proposal] Add more content pages 

### ISSUE THREAD

**Issue by pseudo-rnd-thoughts** [Farama-Foundation/Gymnasium#142]
### Proposal

Below the introduction section on the [website](https://gymnasium.farama.org/), we include several pages on critical topics that provide an explanation in a short and less example based than tutorials

I believe we need to have the following pages (Some of these exist already)
1. Basic usage -  A basic explanation of how to use Gymnasium
2. Compatibility with OpenAI Gym -  How to use Gym compatible environments
3. v22 to v26 Migration Guide -  A migration guide for users updating code from v22 to v26 necessary for Gymnasium
4. Registering an environment - How to register / make an environment, including entry_points for environments
5. Training agents for environments - How to train an agent for environments, with links to cleanrl, etc
6. Speeding up environments - A discussion on how optimise environments, particularly through vectorisation 
7. Recording environments - How to record environments

**Comment by Kallinteris-Andreas** [comment]
@pseudo-rnd-thoughts close?
