### ISSUE TITLE
[Bug Report] Need to update `mujoco` version

### ISSUE THREAD

**Issue by vwxyzjn** [Farama-Foundation/Gymnasium#151]
### Describe the bug

When trying to add `dm_control`, dependency resolution fails because `mujoco` version is pinned at https://github.com/Farama-Foundation/Gymnasium/blob/33e32178ffdf040a095bd2c856f6410bc7ec1306/setup.py#L41

```
poetry add -G dm_control Shimmy dm_control
Using version ^0.1.0 for shimmy
Using version ^1.0.8 for dm-control

Updating dependencies
Resolving dependencies... (0.9s)

Because dm-control (1.0.8) depends on mujoco (>=2.3.0)
 and no versions of dm-control match >1.0.8,<2.0.0, dm-control (>=1.0.8,<2.0.0) requires mujoco (>=2.3.0).
So, because cleanrl depends on both mujoco (2.2) and dm-control (^1.0.8), version solving failed.
```

## Solution

Update the `mujoco` version in the `setup.py`

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Will be done in https://github.com/Farama-Foundation/Gymnasium/pull/71
