### ISSUE TITLE
[Bug Report] AtariPreprocessing Wrapper is unavailable

### ISSUE THREAD

**Issue by sdpkjc** [Farama-Foundation/Gymnasium#162]
### Describe the bug

AtariPreprocessing Wrapper does not seem to be available. Probably because of the lack of interfaces, no good solution has been thought of yet.

### Code example

```python
import gymnasium as gym

env = gym.make("GymV26Environment-v0", env_id="ALE/Breakout-v5")
env = gym.wrappers.AtariPreprocessing(env, frame_skip=1)
```

Output:

```shell
❯ python a.py
A.L.E: Arcade Learning Environment (version 0.8.0+919230b)
[Powered by Stella]
Traceback (most recent call last):
  File "/Users/zhaoyanxiao/Dev/abcdrl/a.py", line 4, in <module>
    env = gym.wrappers.AtariPreprocessing(env, frame_skip=1)
  File "/Users/zhaoyanxiao/opt/anaconda3/envs/abcdrl/lib/python3.9/site-packages/gymnasium/wrappers/atari_preprocessing.py", line 80, in __init__
    assert env.unwrapped.get_action_meanings()[0] == "NOOP"
AttributeError: 'GymEnvironment' object has no attribute 'get_action_meanings'
```

### System info

pip install
gymnasium0.26.3
python3.9.13
mypy0.991
macOS13.0.1

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for the issue, that is an interesting problem. 

In v0.27, we have solved the atari with `pip install shimmy[atari]` such that `gymnasium.make("ALE/Pong-v5")` works.
Could you test this with shimmy and see if the same issues exist.

**Comment by sdpkjc** [comment]
Thank you for your reply. The problem seems to have been resolved after installing shimmy[atari].

```python
import gymnasium as gym

env = gym.make(id="ALE/Breakout-v5")
env = gym.wrappers.AtariPreprocessing(env, frame_skip=1)
```

There is no error message in this code.

---

The existence of this problem also seems to indicate that the test code is not perfect, will future versions consider improving this part of the test?

**Comment by pseudo-rnd-thoughts** [comment]
Yes, I have opened an issue on this, it should be solved by the next release
