### ISSUE TITLE
[Bug Report] Lunar Lander Runs Slowly

### ISSUE THREAD

**Issue by ian-hendo** [Farama-Foundation/Gymnasium#170]
### Describe the bug

The Lunar Lander environment creates particles and updates their physics, even when not being rendered. This slows down wall-time training on the environment by ~5x-10x.

Wrapping said code within the step(.) function with if self.render_mode == "human": resolves the issue.

### Code example

```shell
if self.render_mode == "human":
    p = self._create_particle(
        3.5,  # 3.5 is here to make particle speed adequate
        impulse_pos[0],
        impulse_pos[1],
        m_power,
    )  # particles are just a decoration
    p.ApplyLinearImpulse(
        (ox * MAIN_ENGINE_POWER * m_power, oy * MAIN_ENGINE_POWER * m_power),
        impulse_pos,
        True,
    )
```

### System info

N/A

### Additional context

N/A

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Wow, if this is true that would be a significant speed up. Could you make a PR with the results and show that the observations don't change as a well

**Comment by ian-hendo** [comment]
Hi Mark,

Thanks for the quick reply. I will try and do as you say, but finding time
may be difficult at the moment unfortunately.

Also - off topic, but I see your bio on github says you are a PhD student
at UoS studying RL. Incidentally, I am also a PhD student at UoS studying
RL! Perhaps it would be good to have a chat to each other outside of this
issue report?

Kind Regards,
Ian

**Comment by pseudo-rnd-thoughts** [comment]
Yes, am at the Uni of Southampton. I will send you an email to your soton address

**Comment by pseudo-rnd-thoughts** [comment]
We can include the optimising in the `render_mode=="rgb_array"`

**Comment by mbertheau** [comment]
I'm currently at `if self.render_mode is not None`. That seems to cover all cases.

**Comment by mbertheau** [comment]
What did you have in mind for the test?

**Comment by pseudo-rnd-thoughts** [comment]
If the rendering is deterministic, could you save the rendered frames then make the change and see if the rendered frames are the same (using the same actions and reset seed). Don't think we want this added to the actual tests, could include the test code for someone to replicate. 
Then add a quick performance test to show the difference in fps? 

I don't think we can add anything to the actual tests in the project as the old version won't exist after the fix.

**Comment by PaulMest** [comment]
I've been going through the HuggingFace RL course over the holidays and also discovered this. Submitted the fix for it here: https://github.com/Farama-Foundation/Gymnasium/pull/235. Results appear to be pretty great for such a small change!
