### ISSUE TITLE
[Proposal] Add wrappers used to EnvSpec

### ISSUE THREAD

**Issue by WillDudley** [Farama-Foundation/Gymnasium#181]
### Proposal

Add wrapper info to an environment's spec to achieve full reproducibility in a readable manner.

### Motivation

I'm no expert on the registry, but from my understanding [EnvSpec](https://github.com/Farama-Foundation/Gymnasium/blob/7e885597633bd7d9730ddf7c9524fda5d960ecb9/gymnasium/envs/registration.py#L122) is meant to aid in maximal reproducibility of Gymnasium environments. I trust that it does this at the base level, but I don't think it includes wrappers.

Maximal, complete reproducibility of RL environments is of vital importance for reproducibility and versioning of both models and datasets. We need a system that provides a bijection (two-way conversion) between structured, readable data and a Gymnasium environment.

### Pitch

We need a system that provides a bijection (two-way conversion) between structured, readable data and a Gymnasium environment. This involves:

- Extending env.spec to include wrappers,
- creation of a function to generate a gymnasium environment from env.spec,
- writing of tests to assert this complete reproducibility.

Something of this ilk:

```py
env = gym.make("halfcheetah-v4", <kwargs>)
env = wrapper_1(env, <kwargs>)
env = wrapper_2(env, <kwargs>)

complete_env_spec = env.spec

recreated_env = gym.make_from_spec(complete_env_spec)

assert env == recreated_env
```

### Alternatives

EzPickle was/is an answer to this which some of us have contributed to. Here are some disadvantages of it:

- It's unreadable data,
- it relies on pickle, making it unsafe to share,
- there's little documentation surrounding it.

### Additional context

Note that the order of wrappers applied may matter, so this information should be kept.

This feature is necessary for Minari to fully shine, as datasets need to be fully reproducible.

This feature should also be added to PettingZoo 2.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by WillDudley** [comment]
This could be achieved by having wrappers inherit from a superclass which modifies/extends env.spec with important wrapper attributes.

**Comment by WillDudley** [comment]
I'm not committed to this proposal but I do think there needs to be a standardised env stack spec. We're wanting to generate datasets for gymnasium robotics soon, and it'd be good to include the env stack in the metadata for reproducibility puroposes.

1. JSON would provide a readable data structure. I'm envisioning utility in being able to read the JSON file without needing to rebuild the code. I didn't consider arrays and lists though, but there are non-pickle ways. I'm not entirely against using pickle if it is already the established way to store environment specs.
2&3. I'm unsure of the details on how to answer these questions. 

Admittedly, I've never used `EzPickle` before and I can't seem to find examples on how it is used. However, if EzPickle is the recommended way to store environments, what's the use of `env.spec`? Something like `encode_env_stack(env)` is along the lines of what I'm thinking.

**Comment by pseudo-rnd-thoughts** [comment]
I agree that this is a feature we should agree on before the experimental wrappers are set as default

I think the most important feature that you note is if we need to safely load the specifications. 
Looking at Huggingface, who have the same issues as us, https://huggingface.co/docs/hub/security-pickle https://huggingface.co/docs/hub/security-malware

From the first page, there doesn't seem to be an optimal solution for this, so Huggingface have started creating its own module, `safetensor`. Im in the process of working out if we need use it

`EzPickle` doesn't have any documentation which we should probably change, but all it does is save all of the args and kwargs and implements the `__getstate__` and `__setstate__` functions which are used by pickle. 
Therefore, I think we should add `EzPickle` to each wrapper individually, not to `Wrapper` itself.

The more I think about `encode_env_stack`, the more I dislike the name, `env.spec_stack` could be better which is very similar to your original proposal but keeps `spec` however is similar enough for users. Im uncertain about a new `make` function, I think it should be possible to implement this in `make`.

```python
@dataclasses
class WrapperSpec:
    name: str
    entry_point: str
    args: list[Any]
    kwargs: list[Any]
```

**Comment by WillDudley** [comment]
What would the link be between `env.spec_stack` and `EzPickle`? I'm still confused why both are being used if they hold the same information.

**Comment by pseudo-rnd-thoughts** [comment]
The reason for wanting a `WrapperSpec` is that `gymnasium.make(EnvSpec)` can create an environment from the spec. I was thinking about a `gymnasium.make(list[WrapperSpec])` should work as well and is easier to interpret that `EzPickle` data. 
I think the `env.spec_stack` should look something like
```python
@property
def spec_stack(self):
    wrapper_spec = WrapperSpec(self.__name__, self.__module__ + "." + self.__name__, self._ezpickle_args, self.ezpickle_kwargs)
    if isinstance(self.env, Wrapper):
         return (wrapper_spec,) + self.env.spec_stack
    else:
         return (wrapper_spec,) + self.env.spec
```

**Comment by WillDudley** [comment]
Ah ok, so `EzPickle` is just used to generate `spec_stack`? Because it's the standard way to serialise arguments that may be lists/arrays? 

So basically if we had
```py
env = gym.make('LunarLander-v2')
env = RescaleAction_v0(env, -10, 10)
env = TransformReward_v0(env, lambda r: 0.01*r)
```

then `env.spec_stack` would be 
```py
(WrapperSpec('TransformReward_v0', <lambda r: 0.01*r>), WrapperSpec('RescaleAction_v0', <-10>, <10>), EnvSpec('LunarLander-v2'))
```
, where `<x>` means the pickled version of `x`?

Would this mean it's impossible to easily read the kwargs if they're pickled?
