### ISSUE TITLE
[Bug Report] The Incredible Shrinking Window! (PyGame surface resizes in infinite loop)

### ISSUE THREAD

**Issue by statusfailed** [Farama-Foundation/Gymnasium#187]
### Describe the bug

I'm trying to run the [example code](https://gymnasium.farama.org/api/utils/#visualization) given for the `play` utility function.

However, when I run this code, the window shrinks by 2 pixels for every frame rendered.
I think this is because my window manager adds a `1px` border to the game window.

The problem seems to come from the following code in `play.py` on [lines 116-118](https://github.com/Farama-Foundation/Gymnasium/blob/main/gymnasium/utils/play.py#L116-L118):

        elif event.type == VIDEORESIZE:
            self.video_size = event.size
            self.screen = pygame.display.set_mode(self.video_size)

If I add `print(event)` to this `elif` block, I get the following output:

    <Event(32769-VideoResize {'size': (598, 398), 'w': 598, 'h': 398})>
    <Event(32769-VideoResize {'size': (596, 396), 'w': 596, 'h': 396})>
    <Event(32769-VideoResize {'size': (594, 394), 'w': 594, 'h': 394})>
    <Event(32769-VideoResize {'size': (592, 392), 'w': 592, 'h': 392})>
    <Event(32769-VideoResize {'size': (590, 390), 'w': 590, 'h': 390})>

Removing the line

            self.screen = pygame.display.set_mode(self.video_size)

fixes the problem. I believe this is because setting the video mode creates an infinite loop where a new `VIDEORESIZE` event is created, triggering `set_mode` again.

### Code example

```shell
#!/usr/bin/env python3

import numpy as np
import gymnasium as gym
from gymnasium.utils.play import play

import gymnasium as gym

from gymnasium.utils.play import play

play(gym.make("CarRacing-v2", render_mode="rgb_array"), keys_to_action={
        "w": np.array([0, 0.7, 0]),
        "a": np.array([-1, 0, 0]),
        "s": np.array([0, 0, 1]),
        "d": np.array([1, 0, 0]),
        "wa": np.array([-1, 0.7, 0]),
        "dw": np.array([1, 0.7, 0]),
        "ds": np.array([1, 0, 1]),
        "as": np.array([-1, 0, 1]),
        }, noop=np.array([0,0,0]))
```

### System info

Installation method: `pip install`
gymnasium version: `0.26.3`
OS: Arch Linux
Python version: `3.10.8`

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for the issue, this is very strange. 
I suspect that the issue is with Arch and pygame but we will investigate to see if we can replicate this on other OS.

**Comment by Markus28** [comment]
I can't reproduce this issue on MacOS. I will try later on Ubuntu.

**Comment by statusfailed** [comment]
I'm pretty sure this is a window manager issue. I've had a similar issue when developing with Vulkan.
IIRC, when creating a surface with a given size, the result comes back with a size that subtracts the window border.

I'm using xmonad, but I suspect similar tiling window managers (e.g., sway(?)) might have the same problem.

**Comment by pseudo-rnd-thoughts** [comment]
> In the meantime, we could allow users to disable resizing using some keyword argument? @pseudo-rnd-thoughts ?

I don't think that is necessary as unless users try to resize the window then this should be completely backward compatibility

**Comment by statusfailed** [comment]
@Markus28 Yep, the code in #190 fixes it. Also the window is resizable, which is neat :-)
