### ISSUE TITLE
[Proposal] `play` callback for Minari

### ISSUE THREAD

**Issue by Markus28** [Farama-Foundation/Gymnasium#202]
### Proposal

Add a class that implements a callback function to record transitions that are generated in `play` to a Minari dataset.

### Motivation

This might be convenient for anyone who wants to train agents from human demonstrations

### Alternatives

Implement it in the Minari repository, or somewhere else.

### Additional context

We might want to add a cleanup callback to the play function that is executed once the window is closed. This cleanup callback would be used to actually store the data to disk. 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Kallinteris-Andreas** [comment]
@younik do you want such a function in minari?
If so, transfer the issue there, if not feel free to close this issue

**Comment by pseudo-rnd-thoughts** [comment]
#203 specified that this change would happen in Minari
