### ISSUE TITLE
[Bug Report] Why does reacher have z-value of position_fingertip - position_target 

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [Farama-Foundation/Gymnasium#220]
### Describe the bug

[z-value of position_fingertip - position_target ](https://gymnasium.farama.org/environments/mujoco/reacher/#observation-space)

the last observation is a constant 0, no reason for it to be there, perhaps a thing to change, if we decide to make mujoco-v5

@rodrigodelazcano 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by rodrigodelazcano** [comment]
Yes, we should benchmark this as well and then consider the fix.

**Comment by Kallinteris-Andreas** [comment]
![](https://github.com/Kallinteris-Andreas/gymnasium-robotics-mujuco-v5-envs-validation/blob/main/figures/TD3_Reacher.png?raw=true)
The only difference between `v4` and `v5` is that `v5` excludes the z-distance of tip-target
Note: thought the benchmark it was asserted that the value was constant 0

I can not justify the difference in performance

**Comment by pseudo-rnd-thoughts** [comment]
RL is strange, could you share your code? Could it be due to any other changes in v5?

**Comment by Kallinteris-Andreas** [comment]
`V4` code: https://github.com/Farama-Foundation/Gymnasium/blob/main/gymnasium/envs/mujoco/reacher_v4.py
`V5` code: https://github.com/Kallinteris-Andreas/gymnasium-robotics-mujuco-v5-envs-validation/blob/main/envs/reacher_v5.py

you can use a service like [diffchecker.com](https://www.diffchecker.com/)
and you can see the only difference in `_get_obs()`

**Comment by Kallinteris-Andreas** [comment]
Update:
![](https://github.com/Kallinteris-Andreas/gymnasium-robotics-mujuco-v5-envs-validation/blob/main/figures/Reacher.png?raw=true)
I was running the `Reacher-v5` with `max_time_steps=1000` instead of `50`

Here we have `reacher-v5` with `max_time_steps=50`, we can see besides some weird transient training performance, it does appear to converge to near the same point

**Comment by pseudo-rnd-thoughts** [comment]
It seems to just be much slower to converge which makes sense. 
Are you planning on keeping `max_time_steps=50` then?

**Comment by Kallinteris-Andreas** [comment]
I was never planning on changing `max_time_steps=50`

**Comment by Kallinteris-Andreas** [comment]
KK
