### ISSUE TITLE
[Bug Report] RecordEpisodeStatistics wrapper doesn't return the correct number of datapoints.

### ISSUE THREAD

**Issue by till2** [Farama-Foundation/Gymnasium#226]
### Describe the bug

When using the wrapper env to record episode returns (return_queue) and episode lengths (length_queue), the number of datapoints in the queues is less than the number of episodes played, which shouldn't be the case when using deque_size=n_episodes as in:

`wrapper_env = gym.wrappers.RecordEpisodeStatistics(env, deque_size=n_episodes)`

The number of datapoints that are being saved in the queues also varies run to run (with the same code and parameters).

Maybe this is an issue with how i am using `for i in range(max_episode_length):` and `if done: break`?

Added code to reproduce this issue below.

### Code example

```shell
import gymnasium as gym
from tqdm import tqdm 

# environment setup
env = gym.make('LunarLander-v2')
n_episodes = 10000
max_episode_length = 100

# create a wrapper environment to save episode returns and episode lenghts
wrapper_env = gym.wrappers.RecordEpisodeStatistics(env, deque_size=n_episodes)

# use tqdm to get a progress bar for training
for episode in tqdm(range(n_episodes)): 

    # reset the environment
    done = False
    state, info = wrapper_env.reset()

    # play one episode
    for i in range(max_episode_length):
        
        state, reward, terminated, truncated, info = wrapper_env.step(env.action_space.sample())
        
        # update if the environment is done
        done = terminated or truncated
        
        if done:
            break

# how many datapoints were saved?
print(len(wrapper_env.return_queue))

wrapper_env.close()
```

### System info

Linux Mint (PC)
Python: 3.10.4
Gymnasium: 0.26.2

### Additional context

Here are some runs with the code above and different parameters `n_episodes` and `max_episode_length`:

- with n_episodes=500,   max_episode_length=600:  500   (correct)
- with n_episodes=1000,  max_episode_length=600:  998   (wrong)
- with n_episodes=4000,  max_episode_length=600:  3996  (wrong)
- with n_episodes=5000,  max_episode_length=600:  4995  (wrong)
- with n_episodes=5000,  max_episode_length=1000: 5000  (correct)
- with n_episodes=10000, max_episode_length=1000: 10000 (correct)
- with n_episodes=10000, max_episode_length=300:  9990  (wrong)
- with n_episodes=10000, max_episode_length=50:   0     (wrong)
- with n_episodes=10000, max_episode_length=100:  6694  (wrong), second run: 6655, third run: 6765
- with n_episodes=10000, max_episode_length=150:  9942  (wrong)

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
It is as the return queue is only added when `terminated or truncated` is true. 
However as the environment time limit is < `max_episode_lengths` then there are a number of cases where `terminated or truncated` is never true

**Comment by till2** [comment]
So `while not done` would be the only correct implementation and `for i in range(max_episode_length)` to limit the episode length is not a good way of implementing it?

**Comment by pseudo-rnd-thoughts** [comment]
If you want a different max limit on the number of time steps, you can do `gym.make("env_name", max_episode_steps=100)` which will modify the `TimeLimit` wrapper value. 
Otherwise, yes, the only way for `return_queue` to include all episode returns is to use `while not done`

**Comment by till2** [comment]
I see, didn't know about the TimeLimit wrapper. Thanks for the explanation!
