### ISSUE TITLE
[Bug Report] Link error in envrionment_creation tutorial

### ISSUE THREAD

**Issue by helpingstar** [Farama-Foundation/Gymnasium#231]
### Describe the bug

https://github.com/Farama-Foundation/Gymnasium/blob/8f0baf62aa13c69c77dc00bed0060e09d700890a/docs/tutorials/environment_creation.py#L23

If you click [the documentation of Gymnasium’s API](https://gymnasium.farama.org/api/core) in [Make your own custom environment](https://gymnasium.farama.org/tutorials/environment_creation/) of the doc's tutorial, '404 Page not found' occurs.

The link connects to `/api/core`, which does not currently exist in the "gymnasium.farama.org" doc.

It seems to be a problem caused by moving the doc from gymlibrary.dev.

It would be nice to change from `/api/core` to `/api/env`.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Thanks, could you make a PR to solve this. 
You will need to modify the `docs/api/core`
