### ISSUE TITLE
[Bug Report] High values of up-bounded ints are never sampled in spaces.Box

### ISSUE THREAD

**Issue by khoda81** [Farama-Foundation/Gymnasium#236]
### Describe the bug

When int spaces are only up-bounded, `space.sample()` never returns the high value. I investigated this issue and it turns out to be related to this line:
https://github.com/Farama-Foundation/Gymnasium/blob/78b50ff6bc5b09be57a9a8c9f10c687fadb746b1/gymnasium/spaces/box.py#L221
The high value is missed when taking the floor of the continuously sampled values. This could be a fix:
```python
sample[unbounded] = np.round(sample[unbounded])
sample[low_bounded] = np.floor(sample[low_bounded])
sample[upp_bounded] = np.ceil(sample[upp_bounded])
sample[low_bounded] = np.round(sample[low_bounded])
```

### Code example

```shell
>>> space = gymnasium.spaces.Box(low=-float("inf"), high=0, shape=(), dtype=int)
>>> 0 in space
True
>>> 0 in [space.sample() for _ in range(10000)]
False
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for the issue but Im still a bit confused.

With your example, it seems unlikely that you will ever sample `0` even with `dtype=int` with a lower bound of `-inf`.
If you don't use `-inf` as the lower bound is it now possible or what are the values that are generated from this space.

@RedTachyon Do you understand?

**Comment by khoda81** [comment]
@pseudo-rnd-thoughts Thanks for the reply
> With your example, it seems unlikely that you will ever sample `0` even with `dtype=int` with a lower bound of `-inf`.
```python
>>> from collections import Counter
>>> from gymnasium.spaces import *
>>> space = gymnasium.spaces.Box(low=-float("inf"), high=0, shape=(), dtype=int)
>>> Counter(space.sample() for _ in range(10000))
Counter({-1: 6286,
         -2: 2289,
         -4: 324,
         -3: 891,
         -5: 115,
         -6: 59,
         -8: 5,
         -7: 24,
         -10: 2,
         -9: 4,
         -11: 1})
```
It is not unlikely its impossible that's the issue. Look at how many -1s there are. The reason I expect thisto be a bug is that by using exponential distribution 0's should be more likely than -1s. It works the other way though:
```python
>>> space = gymnasium.spaces.Box(low=0, high=float("inf"), shape=(), dtype=int)
>>> Counter(space.sample() for _ in range(10000))
Counter({0: 6419,
         1: 2282,
         3: 299,
         2: 838,
         4: 105,
         6: 9,
         5: 39,
         7: 6,
         9: 1,
         8: 1,
         12: 1})
```

**Comment by pseudo-rnd-thoughts** [comment]
Ahh that makes sense. Sorry I forgot that we use the exponential distribution for cases with only one `inf` for `low` or `high`. 
So you are right. 
Could you make a PR to solve this with tests in `tests/spaces/test_box.py` for both `low=-inf` and high=`inf` that it is possible to sample the `high` or `low` value respectively. 

Quick question, does the sampling work for `low=[0, -inf]` and `high=[inf, 0]`

**Comment by khoda81** [comment]
@pseudo-rnd-thoughts 
How can I test the random behavior of `sample`? Yes, with `low=[0, -inf]` and `high=[inf, 0]` the problem still persists on the second value.

**Comment by pseudo-rnd-thoughts** [comment]
> How can I test the random behavior of sample?

This is a complex question, I have implemented statistical testing for all of the other spaces to use custom KS testing. However, as Box has continuous sample value then I haven't bothered yet.
If you are interested in reading about the KS test and trying to implement it for Box.
See the `tests/spaces/test_spaces.py` for `test_samples` and `test_sample_masks` functions.

Otherwise, a simple test that you can sample `0` with the two examples `inf` spaces you show

**Comment by khoda81** [comment]
I'm working on a pr to implement the ks test for `Box` and fix this bug and another bug related to this. Apparently `Box(low=False, high=True, dtype=bool)` never samples `False`.
Quick question, is it okay if I use `scipy` for the ks test?

**Comment by pseudo-rnd-thoughts** [comment]
Yes but you will need to add it to the testing dependencies in pyproject.toml
