### ISSUE TITLE
[Bug Report] StepAPICompatibility wrapper incompatible with Vector Environments

### ISSUE THREAD

**Issue by nidhishs** [Farama-Foundation/Gymnasium#237]
### Describe the bug

The `gymnasium.wrappers.StepAPICompatibility` to convert from v26 API to v21 API is non-functional with vector environments. A quick fix is to accept `is_vector_env` boolean flag in the wrapper arguments or determine using `isinstance` and pass it to the corresponding functions in `gymnasium.utils.step_api_compatibility` package.

### Code example

```shell
import gymnasium

vec_env = gymnasium.vector.make("CartPole-v1", num_envs=3)
vec_env_compat = gymnasium.wrappers.StepAPICompatibility(vec_env, False)
env = gymnasium.make("CartPole-v1")
env_compat = gymnasium.wrappers.StepAPICompatibility(env, False)

_ = env.reset()
step_returns = env.step(env.action_space.sample())
print("Without compatibility - Env:", len(step_returns))
# Without compatibility - Env: 5

_ = env_compat.reset()
step_returns = env_compat.step(env_compat.action_space.sample())
print("With compatibility - Env:", len(step_returns))
# With compatibility - Env: 4

_ = vec_env.reset()
step_returns = vec_env.step(vec_env.action_space.sample())
print("Without compatibility - VecEnv:", len(step_returns))
# Without compatibility - VecEnv: 5

_ = vec_env_compat.reset()
step_returns = vec_env_compat.step(vec_env_compat.action_space.sample())
print("With compatibility - VecEnv:", len(step_returns))_ = env.reset()
# Expected: Without compatibility - VecEnv: 4
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-8e284eb0ee61> in <module>
     12 
     13 _ = vec_env_compat.reset()
---> 14 step_returns = vec_env_compat.step(vec_env_compat.action_space.sample())
     15 print("With compatibility - VecEnv:", len(step_returns))

/usr/local/lib/python3.8/dist-packages/gymnasium/wrappers/step_api_compatibility.py in step(self, action)
     56             return convert_to_terminated_truncated_step_api(step_returns)
     57         else:
---> 58             return convert_to_done_step_api(step_returns)

/usr/local/lib/python3.8/dist-packages/gymnasium/utils/step_api_compatibility.py in convert_to_done_step_api(step_returns, is_vector_env)
     93         # Cases to handle - info single env /  info vector env (list) / info vector env (dict)
     94         if is_vector_env is False:
---> 95             if truncated or terminated:
     96                 infos["TimeLimit.truncated"] = truncated and not terminated
     97             return (

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

### System info

Tested on Google Colab: 
`gymnasium.__version__ = '0.27.0'`
`sys.version = 3.8.16`

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by nidhishs** [comment]
Would be happy to open a PR with a fix.

**Comment by pseudo-rnd-thoughts** [comment]
Yes, that would be great. Looking at the utility functions, vector environments are already supported, it just looks like you forgot to implement a parameter for the wrapper. 
Could you additionally, add test for check this still works

**Comment by pseudo-rnd-thoughts** [comment]
I would simply add an argument to the wrapper, this should avoid the `self.is_vector_env` part which confusingly can be fail in cases where users use a wrapper over a vector env then this would be false. 
You could add a warning
```python
if is_vector_env is True: 
    if not isinstance(env.unwrapped, gym.vector.VectorEnv):
        warn("...")
else:
    if isinstance(env.unwrapped, gym.vector.VectorEnv):
        warn("...")
```

For the testing, I would just create a new test and numpy is already a dependency so I wouldn't worry about that

**Comment by nidhishs** [comment]
I might be understanding you wrong, but what would be the benefit of adding an argument to the wrapper when it can be handled internally? Wouldn't something like `self.is_vector_env = isinstance(env.unwrapped, gym.Vector.VectorEnv)` be sufficient? Moreover, I think only a warning would not be sufficient since passing `is_vector_env = False` for a vector environment will cause a runtime error in the `step_api_compatibility` function.

**Comment by pseudo-rnd-thoughts** [comment]
The reason will be solve in a couple of versions time but `VectorEnv` are subclasses of `Env` however all wrappers are only subclasses of `Env`. Therefore, currently, this is normal code in gym / gymnasium (will be changed in the next release, v0.28 as an experimental feature and roll out in v0.30)

```python
import gymnasium as gym
from gymnasium.wrappers import RecordEpisodeStatistics, StepAPICompatibility 

vector_env = gym.vector.make("CartPole-v1", num_envs=3)
wrapped_env = RecordEpisodestatistics(vector_env)

old_env = StepAPICompatibility(wrapped_env)
```

As `wrapped_env` is not an instance of `VectorEnv` then the check you propose will fail. 
We could solve this through doing `isinstance(env.unwrapped, VectorEnv)` to avoid the wrapper issue.
