### ISSUE TITLE
Transferring from Gym to Gymnasium

### ISSUE THREAD

**Issue by sryu1** [Farama-Foundation/Gymnasium#242]
### Question

I'm having trouble transferring one of my Gym environments to Gymnasium, is there a fully documented changelog/documention that covers everything that changed?

**Comment by pseudo-rnd-thoughts** [comment]
If you have updated to gym v26, then it should be very easy to change but we provide compatibility environments if you want to use them
https://gymnasium.farama.org/content/gym_compatibility/

If you need to update gym version, we have a migration guide - https://gymnasium.farama.org/content/migration-guide/

**Comment by sryu1** [comment]
Hi! I don't really understand how to use the converter: https://gymnasium.farama.org/content/gym_compatibility/#step-api-compatibility

**Comment by sryu1** [comment]
could you please provide me an example for converting it? I don't really understand the documentation.

**Comment by sryu1** [comment]
nevermind, I got it.
