### ISSUE TITLE
[Question] DataLoader with AsyncVectorEnv

### ISSUE THREAD

**Issue by mvkvc** [Farama-Foundation/Gymnasium#253]
### Question

Hello! I am working with an environment where it loads time series data from a torch dataloader. When the environment resets I would like to change the time series interval and get a new sample from the dataloader.

Since it uses multiprocessing I am guessing that passing a shared dataloader object is not a good idea? Can I use a multiprocessing Queue that I fill with samples and pass that to the environment when using gymnasium.vector.make?

Thank you for taking the time to read this

**Comment by pseudo-rnd-thoughts** [comment]
Yes, it is possible to pass keywords to all of the sub-environments
Therefore, you should be able to do, `gym.vector.make("CustomEnv", dataloader=shared_dataloader)`
