### ISSUE TITLE
[Proposal] NormalizeX Wrappers should not always update their running statistics

### ISSUE THREAD

**Issue by raphajaner** [Farama-Foundation/Gymnasium#256]
### Proposal

Hi All,

Since I saw that there's some work done on rewriting the existing `gym.wrappers` (#140), I wanted to suggest that for wrappers that normalize something, e.g., `NormalizeObservation`, there should be a parameter that allows/blocks the updating of the running statistics of the `RunningMeanStd` object. During learning, I surely want to update these values but it should be possible to freeze these statistics during evaluation. What's your take on that?

### Pitch

Wrappers that normalize stuff should have a parameter, e.g., `self.allow_update: bool` that can be set and allows/blocks updating of the `RunningMeanStd`. For the new `NormalizeObservationV0` in `gymnasium/experimental/wrappers/lambda_observations.py`, I could image something simple like:
```python
class NormalizeObservationV0(ObservationWrapper):
    def __init__(self, env: gym.Env, epsilon: float = 1e-8):
        ...
        self.allow_update = True

    def observation(self, observation: ObsType) -> WrapperObsType:
        """Normalises the observation using the running mean and variance of the observations."""
        if self.allow_update:
            self.obs_rms.update(observation)
        return (observation - self.obs_rms.mean) / np.sqrt(
            self.obs_rms.var + self.epsilon
        )

```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
I think this is a good idea. 
@raphajaner Would you be able to make a PR to implement this?

**Comment by raphajaner** [comment]
Yes sure, might just that a few days :)

**Comment by pseudo-rnd-thoughts** [comment]
That is fine, I think we are hoping to make a minor release in the next week otherwise, there will be a major release in the next month

**Comment by pseudo-rnd-thoughts** [comment]
Completed in #268
