### ISSUE TITLE
[Proposal] `MuJoCo` add action space visualizations

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [Farama-Foundation/Gymnasium#261]
### Proposal

Add images to `MuCoCo` environments, that visualize the action space.

Example:
add this image:
![humanoid](https://user-images.githubusercontent.com/30759571/211975393-bdefa58c-543f-41f4-b4a8-611e247010ba.png)
to: https://gymnasium.farama.org/environments/mujoco/humanoid/#action-space

### Pitch

Assuming that the `Brax` based environments use the same action space, you could use them there also.

### Additional context

I have already made the images for `MaMuJoCo` example: https://gymnasium.farama.org/environments/mujoco/humanoid/#action-space

So it is not really any work.

Note: I do not have images for pendulum enviroments

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Yes, if you have able to make the figures then we would happily add them to the documentation

**Comment by rodrigodelazcano** [comment]
I've seen you've added the joint id's to the model image. Can you also add a table with joint id's, name in the xml file and type of joint?

**Comment by Kallinteris-Andreas** [comment]
It has actuators not, joints

and please elaborate, I do not understand, what do mean

**Comment by Kallinteris-Andreas** [comment]
i am closing this issue for now, i will do this after mujoco gets moves to robotics
