### ISSUE TITLE
[Bug Report] Cannot render CartPole-v1 on Ubuntu

### ISSUE THREAD

**Issue by tungts1101** [Farama-Foundation/Gymnasium#262]
### Describe the bug

I cannot render the CartPole game on my machine. There is no error showing up but there is also no window displaying.

### Code example

```shell
import gymnasium as gym
import time

env = gym.make('CartPole-v1', render_mode="rgb_array")
env.reset()

while True:
    action = env.action_space.sample()  # agent policy that uses the observation and info
    observation, reward, terminated, truncated, info = env.step(action)
    env.render()
    time.sleep(0.03)
    input("Press Enter to continue...")
    if terminated or truncated:
        observation, info = env.reset()

env.close()
```

### System info

Ubuntu 22.04.1, Python 3.10.6, Gym 0.27.0

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
You need to use `render_mode="human"`, "rgb_array" will only return the rendering info but present it to the user
