### ISSUE TITLE
[Question] Expected shape of one element arrays

### ISSUE THREAD

**Issue by ikamensh** [Farama-Foundation/Gymnasium#265]
### Question

I am wondering if np.array([1]) should be a valid element of Discrete(2) action space. It currently isn't because shape is expected as (), not (1,): https://github.com/Farama-Foundation/Gymnasium/blob/dcb150e8893161d941f8a3fff1baef232cad4d96/gymnasium/spaces/discrete.py#L95

How do people experienced in gym codebase reason about this? :)

**Comment by pseudo-rnd-thoughts** [comment]
Interesting question, personally, I wouldn't have an issue with modifying the contain function but I think users should require their space to `Box(low=discrete_space.start, high=discrete_space.start + discrete_space.n, shape=(1,), dtype=np.int64)` which is equivalent to what you want

**Comment by RedTachyon** [comment]
I think it makes sense as it is, i.e. `[1]` isn't a valid member of `Discrete(2)`. A discrete state is meant to be a lone integer and not an array. Shape-related errors are common enough as it is, so this extra piece of rigidity can help prevent them.
