### ISSUE TITLE
[Question] I don't know why RescaleAction example doesn't work on my project

### ISSUE THREAD

**Issue by alberto-atk** [Farama-Foundation/Gymnasium#266]
### Question

This is the example that appears in the library:
![image](https://user-images.githubusercontent.com/73551392/213161024-6794bd32-bb52-4687-84e4-1ac5368d7e36.png)

And that's the execution when I run the example in my Jupyter Notebook:
![image](https://user-images.githubusercontent.com/73551392/213161120-e150b8a8-f9d1-4e3f-a7bf-c8af88ae2103.png)

Does anyone know why?
Thanks!

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for pointing this out, it looks like the documentation is wrong as `RescaleAction` doesn't actually modify the `action_space` variable. 
If you have updated to v0.27.0 then we have new experimental wrappers that do implement this correctly.
`gymnasium.experimental.wrappers.RescaleActionV0` or `from gymnasium.experimental.wrappers import RescaleActionV0` which should update the `action_space` as expected

**Comment by alberto-atk** [comment]
Okey, thank you so much!!
