### ISSUE TITLE
[Proposal] Env checker is too strict

### ISSUE THREAD

**Issue by aaronwalsman** [Farama-Foundation/Gymnasium#269]
### Proposal

Either remove or improve the implementation of at least the following env checker warnings:
"It seems a Box observation space is an image but the lower and upper bounds are not [0, 255]...."
"A box observation space has an unconventional shape (neither an image, nor a 1D vector)..."
"It seems a Box observation space is an image but the `dtype` is not `np.uint8`..."

### Motivation

The Box is a generic observation/action space and (in my opinion, humbly) should not be restricted to 1D arrays and images.  Currently you get env checker warnings if your Box does not conform to one of these types.  I work a lot on custom environments, and use the Box extensively to represent image masks (2D with either a boolean dtype for binary masks or a long dtype for multi-class masks) and also 3D transforms (4x4 float32).  The env checker is useful to check for out-of-bounds errors, and actual issues that may cause serious problems, but it's not useful if those warnings are buried under a mountain of warnings about my non-standard (but totally working as I intention) spaces.

### Pitch

One option to solve this would be to just remove those warnings, but I suspect they are there for a reason?

Another option would be to make an ImageSpace that inherits from Box, but either hard-codes or has good defaults for the number of channels, low, high, dtype, etc.  For example the hard-coded version would look like:
```
class ImageSpace(Box):
    def __init__(height, width):
        super().__init__(low=0, high=255, shape=(height, width, 3), dtype=numpy.uint8)
```
...or the good-defaults version would look like:
```
class ImageSpace(Box):
    def __init__(height, width, batch=0, channels=3, dtype=numpy.uint8, low=0, high=255):
        if batch == 0:
            shape = (height, width)
        else:
            shape = (batch, height, width)
        if channels != 0:
            shape = shape + (channels,)
        super().__init__(low=low, high=high, shape=shape, dtype=dtype)
```
Then the env-checker could run whatever tests are necessary for images on the Image space, and whatever looser checks on the Box space, and it would be possible to build envs with non-standard spaces using Box without getting output polluted by well-meaning, but in this case irrelevant warnings.

### Alternatives

Add more verbosity levels to the checker?  I usually don't like these solutions though.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
This is an interesting point, Im reminded of pyright options, "strict", "basic" and "none". 

We would need to be careful but we could change the `disable_env_checker: Optional[bool]` to `Optional[bool | str]` where we provide the three options. This would provide future compatibility to increase or decrease changes. I would propose that `True -> "strict"` and `False -> "none"`.
The issue with this proposal is backward compatibility which we would need to be careful with

**Comment by aaronwalsman** [comment]
I want to follow up and explain a little bit about why I think handling this particular issue with verbosity levels is maybe not the best way to do it (there may be a good argument for verbosity levels for some other set of warnings however).  Let's consider three people who might see this error:

1. A person running RL experiments on an existing env, who is not interested in actively debugging the env.  These messages are just spam to this person, they are not developing the environment, they are just trying to make their thing work.
2. A person making a new env who is intentionally making nonstandard Box spaces (like me).  This message is also spam to this person.  They want to make a weirdly shaped/typed box, and this is the only way to do it.  It's annoying to be told your thing is wrong when you know what you're doing.
3. A person making a new env who is actually trying to make a space that is an image or 1D array, but set the parameters wrong.  This message may have some utility to this person, but in order to get that utility, these messages either need to be on by default, or this person needs to know enough to turn on the strict checking flag to get these warnings.  I'm going to further conjecture that if they don't know how to setup their Box space correctly, they probably also don't know how to set the strict flag.  If the strict flag is on by default, then persons 1 and 2 are going to have to remember to always turn down the verbosity level in their code or be perpetually annoyed.

The further point to make is that person 3 would get much more utility out of a special Image subclass of Box, because then they don't have to notice the warning, look it up, figure out how fix their Box, etc, they just have to use an Image and then there are no parameters for them to get wrong.

Granted, there's a lot of legacy code out there that uses Box spaces for images, but I'm going to (humbly) argue that adding the Image and making that the "correct/standard/future" way to do it isn't even that big of a breaking change.  Having old envs around that use Box spaces and new envs around that use Image spaces isn't really a problem because Image spaces are just a thin wrapper around the Box anyway.

Finally finally, if adding the Image space is too weird, the small utility that person 3 gets from seeing this message is probably not worth keeping these warnings in.  The odds are that if their Box is setup incorrectly and they are trying to do a standard thing, then they will notice as soon whatever problems the warnings are trying to make them aware of actually occur.

With that said, I defer to the wisdom of the core maintainers, but I do think having a general Box class that supports anything, but throws all kinds of warnings when you use it for anything outside of two common use cases is somewhat undesirable.

**Comment by gbenson** [comment]
I ran into the "Box observation space has an unconventional shape" warning trying to describe a 9x9 grid where each cell may or may not contain an items. The space I tried to create was this:

      spaces.Box(low=0, high=1, dtype=np.uint8, shape=(9, 9))

It seems this check would warn if you were using greyscale images too.  The ALE (Atari) environment does this:

       self._obs_type == "rgb" or self._obs_type == "grayscale":
            (screen_height, screen_width) = self.ale.getScreenDims()
            image_shape = (
                screen_height,
                screen_width,
            )
            if self._obs_type == "rgb":
                image_shape += (3,)
            self._obs_space = spaces.Box(
                low=0, high=255, dtype=np.uint8, shape=image_shape
            )

With this code, you'll get warned for obs_type="grayscale"  images, but RGB images will be allowed through.

Is there a way to sidestep this warning? It seems the only facility gymnasium offers is disabling the environment checker entirely for this environment, in register or make. I'd like the warning to go away (I'm using pytest, it's complaining) but I also don't want to lose _all_ checks.

Things I considered:
* The warning says "We recommend flattening the observation to have only a 1D vector or use a custom policy to properly process the data. ".  I couldn't find any hooks to implement this though, other than maybe subclassing `spaces.Box` and presumably losing all other useful checks.
* I _could_ silence the warning by creating an array of shape (9,9,1), but that seems unnatural. I'm not super experiened with numpy or ML though... is it common practice  to represent greyscale images this way? 
* I could also potentially make the logger filter out that warning alone, but that's very much a last resort!

**Comment by pseudo-rnd-thoughts** [comment]
@aaronwalsman Sorry for now responding, in working on [shimmy](https://github.com/farama-Foundation/shimmy/) then this warning comes up more than I expected when originally added. 
Personally, I would be happy to comment out these warnings, while helpful in some cases, I think you are right that the `Box` is a generic space that should not be restrict. 
Would you be interested in making the change?

**Comment by aaronwalsman** [comment]
Sounds good, I think removing them is also a good option.  I will try to make a pull request for this sometime in the next few days.

**Comment by aaronwalsman** [comment]
Sorry, I got distracted and this took me forever.  Just submitted a pull request #401.

**Comment by pseudo-rnd-thoughts** [comment]
Completed in #435
