### ISSUE TITLE
[Question] mujoco v4 environments need mujoco-py

### ISSUE THREAD

**Issue by maruya24** [Farama-Foundation/Gymnasium#273]
### Question

I tried to use mujoco v4 environments of gymnasium and I got error that need me to install mujoco-py. But I think v4 environments only need deepmind's mujoco, not mujoco-py which v3 environments need. Is that a bug or Did I misunderstand something? In fact, I can use mujoco v4 environments of gym 0.24.1 without mujoco-py.

**Comment by BalajiAI** [comment]
Which OS are you using? Coz, Mujoco environments have some problems with Windows.

**Comment by rodrigodelazcano** [comment]
@maruya24 what environment is giving you the error? And how are you installing gymnasium? `pip install gymnasium[mujoco]` should work. 

I'm not able to replicate the issue

**Comment by maruya24** [comment]
I'm using macOS Ventura with Intel CPU. And I already done pip install gymnasium[mujoco] and stiil got following exception when I tried to use all mujoco v4 environments
```Exception: 
You appear to be missing MuJoCo.  We expected to find the file here: /Users/Name/.mujoco/mujoco210
```
I think this message indicates that I need OpenAI's mujoco-py that is a legacy for mujoco v4 environments of gymnasium.

**Comment by pseudo-rnd-thoughts** [comment]
Could you uninstall `mujoco_py`?

**Comment by maruya24** [comment]
Uninstalling mujoco-py greatly works. Now I can use mujoco v4 environments. Thank you for your suggestion.

**Comment by pseudo-rnd-thoughts** [comment]
Just for future readers, the issue is not that mujoco v4 environments needs the mujoco executable but rather that if mujoco py is installed then the mujoco executable needs to be installed.
