### ISSUE TITLE
[Question] Can `Env.render` take arguments?

### ISSUE THREAD

**Issue by qgallouedec** [Farama-Foundation/Gymnasium#283]
### Question

This line suggests that it is possible to pass [keyword] arguments to the `gym.Env.render` method.

https://github.com/Farama-Foundation/Gymnasium/blob/b4caf9df16e1f428a8b35c07455a9b8ebe8dfae9/gymnasium/wrappers/pixel_observation.py#L199

Which seems not to be consistent with how `gym.Env` is implemented in core.

https://github.com/Farama-Foundation/Gymnasium/blob/d46ff0e129072163d0aba6736f1b7eb0581cce8d/gymnasium/core.py#L146

Am I right?

**Comment by RedTachyon** [comment]
It used to be the case that `env.render()` would take arguments, but we changed it a few releases ago. Now you set it with `env = gym.make(..., render_mode="rgb_array")`, and call `env.render()` without any arguments. The code you mentioned hasn't been properly updated since, although technically speaking I guess it doesn't really break anything.

**Comment by qgallouedec** [comment]
Thanks for the clarification. Then the then `render_kwargs` args in the constructor is inoperative right?

**Comment by qgallouedec** [comment]
I've just seen https://github.com/Farama-Foundation/Gymnasium/pull/301#issuecomment-1409499303. Should we consider `PixelObservationWrapper` as deprecated then? I read in your roadmap #12  "Release v0.29.0 as an intermediate version with experimental functional, new wrappers and vectors to root". Does it mean that `PixelObservationWrapper` is going to be replaced by `experimental.wrappers.PixelObservationv0` in 0.29?

**Comment by pseudo-rnd-thoughts** [comment]
The roadmap needs to be updated for a new release in the next week not listed on the roadmap so it will replace `PixelObservationWrapper` in v0.31
