### ISSUE TITLE
[Bug Report] TimeLimit doesn't work

### ISSUE THREAD

**Issue by BalajiAI** [Farama-Foundation/Gymnasium#291]
### Describe the bug

I've modified my environment using TimeLimit wrapper inorder to increase the max_episode_steps. But it doesn't work.
Though it changed _max_episode_steps attribute for the environment. Env.step(action) method throws off truncated as True after the _max_episode_steps that the env set to at first has completed.

For example, in case of CartPole-v1 env, the timelimit is 500. Though I changed the timelimit through the wrapper, the env throws off truncated as True after 500 timesteps. I've attached the screenshot for additional information.

### Code example

```shell
import gymnasium as gym
from gymnasium.wrappers import TimeLimit
import torch
import torch.nn as nn


class ValueNetwork(nn.Module):
    def __init__(self, obs_dim, action_dim):
        super().__init__()
        self.policy = nn.Sequential(
                                  nn.Linear(obs_dim, 128),
                                  nn.ReLU(),
                                  nn.Linear(128, 128),
                                  nn.ReLU(),
                                  nn.Linear(128, action_dim)
                                  )
    def forward(self, obs):
        return self.policy(obs)


env_name = "CartPole-v1"
env = gym.make(env_name, render_mode="human")
env = TimeLimit(env, max_episode_steps = 10000)

value_network = torch.load("cartpole_value_network.pth") #trained using DQN

obs, info = env.reset()
terminated, truncated = False, False
for t in range(1, 10_001):
    with torch.no_grad():
        logits = value_network(torch.tensor(obs))
    action = logits.argmax().item()
    next_obs, reward, terminated, truncated, info = env.step(action)
    if terminated or truncated:
        break
    else:
        obs = next_obs
env.close()
```

### System info

1. Gymnasium was installed through pip.
2. Gymnasium version is 0.26.3.
3. Windows 11
4. Python 3.9

### Additional context

![image](https://user-images.githubusercontent.com/77477328/214571431-aca34e3c-5f17-4516-8735-3b25cb7657c2.png)

I also have attached my training code to get the value_network model here - [dqn.txt](https://github.com/Farama-Foundation/Gymnasium/files/10499685/dqn.txt).
Kindly modify the episode to 1k, such that the policy can go beyond the 500 timesteps.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by BalajiAI** [comment]
On further analysis, the bug is turned out to be so simple. Though env.step(action) throws off True for truncated after 500 timesteps. If we ignore the truncated variable and just focus on the terminated, then it works fine. I've used the following code for that.

``` python3
obs, info = env.reset()
terminated, truncated = False, False
for t in range(1, 1000):
    with torch.no_grad():
        logits = value_network(torch.tensor(obs))
    action = logits.argmax().item()
    next_obs, reward, terminated, truncated, info = env.step(action)
    if terminated:
        break
    else:
        obs = next_obs
env.close()
```

I've attached my screenshot for any additional info.
![image](https://user-images.githubusercontent.com/77477328/214583470-acad5312-e5be-406b-90f7-e4720c62289e.png)

**Comment by BalajiAI** [comment]
Inorder to fix this issue, one has to modify the code such that the truncated will be False until the _max_episode_steps has reached.

**Comment by pseudo-rnd-thoughts** [comment]
You just need to pass the updated value to `env = gym.make(env_name, render_mode="human", max_episode_steps=1000)`
As `gym.make` already includes a `TimeLimit` wrapper then you have not modified the underlying value which is why you get this issue

**Comment by BalajiAI** [comment]
Oops. I don't know that `TimeLimit` wrapper is aldready built into `gym.make`.
And the code works as expected now! Thank you so much for helping out :)
