### ISSUE TITLE
Make a pull request to Gym Retro to add support for Python 3.9

### ISSUE THREAD

**Issue by Kenshiro-28** [Farama-Foundation/Gymnasium#310]
### Proposal

Your project has the required updates to support Python 3.9, 3.10, and 3.11. 

I propose you make a pull request to Gym Retro to add support for at least Python 3.9

https://github.com/openai/retro

### Motivation

Gym Retro is a great project that allows to use classic games from consoles like Sega Genesis or SNES for machine learning. Currently it only supports Python 3.8 which is a problem because even conservative distros like Debian stable are already using Python 3.9.

### Pitch

Make a pull request to Gym Retro to enable support for at least Python 3.9

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Hi, the farama foundation is not OpenAI nor currently helping support RetroStable. Therefore, I would raise an issue on either of those projects not on gymnasium.

**Comment by Kenshiro-28** [comment]
Thank you for your answer. I already raised an issue with Gym Retro project but no answer:

https://github.com/openai/retro/issues/274

https://github.com/openai/retro/issues/274

**Comment by pseudo-rnd-thoughts** [comment]
I would put an issue on the stable retro repo or make a PR to solve the issue. I don't know a good reason why they cannot be supported as python versions

**Comment by Kenshiro-28** [comment]
Ok, thank you! :)
