### ISSUE TITLE
[Bug Report] The Atari doc is missing some information

### ISSUE THREAD

**Issue by vmoens** [Farama-Foundation/Gymnasium#313]
### Describe the bug

The Atari doc reads:
> ALE-py doesn’t include the atari ROMs (pip install gymnasium[atari]) which are necessary to make any of the atari environments. To install the atari ROM, use pip install gymnasium[accept-rom-license] which will install AutoROM and download the ROMs, install them in the default location. In doing so, you agree to TODO

from
https://gymnasium.farama.org/environments/atari/

### Code example

```shell
NA
```

### System info

NA

### Additional context

I don't know if I agree to TODO :)

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Apologies for taking so long to respond. This issue should be fixed in https://github.com/Farama-Foundation/Gymnasium/pull/330
