### ISSUE TITLE
[Bug Report] Atari v5 docs incorrectly state default of `full_action_space=True`

### ISSUE THREAD

**Issue by Jammf** [Farama-Foundation/Gymnasium#318]
### Describe the bug

The docs for the Atari envs (the overview page and each env's sub page) claim that that the `v5` versions default to `full_action_space=True`. However, most of the envs seem to actually default to `False`.

### Code example

```shell
>>> import gymnasium
>>> env = gymnasium.make('ALE/Breakout-v5')
env.spec.kwargs["full_action_space"]
False
>>> env.action_space
Discrete(4)
```

### System info

ale-py==0.8.0
gymnasium[atari,other]==0.27.1
shimmy[atari]==0.2.0

### Additional context

Some places to fix would be the `Action Space` and `Version History and Naming Schemes` sections in the overview page, and the `Actions` and `Version History` sections in each env page.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Apologies for taking so long to respond. This issue should be fixed in https://github.com/Farama-Foundation/Gymnasium/pull/330
