### ISSUE TITLE
[Bug Report] Overflow when sampling Box with high=np.iinfo(np.int64).max

### ISSUE THREAD

**Issue by mihaic** [Farama-Foundation/Gymnasium#328]
### Describe the bug

Overflow occurs in [line 196](https://github.com/Farama-Foundation/Gymnasium/blob/main/gymnasium/spaces/box.py#L196):
`high = self.high if self.dtype.kind == "f" else self.high.astype("int64") + 1`

Previously reported in [Gym issue 1929](https://github.com/openai/gym/issues/1929), which was only partially fixed.

### Code example

```shell
gymnasium.spaces.Box(low=0, high=np.iinfo(np.int64).max, dtype=np.int64).sample()

ValueError                                Traceback (most recent call last)
Cell In[18], line 1
----> 1 gymnasium.spaces.Box(low=0, high=np.iinfo(np.int64).max, dtype=np.int64).sample()

File ~/.local/lib/python3.8/site-packages/gymnasium/spaces/box.py:217, in Box.sample(self, mask)
    207 sample[low_bounded] = (
    208     self.np_random.exponential(size=low_bounded[low_bounded].shape)
    209     + self.low[low_bounded]
    210 )
    212 sample[upp_bounded] = (
    213     -self.np_random.exponential(size=upp_bounded[upp_bounded].shape)
    214     + self.high[upp_bounded]
    215 )
--> 217 sample[bounded] = self.np_random.uniform(
    218     low=self.low[bounded], high=high[bounded], size=bounded[bounded].shape
    219 )
    220 if self.dtype.kind == "i":
    221     sample = np.floor(sample)

File _generator.pyx:960, in numpy.random._generator.Generator.uniform()

File _common.pyx:579, in numpy.random._common.cont()

File _common.pyx:484, in numpy.random._common.cont_broadcast_2()

File _common.pyx:369, in numpy.random._common.check_array_constraint()

ValueError: high - low < 0
```

### System info

gymnasium.__version__
'0.27.1'

Installed with pip. Ubuntu 20.04.5. Python 3.8.10.

### Additional context

Encountered in [CompilerGym](https://github.com/facebookresearch/CompilerGym/blob/v0.2.5/compiler_gym/envs/llvm/service/ObservationSpaces.cc#L103).

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
This is an interesting problem but I think that CompilerGym should change their implementation

In testing, this can be solved with `Box(low=0, high=np.iinfo(np.int64).max - 1, dtype=np.int64).sample()`
This should have minimal impact on implementation as `Box` will use a uniform distribution from `low` to `high`.

I have trying solving the issue in Gymnasium but I haven't been able to find a elegant solution to the issue.

**Comment by mihaic** [comment]
Thanks for looking into this, @pseudo-rnd-thoughts.

Indeed, changing the `high` value is a good workaround. Perhaps while you look for an elegant solution, you could add the current limitation for `high` to the Gymnasium documentation.

**Comment by pseudo-rnd-thoughts** [comment]
@mihaic Would you be interested in making a small PR to do this?
