### ISSUE TITLE
[Bug Report] If render mode is not passed before `env.render`, the code derps out instead of being elegantly handled

### ISSUE THREAD

**Issue by RedTachyon** [Farama-Foundation/Gymnasium#33]
See openai/gym#3108

When trying to render the Taxi environment without having passed a `render_mode`, there's a rather weird error message that "This should never happen". It, indeed, should never happen, and we should catch this issue earlier with a descriptive error message.

I'm not sure how general the issue is, and how generally we should tackle it - but some general safeguard of "You can't call `env.render()` without setting `render_mode` on `make`" might be appropriate

I'll take a look at it in more detail in a bit

**Comment by pseudo-rnd-thoughts** [comment]
I believe this is the second or third time someone has got this issue.
I spoke to @younik about this who agreed to make a PR that raised a similar error to the one described after he had finished the PZ rendering mode. We should do this for Gym and Gymnasium I believe
