### ISSUE TITLE
Possibilty of having box [a,b] excluding a range for one action in action space

### ISSUE THREAD

**Issue by AminDar** [Farama-Foundation/Gymnasium#334]
### Question

Is it anyway to use  gymnasium.spaces.Box to define an action space which can get any value between [a,b] excluding a range of actions. For example if you want to control 'current load' of a boiler (actions), it can have a value between [0.3,1] as box but not less than 0.3. However,  the boiler can be turned off, meaning it can get a value 0 also. If it's not possible, is there anyway to map the actions in range (0,0.3] as to be considered a specific value like ==0.

**Comment by pseudo-rnd-thoughts** [comment]
This is not possible currently with `Box` and it most likely is too complex to add. 
One solution is two separate the actions into `Tuple((MultiBinary((1,)), Box(low=0.3, high=1, shape=(1,))` such that you have the first part being if you should turn on the boiler with the second part being if so how much. 
This can be flattened to a single Box. 
 
An alternative solution is to have a wrapper that clips the action if less than 0.3 to 0

**Comment by AminDar** [comment]
Thank you, I believe it's too complicated but this is a very common case when considering control applications.
And would you think it can be done the same way for multiple boilers, say 3 and each with its own 'on/off'  + range operation condition?
like:
`Tuple((MultiBinary((3,)), Box(low=0.3, high=1, shape=(3,))`

**Comment by pseudo-rnd-thoughts** [comment]
Yes that is very possible. 
Another option is to "shift" action space to between `0` and `0.7` with `0` being off and other values being `x + 0.3`.

I don't know how sensitive your RL problem is so while the different action space to use are equivalent, a neural network can struggle to interprete them possibly.

**Comment by AminDar** [comment]
I was thinking that the problem with `Tuple((MultiBinary((3,)), Box(low=0.3, high=1, shape=(3,))` is that the _actions_ , in my case, are applied to a function to get needed observations. The function of each boiler gets **only** one _action_ describing its 'load'.  Meaning with tuple method I create two actions for one boiler, which makes it messy!
