### ISSUE TITLE
[Question] Correct way to check that environment follows Gymnasium API

### ISSUE THREAD

**Issue by mkhlyzov** [Farama-Foundation/Gymnasium#336]
### Question

I am wondering what is the recommended way to check if an environment follows Gym[nasium] API?

Documentation mentions [check_env](https://gymnasium.farama.org/api/utils/#gymnasium.utils.env_checker.check_env) function, but accessing it raises an error
`>>> gymnasium.utils.env_checker.check_env`
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'gymnasium.utils' has no attribute 'env_checker'`

Indeed the only modules I can see from inside the interpriter are:
`>>> gymnasium.utils.`
`gymnasium.utils.EzPickle(               gymnasium.utils.ezpickle                gymnasium.utils.seeding
gymnasium.utils.colorize(               gymnasium.utils.passive_env_checker     gymnasium.utils.step_api_compatibility`

What bothers me the most is that I have access to gymnasium.utils.passive_env_checker , which means I still have the low level things. Do I reimplement env_checker locally in my code? Or is it a bug?

Installed Gymnasium via `pip install gymnasium`, reproducible in [Colab](https://colab.research.google.com/drive/1mWCkrn9adMiHRr-eajTuRh2mmWWsHIsl?usp=sharing)
gymnasium==0.27.1

**Comment by pseudo-rnd-thoughts** [comment]
You need to run as 
`from gymnasium.utils.env_checker import check_env` then `check_env(env.unwrapped)`

**Comment by mkhlyzov** [comment]
ty it worked.
