### ISSUE TITLE
[Bug Report] Migration caused <class 'Discrete'> to be incompatible with stable_baselines3

### ISSUE THREAD

**Issue by EeyoreLee** [Farama-Foundation/Gymnasium#348]
### Describe the bug

I don't have historical code that requires me to use gym, so I chose the recommended gymnasium, but the assertion of stable_baselines3 will verify it, I understand that this is not a direct bug of the package, but it is hard to blame stable_baselines3, what is good Solution to be compatible with gymnasium and stable_baselines3.  like the error `The algorithm only supports (<class 'gym.spaces.discrete.Discrete'>,) as action spaces but Discrete(4) was provided` will raised by the underlying code example. 

### Code example

```shell
import gymnasium as gym
# import gym

from stable_baselines3 import DQN
from stable_baselines3.common.vec_env.dummy_vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy


env = gym.make("LunarLander-v2")
env = DummyVecEnv([lambda : env])
model = DQN(
    "MlpPolicy", 
    env=env,
    verbose=1
)
```

### System info

**Ubuntu 16.04, Python 3.8.16, stable-baselines3 1.7.0, gymnasium 0.27.1**

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
The SB3 releases doesn't support gymnasium currently, use https://github.com/DLR-RM/stable-baselines3/pull/1327 branch for gymnasium support
