### ISSUE TITLE
[Question] Why in the Mujoco Hopper there is the name  "rooty" ? seems confusing

### ISSUE THREAD

**Issue by jamartinh** [Farama-Foundation/Gymnasium#349]
### Question

Why in the Mujoco Hopper there is the name  "rooty" ? seems confusing. All the simulation develops in the (x,z) cords.
I am not sure if this is a historical issue or there is a true reason for this.

Perhaps for Hopper-V5 this shall be corrected if it was a historical typo.

**Comment by pseudo-rnd-thoughts** [comment]
`rooty` refers to the name in the `asserts/hooper.xml` for the joint which is correct.
@Kallinteris-Andreas or @rodrigodelazcano Is the description correct in the observation table?

**Comment by Kallinteris-Andreas** [comment]
The description looks correct to me:
https://github.com/Farama-Foundation/Gymnasium/blob/main/gymnasium/envs/mujoco/assets/hopper.xml#L19 
The hinge is located on the y-axis, but it rotates on the x-z axes
