### ISSUE TITLE
[Question] Lunar Lander State scaling factor

### ISSUE THREAD

**Issue by CGCooke** [Farama-Foundation/Gymnasium#350]
### Question

In the [Lunar Lander](https://github.com/Farama-Foundation/Gymnasium/blob/main/gymnasium/envs/box2d/lunar_lander.py) env, there is a scaling factor of 20.0 which is applied to the Lander Angular Velocity.

Why is the scaling factor 20?

"20.0 * self.lander.angularVelocity / FPS"

(From line 571).
        state = [
            (pos.x - VIEWPORT_W / SCALE / 2) / (VIEWPORT_W / SCALE / 2),
            (pos.y - (self.helipad_y + LEG_DOWN / SCALE)) / (VIEWPORT_H / SCALE / 2),
            vel.x * (VIEWPORT_W / SCALE / 2) / FPS,
            vel.y * (VIEWPORT_H / SCALE / 2) / FPS,
            self.lander.angle,
            20.0 * self.lander.angularVelocity / FPS,
            1.0 if self.legs[0].ground_contact else 0.0,
            1.0 if self.legs[1].ground_contact else 0.0,
        ]

**Comment by CGCooke** [comment]
I also did an experiment where I found that you need to multiply a scaling factor of 2.5, to make the Integral of angular velocity equal the measured angle.

Is it possible that the scaling factor is meant to be 50 (The FPS), instead of 20?


FPS = 50
env = gym.make("LunarLander-v2")
observation, info = env.reset()
samples = []
while True:
    [x,y,dx,dy,theta,dtheta,contact1,contact2] = observation
    samples.append(observation)
    action = 1
    observation, reward, terminated, truncated, info = env.step(action)
    
    if terminated or truncated:
        break
env.close()


samples = np.array(samples)

angle = np.degrees(samples[:,4])
angular_velocity = np.degrees(samples[:,5])

plt.title('Angle')
plt.xlabel('Frame number')
plt.ylabel('Angle (Degrees)')
plt.plot(angle,label='Measured Angle')
plt.plot(angle[0] + 2.5 * np.cumsum(angular_velocity)/FPS,label='Integral of angular velocity')
plt.legend()
plt.show()

![Lander](https://user-images.githubusercontent.com/5202163/222142105-c7cd6631-b33f-40b2-88e5-45eff66a3c92.png)

**Comment by CGCooke** [comment]
Thanks for looking into it, and I understand that while it's broken, it's broken in a reproducible way. 

I'm trying to improve the documentation for the environment, so this is helpful to know.

**Comment by CGCooke** [comment]
Is there a "best practice" for calling out bugs/unexpected behaviour in environments in documentation?

**Comment by CGCooke** [comment]
Thankyou,

I created a new pull request, and documented the behaviour as comments. 

https://github.com/Farama-Foundation/Gymnasium/pull/354

It’s probably not perfect, but appreciate feedback.

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for the PR, it looks good and I have merged it. 
We are considering adding hardware accelerated version of the environment that uses GPU such that massive vectorisation can happen so we will look to see if we can add these changes to the environments then.
