### ISSUE TITLE
[Bug Report] Wrapping with TImeLimit *after* wrapping with RecordEpisodeStatistics

### ISSUE THREAD

**Issue by pi-tau** [Farama-Foundation/Gymnasium#351]
### Describe the bug

Wrapping an environment with TimeLimit *after* wrapping with RecordEpisodeStatistics fails to record statistics when truncated due to the time limit. This bug only occurs with vector environments!

### Code example

```shell
import gymnasium as gym

max_steps = 5
def create_env():
    env = gym.make("LunarLander-v2", render_mode="rgb_array")
    env = gym.wrappers.RecordEpisodeStatistics(env) # wrap with record before time-limit
    env = gym.wrappers.TimeLimit(env, max_episode_steps=max_steps)
    env.observation_space.seed(0)
    env.action_space.seed(0)
    return env

envs = gym.vector.SyncVectorEnv([create_env])

o, _ = envs.reset()
for s in range(100):
    acts = envs.action_space.sample()
    o, r, t, tr, info = envs.step(acts)

    if (t | tr).any():
        assert s == (max_steps-1)
        assert (t | tr)[0]
        assert "episode" in info["final_info"][0].keys() # fails
        break
```

### System info

gymnasium version "0.27.1"
installed with `pip3 install gymnasium`
OS: Ubuntu 22.04.1
python version: 3.10.6

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Make already include a time limit wrapper so there should be no need to do this. If you want to modify the max episode steps then just pass max episode steps to make

**Comment by cacao-macao** [comment]
> Make already include a time limit wrapper so there should be no need to do this. If you want to modify the max episode steps then just pass max episode steps to make

Yes, you don't have to initialize the time-limit wrapper this way,
No doubt there are workarounds: 1. you could pass `max_epsiode_steps` to `make`; 2. you could simply exchange the order of wrapping making TimeLimit come before RecordEpisodeStatistics; 3. maybe some other elaborate workaround.

The purpose of this report is to showcase a somewhat unexpected behavior. Maybe if we try testing with more wrappers specified in various orderings then other bad things might happen (who knows?).

**Comment by pi-tau** [comment]
I guess in this case the correct way to use `RecordEpsiodeStatistics` is to directly wrap the vector environment instead of wrapping individual sub-environments:

```python3
def create_env():
    env = gym.make("LunarLander-v2", render_mode="rgb_array")
    # don't wrap with RecordEpisodeStatistics here
    env = gym.wrappers.TimeLimit(env, max_episode_steps=max_steps)
    env.observation_space.seed(0)
    env.action_space.seed(0)
    return env

envs = gym.wrappers.RecordEpisodeStatistics(
    gym.vector.SyncVectorEnv([create_env])
)
```

Everything seems to work fine now.
If this is the case, then I would suggest adding a comment to the documentation of `RecordEpisodeStatistics` stating how the wrapper should be applied in the case of vectorized environments.

Previously I was somewhat confused whether I should wrap individual sub-environments with `RecordEpisodeStatistics` and then create the vectorized environment or vice-versa.
