### ISSUE TITLE
[Question] Gymnasium docs/seaquest import version

### ISSUE THREAD

**Issue by devhoodit** [Farama-Foundation/Gymnasium#360]
### Question

https://gymnasium.farama.org/environments/atari/seaquest/

First table, import gymnasium.make("ALE/Seaquest-v0")
why not gymnasium.make("ALE/Seaquest-v5")?

if this need to change, where i need to ask?
(i tried to change docs, it redirect to md file, but i can't find to change this string)
![image](https://user-images.githubusercontent.com/72541438/222988283-73df4378-854e-490a-a42b-d8bb66bc09a7.png)

**Comment by pseudo-rnd-thoughts** [comment]
This is a weird documentation issue, thanks for pointing it out. This seems to be fixed in main, you can see the "live" version of the website with https://gymnasium.farama.org/main/environments/atari/seaquest/

This is probably why the markdown didn't reflect the website page you were looking at
