### ISSUE TITLE
[Bug Report] Blackjack-v1 env observation state return type is different from docs

### ISSUE THREAD

**Issue by devhoodit** [Farama-Foundation/Gymnasium#361]
### Describe the bug

Blackjack-v1 environment docs, observation space return as tuple(int(), int(), int()) https://gymnasium.farama.org/environments/toy_text/blackjack/
but, it return tuple(int(), int(), boolen())
```python
import gymnasium as gym
env = gym.make('Blackjack-v1', natural=False, sab=False)
s, _ = env.reset()

print(s)
print(type(s[0]), type(s[1]), type(s[2]))
```
output is
```
<class 'tuple'>
(11, 6, False)
<class 'int'> <class 'int'> <class 'bool'>
```

### Code example

```shell
import gymnasium as gym
env = gym.make('Blackjack-v1', natural=False, sab=False)
s, _ = env.reset()

print(s)
print(type(s[0]), type(s[1]), type(s[2]))
```

### System info

gymnasium=0.27.1

### Additional context

gymnasium/envs/toy_text/blackjack.py line: 28
```python
return 1 in hand and sum(hand) + 10 <= 21
```
to
```python
return int(1 in hand and sum(hand) + 10 <= 21)
```
can be solution

_No response_

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by balisujohn** [comment]
I think it would be reasonable to go ahead and make pull request to address this. This may require a version number bump to the blackjack env.

**Comment by pseudo-rnd-thoughts** [comment]
I would happy to update the code to correctly reflect the expected integer type and I don't think we need to update the version number @balisujohn 
While I say that, there is a reason why this hasn't been "fixed" or change, is that int and bool are very similar and I'm unsure where using a bool rather than a int causes an issue

**Comment by devhoodit** [comment]
Ok, i will make pr for this
I think environment outputs need to be consistency
I'm now studying rl, and i want to test rl methods with change some factors (like discounting factor etc) for every gym environment
For discrete observation space, making return type int can be give some consistency to developers

In SARSA algorithm, i make q table with numpy, this numpy array has same shape as observation space
but output has bool type can't access directly to numpy array
This can be solved with making table with dict type, but i think type consistency will give better experience
(ref this https://github.com/devhoodit/egym/blob/main/egym/methods/sarsa.py line: 49)

i think this change is not for neccessary, but it's good for developing
