### ISSUE TITLE
[Bug Report] gym.make(env_id) adds a StreamHandler to the root logger

### ISSUE THREAD

**Issue by jtatusko** [Farama-Foundation/Gymnasium#363]
### Describe the bug

```python
env_id = "PongNoFrameskip-v4"
print("HANDLERS", logging.root.handlers)
env = gym.make(env_id)
print("HANDLERS", logging.root.handlers)
```
output:
```
HANDLERS []
HANDLERS [<StreamHandler <stderr> (NOTSET)>]
```

Having an extra stream handler is making all my log messages show twice. Also I'm looking for a way to not print this:
```
A.L.E: Arcade Learning Environment (version 0.8.1+53f58b7)
[Powered by Stella]
```
I'm spawning many environments for RL and this message spams stderr

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
The message is either being produced by Stella itself or ale-py https://github.com/mgbellemare/Arcade-Learning-Environment could you move your question to the project that has this code

**Comment by jtatusko** [comment]
Will do, thx
