### ISSUE TITLE
[Question] Wrappers for Atari games

### ISSUE THREAD

**Issue by TheGravityZero** [Farama-Foundation/Gymnasium#364]
### Question

Where can I get these wrappers that are compatible with gymnasium?
```
from stable_baselines3.common.atari_wrappers import (
    ClipRewardEnv,
    EpisodicLifeEnv,
    FireResetEnv,
    MaxAndSkipEnv,
    NoopResetEnv,
)
```
If you use them from sb3, then there is a problem:
```
obs, reward, done,  info = self.env.step(action)
ValueError: too many values to unpack (expected 4)
```

**Comment by pseudo-rnd-thoughts** [comment]
Sb3 main doesn't support gym / gymnasium v0.26 but is in the process of adding it
https://github.com/DLR-RM/stable-baselines3/pull/780
