### ISSUE TITLE
[Question] What is the status of gym-retro?

### ISSUE THREAD

**Issue by martinlicht** [Farama-Foundation/Gymnasium#381]
### Question

Hi,
What is the status of gym-retro? I understand it's a part of gym. There are numerous issues with installing gym-retro together with newer Python versions. Are there any plans to give gym-retro modern compatibility?

In the meanwhile, what is the recommended workaround for using gym-retro?

Thanks and have a nice day!

**Comment by pseudo-rnd-thoughts** [comment]
Gym-retro was originally a project by OpenAI but we are not related to the original project, there is a slightly maintained version of gym-retro called stable-retro if you are interested but sadly we can't help with any of those questions. 
We are interested in maintaining a version of retro if someone is wanting to do that
