### ISSUE TITLE
[Bug Report] BipedalWalker-v3 gets stuck in split position

### ISSUE THREAD

**Issue by prestonyun** [Farama-Foundation/Gymnasium#384]
### Describe the bug

Fairly often, the BipedalWalker-v3 does a split or a lunge and gets stuck in that position. My agent still attempts to move, and manages to slowly shuffle forward, but ultimately is unable to overcome the position. I've found this happens once every ~10 episodes on an untrained agent, and it dramatically prolongs the episode length.

![image](https://user-images.githubusercontent.com/40635145/224895213-8b59d895-6903-496f-9a57-39d237b03e3f.png)

### System info

- Gymnasium 0.27.1 was pip installed
- Windows 10
- Python 3.9

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
This is an interesting problem but what would you suggest the solution is?

**Comment by prestonyun** [comment]
I absolutely understand, and I thank you for your consideration of my post!
