### ISSUE TITLE
[Question] Interpretation of ground contact forces in Ant-v4

### ISSUE THREAD

**Issue by BeFranke** [Farama-Foundation/Gymnasium#385]
### Question

I am trying to detect if the agent of the Ant-v4 environment has ground contact on any of its legs and had the idea to monitor the contact forces (via `use_contact_forces=True`). However, from the documentation it is not clear to me which force corresponds to what. My first guess was the "ground link", however these forces are constantly zero in my experiments.

Could you please clarify which forces are applicable to my problem? 

Thank you very much in advance.

**Comment by Kallinteris-Andreas** [comment]
The docs for contact forces are wrong 
The "ground link" is a lie.

**Comment by Kallinteris-Andreas** [comment]
Try using the `aux` objects

**Comment by BeFranke** [comment]
Could you expand on these aux-objects, please? I searched it in the documentation, but did not find anything that seemed applicable...

**Comment by Kallinteris-Andreas** [comment]
Ah, sorry, should have clarified to use next version of the DOCs
https://gymnasium.farama.org/main/environments/mujoco/ant/

also, I am sure from memory if it is the `aux` or the `angle` objects try both

**Comment by BeFranke** [comment]
Ah, I see. Thank you very much, I will try this!
