### ISSUE TITLE
[Question] Backward compatibility

### ISSUE THREAD

**Issue by emrul** [Farama-Foundation/Gymnasium#388]
### Question

Hi, I have a custom env I've created with the current version of Gymnasium and it works fine. However, the problem I'm facing now is I'd like to use the plethora of libraries and examples out there on the net that still use older Gym APIs.

I've seen the [compatibility](https://gymnasium.farama.org/api/wrappers/misc_wrappers/#gymnasium.wrappers.EnvCompatibility) Wrappers but they're quite lacking so far:
* As documented, `EnvCompatibility` is to transform old envs into new ones. Given so many RL libs are still using the old APIs this seems the wrong way around - where is the compatibility API to transform new envs into old ones?
* The `StepAPICompatibility` gets some of the job done _but_ it is missing the old `seed()` and doesn't transform the tuple that `reset()` now returns. It can also cause issues with the wrappers (though this is probably something that can't easily be fixed but it is friction).

I'm hoping I missed something and there's a magic wrapper somewhere but as it stands I've had to resort to maintaining 2 versions of my Env - one that's legacy Gym and another that's Gymnasium 🤦

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for the question @emrul 
We are in contact with a number of popular training libraries, stable baseline 3, cleanrl and a couple more and most are planning on updating to gymnasium if they are still maintained.
So hopefully you won't need to maintain two versions for long.

We don't want to add a compatibility wrapper for the reverse as we would prefer people to update to the latest version for all of the bug fixes. But won't be too hard to add your own version.

If there are any projects that need advise on how to update then we would be happy to help

**Comment by emrul** [comment]
Thank you @pseudo-rnd-thoughts for the quick response and explanation and it makes sense. The main challenge I face is probably unique to me - I like trying out code that accompanies research papers and a lot of them from 2019-2022 period are using 'old' gym and the nature of that work often means the codebases remain static.

Hopefully with time that will change as new research will use the Gymnasium envs.  I'll close this issue for now.
