### ISSUE TITLE
Is the truncation statement missing in CartPoleEnv()?

### ISSUE THREAD

**Issue by bertanimre** [Farama-Foundation/Gymnasium#393]
### Question

Hello!

I want to modify (the action space and the reward) an existing gymnasium environment (CartPole-v2). Probably this is not the best way to do it, but I copied the source code from the gymnasium repository (v0.27.1) to make the modifications. When I checked the code, I saw that "Truncation: Episode length is greater than 500 (200 for v0)" wasn't applied to CartPoleEnv(). It seems easy to apply, like in CartPoleVectorEnv(). But unfortunately, when I tried to do it, the reinforcement learning library I used (SB3) didn't work properly.

Why isn't the statement in the code? Did I miss something, or was it on purpose?

Thanks in advance!

Best regards,
Bertan

**Comment by pseudo-rnd-thoughts** [comment]
Hi,

Truncation is done by the `TimeLimit` wrapper that is applied during `gymnasium.make` rather than the environment itself

**Comment by bertanimre** [comment]
Thank you for the quick response!

When I applied the TimeLimit wrapper, it worked properly.

Best regards,
Bertan
