### ISSUE TITLE
[Proposal] Clean some history code

### ISSUE THREAD

**Issue by NaiveXu** [Farama-Foundation/Gymnasium#396]
### Proposal

clean history code like `seed()` in [sync_vector_env.py](https://github.com/Farama-Foundation/Gymnasium/blob/8c167b868dd386ac1eb4bbe2fb25da3da174c75d/gymnasium/vector/sync_vector_env.py#L75) 

### Motivation

excuse for my bother.
it is said that `Function 'env.seed(seed)' is marked as deprecated and will be removed in the future. Please use 'env.reset(seed=seed)' instead.` and yes, there is no self.seed() in ['vector_env.py'](https://github.com/Farama-Foundation/Gymnasium/blob/8c167b868dd386ac1eb4bbe2fb25da3da174c75d/gymnasium/vector/vector_env.py).
but there is still [seed()](https://github.com/Farama-Foundation/Gymnasium/blob/8c167b868dd386ac1eb4bbe2fb25da3da174c75d/gymnasium/vector/sync_vector_env.py#L75) method in class `SyncVectorEnv`. when some old codes calls this method like `self.env.seed()`, there will rise a `builtins.AttributeError: 'super' object has no attribute 'seed'`.
so i was wondering if these history code can be deleted?
sorry for my poor English.

### Additional context

![2023-03-20 12-42-30屏幕截图](https://user-images.githubusercontent.com/33507880/226248758-603451f7-ba6b-44a8-8a2f-faae8e01fde8.png)

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Thanks @NaiveXu, yes that seems to be have been forgotten. 
Could you make a PR to remove the function?
