### ISSUE TITLE
[Bug Report] AttributeError: 'VideoRecorder' object has no attribute 'path'

### ISSUE THREAD

**Issue by stelladk** [Farama-Foundation/Gymnasium#398]
### Describe the bug

Using gymnasium wrapper `RecordVideo` causes AttributeError on calling env.step()
I am using it inside a SyncVectorEnv after a RecordEpisodeStatistics wrapper but the same error is reproduced with single usage of the wrapper.

### Code example

```shell
import gymnasium as gym

def make_env(gym_id):
    def thunk():
        env = gym.make(gym_id)
        env = gym.wrappers.RecordEpisodeStatistics(env)
        env = gym.wrappers.RecordVideo(env, "videos", episode_trigger=lambda t: t % 100 == 0)
        return env
    return thunk

envs = gym.vector.SyncVectorEnv([make_env(args.gym_id)])
observation = envs.reset()
for _ in range(200):
    action = envs.action_space.sample()
    observation, reward, terminated, truncated, info = envs.step(action)

--------------------------
Stack Trace:
    observation, reward, terminated, truncated, info = envs.step(action)
  File "/Users/stella/RL/lib/python3.9/site-packages/gymnasium/vector/vector_env.py", line 198, in step
    return self.step_wait()
  File "/Users/stella/RL/lib/python3.9/site-packages/gymnasium/vector/sync_vector_env.py", line 151, in step_wait
    ) = env.step(action)
  File "/Users/stella/RL/lib/python3.9/site-packages/gymnasium/wrappers/record_video.py", line 172, in step
    self.close_video_recorder()
  File "/Users/stella/RL/lib/python3.9/site-packages/gymnasium/wrappers/record_video.py", line 185, in close_video_recorder
    self.video_recorder.close()
  File "/Users/stella/RL/lib/python3.9/site-packages/wandb/integration/gym/__init__.py", line 66, in close
    m = re.match(r".+(video\.\d+).+", getattr(self, path))
AttributeError: 'VideoRecorder' object has no attribute 'path'
```

### System info

Python 3.9.13
Gymnasium 0.27.1
Installed via pip 23.0.1
MacOS Ventura 13.2.1

### Additional context

- This was tested using environments CartPole-v1 and LunarLander-v2. Both produce the same error.

- The code example was followed by a tutorial that was using the attribute `record_video_trigger` on RecordVideo that I assume was an older version of gym, so could this be a backward compatibility problem? 
Tutorial: https://www.youtube.com/watch?v=MEt6rrxH8W4&t=522s&ab_channel=Weights%26Biases

Thank you in advance!

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by younik** [comment]
This is a problem with WandB integration; which version of WandB do you have? I am not able to reproduce the error with the latest `0.14.0`

**Comment by younik** [comment]
> I am also using version 0.14.0 installed with pip

Okay, I was importing `wandb` before `gymnasium`.

The error arises because you don't specify the `render_mode`; change your code in this way:
```diff
- env = gym.make(gym_id)
+ env = gym.make(gym_id, render_mode="rgb_array")
```

There is a warning saying this, however, no error should be raised; I will propose a fix to WandB
