### ISSUE TITLE
[Question] Error when switching from gym to gymnasium

### ISSUE THREAD

**Issue by PBerit** [Farama-Foundation/Gymnasium#399]
### Question

Hi all,

I have a couple of gym environments that usually start with

```
from gym import Env
from gym.spaces import Discrete, Box, Tuple, MultiDiscrete
```

Now I would like to switch to gynmasium and for that I tried the following:

```
import gymnasium as gym

from gym import Env
from gym.spaces import Discrete, Box, Tuple, MultiDiscrete
```

But I get the error message "ModuleNotFoundError: No module named 'gym'". 

I also tried the following suggestion form the website:

```
import gymnasium as gym
env = gym.make("GymV26Environment-v0", env_id="ALE/Pong-v5")
from gym import Env
from gym.spaces import Discrete, Box, Tuple, MultiDiscrete
```

But then I get the error message "gymnasium.error.DependencyNotInstalled: No module named 'gym' (Hint: You need to install gym with `pip install gym` to use gym environments". I also did what is mentioned in the Terminal of PyCharm "pip install gym" but I get the output "Requirement already satisfied".

Can anyone tell me how I can make my gym environments run with gymnasium?

**Comment by pseudo-rnd-thoughts** [comment]
For the GymV26Environment, you are required to have both `gymnasium` and `gym` installed.
To test could you do 
```python
import gym
import gymnasium
```

**Comment by PBerit** [comment]
Ah okay, thanks a lot. The problem was, that gym was not correctly installed, altough pip told me that it was installed (this is generally kind of strange in python, that the package management is extremely confusing and highly errorprone).
