### ISSUE TITLE
NamespaceNotFound: Namespace gym_examples not found

### ISSUE THREAD

**Issue by jlsvane** [Farama-Foundation/Gymnasium#400]
### Describe the bug

Hi 

Conda environment: see attached yml file as txt

I'm trying to run the custom environment  example from [url](https://gymnasium.farama.org/tutorials/gymnasium_basics/environment_creation/#sphx-glr-tutorials-gymnasium-basics-environment-creation-py)
by cloning the git and then following the instructions and installing by "pip install -e ." It fails unless I change the setup file from install_requires=["gym==0.26.0", "pygame==2.1.0"] to this install_requires=["gym>=0.26.0", "pygame>=2.1.0"] when it installs pygame==2.1.0.

When changing this it appears to install. However, when running:
`import gymnasium`
`import gym_examples`
`env = gymnasium.make('gym_examples/GridWorld-v0')`

it fails with this error:

Traceback (most recent call last):
  File "/home/novelty/gym-examples/grid_test.py", line 10, in <module>
    env = gymnasium.make('gym_examples/GridWorld-v0')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/novelty/miniconda3/envs/gymnas_test/lib/python3.11/site-packages/gymnasium/envs/registration.py", line 592, in make
    _check_version_exists(ns, name, version)
  File "/home/novelty/miniconda3/envs/gymnas_test/lib/python3.11/site-packages/gymnasium/envs/registration.py", line 218, in _check_version_exists
    _check_name_exists(ns, name)
  File "/home/novelty/miniconda3/envs/gymnas_test/lib/python3.11/site-packages/gymnasium/envs/registration.py", line 185, in _check_name_exists
    _check_namespace_exists(ns)
  File "/home/novelty/miniconda3/envs/gymnas_test/lib/python3.11/site-packages/gymnasium/envs/registration.py", line 180, in _check_namespace_exists
    raise error.NamespaceNotFound(f"Namespace {ns} not found. {suggestion_msg}")
gymnasium.error.NamespaceNotFound: Namespace gym_examples not found. Have you installed the proper package for gym_examples?

[environment.txt](https://github.com/Farama-Foundation/Gymnasium/files/11044787/environment.txt)

### Code example

```shell
import gymnasium
import gym_examples
env = gymnasium.make('gym_examples/GridWorld-v0')
```

### System info

Gymnasium installed using pip

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Hey, thanks for raising the issue. 
I think the issue is that the tutorial still uses gym and should be using gymnasium. If you replace `import gym` with `import gymnasium as gym` does this fix the issues ?

**Comment by elmbeech** [comment]
The error still occurs and cannot be fixed via pull request because: https://github.com/Farama-Foundation/gym-examples` is no longer maintained.

However, https://github.com/Farama-Foundation/gym-examples is used in the current documentation here: https://gymnasium.farama.org/tutorials/gymnasium_basics/environment_creation/#sphx-glr-tutorials-gymnasium-basics-environment-creation-py

As Jorgen @jlsvane mentioned, two files would have to be fixed:

1.  `gym_examples/__init__.py` 
```python3
#from gym.envs.registration import register                                     
from gymnasium.envs.registration import register                                
```

2. `gym_examples/envs/grid_world.py`
```python3
#import gym                                                                     
#from gym import spaces                                                         
import gymnasium as gym                                                         
from gymnasium import spaces                                                    
```
As a newcomer, trying to understand how to use the gymnasium library by going through the official documentation examples, it makes things hard when things break by designer. 

So please, someone who can fix this in the archived repo, please fix it.
Thank you, Elmar

**Comment by pseudo-rnd-thoughts** [comment]
For the updated tutorials see https://gymnasium.farama.org/main/introduction/create_custom_env/ and a larger version - https://gymnasium.farama.org/main/tutorials/gymnasium_basics/environment_creation/

**Comment by elmbeech** [comment]
ah, I see. 
thank you, @pseudo-rnd-thoughts  for the link to the recent version!
this is very helpful.
