### ISSUE TITLE
install gym: metadata-generation-failed

### ISSUE THREAD

**Issue by 9muso8** [Farama-Foundation/Gymnasium#402]
Good morning, I'm trying to install gym on a Google Colab notebook, however, I keep receiving the following error. 
How can I solve it? Thank you.
![code](https://user-images.githubusercontent.com/120261383/227532183-68a7df72-99b0-441e-968e-4febe157cb2d.png)

![error](https://user-images.githubusercontent.com/120261383/227532190-ff84f0d0-f4fb-4bea-a04a-c39f5ab18df1.png)

**Comment by pseudo-rnd-thoughts** [comment]
The issue is with setuptool, you need to downgrade to 66.X 
https://github.com/openai/gym/issues/3200
