### ISSUE TITLE
[Question] Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by TongYan1999** [Farama-Foundation/Gymnasium#409]
### Question

![图片](https://user-images.githubusercontent.com/108660936/228220231-d1377c09-9894-4913-b2c0-f86cee41dc3d.png)
When I run : env = gym.make("FrozenLake-v1") and reset the env,
report error: Segmentation fault (core dumped), actually all the envs have the same question.
my environment: ubuntu16.04 & python3.7

**Comment by Kallinteris-Andreas** [comment]
try without `render_mode`

**Comment by pseudo-rnd-thoughts** [comment]
What version of pygame are you using?

**Comment by TongYan1999** [comment]
> What version of pygame are you using? 
I tried 2.1.3, 2.2.0, 2.3.0 they all didn't work
