### ISSUE TITLE
[Proposal] Future APIs (and revisions) should include a version system (similar to environments)

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [Farama-Foundation/Gymnasium#410]
### Proposal

New APIs and new revisions of existing APIs should include a versioning system (for `Gymansium` and all other `Farama` projects)
e.g. if a future revision of `gymnasium.vector.VectorEnv` is made, it should be called `gymnasium.vector.VectorEnv_v1`
e.g. if a new API is created for `pettingzoo`  hybrid AEC/parallel, it should be called `pettingzoo.utils.env.HybridEnv_v0`  

Note:
I am not proposing here:
- a new API revision
- the creation of a new API

### Motivation

It should create less confusion when a new revision of an API is created 
e.g. look at the confusion of the old Gymnasium API, and the new Gymnasium API

and should make Shimmy Docs easier to read

### Pitch

This should make the creation of new API revisions less painful,

For example, when making a new version of PettingZoo APIs (to be more Aline with the "new" gymnasium API), the new API versioning system could be used to reduce confusion. 

I do not see a downside 

### Alternatives

Currently, the API versioning system is to list the version of the project at the API revision
e.g. `Gymansium` API v21 (old), `Gymansium` API v26 (new)

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
I think the OpenAI adding version numbers to environments was very helpful to some degree as it helped with reproducing environment and reporting this information for academic work.
However, there is a reason that 99% of coding projects do not include version numbers in their function names as the project versions should be used.
The problem is that due to the environment version number, people use this as the primary method to specify the version rather than the project version.

**Comment by Kallinteris-Andreas** [comment]
"""The problem is that due to the environment version number, people use this as the primary method to specify the version rather than the project version."""

why is that a problem

**Comment by pseudo-rnd-thoughts** [comment]
As functions change and bugs get fixed etc, then you either must have a version number on every function IMO or you use the project version to specify the version of the code

**Comment by Kallinteris-Andreas** [comment]
I was only suggesting versioning on APIs no other functions, as it would help users who use old revisions and developers who make environments using the APIs

If you believe that there is no merit, feel free to close this proposal

**Comment by RedTachyon** [comment]
I'm moderately strongly opposed to this, for basically the same reasons as Mark. This is not a practice used in any part of software engineering as far as I'm aware, and for a good reason - it breaks backwards compatibility even if the API remains unchanged, and the "version" of a given class/API/function is deterministically identified by the library version. You might say that's the entire point of having versioned releases.

**Comment by pseudo-rnd-thoughts** [comment]
@Kallinteris-Andreas Im happy to consider talking about this but I don't think we will adopt this except for wrapper which we are still not certain of
