### ISSUE TITLE
[Bug Report] Wrong number of simulation steps in the step function of class MujocoEnv

### ISSUE THREAD

**Issue by xuanhien070594** [Farama-Foundation/Gymnasium#420]
### Describe the bug

In the function `_step_mujoco_simulation` of class `MujocoEnv`, the correct value for the argument `nstep` should be `n_frames` instead of `self.frame_skip`.

https://github.com/Farama-Foundation/Gymnasium/blob/7fa9702cd4b469163aa31f1efe8b275c3848712a/gymnasium/envs/mujoco/mujoco_env.py#L371

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Kallinteris-Andreas** [comment]
@xuanhien070594, Thanks for finding that out

Note: In practice, it does not affect anything since the argument is `n_frames=self.frame_skip`

e.g. https://github.com/Farama-Foundation/Gymnasium/blob/7fa9702cd4b469163aa31f1efe8b275c3848712a/gymnasium/envs/mujoco/ant_v4.py#L315

**Comment by pseudo-rnd-thoughts** [comment]
@xuanhien070594 wow, impressive to find that and @Kallinteris-Andreas thanks for finding that
Could someone make a PR to update the `mj_step` function to use the correct variable for the future. I should make a note in the documentation as I don't think anyone uses this variable, it does technically break backward compatibility

**Comment by Kallinteris-Andreas** [comment]
@xuanhien070594 close this issue
