### ISSUE TITLE
[Question] Limiting vector environment reset seeds 

### ISSUE THREAD

**Issue by Howuhh** [Farama-Foundation/Gymnasium#422]
### Question

Hi! There are many situations where you need to be able to distinguish between seeds for training and evaluation. This is especially important in more complex and procedurally generated environments such as NetHack, ProcGen, Minecraft, etc. Therefore, for a proper comparison, it is important to be able to fix the seeds (for example, so that the seeds for training do not overlap with the seeds for testing).  

With a single environment this can be done easily, but I don't see an obvious way to do it with vectorized environments. How is this supposed to be achieved currently?

**Comment by pseudo-rnd-thoughts** [comment]
How is this normally done in single agent environments? 

My initial thoughts is to use a custom wrapper to specify a set of training or evaluation seeds?

**Comment by kbkartik** [comment]
@Howuhh were you able to figure this out?

**Comment by Howuhh** [comment]
@kbkartik I did it through the wrapper as advised

**Comment by kbkartik** [comment]
Do you have a code snippet?
