### ISSUE TITLE
Is the `env.reset()` controllable in SynVectorEnv?

### ISSUE THREAD

**Issue by YangyangFu** [Farama-Foundation/Gymnasium#427]
### Question

After investigating the implementation of `SynVectorEnv` at [here](https://github.com/Farama-Foundation/Gymnasium/blob/7094298ad4d4bb1d1095dbf9095db6d17861b42b/gymnasium/vector/sync_vector_env.py#L153), I didn't see the `env.reset()` is controlled by a seed after `done` or `truncated`.

Is there any way for user to control the reset state in a reproducible way?

**Comment by YangyangFu** [comment]
I figured it out.

The vector environment is seed by `env.reset()` at the very beginning.

**Comment by kbkartik** [comment]
@YangyangFu were you able to figure this out?

**Comment by pseudo-rnd-thoughts** [comment]
Vector environment autoreset and you don't have control over that currently meaning that you can only set the initial reset seed
If you want to do this, I would recommend not vectorising to have this level of control or implement your own for-loop like vectorisation
