### ISSUE TITLE
[Question] Setting a custom camera distance when recording videos of a MuJoCo environment using RecordVideo

### ISSUE THREAD

**Issue by Omer1Yuval1** [Farama-Foundation/Gymnasium#446]
### Question

Using `gymnasium.wrappers.RecordVideo` to record a video of a MuJoco environment (e.g., Ant-v4) seems to ignore the camera distance specified by the underlying MuJoCo environment.

When I initialize the environment using `render_mode="human"`, the value of `default_camera_config` passed to `MujocoEnv.__init__` in `AntEnv` correctly affects the rendering displayed by the MuJoCo engine. However, using `render_mode="rgb_array"`, the video file generated by `RecordVideo` ignores this value and generates frames using some default value (possibly 4.0).

I validated that `env.unwrapped.mujoco_renderer.viewer.cam.distance` is set to the new value (e.g., 10.0) before and after the wrapping, but the resulting video frames are recorded using the default value and are unaffected.

**Comment by pseudo-rnd-thoughts** [comment]
Could you provide example code to test this
Is this an issue with v2 or v3 environments as well? 

I suspect that the issue is there are two different methods for `human` and `rgb_array` with `rgb_array` ignoring the values. 

@rodrigodelazcano @Kallinteris-Andreas Any thoughts?

**Comment by Omer1Yuval1** [comment]
Thanks @pseudo-rnd-thoughts for the quick response. Here is an example code to reproduce this behaviour.
I tried with v2 and v3 but it resulted in an error and I didn't look into it further (to my understanding they have different dependencies).

At the top of the ant_v4.xml file, the `DEFAULT_CAMERA_CONFIG` is set, and then passed to `MujocoEnv.__init__`. As I mentioned, modifying this parameter (e.g., from 4.0 to 10.0) has an effect on MuJoCo rendering in `render_mode="human"`, but has no effect on the video file generated by `RecordVideo` in `render_mode="rgb_array"`.

```
import numpy as np
import os
import gymnasium as gym
from gymnasium.wrappers import RecordVideo

env = gym.make("Ant-v4", render_mode="rgb_array")

env.reset()

env = gym.wrappers.RecordVideo(env, video_folder="resources/")

terminated = 0
truncated = 0
while(not terminated and not truncated):
    action = env.action_space.sample()
    obs, reward, terminated, truncated, info = env.step(action)

env.close()
```

p.s. probably unrelated, but while you are at it, note that in the `Ant-v4` environment, `truncated` is always returned as `False` by the `step()` function, regardless of the number of steps and despite what the documentation says: "1. Truncation: The episode duration reaches a 1000 timesteps".

**Comment by rodrigodelazcano** [comment]
@Omer1Yuval1 by default when rendering in `rgb_array` mode the `track` camera is selected which is fixed and the config can't be modified. Can you try initializing the environment with the `free` camera?

```
env = gym.make("Ant-v4", render_mode="rgb_array", camera_name="free")
```

This works for me

**Comment by pseudo-rnd-thoughts** [comment]
@rodrigodelazcano Is this documented anywhere? If so, this would be great to do so

**Comment by rodrigodelazcano** [comment]
@pseudo-rnd-thoughts no, where do you think it's best to add it. I was thinking in the docstrings of the MujocoRenderer

**Comment by Omer1Yuval1** [comment]
Awesome, thanks both!

> ```
> env = gym.make("Ant-v4", render_mode="rgb_array", camera_name="free")
> ```
@rodrigodelazcano I tested it and it's working.

> In `gym.make`, a `TimeLimit` wrapper is added that contains the specified number of timesteps, therefore it is technically not the environment that has the 1000 step limitation but the wrapped environment from `gym.make`.

@pseudo-rnd-thoughts That's great. Tested and working:
`gym.make("Ant-v4", max_episode_steps=max_episode_steps)`

 p.s. @pseudo-rnd-thoughts I wanted to test this for `make_vec()` too, but I get errors for both `gym.make_vec("Ant-v4")` and `env = gym.make_vec(gym.make("Ant-v4"))`.
