### ISSUE TITLE
[Question] How to import serialize_spec_stack for dataset creation in minari

### ISSUE THREAD

**Issue by DarthMalloc** [Farama-Foundation/Gymnasium#449]
### Question

Because of some recent changes to the class hierarchy in Gymnasium, the Minari dataset creation example given here 
[https://minari.farama.org/tutorials/dataset_creation/](url) no longer works.

In place of `from gymnasium.utils.serialize_spec_stack import serialise_spec_stack`, what should I be using now?

**Comment by rodrigodelazcano** [comment]
@DarthMalloc Minari has been refactored for the beta release, this is the new documentation for dataset creation in the current source code https://minari.farama.org/main/tutorials/dataset_creation/point_maze_dataset/
