### ISSUE TITLE
[Bug Report] Missing figure in environment creation

### ISSUE THREAD

**Issue by Alian3785** [Farama-Foundation/Gymnasium#452]
### Describe the bug

In the article https://gymnasium.farama.org/tutorials/gymnasium_basics/environment_creation/ we have this part:

_An episode in this environment (with size=5) might look like this:

where the blue dot is the agent and the red square represents the target.

Let us look at the source code of GridWorldEnv piece by piece:_

So env looks like what exactly? I suppose there should be a picture

### System info

Chrome browse last version

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for spotting that. It doesn't seem that the image isn't been rendered, rather the image just doesn't exist currently. We will see if we can solve it and add a figure
