### ISSUE TITLE
[Bug Report] Issues with provided RescaleAction wrapper

### ISSUE THREAD

**Issue by realquantumcookie** [Farama-Foundation/Gymnasium#460]
### Describe the bug

The `RescaleAction` Wrapper in `gymnasium.wrappers` does not wrap over the action space of the wrapped environment.

### Code example

```shell
import gymnasium as gym
import numpy as np

env = gym.make("...") #suppose env has action space Box((2,),low=-2.0, high=2.0, dtype=np.float32)
env = gym.wrappers.RescaleAction(env,-1,1) # this will rescale action to be in range [-1,1] but action space is [-2,2]
```

### Additional context

Solution is pretty simple, just add a @property action_space for the wrapper. I can make a pull request if needed.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Could you try using `gymnasium.experimental.wrappers.RescaleActionV0`? 
We are updating all of the wrappers and should fix issues like this

**Comment by realquantumcookie** [comment]
Hi @pseudo-rnd-thoughts I think that worked well :) I will close this issue
