### ISSUE TITLE
[Question] Displaying contact forces and contact points in video recordings of a MuJoCo environment using RecordVideo

### ISSUE THREAD

**Issue by Omer1Yuval1** [Farama-Foundation/Gymnasium#464]
### Question

Inside the MuJoCo simulation GUI (simulate.exe), I can click buttons to display contract forces and contact points. I would like to be able to display such information in the videos generated by `gymnasium.wrappers.RecordVideo`. Can this be done from the `MujocoEnv` class? Otherwise, can you please suggest a workaround or consider adding this option?
I couldn't find in MuJoCo's documentation a way to specify this in the XML.

p.s. this is important for validating what the agent is doing in locomotion tasks, as it is often hard to see in the video if a body part is touching the floor.

**Comment by Kallinteris-Andreas** [comment]
The Gymnaisum/MuJoCo `OffScreenViewer` (for `rgb_array` and `depth_array`) do not support being configured to show contact forces through an argument.

This should work (after you have rendered your first frame):
```python
>>> env.unwrapped.mujoco_renderer.viewer.vopt.flags[mujoco.mjtVisFlag.mjVIS_CONTACTFORCE] = True
```

**Comment by Omer1Yuval1** [comment]
> ```python
> >>> env.unwrapped.mujoco_renderer.viewer.vopt.flags[mujoco.mjtVisFlag.mjVIS_CONTACTFORCE] = True
> ```

Thanks @Kallinteris-Andreas. I am able to access `env.unwrapped.mujoco_renderer.viewer.vopt.flags`, but I don't understand what the `mujoco` object in `mujoco.mjtVisFlag.mjVIS_CONTACTFORCE` is and where it comes from.

**Comment by Kallinteris-Andreas** [comment]
```python
>>> import mujoco
>>> mujoco.mjtVisFlag.mjVIS_CONTACTFORCE
```

**Comment by Omer1Yuval1** [comment]
Great, thank you @Kallinteris-Andreas, this works. This actually shows vectors with length proportional to the contact force (rather than the numbers shown in simulate.exe).

To show the yellow discs that indicate contact points:
`env.unwrapped.mujoco_renderer.viewer.vopt.flags[mujoco.mjtVisFlag.mjVIS_CONTACTPOINT] = True`.

**Comment by pseudo-rnd-thoughts** [comment]
@Kallinteris-Andreas Is this something we could add easily to mujoco-render such that users don't need this extra code?
