### ISSUE TITLE
[Question] Is 'truncated' actually returned correctly?

### ISSUE THREAD

**Issue by sparisi** [Farama-Foundation/Gymnasium#470]
### Question

From my understanding, `env.step(action)` should return `truncated = True` if `_max_episode_steps` are executed. 
The pendulum [just returns False all the time](https://github.com/Farama-Foundation/Gymnasium/blob/e0994f028ab9a88f6c8c1afa9e75f6517b1c1c1e/gymnasium/envs/classic_control/pendulum.py#L144), so I am wondering how it is computed in other environments.

**Comment by pseudo-rnd-thoughts** [comment]
This is a bit hidden from the user but in `gym.make` then the `TimeLimit` wrapper is applied to the environment. It is the `TimeLimit` wrapper that returns `truncated=True` when the max episode steps is executed. 

So you are partially right that the pendulum environment always returns False, it just that the truncation is happens in a separate class.

**Comment by sparisi** [comment]
Perfect, thanks for the quick response!
