### ISSUE TITLE
[Question] Atari time limit

### ISSUE THREAD

**Issue by sparisi** [Farama-Foundation/Gymnasium#483]
### Question

Most of the environments have `max_episode_steps` in `env.spec`. Atari games do not. Also MiniGrid and MiniWorld don't, but they have it as environment specific attributes. Is there a way to see (and set) the time limit for every env?

**Comment by pseudo-rnd-thoughts** [comment]
Sadly no is the answer. As the `max_episode_steps` is used in `gym.make` to create a `TimeLimit` wrapper whereas for atari, minigrid and miniworld have their own internal time limit implementation

**Comment by sparisi** [comment]
Alright, thanks for answering!
