### ISSUE TITLE
[Question] mujoco.FatalError: gladLoadGL error

### ISSUE THREAD

**Issue by wadiuvatzy** [Farama-Foundation/Gymnasium#501]
### Question

hello, I'm facing a problem when i am using gymnasium with mujoco. Every time i call env.render() i would get this error  Does someone have any clue about how I could fix it ?
![image](https://github.com/Farama-Foundation/Gymnasium/assets/100420643/1a1d5012-e575-4d58-b0ef-0e4b96896288)

**Comment by pseudo-rnd-thoughts** [comment]
The issue is that the `GLFW` library could not be initialized

**Comment by bolisteward** [comment]
@pseudo-rnd-thoughts  have you solved it?

**Comment by pseudo-rnd-thoughts** [comment]
Could you see if GLFW is installed?

**Comment by bolisteward** [comment]
@pseudo-rnd-thoughts  yes, it is installed



![lib](https://github.com/Farama-Foundation/Gymnasium/assets/56736636/0ff9af1f-b032-41f1-9e95-33a7eda82d68)

**Comment by pseudo-rnd-thoughts** [comment]
@rodrigodelazcano Do you know the solution?

**Comment by laktionov** [comment]
Hi, I was wondering if there were any updates regarding this issue?
By the way, I found that the second code cell from the [official mujoco tutorial](https://colab.research.google.com/github/deepmind/mujoco/blob/main/python/tutorial.ipynb) fixed the problem in my case.

**Comment by mquangsmu** [comment]
> Hi, I was wondering if there were any updates regarding this issue? By the way, I found that the second code cell from the [official mujoco tutorial](https://colab.research.google.com/github/deepmind/mujoco/blob/main/python/tutorial.ipynb) fixed the problem in my case.

Yes, adding environment variable `%env MUJOCO_GL=egl` also fix my case. I am running on a linux server with GPUs.

**Comment by balloch** [comment]
This isn't really a fix, its just making Mujoco not use GLFW but instead EGL
