### ISSUE TITLE
[Bug Report] `Humanoid-v4` does not have `contact_cost`

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [Farama-Foundation/Gymnasium#504]
### Describe the bug

https://gymnasium.farama.org/main/environments/mujoco/humanoid/#rewards

https://github.com/Farama-Foundation/Gymnasium/blob/c4f67b9fd9e09e222cc37d1a2240ecaa7472054a/gymnasium/envs/mujoco/humanoid_v4.py#L391

https://github.com/Farama-Foundation/Gymnasium/blob/c4f67b9fd9e09e222cc37d1a2240ecaa7472054a/gymnasium/envs/mujoco/humanoid_v3.py#L157

the docs still have `contact_cost_weight` argument

@rodrigodelazcano is it the same reason at the ant contact forces but without the `use_contact_forces` argument? (https://github.com/Farama-Foundation/Gymnasium/issues/214)

### Additional context

Humanoid Standup is not affected

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by rodrigodelazcano** [comment]
At the time I removed it because this reward was almost 0 due to the cost weight. However, I probably missed adding it back. Can you re-add this argument and additional reward so that the user has access to it? Thanks

**Comment by Kallinteris-Andreas** [comment]
I will add it to the change list for `v5`

**Comment by pseudo-rnd-thoughts** [comment]
I agree that including the `contact_cost` is not equivalent but the performance difference is minimal so I'm not sure if it is worth including the parameter when there is little impact on the environment / agent

**Comment by Kallinteris-Andreas** [comment]
@pseudo-rnd-thoughts That original implementation included `contact_cost`, and it is an important part of robotic systems. (Note: the user could set `contact_cost_weight=0` if they wanted to disable it.)
