### ISSUE TITLE
Documentation: number of fields returned by step()

### ISSUE THREAD

**Issue by fede72bari** [Farama-Foundation/Gymnasium#505]
### Question

https://gymnasium.farama.org/tutorials/gymnasium_basics/environment_creation/

In the explanation text "...and returns the 4-tuple (observation, reward, done, info)"; in the code instead:

`return observation, reward, terminated, False, info`

**Comment by Kallinteris-Andreas** [comment]
The code is correct, not the text
https://gymnasium.farama.org/api/env/#gymnasium.Env.step

@fede72bari  do you want to make a PR fixing it

**Comment by robertoschiavone** [comment]
#565
