### ISSUE TITLE
[Question] Integration of POPGym into Gymnasium

### ISSUE THREAD

**Issue by smorad** [Farama-Foundation/Gymnasium#507]
### Question

Hi, I'm the author of [POPGym](https://github.com/proroklab/popgym) which contains 45 partially observable `gymnasium` tasks, requiring just gymnasium and numpy (and mazelib if you want the maze envs) as dependencies. I'm curious if you would be interested in integrating this into `gymnasium`. We [slightly extend](https://github.com/proroklab/popgym/blob/master/popgym/core/env.py) the `gymnasium.Env` api to differentiate between `state` and `observation`.

**Comment by pseudo-rnd-thoughts** [comment]
Hey, we don't merge new environments into gymnasium but we are happy to list the project in our third-party page - https://gymnasium.farama.org/environments/third_party_environments/#

If you want to do this, please make a PR with your changes in https://github.com/Farama-Foundation/Gymnasium/blob/main/docs/environments/third_party_environments.md
