### ISSUE TITLE
[Proposal] FrameStack wrapper but for vector observations

### ISSUE THREAD

**Issue by sparisi** [Farama-Foundation/Gymnasium#509]
### Proposal

Maybe I missed it, but there is nothing like that, right?
Basically the idea would be to concatenate consecutive vector observations (the default ones) by stacking them. Eg, Pendulum-v0 returns obs of shape (3,): VectorStack(env, 4) would return obs of shape (12,), where obs are stacked like in FrameStack. 

[This paper](https://arxiv.org/abs/2101.01857) does something similar, but instead of just stacking obs it stacks the difference of consecutive observations. Something like this could be achieved by having an extra argument that defines how obs are stacked. 

### Motivation

Using a wrapper like that may be an alternative to recurrent policies like LSTM.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
If there is an elegant way of doing this, could you add this to `FrameStackingV0` in `experimental/wrappers/stateful_observation.py` with a parameter?

**Comment by sparisi** [comment]
Actually `FrameStackObservationV0` works even if the shape is `[n, obs_size]`. I thought it was just for frames like `FrameStack`. I think the name is a bit misleading, maybe should be called `ObservationStack`? 

The concatenate part is easy, but given that there are already `FrameStack` and `FrameStackObservationV0`, I think it would be more useful to have another wrapper that returns the difference. This wrapper would be applied on the top of frame stacks. 
I wrote it but I am not sure about:
- The best name for it.
- Where to place it. In `stateful_observation`? 
- The wrapper should be used only if the observation space is at least 2D, and it makes sense to use it only for stacked observations. Not sure if just the docs is enough of if there should be an `assert`.


```python
"""Wrapper for returning the difference of stacked consecutive observations of an environment."""
import gymnasium as gym
import numpy as np

class DiffObservationV0(gym.ObservationWrapper, gym.utils.RecordConstructorArgs):
    """Observation wrapper that returns the difference of stacked observations. 
    The first observation in the stack is also returned. 

    Example:
        >>> import gymnasium as gym
        >>> from gymnasium.experimental.wrappers import FrameStackObservationV0, DiffObservationV0
        >>> env = gym.make("Pendulum-v1")
        >>> env = FrameStackObservationV0(env, 4)
        >>> obs, _ = env.reset(seed=42)
        >>> for _ in range(4):
        ...     obs, *_ = env.step([1.])
        >>> obs
        array([[-0.1878612 ,  0.98219556,  0.7692768 ],
               [-0.26844683,  0.9632945 ,  1.6559235 ],
               [-0.38775983,  0.92176044,  2.5283945 ],
               [-0.5368388 ,  0.8436848 ,  3.3697147 ]], dtype=float32)
        >>> env = DiffObservationV0(env)
        >>> obs, _ = env.reset(seed=42)
        >>> for _ in range(4):
        ...      obs, *_ = env.step([1.])
        >>> obs
        array([[-0.1878612 ,  0.98219556,  0.7692768 ],
               [ 0.10727558, -1.0010966 ,  0.11736989],
               [-0.03872737, -0.02263302, -0.01417571],
               [-0.02976599, -0.03654158, -0.0311507 ]], dtype=float32)
    """

    def __init__(self, env: gym.Env):
        """Returns the difference of stacked observations of an environment.

        Args:
            env: The environment to apply the wrapper
        """
        gym.utils.RecordConstructorArgs.__init__(self)
        gym.ObservationWrapper.__init__(self, env)

    def observation(self, observation):
        """Computes the difference of stacked observations. 
        The first observation is also returned. 

        Args:
            observation: The stacked observations

        Returns:
            The difference of the observations
        """
        return np.concatenate((observation[0][None], np.diff(observation, axis=0)))
```

**Comment by pseudo-rnd-thoughts** [comment]
I realised after my message that this is easily implemented with `ReshapeObservation(FrameStackObservationV0(env), (-1,))`

**Comment by sparisi** [comment]
`ReshapeObservation` does not computes the difference, right? 
Anyway, I don't mind not committing my wrapper and have it in just in my repo. My main issue was that I thought there was no "VectorStack" wrapper, since I didn't know "FrameStackObservationV0" works also with vector obs despite its name.

**Comment by pseudo-rnd-thoughts** [comment]
We are working on a specialist vector based version of all the wrappers for a new release soon
