### ISSUE TITLE
[Bug Report] Fix recording of final observations/infos in vectorized jax functional envs

### ISSUE THREAD

**Issue by RedTachyon** [Farama-Foundation/Gymnasium#514]
Making this mainly as a mental note, also as a reminder what we need to fix before stabilizing the jax envs.

https://github.com/Farama-Foundation/Gymnasium/blob/main/gymnasium/experimental/functional_jax_env.py#L232

The arrays are initialized to a numpy array with Nones inside, which makes them object arrays. Then, in a loop, parts of jax arrays are assigned to that array, but they're still treated as objects, so it's all sorts of messed up and inefficient.

At the very least we need to fix the arrays being used, and ideally the loop would be vectorized.

I'm planning to take a look at it soon-ish, unless someone is up for a challenge (though I don't think this is suitable for beginners/new contributors, it will also be important to compare the performance of the new implementation)

**Comment by pseudo-rnd-thoughts** [comment]
It might be possible to use the `create_empty_array` function for generating the expected shape then use the `numpy_to_jax` converter function to transform into the expected jax version

**Comment by RedTachyon** [comment]
Indirectly closed by #808
