### ISSUE TITLE
[Bug Report] env_render_passive_checker missing arguments

### ISSUE THREAD

**Issue by Plahmy** [Farama-Foundation/Gymnasium#519]
### Describe the bug

The render function of the [env_checker](https://github.com/Farama-Foundation/Gymnasium/blob/main/gymnasium/wrappers/env_checker.py) wrapper in line 63 calls the
env_render_passive_checker with *args and **kwargs but the
[env_render_passive_checker](https://github.com/Farama-Foundation/Gymnasium/blob/main/gymnasium/utils/passive_env_checker.py) is not able to handle extra arguments and throws an Type error when the render function uses extra arguments.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Plahmy** [comment]
Okay, I thought about this too but only after I read through the code and found this discrepancy.

**Comment by pseudo-rnd-thoughts** [comment]
I'm not going to fix it as it will be replaced by the experimental version of the wrapper where this is already fixed - https://github.com/Farama-Foundation/Gymnasium/blob/d1076ba3fdbbbbf9caa96f6dbfb756c06f2b1327/gymnasium/experimental/wrappers/common.py#L117
