### ISSUE TITLE
[Bug Report] MuJoCo `Ant` & `Humanoid` have wrong "x_position" & "y_position" `info`

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [Farama-Foundation/Gymnasium#521]
### Describe the bug

For the `Humanoid` and `Ant` the `info['x_position']` and `info['y_position']` are not the same as the observations when `exclude_current_positions_from_observation=False` is passed. (which is what the documentation suggests)

In general, I see no unit tests for MuJoCo `info`

## Humanoid
The humanoid returns the center of mass instead of `qpos[0:2]`

https://github.com/Farama-Foundation/Gymnasium/blob/ae5d8888aae23cdb0bafc9dc0648481d9e51ebaa/gymnasium/envs/mujoco/humanoid_v4.py#L378

https://github.com/Farama-Foundation/Gymnasium/blob/ae5d8888aae23cdb0bafc9dc0648481d9e51ebaa/gymnasium/envs/mujoco/humanoid_v4.py#L397-L398

## Ant
The humanoid returns the `get_body_com('torso')[0:2]` instead of `qpos[0:2]`
https://github.com/Farama-Foundation/Gymnasium/blob/ae5d8888aae23cdb0bafc9dc0648481d9e51ebaa/gymnasium/envs/mujoco/ant_v4.py#L315

https://github.com/Farama-Foundation/Gymnasium/blob/ae5d8888aae23cdb0bafc9dc0648481d9e51ebaa/gymnasium/envs/mujoco/ant_v4.py#L333-L334

### Code example

```shell
import gymnasium as gym
import pytest


# Note: "HumnanoidStandup-v4" does not have `info`
@pytest.mark.parametrize("env_id", ['Ant-v4', 'Ant-v3', 'HalfCheetah-v4', 'HalfCheetah-v3', 'Hopper-v4', 'Hopper-v3', 'Humanoid-v4', 'Humanoid-v3', 'Swimmer-v4', 'Swimmer-v3', 'Walker2d-v4', 'Walker2d-v3'])
def test_verify_info_x_position(env_id):
    """Asserts that the environment has position[0] == info['x_position']"""
    env = gym.make(env_id, exclude_current_positions_from_observation=False)

    _, _ = env.reset()
    obs, _,  _, _, info = env.step(env.action_space.sample())

    assert(obs[0] == info['x_position'])


# Note: "HumnanoidStandup-v4" does not have `info`
@pytest.mark.parametrize("env_id", ['Ant-v4', 'Ant-v3', 'Humanoid-v4', 'Humanoid-v3', 'Swimmer-v4', 'Swimmer-v3'])
def test_verify_info_y_position(env_id):
    """Asserts that the environment has position[0] == info['y_position']"""
    env = gym.make(env_id, exclude_current_positions_from_observation=False)

    _, _ = env.reset()
    obs, _,  _, _, info = env.step(env.action_space.sample())

    assert(obs[1] == info['y_position'])
```

### System info

```sh
$ pip list | grep gym  
gym                           0.26.2
gym-notices                   0.0.8
gymnasium                     0.28.1
gymnasium-notices             0.0.1
gymnasium-robotics            1.2.2
```

### Additional context

`['HalfCheetah-v5', 'Hopper-v5', 'HumanoidStandup-v5', 'Swimmer-v5', 'Walker2d-v5']` are not affected

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
@Kallinteris-Andreas could you make tests and update the code. I think we can make the changes in the v4 environments without a version change due to how infrequently `exclude_current_positions_from_observation` and `info` are used

**Comment by Kallinteris-Andreas** [comment]
I would rather not (by that logic, we should fix `v3` too), we should keep `v4` as is and fix it in `v5`.

**Comment by Kallinteris-Andreas** [comment]
@rodrigodelazcano is there a reason the `info` was implemented this way, or simply an oversight?
