### ISSUE TITLE
Default camera config

### ISSUE THREAD

**Issue by zichunxx** [Farama-Foundation/Gymnasium#523]
### Question

Is there some simple way to determine `DEFAULT_CAMERA_CONFIG` to render mujoco with human render mode, like [this](https://github.com/Farama-Foundation/Gymnasium/blob/95f2a426ce8d0d339ed6c7d6aacb0edbf668b64e/gymnasium/envs/mujoco/ant_v4.py#L8).

As far as I know, in addition to `distance,` there are `azimuth`, `elevation`, and `lookat` that can be customized. 

How can I visually determine these parameters in the `mujoco` window?

Besides, even given `camera_name="tracking"` and `camera_id=0` [here](https://github.com/Farama-Foundation/Gymnasium/blob/95f2a426ce8d0d339ed6c7d6aacb0edbf668b64e/gymnasium/envs/mujoco/ant_v4.py#L266), there is no change in the mujoco window view after registration, did I miss something?

Thanks!

**Comment by Kallinteris-Andreas** [comment]
If you want `mjCAMERA_FREE` you can do:

```py
env = gymnasium.make('Ant-v5', render_mode='rgb_array', camera_id=-1)
```

**Comment by pseudo-rnd-thoughts** [comment]
What do you mean by 
> render in the current mujoco window

**Comment by Kallinteris-Andreas** [comment]
Arguments `camera_id`, `camera_name` are ignored for the `human` window render

you can press TAB to change the camera

**Comment by Kallinteris-Andreas** [comment]
1) Has your original issue been solved, if so close the GitHub issue.
2) `v5` is under development (https://github.com/Farama-Foundation/Gymnasium-Robotics/pull/104)

**Comment by Kallinteris-Andreas** [comment]
Print this after modifying render window:
`>>> print(env.unwrapped.mujoco_renderer.viewer.cam`
