### ISSUE TITLE
[Question] Change the default glfw window height and width

### ISSUE THREAD

**Issue by zichunxx** [Farama-Foundation/Gymnasium#530]
### Question

Hi!

Is it possible to change the default glfw window height and width with the `human` rendering mode?

**Comment by Kallinteris-Andreas** [comment]
We do not currently support this feature, you have to use your Window Manager to resize the window

You can offer a PR, to add this feature.

P.S. In the future, please include `MuJoCo` in the title of the question. (or whichever framework you use)
