### ISSUE TITLE
[Proposal] Explicitly requires to allow closing a closed environment

### ISSUE THREAD

**Issue by qgallouedec** [Farama-Foundation/Gymnasium#531]
### Proposal

- Add a warning in the env checker when the custom environment that doesn't allow to be closed multiple times.
- Mention that it is recommended to be able to call the close function on an already closed environment.

### Motivation

It's usually possible to reset an environment several times.

```python
env = gym.make("CartPole-v1")
env.close()
env.close()
```

Is it good practice to do so? Since there's no simple way of checking whether an environment is closed, I propose to consider that calling the `close` method on a closed environment should not raise an error.

### Pitch

Give your opinion, I'll handle the PR if you're ok.

### Alternatives

Add an `is_closed` method, and always raise an error when the user tries to close a closed environment.

(But it would break so many things...)

### Additional context

See https://github.com/DLR-RM/stable-baselines3/pull/1525, and especially https://github.com/DLR-RM/stable-baselines3/pull/1525#issuecomment-1570998382

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Yes, I think this is a good idea and yes on the PR, thanks for offering
Would we prevent the second close in the `PassiveEnvCheckerWrapper` from being forwarded to the base environment?

**Comment by qgallouedec** [comment]
> Would we prevent the second close in the PassiveEnvCheckerWrapper` from being forwarded to the base environment?

I would say no. From a user's perspective, I expect the `PassiveEnvChecker` to check the environment passively. Preventing a second close can't be considered "passive" anymore.
