### ISSUE TITLE
[Proposal] `VideoRecorder` shouldn't close the env when it's closed

### ISSUE THREAD

**Issue by qgallouedec** [Farama-Foundation/Gymnasium#532]
### Proposal

Don't close the environment in `VideoRecorder.close`

### Motivation

- The VideoRecorder, not being a wrapper, shouldn't be permitted to close the environment.
- The functioning of the `VideoRecorder` when closed, i.e. saving the video, doesn't rely on the environment being closed.
- We may desire to continue interacting with the environment even after the recording has concluded.

### Pitch

Remove these two lines:

https://github.com/Farama-Foundation/Gymnasium/blob/d1076ba3fdbbbbf9caa96f6dbfb756c06f2b1327/gymnasium/wrappers/monitoring/video_recorder.py#L147-L148

### Alternatives

- Add an arg `close_env` to `VideoRecorder.close`
- Mention in the documentation that closing the recorder also closes the environment.

### Additional context

See https://github.com/DLR-RM/stable-baselines3/pull/1525 and more specifically https://github.com/DLR-RM/stable-baselines3/pull/1525#issuecomment-1570998382

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
The implementation of `VideoRecord` is updated in `experimental.wrappers.rendering.RecordVideoV0`
@younik is this a good idea to add in the meantime?

**Comment by younik** [comment]
> The implementation of `VideoRecord` is updated in `experimental.wrappers.rendering.RecordVideoV0`
> @younik is this a good idea to add in the meantime?

Closing the environment is a bug; I think it is a good idea removing it anyway
