### ISSUE TITLE
[Proposal] Check render_mode for RecordVideo wrapper early

### ISSUE THREAD

**Issue by robertoschiavone** [Farama-Foundation/Gymnasium#560]
### Proposal

Right now, when you wrap an `env` in a `RecordVideo`, the code throws only an user warning **at the end** of the training when it tries to save a video but `render_mode` is set to `None`, or in general to any other value except `rgb_array` and `rgb_array_list`.

It would be nice to check the render mode early, ideally inside the `RecordVideo` constructor, so that the training doesn't have to be restarted in case the parameter was accidentally left unspecified.

TL; DR:

- right now

```python
env = gym.make(env_name)
env = RecordVideo(env, directory)
train(model, env)
...
# throws user warning here, without recording
```

- proposal

```python
env = gym.make(env_name)
env = RecordVideo(env, directory) # 🚫 will throw exception here
```

```python
env = gym.make(env_name, render_mode="rgb_array")
env = RecordVideo(env, directory)  # ✅ will continue execution
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
@robertoschiavone Yes, that would be very helpful, could you make a PR for it

**Comment by robertoschiavone** [comment]
Absolutely, I will try to open a PR by the end of the week.
