### ISSUE TITLE
[Proposal] Consider moving away from `pygame`

### ISSUE THREAD

**Issue by epignatelli** [Farama-Foundation/Gymnasium#563]
### Proposal

As per title, consider removing the `pygame` dependency from gymnasium.

### Motivation

More than one motivation, as follows:
1. Bad netiquette, the library advertises itself though a `print` statement at every `import`.
This is not only impractical when running python code, but it does not respect other's people softwares. What if every python library were to do that?
2. Bad culture. When people expressed opinions on the matter, they a) censored the opinion (see https://github.com/pygame/pygame/issues/1468#issuecomment-565535040), and b) locked the issue https://github.com/pygame/pygame/issues/1468 because it is not convenient for them, and not because it the bahaviour is abusive.

I also reported the matter to GitHub support, the ticket is currently open.

I personally, do not want to be part of such a culture, and as of my own choice, do not use pygame anymore, and libraries that depend on it. I'd be happy to revert back using it, should the situation change.
Gymnasium is one of them unfortunately, but because I don't think that Gymnasium shares that culture, I am opening this proposal because I want to keep using it.

### Pitch

Remove the dependency from `pygame`, and find an alternative foundation library.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Kallinteris-Andreas** [comment]
```
>>> import gymnasium
>>> env = gymnasium.make('Taxi-v3')
>>> import pygame
>>> pygame.__version__
'2.1.3'
```
Nothing prints on my end

**Comment by pseudo-rnd-thoughts** [comment]
@epignatelli Thanks for making us aware of this, I wasn't aware of this issue with Pygame. 
Previously the environments were implemented with pyglet which is much lower level and difficult to understand / implement. 
Would you have any suggestions of what to move to?

**Comment by epignatelli** [comment]
I had a brief look at what `pygame` is used for in `gymnasium`, but I don't think I know enough to have a useful proposal.

Perhaps, as a workaround in the meanwhile, we could hide the message from gymnasium, even if that doesn't solve the problem yet.
```bash
export PYGAME_HIDE_SUPPORT_PROMPT='hide'
```
or
```python
import os
os.environ["PYGAME_HIDE_SUPPORT_PROMPT"] = "hide"
```

I was about to make a pr, but I found that this was already implemented https://github.com/Farama-Foundation/Gymnasium/commit/2b993c8b980b570ffd794ac6dc4c3cfa12cddcbd
I didn't debug further, though.

**Comment by Kallinteris-Andreas** [comment]
@epignatelli so the issue has been fixed

**Comment by epignatelli** [comment]
1. The issue is not that gymnasium prints the statement. It is that it employs `pygame`. Hiding the print is a workaround, not a fix.
2. Have you read this comment? https://github.com/Farama-Foundation/Gymnasium/issues/563#issuecomment-1600676641

**Comment by epignatelli** [comment]
Btw, I opened another issue in `pygame`, at:
https://github.com/pygame/pygame/issues/3933 

Which got closed as duplicate to censor it again.

And they banned me from opening new issues:

<img width="1278" alt="image" src="https://github.com/Farama-Foundation/Gymnasium/assets/26899347/598833d0-5b5c-4562-850b-312fae53224a">

This is the `pygame` community.

**Comment by pseudo-rnd-thoughts** [comment]
I understand your issues @epignatelli and feel similarly (but as someone who manages a large project, I know that banning is sometimes necessary). 
I'm going to close the issue as currently to my knowledge there is no similar game engine project that we could use and unless this gets really bad then there I think we can continue using pygame.

We can continue the discuss if anyone has ideas of what to do
