### ISSUE TITLE
[Question] Is `check_env` supposed to call `step` without first calling `reset`?

### ISSUE THREAD

**Issue by robertoschiavone** [Farama-Foundation/Gymnasium#566]
### Question

I have a custom env that starts with a field object set to None, and the object is only initialized inside `reset`, since it needs to be reset each new episode.

My `step` method calls a method of this object knowing that it will be always initialized, since docs also say that we should always call `env.reset()` before the first `step` call.

Calling `check_env` on my env throws `AttributeError: 'NoneType' object has no attribute 'my_method'`. Is it how it's supposed to work?

**Comment by pseudo-rnd-thoughts** [comment]
Could you provide a minimal working example to test with? This is unexpected behaviour, `check_env` should test the `reset` function first before `step` preventing the issue that you report
