### ISSUE TITLE
[Proposal] Unkown `render_mode` should actually throw an exception

### ISSUE THREAD

**Issue by robertoschiavone** [Farama-Foundation/Gymnasium#567]
### Proposal

`UserWarning: WARN: The environment is being initialised with render_mode='something' that is not in the possible render_modes (['human', 'rgb_array']).`

Initializing an env with an unsupported render mode will almost certainly lead to undefined behavior. In my opinion, that should be stopped before it happens by throwing an exception instead of a warning.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
We considered this, currently we just raise a warning but it is the environment's responsibility to raise an error for an unknown render mode not gymnasium was our thought. 
Is there a particular case where you are having an issue?
