### ISSUE TITLE
[Bug Report] `RescaleAction` wrapper does not change the `action_space` accordingly

### ISSUE THREAD

**Issue by bheijden** [Farama-Foundation/Gymnasium#568]
### Describe the bug

The `RescaleAction` wrapper in (`gymnasium.wrappers.rescale_action`) does not change the `action_space` accordingly.

In contrast, the `RescaleAction` wrapper in `gym.wrappers.rescale_action` does!

When I compare both implementations, the following lines are missing in the `gymnasium` variant compared to the `gym` variant.

```python
self.action_space = spaces.Box(
    low=min_action,
    high=max_action,
    shape=env.action_space.shape,
    dtype=env.action_space.dtype,
)
````

This looks like a bug to me.

### Code example

```shell
import gymnasium as gym
#import gym

env = gym.make("Pendulum-v1")
env = gym.wrappers.rescale_action.RescaleAction(env, min_action=-1, max_action=1)

print(env.action_space)
# gymnasium-->Box(-2.0, 2.0, (1,), float32)
# gym --> Box([-1.], [1.], (1,), float32)
```

### System info

gymnasium: 0.28.1 (pip)
gym: 0.21.0 (pip)
python: 3.7
Ubuntu 20.04

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Thanks, this is also fixed in the experimental version of the wrapper, `experimental.wrappers.RescaleActionV0`
