### ISSUE TITLE
[Proposal] restrict `mujoco` version for "mujoco environments" (v4+)

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [Farama-Foundation/Gymnasium#570]
### Proposal

mujoco v4 environments support: `"2.1.5" <= mujoco.__version__ <= "2.3.3"`
mujoco v5 environments (will) support: `"2.3.3" <= mujoco.__version__`
and it is a good long term solution to pin `mujoco==2.3.3`

and so a restriction should be added to prevent making a mujoco-v4 environment with an unsupported version of `mujoco`
e.g. `gym.make("Hopper-v4")  # with mujoco==2.3.5`

a possible implementation would be to add something like to all the `v4` environments
```py
if "2.1.5" <= mujoco.__version__ <= "2.3.3":
    generate_error....  # tell the user to `pip instal mujuco==2.3.3`
```

There may be a better way to implement this. (Perhaps in `registration`?)

### Alternatives

generate a warning instead of an error

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Yes, for now, we have pinned the mujoco version for the CI to avoid this issue
But I think your plan is a good idea

**Comment by Kallinteris-Andreas** [comment]
We would have to skip CI for `mujoco-v4` environments if an incompatible version of `mujoco` was installed, what would be the best way to do that?

**Comment by pseudo-rnd-thoughts** [comment]
An elegant way, not way. We have a `mujoco_envs` variable I believe we could modify or we could add a `skipIf` for certain environment id

**Comment by Kallinteris-Andreas** [comment]
issues has been fixed with: https://github.com/Farama-Foundation/Gymnasium/pull/589

**Comment by Longyouyuan** [comment]
hi, how to pin the mujoco to 2.3.3? just input pip install mujoco==2.3.3?

**Comment by Kallinteris-Andreas** [comment]
yes
