### ISSUE TITLE
[Bug Report] Is `hopperEnv.viewer_setup()` obsolete

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [Farama-Foundation/Gymnasium#586]
### Describe the bug

https://github.com/Farama-Foundation/Gymnasium/blob/7d75d599b080116cc25f9c190f64c32d1e008cf8/gymnasium/envs/mujoco/hopper_v4.py#L299-L306

Hopper has `viewer_setup()` which serves no purpose

@rodrigodelazcano is that a remnant from the old render API?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
@rodrigodelazcano Do you know?
