### ISSUE TITLE
[Bug Report] `SyncVectorEnv` has a deprecated but unremoved method `seed()`, causing AttributeError

### ISSUE THREAD

**Issue by zhengzl18** [Farama-Foundation/Gymnasium#601]
### Describe the bug

The `SyncVectorEnv` has a method `seed()`, in which `super().seed(seed=seed)` is called. However, the method `seed()` has already been deprecated in `Env`.

### Code example

```python
import gymnasium as gym

sync_env = SyncVectorEnv([lambda: gym.make("CartPole-v1") for _ in range(3)])
sync_env.seed(0)
```

This yields:
> AttributeError: 'super' object has no attribute 'seed'

### System info

`gymnasium==0.28.1`

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Kallinteris-Andreas** [comment]
note: `reset_wait` does have a `seed` argument 
@pseudo-rnd-thoughts

**Comment by pseudo-rnd-thoughts** [comment]
You should do `envs.reset(seed=123)`, this will be updated soon
