### ISSUE TITLE
[Question] Ground-truth dynamics model in mujoco

### ISSUE THREAD

**Issue by KehanLong** [Farama-Foundation/Gymnasium#605]
### Question

Hi, 

Anyone know where can we access the ground-truth dynamics model for the mujoco environments? For example, the cart-pole, it seems the dynamics equations are not given in any files. (.xml file has some parameters, but not same as the standard cart-pole parameters, e.g. cart mass, pole mass, pole length, and so on). 

Thanks!

**Comment by Kallinteris-Andreas** [comment]
Pole length is 1 meter
cart mass is   mass: array([10.47197551])
pole mass is   mass: array([5.01859164])

**Comment by pseudo-rnd-thoughts** [comment]
@KehanLong Are you interested in the mujoco or cartpole dynamics? The Cartpole dynamics are programmed into the step and reset functions while the mujoco environment dynamics are the mujoco physics engine https://github.com/deepmind/mujoco

**Comment by KehanLong** [comment]
Thank you for the answer. Sorry for the confusion. I am interested in the cartpole and other robotic dynamics. I checked the step and reset functions, it looks like the states are updated by the mujoco physics engine. Would you please tell me if I can access the underlying dynamics model of those robotic systems?

**Comment by Kallinteris-Andreas** [comment]
yes, what do you want to do?

**Comment by KehanLong** [comment]
I am implementing some classical control algorithms for those systems and comparing with RL algorithms, for example: the Lyapunov based approach. And those algorithms will require the known knowledge of the dynamics model.

**Comment by Kallinteris-Andreas** [comment]
Well then you will need to understand how `mujoco` works then https://mujoco.readthedocs.io/en/latest/overview.html

**Comment by KehanLong** [comment]
I see, thank you. May I ask where you find the parameters of the cartpole (pole length, mass, and so on)?

**Comment by Kallinteris-Andreas** [comment]
`env.unwrapped.model.body("cart")` (or "pole")

**Comment by KehanLong** [comment]
Thank you for your quick reply and help! Appreciated.

**Comment by KehanLong** [comment]
@pseudo-rnd-thoughts  I am interested in the dynamics of the cart pole and other robotic systems. I checked the step and reset functions in the repo but it looks like the states are updated by the Mujoco physics engine (not explicitly in the code). Could you please tell me if I can access the dynamics model (ODEs) of those robotic systems?

**Comment by Kallinteris-Andreas** [comment]
@KehanLong I would redirect you to https://github.com/deepmind/mujoco if you need further help, we can only help you with RL related questions here

**Comment by KehanLong** [comment]
Sure. Thank you for your help!

**Comment by KehanLong** [comment]
@Kallinteris-Andreas: Sorry, I think I need a few more clarifications. I found that I may not really need the underlying dynamical equations; instead, I will only need the \dot{x} (how the state changes over time). Do you have any suggestions on this? I am thinking about taking the differences between two consecutive states. I wonder if there may be a more accurate approach to knowing/estimating the \dot{x}, or, is there a way of setting the integration time (step function) small?

**Comment by rodrigodelazcano** [comment]
Hey @KehanLong. What I'm assuming is that \dot{x} are your state variables of your linearized dynamic equation system, right? If so, your \dot{x} will contain the carts position and poles angle, plus their derivatives (how they change over time) which will be the carts velocity and the poles angular velocity. Good news is that all these variables are in the observation space of the environment. If you have a look at the `InvertedPendulum` documentation you can check which of the variables is contained in each element of the array observation (https://gymnasium.farama.org/environments/mujoco/inverted_pendulum/#observation-space).
Also, note that the pole's angle is with respect to its vertical position (I think this should be a bit more clear in the docs @Kallinteris-Andreas ).

If this is not the case can you describe specifically which state variables do you require? We can try providing you with some help to get them in the Mujoco simulation. Usually these variables are retrieved from the MjData object in the simulation, which in the gymnasium environment you can get as `env.data`. You can also read the MjData documentatin here https://mujoco.readthedocs.io/en/latest/APIreference/APItypes.html#mjdata

**Comment by rodrigodelazcano** [comment]
@KehanLong I see that you also need these state variables for other environments. Can you also provide us with the environments you are planning to use and the state variables you need for each of them?

**Comment by KehanLong** [comment]
Thank you for your reply! I checked Mujoco and found that mj_forward is probably the function I need for the state variables. It seems that the variable 'qacc' is the corresponding \dot{x}. What do you think? Is there a wrapper function in Gymnasium that I should use?

**Comment by rodrigodelazcano** [comment]
I don't think `mj_forward` is what you need since this function only steps the simulation and without any time integration (no state variable updates), `mj_step` is rather used to step the simulation in the gymnasium environments.
I can't confidently assure that `qacc` corresponds to your state if you don't provide me with more details about your control system sorry. `qacc` contains the accelerations of the cart and the pole (angular). 
We don't have any wrappers to get this variable but you can get it after each step with:

```python
env.step(action)
qacc = env.data.qacc
```
It would be nice if you could provide us with more detail on what \dot{x} is

**Comment by KehanLong** [comment]
Thank you for your reply. What I mean for \dot{x} is how the state changes over time, which does not involve time integration. And if we integrate dot{x} over some short time interval, we will get the new state (I guess this is the env.step). 

So I think qacc should be exactly what I need. There is one thing I would like to make sure, does env.data.qacc correspond to the accelerations of applying the action (control) to the current state?
