### ISSUE TITLE
[Question] frame-skipping check in AtariPreprocessing wrapper

### ISSUE THREAD

**Issue by mzamini92** [Farama-Foundation/Gymnasium#611]
### Question

Correct me if I am wrong. There is a logical error in this check. The intended behavior is to raise an error if frame-skipping is enabled in the original environment because the AtariPreprocessing wrapper itself applies frame-skipping. But the current check is incorrect because it raises an error only if frame-skipping is disabled in the original environment. The condition should be negated like this:
```
if (
    env.spec is not None
    and "NoFrameskip" not in env.spec.id
    and getattr(env.unwrapped, "_frameskip", None) == 1
):
    raise ValueError(
        "Disable frame-skipping in the original env. Otherwise, more than one "
        "frame-skip will happen as through this wrapper"
    )
```

**Comment by pseudo-rnd-thoughts** [comment]
No, as we only want the issue raised if the environment has been internal frameskip of > 1, therefore, we **don't** want the error when `getattr(env.unwrapped, "_frameskip", None) == 1`

Looking at the code, I'm uncertain about the first two conditions rather than the third for the v5 environments
