### ISSUE TITLE
[Proposal] Pass `max_episode_steps` to `env.unwrapped.spec` in `gym.make`

### ISSUE THREAD

**Issue by rickstaa** [Farama-Foundation/Gymnasium#615]
### Proposal

It would be great to have a way to retrieve the `max_episode_steps` a user used when calling the [gym.make](https://github.com/Farama-Foundation/Gymnasium/blob/8a75f5a5cab9cca68ddfd7156bcf8639152e7625/gymnasium/vector/__init__.py#L22) function. My first thought was to pass it on to `EnvSpec` class in the [gym.make](https://github.com/Farama-Foundation/Gymnasium/blob/8a75f5a5cab9cca68ddfd7156bcf8639152e7625/gymnasium/vector/__init__.py#L22) function.

https://github.com/Farama-Foundation/Gymnasium/blob/9d8db14e7f84a8c4e6b5bf5135d9f60de40e168b/gymnasium/envs/registration.py#L821

but it looks like this might conflict with how the [TimeLimit](https://github.com/Farama-Foundation/Gymnasium/blob/8a75f5a5cab9cca68ddfd7156bcf8639152e7625/gymnasium/wrappers/time_limit.py#L14) wrapper works 🤔 (see [this comment](https://github.com/Farama-Foundation/Gymnasium/pull/355#issuecomment-1455274560) by @pseudo-rnd-thoughts). Maybe we can append it to the `kwargs` that are passed to this method as `make_max_episode_steps`?

https://github.com/Farama-Foundation/Gymnasium/blob/9d8db14e7f84a8c4e6b5bf5135d9f60de40e168b/gymnasium/envs/registration.py#L826C13-L826C13

### Motivation

In some environments, I would like to give the agent a variable reward penalty when it collides with the environment. This penalty should decrease based on how many steps the agent is from being truncated:

$n_{max} - n_{collision}$

In which:

* $n_{max}$ - the maximum number of steps an agent can take before begin truncated.
* $n_{collision} - the step when the collision occurred.

### Pitch

I noticed that the `max_episode steps` variable is not passed to the environment by the [gym.make](https://github.com/Farama-Foundation/Gymnasium/blob/8a75f5a5cab9cca68ddfd7156bcf8639152e7625/gymnasium/vector/__init__.py#L22) function:

https://github.com/Farama-Foundation/Gymnasium/blob/8a75f5a5cab9cca68ddfd7156bcf8639152e7625/gymnasium/envs/registration.py#L824

I think the reason is that the episode truncation is handled by the [TimeLimit](https://github.com/Farama-Foundation/Gymnasium/blob/8a75f5a5cab9cca68ddfd7156bcf8639152e7625/gymnasium/wrappers/time_limit.py#L14) wrapper. By setting it in the [gym.make](https://github.com/Farama-Foundation/Gymnasium/blob/8a75f5a5cab9cca68ddfd7156bcf8639152e7625/gymnasium/vector/__init__.py#L22) function, this variable could become outdated when somebody changes it directly on the wrapper.

### Alternatives

I currently use the value found in the [gym.registry](https://github.com/Farama-Foundation/Gymnasium/blob/8a75f5a5cab9cca68ddfd7156bcf8639152e7625/gymnasium/envs/registration.py#L258) dictionary, but this value is outdated when a user supplies the [gym.make](https://github.com/Farama-Foundation/Gymnasium/blob/8a75f5a5cab9cca68ddfd7156bcf8639152e7625/gymnasium/vector/__init__.py#L22) function with a different `max_episode_steps`.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Hey, I would solve this by not using the time limit wrapper and implementing the truncation code within the environment. 
Then you should have access to all of the variables. Sadly you can't use max episode steps as the parameter.

For an example of this, see Minigrid project, it already implements this

**Comment by rickstaa** [comment]
> Hey, I would solve this by not using the time limit wrapper and implementing the truncation code within the environment. Then you should have access to all of the variables. Sadly you can't use max episode steps as the parameter.
> 
> For an example of this, see Minigrid project, it already implements this

@pseudo-rnd-thoughts Thanks for your fast response. I did consider the method you described, but since there is currently no way to disable the [TimeLimit](https://github.com/Farama-Foundation/Gymnasium/blob/8a75f5a5cab9cca68ddfd7156bcf8639152e7625/gymnasium/wrappers/time_limit.py#L14) wrapper from within the environment, the environment will break without a warning when a user supplies the [gym.make](https://github.com/Farama-Foundation/Gymnasium/blob/8a75f5a5cab9cca68ddfd7156bcf8639152e7625/gymnasium/vector/__init__.py#L22) function with the `max_episode_steps` argument.

```python
import gymnasium as gym

ENV_NAME = "minigrid:MiniGrid-Empty-5x5-v0"

MAX_TIME_WRAPPER_STEPS = 10
MAX_ENV_STEPS = 110

if __name__ == "__main__":
    env = gym.make(
        ENV_NAME,
        render_mode="human",
        max_episode_steps=MAX_TIME_WRAPPER_STEPS,
        max_steps=MAX_ENV_STEPS,
    )

    # Define a policy function.
    # NOTE: Can be any function that takes an observation and returns an action.
    def policy(*args, **kwargs):
        """A simple policy that samples random actions."""
        return env.action_space.sample()

    # Run training loop.
    observation, info = env.reset(seed=42)
    for step in range(1000):
        action = policy(observation)  # User-defined policy function
        observation, reward, terminated, truncated, info = env.step(action)

        if terminated or truncated:
            assert (
                truncated and step != MAX_TIME_WRAPPER_STEPS - 1
            ), "The time wrapper truncated the environment before the max number of steps was reached."
            print("Environment terminated or truncated. Resetting.")
            observation, info = env.reset()
    env.close()
```

It would be nice to have a way to retrieve this information from within the environment class. I noticed that this information was available in the past but has been removed in #355. I also saw that some other users wanted to know a way to retrieve this information (see https://github.com/openai/gym/issues/1465 and a question was asked about this in https://stackoverflow.com/questions/55955630/openai-gym-how-do-i-access-environment-registration-data-for-e-g-max-episode). I fully understand why this information was removed since it might confuse people into thinking that the `max_episode_steps` variable inside the environment influences the `max_episode_steps` into the [TimeLimit](https://github.com/Farama-Foundation/Gymnasium/blob/8a75f5a5cab9cca68ddfd7156bcf8639152e7625/gymnasium/wrappers/time_limit.py#L14) wrapper. I agree that turning off all parameters in the `env.unwrapped.spec`'s EnvSpec such that gym.make(env.unwrapped.spec) is equivalent to just the base environment preventing this confusion. I, however, think that having this information stored somewhere would be beneficial in some use cases:

- People like me who want to use the [TimeLimit](https://github.com/Farama-Foundation/Gymnasium/blob/8a75f5a5cab9cca68ddfd7156bcf8639152e7625/gymnasium/wrappers/time_limit.py#L14) wrapper but require the `max_episode_steps` information for things other than the episode truncation.
- People who want to prevent people from using the [TimeLimit](https://github.com/Farama-Foundation/Gymnasium/blob/8a75f5a5cab9cca68ddfd7156bcf8639152e7625/gymnasium/wrappers/time_limit.py#L14) wrapper by throwing a warning when this wrapper is used.

Therefore, I propose injecting this information as a private variable into the environment. You can see my proposal in #618.

**Comment by rickstaa** [comment]
> 1. If you pass `max_episode_steps=None` this should result in the `TimeLimit` wrapper not being added to the environment
> 2. Could you implement this as a wrapper, if so, you could include it in the `gymnasium.register(..., addition_wrappers=(...,))` then access the environment and time limit wrapper?
> 
> Personally, I don't like the idea of treating `TimeLimit` in this special way for a minimally used use-case

You are right. It is better to have users like me inject this variable themselves through a wrapper when they need it than to add it to the main codebase just for these edge cases. Let's go ahead and close this proposal and the accompanying pull request. I will create a wrapper and attach it to this pull request and the related [StackOverflow](https://stackoverflow.com/questions/55955630/openai-gym-how-do-i-access-environment-registration-data-for-e-g-max-episode) question so that other people can also use it.

**Comment by rickstaa** [comment]
@pseudo-rnd-thoughts, as promised, here, for future reference, a small wrapper user can use to inject the `max_episode_steps` attribute found in into the base environment:

```python
"""This file contains a small gymnasium wrapper that injects the `max_episode_steps`
argument of a potentially nested `TimeLimit` wrapper into the base environment under the
`_time_limit_max_episode_steps` attribute.
"""

import gymnasium as gym


def get_time_limit_wrapper_max_episode_steps(env):
    """Returns the ``max_episode_steps`` attribute of a potentially nested
    ``TimeLimit`` wrapper.

    Args:
        env (gym.Env): The gymnasium environment.

    Returns:
        int: The value of the ``max_episode_steps`` attribute of a potentially nested
            ``TimeLimit`` wrapper. If the environment is not wrapped in a ``TimeLimit``
            wrapper, then this function returns ``None``.
    """
    if hasattr(env, "env"):
        if isinstance(env, gym.wrappers.TimeLimit):
            return env._max_episode_steps
        get_time_limit_wrapper_max_episode_steps(env.env)
    return None


def inject_attribute_into_base_env(env, attribute_name, attribute_value):
    """Injects the ``max_episode_steps`` argument into the base environment under the
    `_time_limit_max_episode_steps` attribute.

    Args:
        env (gym.Env): The gymnasium environment.
        attribute_name (str): The attribute's name to inject into the base
            environment.
        attribute_value (object): The attribute's value to inject into the base
            environment.
    """
    if hasattr(env, "env"):
        return inject_attribute_into_base_env(env.env, attribute_name, attribute_value)
    setattr(env, attribute_name, attribute_value)


class MaxEpisodeStepsInjectionWrapper(gym.Wrapper):
    """A gymnasium wrapper that injects the ``max_episode_steps`` attribute of the
    ``TimeLimit`` wrapper onto the base environment as the
    ``_time_limit_max_episode_steps`` attribute. If the environment is not wrapped in
    a ``TimeLimit`` wrapper, then the ``_time_limit_max_episode_steps`` attribute is
    set to ``None``.
    """
    def __init__(self, env):
        """Wrap a gymnasium environment.
        Args:
            env (gym.Env): The gymnasium environment.
        """
        super().__init__(env)

        # Retrieve max_episode_steps from potentially nested TimeLimit wrappers.
        max_episode_steps = get_time_limit_wrapper_max_episode_steps(self.env)

        # Inject the max_episode_steps attribute into the base environment.
        inject_attribute_into_base_env(
            self.env, "_time_limit_max_episode_steps", max_episode_steps
        )
```
