### ISSUE TITLE
[Question] Frame stacking hasn't been applied to AtariPreprocessing wrapper

### ISSUE THREAD

**Issue by olenmg** [Farama-Foundation/Gymnasium#619]
### Question

As I saw the `AtariPreprocessing` wrapper implemented in `gymnasium.wrappers.atari_preprocessing`, I cannot figure out the code for frame stacking.
Docstring described that `AtariPreprocessing` follows Machado et al. (2018), and the paper mentioned that they used frame stacking in section 2.1 Setting.

But I'm not sure about this yet. Can you check it out?
If this is the case, I can try PR. If it was intentionally taken out, can you tell me the reason?

**Comment by pseudo-rnd-thoughts** [comment]
Hey, the frame stacking wrapper is provided separately, `gymnasium.wrappers.FrameStackWrapper` I believe

**Comment by pseudo-rnd-thoughts** [comment]
We can update the docstring, for the reason, I believe because it can be sub-optimal for replay buffers, therefore, google dopamine libraries does the frame stacking within the agent rather than environment

**Comment by olenmg** [comment]
I see. Thank you for your answer.
