### ISSUE TITLE
[Bug Report] Conda installs 0.28.1

### ISSUE THREAD

**Issue by BertrandDecoster** [Farama-Foundation/Gymnasium#621]
### Describe the bug

As of 0.29.0, there is now support for conda packages. However, doing `conda install gymnasium` offers to install 0.28.1 and forcing `conda install gymnasium==0.29.0` fails to find any package

### Code example

```shell
conda install gymnasiumn
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Kallinteris-Andreas** [comment]
@ChristofKaufmann

**Comment by ChristofKaufmann** [comment]
I saw the conda package for 0.29.0 is not ready yet, because there is an issue with a test on linux-aarch/ppc, see [here](https://github.com/conda-forge/gymnasium-feedstock/pull/30#issuecomment-1636714378). I might look into it, but haven't had time yet.

**Comment by pseudo-rnd-thoughts** [comment]
The conda forge has been updated, https://github.com/conda-forge/ale-py-feedstock, therefore, closing this issue
