### ISSUE TITLE
[Bug Report] `vector_entry_point` not working as expected

### ISSUE THREAD

**Issue by nollied** [Farama-Foundation/Gymnasium#625]
### Describe the bug

I was expecting that when defining the `vector_entry_point` in the gym.register function that it would defer to my custom vectorized create function instead of looping over the environment create method and wrapping with sync/async. for my env, i wrote custom vectorization code, but its totally useless when wrapped with sync/async vec wrapper.

### Code example

```shell
Inside of "path/to/vec_func.py"

import gymnasium as gym
class CustomVecEnv(gym.vector.VectorEnv):
    pass

def vec_func(*args, **kwargs):
    return CustomVecEnv(*args, **kwargs)
```

```
gymnasium_register(
    id="MyEnv-v0",
    entry_point="path/to/func:func",
    vector_entry_point="path/to/vec_func:vec_func",
)
```

then

```
env = gym.vector.make("MyEnv-v0")
```

doesn't work, for me it just hangs, but if you get it not to hang it should return a sync/async instance of the env instead of returning the custom class env definition.
```


### System info

`gymnasium                     0.28.1`
`ubuntu 20.04`
`python = 3.8.12`

### Additional context

i'm using a custom vectorized environment. I can't share it, but it should be purely an interface issue. 

also, what is `vector_entry_point` even doing?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Hey, could you try using the 'gymnasium.make_vec' function?

**Comment by nollied** [comment]
@pseudo-rnd-thoughts yeah, but i have to specify the vectorization method as custom, right? i'm creating a PR that auto-determines custom when a custom vectorization method is sepcified. otherwise it'll default to "async" as usual. that okay?

**Comment by nollied** [comment]
@pseudo-rnd-thoughts PR is open https://github.com/Farama-Foundation/Gymnasium/pull/626

it should be ready to go, ran pre-commit and everything + a test
