### ISSUE TITLE
[Bug Report] vectorized environment wrappers not working properly

### ISSUE THREAD

**Issue by verbose-void** [Farama-Foundation/Gymnasium#627]
### Describe the bug

Is this intended? right now the observation flatten wrapper for vectorized environments won't update the single_observation_space, only the observation_space.

### Code example

It breaks compatibility with this:

```
    env = gym.make_vec(
        "SomeEnv-v0",
        num_envs=16,
        vectorization_mode="sync",
    )
    
    env = gym.wrappers.FlattenObservation(env)
    env = gym.wrappers.RecordEpisodeStatistics(env)
    env = gym.wrappers.ClipAction(env)
    env = gym.wrappers.NormalizeObservation(env)
    env = gym.wrappers.TransformObservation(env, lambda obs: np.clip(obs, -10, 10))
    env = gym.wrappers.NormalizeReward(env, gamma=0.99)
    env = gym.wrappers.TransformReward(env, lambda reward: np.clip(reward, -10, 10))

    env.reset()
```

it works if you apply these transformations to a single environment then put them in a sync or async, but it doesn't work if you apply them to pre-created vector envs.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
This is a historic issue with Gym that we are solving in v1.0 
'make_vec' is part of this solution which uses the new experimental vector env. Importantly we have implemented new wrappers for vector environments only. 
This should correctly modify the spaces. 
To use them for now you need to use 'experimental.wrappers.vector'

**Comment by nollied** [comment]
@pseudo-rnd-thoughts okay cool thanks, i gave it a shot and am getting recursion depth issues. maybe they aren't fully ready yet?

**Comment by nollied** [comment]
@pseudo-rnd-thoughts you don't think the current vec env interface is sufficient to support vec and non-vec envs?

**Comment by pseudo-rnd-thoughts** [comment]
In short, as all 'VectorEnv' inherit from 'Env' it is not possible to determine if an environment is a vector environment or not, in particular with wrappers involved. 

Therefore, we have developed a way of separating out the 'Env' and 'VectorEnv'. This is helpful for type checking as the return types are completely different. However, this requires reimplementing most of the wrappers for vector envs. Most of this is novel work as most wrappers didn't support vector envs anyway.

You should just need to use the 'VectorWrapper' compared to 'Wrapper'

**Comment by nollied** [comment]
I never used the wrapper class, i inherited from the VecEnv class directly because i wrote custom batched operations
