### ISSUE TITLE
Updating custom OpenAI Gym environment developed with version 0.13.0 to Gymnasium version 0.29.0 ?

### ISSUE THREAD

**Issue by ChristosPeridis** [Farama-Foundation/Gymnasium#631]
### Question

Hello dear members of Farama-Foundation Team!

I have been using a custom OpenAI Gym environment that was developed using the version 0.13.0 of the Gym library. What would be the necessary steps that I would have to follow in order to update the environment to the latest Gymnasium 0.29.0 spec? Can you provide me with any supporting material or guide for achieving this goal?

Thank you very much for your valuable help!

Kind regards,

Christos Peridis

**Comment by pseudo-rnd-thoughts** [comment]
Hi @ChristosPeridis,

Thanks for wanting to update
V0.13.0 is so old that I have no idea what the API is 

https://gymnasium.farama.org/content/migration-guide/
This is a migration guide for v0.21 to the latest API
