### ISSUE TITLE
[Proposal] Blackjack action and observation space improvement

### ISSUE THREAD

**Issue by GiovanniGrotto** [Farama-Foundation/Gymnasium#646]
### Proposal

Hello! I would like to propose adding a more comprehensive version of blackjack to the existing environment. The current environment is quite simple, only considering 'stick' and 'hit' as actions and providing the sum of cards as observation.

### Motivation

 While this is good for simplify RL projects, I believe it limits the observation and action space, making the game heavily reliant on luck rather than strategy.

### Pitch

My suggestion is to introduce a complete version of blackjack where players can bet and also have options to 'double,' 'surrender,' and 'split.' Additionally, the observation would include information about each individual card, not just their sum. This enhancement would offer a more engaging and strategic gameplay experience, empowering agents to approximate the optimal strategy while keeping the action and observation space manageable.

I'm willing to work on this feature and I've already thought of some implementation details on how to do it without breaking previous code written with this env, but before explaining further and potentially wasting anybody's time, I would love to hear from experienced contributors if this idea is doable and interesting. Thanks in advance!

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Kallinteris-Andreas** [comment]
1) regarding the change to the observation (as an additional change) makes sense.
2) regarding the change to the action space it does not make sense, 'double' is not an action in standard blackjack, 'surrender' is game theoretically suboptimal, 'split' happens automatically.

**Comment by GiovanniGrotto** [comment]
Ok, I understand, thanks for the help.
Before changing the code and making a pull request I would like to ask the best way to implement it.
To make a change that will not break previous code written with this env I was thinking of adding a parameter like "natural" and "sab" in the initialization of the env.
If this parameter is set to true, then the observation space will be Tuple(List[Discrete(11)],  Discrete(11)), and I think that there is no more need to specify if there is a usable ace, in this way the observation will return the single card in the player's hand and not their sum.
Let me know if you think this may be a good approach or if you have any other ideas.

**Comment by pseudo-rnd-thoughts** [comment]
For us to change a game that involves a version change, the bonus of adding it must be significant otherwise it is not worth for users.
I don't totally understand your proposed changes but IMHO they are not a significant upgrade to the current environment.

If you want to make a more complex version I would make a GitHub project that people can download and use rather than modify this version.

**Comment by GiovanniGrotto** [comment]
I understand your point and it actually make a lot of sense.
