### ISSUE TITLE
[Question] why `call`, `get_attr`, and `set_attr` in the vec env interface?

### ISSUE THREAD

**Issue by nollied** [Farama-Foundation/Gymnasium#647]
### Question

I found when developing my own vectorized environments, I had not ever used the get and set attr in the way i think they were expected to be used. it's a bit confusing as the vector env class doesn't have a default implementation and it's unclear as to why it even exists.

would it be possible to remove these from the vector env interface? or maybe i'm missing key information

**Comment by nollied** [comment]
same goes for `call`. it seems these functions are redundant

**Comment by nollied** [comment]
it makes it less friendly to custom vectorization methods.

for example; if i have an environment like cartpole, but I vectorize it such that it's not merely a list of cartpole environments, but rather it's calculating the next states and rewards using tensor operations, there would be no individual function calls to aggregate, because they don't exist. so `.call`ing a method for a single env wouldn't really make sense. same goes for getting an attribute or setting one, it only really works for trivial vectorization implementations.

**Comment by nollied** [comment]
i came to this conclusion when [a test failed for this PR](https://github.com/Farama-Foundation/Gymnasium/pull/626/commits/35104f7eb3f9ab201154352c5ba9fff2a730e6db). this is the exact scenario that cropped up; doing `.call` and `.get_attr` seems to only make sense for the trivial vectorizations (sync and async) but in fact doesn't and can't exist for the custom cartpole vectorization.

**Comment by pseudo-rnd-thoughts** [comment]
In the v1.0.0 branch we have merged the experimental version of the `VectorEnv` which does not contain the `call`, `get_attr` or `set_attr` functions. These are only found in the `Async` and `Sync` vector environments

**Comment by nollied** [comment]
@pseudo-rnd-thoughts sweet!
