### ISSUE TITLE
[Bug Report] NormalizeReward wrapper only uses variance (doesn't use mean)

### ISSUE THREAD

**Issue by verbose-void** [Farama-Foundation/Gymnasium#651]
### Describe the bug

![image](https://github.com/Farama-Foundation/Gymnasium/assets/26421036/b7bfe727-339c-4623-8a39-a35dd3fe982a)

docstring says it uses the mean but it doesn't. constrastively, this is how NormalizeObservation is implemented:

![image](https://github.com/Farama-Foundation/Gymnasium/assets/26421036/22976f54-478f-4fc5-b302-77cd92fcbd5c)

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by nollied** [comment]
basically this can be solved by applying the same formula. i recommend adding a base function to RunningMeanStd "normalize" and just call it from everywhere else that way you don't have to reimplement the same method over and over.

**Comment by Kallinteris-Andreas** [comment]
Here is some context: https://github.com/openai/baselines/issues/538
