### ISSUE TITLE
[Question] Reset function leads to an Assertion error because of the seed

### ISSUE THREAD

**Issue by PBerit** [Farama-Foundation/Gymnasium#655]
### Question

Hi all,

I have the following reset function 

```
    def reset (self, **kwargs):
        seed = 1
        super().reset(seed=seed)
        self.state_difference_costs_to_conventional_solution = 0
        self.state_difference_peak_to_conventional_solution = 0
        self.state_thermal_discomfort = 0
        info = {}
        self.observation_space = np.array([0,0, 0])

        return  self.observation_space, info
```

This leads to the Assertion error of the gynasium environment checker
`AssertionError: Mostly likely the environment reset function does not call `super().reset(seed=seed)` as the random number generators are not different when different seeds are passed to `env.reset`.`

I tried multiple things but they all were not successfull. 

It says that `super().reset(seed=seed)` is not called but it is in fact called as you can see. I also tried `super().reset(seed=None)` but this leads to the same error.  I also tried:
```
    def reset (self):
        self.state_difference_costs_to_conventional_solution = 0
        self.state_difference_peak_to_conventional_solution = 0
        self.state_thermal_discomfort = 0
        info = {}
        self.observation_space = np.array([0,0, 0])

        return  self.observation_space, info
```
which leads to the error 
```
    raise gym.error.Error(
gymnasium.error.Error: The `reset` method does not provide a `seed` or `**kwargs` keyword argument.
```

Actually I don't need a seed argument at all as I don't use it. Can anyone tell me why this problem occurs and how to solve it?

**Comment by mvhensbergen** [comment]
Hello,

I am not part of this project but I would like to help you as I am getting to know the library myself.
From the documentation I read:

`For Custom environments, the first line of [reset()](https://gymnasium.farama.org/api/env/#gymnasium.Env.reset) should be super().reset(seed=seed) which implements the seeding correctly.`

So could you try this (and not setting the seed=1 yourself) and see what happens?

Also, it helps if you could attach the minimum amout of source code that triggers this bug so I can try to reproduce it.

**Comment by pseudo-rnd-thoughts** [comment]
The issue is not as clear as I expected given the warning

The problem is that you have a fixed `seed` as you don't use the seed from `kwargs` if provided
You could solve this with `seed = kwargs.get("seed", default=1)`

The issue is not 100% an issue but you probably shouldn't do it

There is a second issue that you are overwriting your environment's observation space in reset, you definitely shouldn't do this. I would just rename your variable to `obs`

**Comment by PBerit** [comment]
@mvhensbergen @pseudo-rnd-thoughts  thanks for your answer. 

I tried what you suggested by still get an error (I tried many options). My current code looks like this:
```

import gymnasium as gym
from gymnasium import Env
from gymnasium.spaces import Discrete, Box, Tuple, MultiDiscrete

import Run_Simulations_Help
import SetUpScenarios
import os
import pickle
import numpy as np

class DSM_Env(Env):
    def __init__(self, total_number_of_solutions_per_day, number_of_days_for_training, number_of_new_solutions_per_solution):

        self.action_space = Discrete(3)
        self.observation_space = Box(low=np.array([0, 0, 0]), high=np.array([1, 1, 1]),  dtype=np.float64)

        #State parameters
        self.state_difference_costs_to_conventional_solution = 0
        self.state_difference_peak_to_conventional_solution = 0
        self.state_thermal_discomfort = 0
        self.help_state_costs_conventional_solution = 0
        self.help_state_peak_conventional_solution = 0
        self.help_state_thermal_discomfort = 0


        #Auxillary variables
        self.current_number_total_solutions_of_the_run = 0
        self.current_iteration_of_the_training_day = 0
        self.current_training_day = 0
        self.solution_of_current_iteration = 0
        self.read_data_for_new_iteration = True
        self.list_of_solution_current_training_day = []
        self.help_counter_current_number_new_solution_per_solution = 0

    def reset (self, **kwargs):
        seed = kwargs.get("seed", default=1)
        super().reset(seed=seed)
        self.state_difference_costs_to_conventional_solution = 0
        self.state_difference_peak_to_conventional_solution = 0
        self.state_thermal_discomfort = 0
        info = {}
        obs = np.array([0,0, 0])

        return  obs, info


    def render (self):
        pass

    def step(self, action ):

        #Read the base solution when a new training day is used
        if self.read_data_for_new_iteration == True:
            
            #read list of base solutions for a new iteration
            read_RL_data_day = 200 #ToDo: Adjust dynamically
            read_RL_data_iteration = 1 #ToDo: Adjust dynamically
    
            file_path = r"C:\Users\wi9632\Desktop\Ergebnisse\DSM\RL_Input\list_population_NB" + str(SetUpScenarios.numberOfBuildings_Total) + "_Day" + str(read_RL_data_day) + "_It" + str(read_RL_data_iteration) + ".pkl"
            # Load the list from the file
            try:
                with open(file_path, "rb") as file:
                    self.list_of_solution_current_training_day = pickle.load(file)
            except FileNotFoundError:
                print(f"Error: File '{file_path}' not found.")
                return 0, 0, 0
    
            #read conventional solution
            read_RL_data_iteration = 0
            file_path = r"C:\Users\wi9632\Desktop\Ergebnisse\DSM\RL_Input\list_population_NB" + str(SetUpScenarios.numberOfBuildings_Total) + "_Day" + str(read_RL_data_day) + "_It" + str(read_RL_data_iteration) + ".pkl"
            try:
                with open(file_path, "rb") as file:
                    conventional_solutions = pickle.load(file)
                self.help_state_costs_conventional_solution = conventional_solutions[0]['simulationObjective_costs_Euro_combined'][0]
                self.help_state_peak_conventional_solution = conventional_solutions[0] ['simulationObjective_maximumLoad_kW_combined'][0]
                self.help_state_thermal_discomfort = conventional_solutions[0]['simulationObjective_thermalDiscomfort_combined'][0]
            
            except FileNotFoundError:
                print(f"Error: File '{file_path}' not found.")
                return 0, 0, 0

            self.read_data_for_new_iteration = False
       
        current_solution = self.list_of_solution_current_training_day[self.solution_of_current_iteration]
        peak_load_current_solution = current_solution['simulationObjective_maximumLoad_kW_combined'][0]
        costs_current_solution = current_solution['simulationObjective_costs_Euro_combined'][0]
        thermal_discomfort_current_solution = current_solution['simulationObjective_thermalDiscomfort_combined'][0]



        # Execute the action in the external simulation and return the next observation, reward, done, and info
        result_costs, result_peak, result_DC= Run_Simulations_Help.execute_single_modification_operator_decision(current_solution, action, read_RL_data_iteration, read_RL_data_day )

        #calculate state
        state = 0
        self.state_thermal_discomfort = result_DC
        self.state_difference_peak_to_conventional_solution = result_peak /self.help_state_peak_conventional_solution
        self.state_difference_costs_to_conventional_solution= result_costs /self.help_state_peak_conventional_solution

        #self.observation_space = np.array([self.state_thermal_discomfort, self.state_difference_peak_to_conventional_solution,self.state_difference_costs_to_conventional_solution])
        self.observation_space = np.array([1, 1,1])
        #Update auxilliary variables
        if self.help_counter_current_number_new_solution_per_solution >= number_of_new_solutions_per_solution:
            self.solution_of_current_iteration += 1
        if self.solution_of_current_iteration > len(self.list_of_solution_current_training_day):
            self.solution_of_current_iteration = 0
            read_RL_data_iteration += 1
            self.read_data_for_new_iteration = False


        #Calculate reward
        improvement_peak = 1 - result_peak/ peak_load_current_solution
        improvement_costs = 1 - result_costs/ costs_current_solution
        improvement_discomfort = 1 - result_DC/thermal_discomfort_current_solution
        reward = improvement_peak + improvement_costs + improvement_discomfort

        #Check termination criteria
        done = False


        info = {}
        return self.observation_space, reward, done, info


#Use Stable Baselines 3 to apply a RL algorithm on the environmetn
from stable_baselines3 import ppo
from stable_baselines3 import A2C


total_number_of_solutions_per_day = 100
number_of_days_for_training = 1
number_of_new_solutions_per_solution = 5

env = DSM_Env(total_number_of_solutions_per_day, number_of_days_for_training, number_of_new_solutions_per_solution)
from gymnasium.utils.env_checker import check_env
check_env(env)
#Ceck environment


models_dir = "models/A2C"
logdir = "logs/RL_BT1"
if not os.path.exists(models_dir):
    os.makedirs(models_dir)
if not os.path.exists(logdir):
    os.makedirs(logdir)

#Define the model
model = A2C('MlpPolicy', env, verbose=1)

#train and save the model

model.learn(total_timesteps=1000)


```
The current error I get is "TypeError: dict.get() takes no keyword arguments"

**Comment by pseudo-rnd-thoughts** [comment]
Sorry it should be `super().reset(**kwargs)`

**Comment by PBerit** [comment]
@pseudo-rnd-thoughts : Thanks for your answer. When using the above posted code with the modified `reset` method:
```
    def reset (self, **kwargs):
        super().reset(**kwargs)
        seed = kwargs.get("seed", default=1)
        self.state_difference_costs_to_conventional_solution = 0
        self.state_difference_peak_to_conventional_solution = 0
        self.state_thermal_discomfort = 0
        info = {}
        obs = np.array([0,0, 0])

        return  obs, info

I still get the same error "TypeError: dict.get() takes no keyword arguments"
```

**Comment by PBerit** [comment]
@pseudo-rnd-thoughts : Thanks for your answer. What I don't understand is why I can't return
`self.observation_space = np.array([0,0, 0])`

In the official documentation (https://gymnasium.farama.org/api/env/) it says: "observation (ObsType) – Observation of the initial state. This will be an element of [observation_space](https://gymnasium.farama.org/api/vector/#observation_space) (typically a numpy array) and is analogous to the observation returned by [step()](https://gymnasium.farama.org/api/env/#gymnasium.Env.step)." Actually In my `step' function, I return `self.observation_space`

**Comment by pseudo-rnd-thoughts** [comment]
Because you are overwriting the `observation_space` variable which is different from the observation returned from `reset` or `step`

**Comment by PBerit** [comment]
@pseudo-rnd-thoughts : Thanks for your answer and effort. I really appreciate it. Still I don't understand your comment. If you have a look at my `step` method, you'll see that I use the code
`self.observation_space = np.array([1, 1,1])`
When using the exact same code in the `reset` method `self.observation_space = np.array([0,0, 0])` (just with other numbers), I get an error and I don't understand att all why. You wrote that I am overwriting the variable. That is true for both methods step and reset. So I don't see the difference between the overwriting of the  `self.observation_space` variable

**Comment by martinvanhensbergen** [comment]
> @pseudo-rnd-thoughts : Thanks for your answer. What I don't understand is why I can't return `self.observation_space = np.array([0,0, 0])`
> 
> In the official documentation (https://gymnasium.farama.org/api/env/) it says: "observation (ObsType) – Observation of the initial state. This will be an element of [observation_space](https://gymnasium.farama.org/api/vector/#observation_space) (typically a numpy array) and is analogous to the observation returned by [step()](https://gymnasium.farama.org/api/env/#gymnasium.Env.step)." Actually In my `step' function, I return `self.observation_space`

As the documentation states what you should return is an observation which is -an element of- the observation space. What you do is overwrite the definition of the observation_space itself and return it.

So self.observation_space is the collection of all possible observations, step should return only one observation out of that space.

I hope this helps.

**Comment by martinvanhensbergen** [comment]
I will need to look into this a bit more (as I am responding while at work). I can try your code tomorrow - that will probably make me better see what the problem is.

**Comment by PBerit** [comment]
@martinvanhensbergen : Thanks a lot for your effort. I really appreciate it. Actually there is something wrong with my general gymnasium related code, especially the observation space. When I run the code now I get the error message "NotImplementedError: [1 1 1] observation space is not supported".

**Comment by mvhensbergen** [comment]
@PBerit

I have cut down your code sample to the essentials below:
`
import gymnasium as gym
from gymnasium import Env
from gymnasium.spaces import Discrete, Box, Tuple, MultiDiscrete

import pickle
import numpy as np

class DSM_Env(Env):
    def __init__(self):
        self.action_space = Discrete(3)
        self.observation_space = Box(low=np.array([0, 0, 0]), high=np.array([1, 1, 1]),  dtype=np.float64)

    def reset (self, **kwargs):
        super().reset(**kwargs)
        obs = np.array([0, 0, 0])
        info = {}
        return  obs, info

    def step(self, action ):
        self.observation_space = np.array([1, 1,1])
        reward = 0
        done = False
        info = {}
        return self.observation_space, reward, done, False, info

env = DSM_Env()
env.reset()
print(type(env.observation_space))
action = env.action_space.sample()
obj, rewards, done, _, info = env.step(action)
print(type(env.observation_space))
`

One remark, your original step function did not return the amount of variables that was required by the new library (got a Warning from the library when running) so you might also not run the latest version of gymnasium?

The output of this script is:
`
<class 'gymnasium.spaces.box.Box'>
<class 'numpy.ndarray'>
`

The above script shows that after your `step` function, you have overwritten the 'observation_space' variable in Env and to a ndarray instead of a Box. This corrupts your Env.

If you remove the 'self.' in the step function (thus making a local variable) you will return an observation without corrupting the `observation_space` variable.

I would advise to carefully look into the example code and tutorial to get a bit more feeling about the classes and try to rewrite your code.

In addition, I don't think this GitHub issue tracker is meant to discuss these things as it appears your issue is not a problem with the library itself ( and also has been closed by the maintainer). If you like you can contact me further outside this platform or perhaps find help elsewhere?

**Comment by PBerit** [comment]
@mvhensbergen : Thanks MV for your answer and effort. I really appreciate it. My gynasium version is 0.28.1 which according to the offical release note website (https://github.com/Farama-Foundation/Gymnasium) is newer than the latest version.

When running the code I get a lot of warnings:
```
C:\Users\wi9632\bwSyncShare\Eigene Arbeit\Code\Python\Demand_Side_Management\Instance_BT6_BT7\venv\Lib\site-packages\gymnasium\spaces\box.py:130: UserWarning: WARN: Box bound precision lowered by casting to float64
  gym.logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
C:\Users\wi9632\bwSyncShare\Eigene Arbeit\Code\Python\Demand_Side_Management\Instance_BT6_BT7\venv\Lib\site-packages\gymnasium\utils\passive_env_checker.py:164: UserWarning: WARN: The obs returned by the `reset()` method was expecting numpy array dtype to be float64, actual type: int32
  logger.warn(
C:\Users\wi9632\bwSyncShare\Eigene Arbeit\Code\Python\Demand_Side_Management\Instance_BT6_BT7\venv\Lib\site-packages\gymnasium\utils\passive_env_checker.py:164: UserWarning: WARN: The obs returned by the `step()` method was expecting numpy array dtype to be float64, actual type: int32
  logger.warn(
C:\Users\wi9632\bwSyncShare\Eigene Arbeit\Code\Python\Demand_Side_Management\Instance_BT6_BT7\venv\Lib\site-packages\gymnasium\utils\passive_env_checker.py:275: UserWarning: WARN: The reward returned by `step()` must be a float, int, np.integer or np.floating, actual type: <class 'numpy.ndarray'>
  logger.warn(
C:\Users\wi9632\bwSyncShare\Eigene Arbeit\Code\Python\Demand_Side_Management\Instance_BT6_BT7\venv\Lib\site-packages\gymnasium\utils\env_checker.py:317: UserWarning: WARN: Not able to test alternative render modes due to the environment not having a spec. Try instantialising the environment through gymnasium.make
  logger.warn(
Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
```

I already had a close look at the example codes and tutorials. The problem is that I had been using gym before and somehow gynasium seems to be way more complex to use (especially when building own environments). The other aspect which makes things more difficult is that I am reading - after some iterations - the state from an external file and execute the actions in an external simulation. So the actions don't always affect the state (as it is sometime read from an external file).

**Comment by pseudo-rnd-thoughts** [comment]
v0.29.0 is the latest version - https://github.com/Farama-Foundation/Gymnasium/releases

Have you read the warnings? 
```The obs returned by the `reset()` method was expecting numpy array dtype to be float64, actual type: int32```
```The obs returned by the `step()` method was expecting numpy array dtype to be float64, actual type: int32```
```The reward returned by `step()` must be a float, int, np.integer or np.floating, actual type: <class 'numpy.ndarray'>```

In short, there is a mismatch between the `observation_space` and the actual observations
You need to correct your observation to match the observation space or the observation space to the observation

Then with the reward, it is a numpy array rather than a float, int which is expected

**Comment by PBerit** [comment]
@pseudo-rnd-thoughts : Thanks a lot 
pseudo for your answer. I corrected all the warnings but I get another one that I don't understand "WARN: Not able to test alternative render modes due to the environment not having a spec. Try instantialising the environment through gymnasium.make
  logger.warn(" Do you have any clue as to why this is occuring and how to tackle it.

**Comment by pseudo-rnd-thoughts** [comment]
You can resolve it if the environment is registered (`gymnasium.register`) then you can initialise the environment with `gymnasium.make`
Then if you pass this environment to `check_env(env.unwrapped)` this shouldn't raise the warning

**Comment by PBerit** [comment]
@pseudo-rnd-thoughts : Thanks Pseudo for your answer and effort. I really appreciate it. Where and how shall I write the code`gymnasium.register` and `gymnasium.make`. When I use it in my code I get the error "NameError: name 'gymnasium' is not defined"

**Comment by pseudo-rnd-thoughts** [comment]
`import gymnasium` or `import gymnasium as gym` then `gymnasium.make` or `gym.make` depending on your code

**Comment by PBerit** [comment]
@pseudo-rnd-thoughts : Thanks for your comment. When using `gymnasium.make` I get the error `NameError: name 'gymnasium' is not defined`, when using `gym.make` I don't get an error but I still get the warning. I tried `gym.make` on many different parts in the code (step, init, reset, import, after the enviornment) but still get the warning "\env_checker.py:321: UserWarning: WARN: Not able to test alternative render modes due to the environment not having a spec. Try instantialising the environment through gymnasium.make
  logger.warn("

**Comment by PBerit** [comment]
Any idea how to get rid of this warning?

**Comment by pseudo-rnd-thoughts** [comment]
`gymnasium` and `gym` are different projects, therefore, `import gymnasium as gym` and `import gym` are actually totally different imports. We suggest `import gymnasium as gym` to minimise the amount of code that users would need to change. 
You should just need to do
```python
import gymnasium as gym
from gymnasium.utils.env_checker import check_env

# code for environment

gym.register("env-name-v0", EnvClassName)
env = gym.make("env-name-v0")

check_env(env.unwrapped)
```

**Comment by PBerit** [comment]
@pseudo-rnd-thoughts : I just have `import gymnasium as gym` but I still get this warning "C:\Users\wi9632\bwSyncShare\Eigene Arbeit\Code\Python\Demand_Side_Management\Instance_BT6_BT7\venv\Lib\site-packages\gymnasium\utils\env_checker.py:321: UserWarning: WARN: Not able to test alternative render modes due to the environment not having a spec. Try instantialising the environment through gymnasium.make
  logger.warn("

**Comment by pseudo-rnd-thoughts** [comment]
Using @mvhensbergen code in https://github.com/Farama-Foundation/Gymnasium/issues/655#issuecomment-1671411947 with additions at the end and changing the observation's dtype, this code produces no warnings for me

```python
from __future__ import annotations

from typing import Any

import numpy as np

import gymnasium as gym
from gymnasium import Env
from gymnasium.core import ObsType
from gymnasium.spaces import Discrete, Box
from gymnasium.utils.env_checker import check_env


class DSM_Env(Env):
    def __init__(self):
        self.action_space = Discrete(3)
        self.observation_space = Box(low=np.array([0, 0, 0]), high=np.array([1, 1, 1]), dtype=np.float64)

    def reset(
        self,
        *,
        seed: int | None = None,
        options: dict[str, Any] | None = None,
    ) -> tuple[ObsType, dict[str, Any]]:
        super().reset(seed=seed, options=options)
        obs = np.array([0.0, 0.0, 0.0])
        info = {}
        return obs, info

    def step(self, action):
        obs = np.array([1.0, 1.0, 1.0])
        reward = 0
        done = False
        info = {}
        return obs, reward, done, False, info


gym.register("dsm-env-v0", DSM_Env)
env = gym.make("dsm-env-v0")
check_env(env.unwrapped)
```

**Comment by PBerit** [comment]
@pseudo-rnd-thoughts : Thanks for your answer. When using:
```
gym.register("dsm-env-v0", DSM_Env(total_number_of_solutions_per_day, number_of_days_for_training, number_of_new_solutions_per_solution))
env = gym.make("dsm-env-v0")
```
I get the error "AttributeError: 'DSM_Env' object has no attribute 'split'" thrown by the line `env = gym.make("dsm-env-v0")`

When using:
`env = DSM_Env(total_number_of_solutions_per_day, number_of_days_for_training, number_of_new_solutions_per_solution)`

the code works but I get this strange warning "C:\Users\wi9632\bwSyncShare\Eigene Arbeit\Code\Python\Demand_Side_Management\Instance_BT6_BT7\venv\Lib\site-packages\gymnasium\utils\env_checker.py:321: UserWarning: WARN: Not able to test alternative render modes due to the environment not having a spec. Try instantialising the environment through gymnasium.make
  logger.warn(". I don't understand this warning. What does it actually say? As far as I know I am not using any rendering approach. And what is actually a "spec"? In your posted code, I also don't see any spec() function or variable

**Comment by mvhensbergen** [comment]
@PBerit In your version you pass an instance of your DSM_Env to gym.register and not the DSM_Env class.

Try:
`gym.register("dsm-env-v0", lambda: DSM_Env(<params>))`

**Comment by PBerit** [comment]
@mvhensbergen : Thanks for your answer and effort. It now runs without any warnings. Also thanks to @pseudo-rnd-thoughts . I really appreciate your help.
