### ISSUE TITLE
[Bug Report] Outdated API documentation in custom environment tutorial

### ISSUE THREAD

**Issue by ernestum** [Farama-Foundation/Gymnasium#669]
### Describe the bug

The [tutorial about writing a custom environment](https://gymnasium.farama.org/tutorials/gymnasium_basics/environment_creation/) still refers to `done` instead of `terminated` and `truncated`.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Kallinteris-Andreas** [comment]
@ernestum 
want to make a PR to fix it?

**Comment by pseudo-rnd-thoughts** [comment]
@kir0ul is in the process of updating the whole tutorial

**Comment by kir0ul** [comment]
Yes, still a work in progress, the new environment template should be up-to-date with the new API: https://github.com/Farama-Foundation/gymnasium-env-template/blob/main/template/%7B%7Benvironment_name%7D%7D/envs/grid_world.py#L101, but I still need to update the Gymnasium docs.

**Comment by ernestum** [comment]
Good to know thanks!

**Comment by kir0ul** [comment]
@ernestum if you want to take a look at the refactoring of the tutorial in https://github.com/Farama-Foundation/Gymnasium/pull/709, that'd be helpful :slightly_smiling_face:
