### ISSUE TITLE
[Bug Report] Own env creation doc points to outdated code example

### ISSUE THREAD

**Issue by adam-ah** [Farama-Foundation/Gymnasium#674]
### Describe the bug

The doc is correct here: https://gymnasium.farama.org/tutorials/gymnasium_basics/environment_creation/

But points to a now read-only and outdated repo here: https://github.com/Farama-Foundation/gym-examples

The repo incorrectly uses `gym` instead of `gymnasium`.

Long story short, the code the doc points to does not work any more.

Could you please remove the reference from the doc?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Hey, thanks for reporting @kir0ul is working on an updated version, I'm closing favour of https://github.com/Farama-Foundation/Gymnasium/issues/669 to keep a single discussion

**Comment by kir0ul** [comment]
@adam-ah if you want to take a look at the refactoring of the tutorial in https://github.com/Farama-Foundation/Gymnasium/pull/709, that'd be helpful :slightly_smiling_face:
