### ISSUE TITLE
[Bug Report] AssertionError on Observation Space Boundaries Check

### ISSUE THREAD

**Issue by novatc** [Farama-Foundation/Gymnasium#675]
### Describe the bug

'm receiving an AssertionError when using the NormalizeObservation wrapper alongside my custom environment and wrapper. The error suggests that the observation returned by the reset() method is outside the defined bounds of the observation space. However, when inspecting the values, they seem to be within the specified bounds. Specifically, the error message indicates:

`Expected: obs >= -90.01000213623047, actual min value: -0.004628769587725401 at index 7`
``

### Code example

```shell
In my custom environment, the observation space is defined as:

`low_boundary = self.dataframe.min().values
low_boundary = np.append(low_boundary, [0.0, 0.0])
high_boundary = self.dataframe.max().values
high_boundary = np.append(high_boundary, [1000.0, 1000.0])
self.observation_space = spaces.Box(low=low_boundary, high=high_boundary, shape=(self.dataframe.shape[1] + 2,), dtype=np.float32)
`
and the reset methode:

`def reset(self, seed=None, options=None):
    observation = self.get_observation().astype(np.float32)
    return observation, {}
`
and my custom wrapper:

`def reset(self, **kwargs):
    obs, info = self.env.reset(**kwargs)
    obs = obs.astype(np.float32)
    return obs, info
`
```

### System info

- Installed Gymnasium via pip.
- Gymnasium version 0.29.0
- macOS 13.4.1
- Python version: 3.9

### Additional context

The observation seems to be within the defined boundaries, and I suspect this might be an issue with the `NormalizeObservation` wrapper or the internal checking mechanism of Gymnasium.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Could you provide an example script to test with. 
Don't worry about the `self.dataframes` parts, just replace with the actual values to make testing easier

**Comment by novatc** [comment]
Sure! 
Here are the obs space boundaries
```
Low Boundary: [-9.0010002e+01  3.3433000e+04  3.2696000e+04 -1.0000000e+00
 -1.0000000e+00 -9.7492790e-01 -9.0096885e-01 -1.0000000e+00
 -1.0000000e+00  0.0000000e+00  0.0000000e+00]
High Boundary: [8.7100000e+02 8.1874000e+04 5.4368775e+05 1.0000000e+00 1.0000000e+00
 9.7492790e-01 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+03
 1.0000000e+03]

```
Here is a minimal test script
```
from stable_baselines3.common.env_checker import check_env
from gymnasium import register
from gymnasium import make
from cutsom_wrappers.custom_wrappers import CustomNormalizeObservation


# Set chosen environment parameters
env_id = "unscaled_env-v0"
entry_point = 'envs.unscaled_env:UnscaledEnv'

# this is unscaled data, that's why I use the Normalization wrapper
data_path = 'data/in-use/unscaled_train_data.csv'

# Register and make environment
register(id=env_id, entry_point=entry_point, kwargs={'data_path': data_path})
env = make(env_id)

# This is a custom wrapper that I use to make sure the observation is a numpy array. Had a dtype error before.
env = CustomNormalizeObservation(env)

# The check_env call throws the error
check_env(env)
```

Thats my custom Wrapper in case you need it:
```import numpy as np
from gymnasium import Wrapper
from gymnasium.wrappers import NormalizeObservation


class CustomNormalizeObservation(Wrapper):
    def __init__(self, env):
        super().__init__(env)
        self.env = NormalizeObservation(env)

    def reset(self, **kwargs):
        obs, info = self.env.reset(**kwargs)
        # make sure the observation is a numpy array
        if isinstance(obs, tuple):
            obs = np.array(obs)
        obs = obs.astype(np.float32)
        return obs, info

    def step(self, action):
        obs, reward, terminated, truncated, info = self.env.step(action)
        return obs.astype(np.float32), reward, terminated, truncated, info

```
I could also provide the dataframe I'using, since it's all open source.

**Comment by pseudo-rnd-thoughts** [comment]
I suspect that the issue is that the `NormalizeObservation` doesn't update the observation space currently even though the data is centred to zero I believe. 

Second, normally, `check_env` should be only passed the env and not a wrapper. 
Third, do you **need** the observation low and high to be correct?

**Comment by novatc** [comment]
Regarding your third point, I'm not sure if I understand correctly. Are you talking about the boundaries?
