### ISSUE TITLE
[Proposal] Observation Space in FrozenLake environment

### ISSUE THREAD

**Issue by PierreCounathe** [Farama-Foundation/Gymnasium#692]
### Proposal

This is a detail but it's confusing, and repeated in HF's RL course.

Right now the [observation space](https://gymnasium.farama.org/environments/toy_text/frozen_lake/#observation-space), and more precisely the player's position in FrozenLake is defined as:

> current_row * nrows + current_col (where both the row and col start at 0)

Although it would not change anything in terms of computations, I believe using describing it as current_row * ncols + current_col would make more sense, as this formula would generalize to non-square environments (grids).

### Motivation

Using the library, I have confirmed that the player position 1 is (x, y) = (0, 1). If this is true, then the current formula does not generalize to non-square grids.

Example with a 2*3 grid. Using the current formula, the players positions would be:
```
[[0, 1, 2],
[2, 3, 4]]
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Good point, thanks for spotting that. Could you make a PR to modify the tutorial

**Comment by PierreCounathe** [comment]
Opened a [PR](https://github.com/Farama-Foundation/Gymnasium/pull/695) to address the changes.

I could not check the tests, doctests, and build the docs because of a docker error I had when building the image, and that I do not have time to solve at the moment:
```shell
all-py.Dockerfile:31
--------------------
  29 |
  30 |     # Test with PyTorch CPU build, since CUDA is not available in CI anyway
  31 | >>> RUN pip install .[all,testing] --no-cache-dir --extra-index-url https://download.pytorch.org/whl/cpu
  32 |
  33 |     ENTRYPOINT ["/usr/local/gymnasium/bin/docker_entrypoint"]
--------------------
ERROR: failed to solve: process "/bin/bash -o pipefail -c pip install .[all,testing] --no-cache-dir --extra-index-url https://download.pytorch.org/whl/cpu" did not complete successfully: exit code: 1
```

Docker build command:
```shell
❯ docker build -f bin/all-py.Dockerfile \                                                 ─╯
             --build-arg PYTHON_VERSION=3.10 \
             --tag gymnasium-all-docker .
```

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for the PR, as the PR is just for documentation and the CI runs all of the tests then don't worry about it
