### ISSUE TITLE
[Bug Report] Custom environment doesn't exist 

### ISSUE THREAD

**Issue by ob-server** [Farama-Foundation/Gymnasium#697]
### Describe the bug

NameNotFound error for previously registered environment

### Code example

```shell
import gymnasium as gym

gym.envs.register(
        id="SprEnv-v0",
        entry_point='spr_rl.envs:SprEnv',
        kwargs={"config": param_config}
    )
print(gym.spec("SprEnv-v0"))
env = gym.make("SprEnv-v0")
```
Line 5 successfully prints the specs:
EnvSpec(id='SprEnv-v0', entry_point='spr_rl.envs:SprEnv', reward_threshold=None, nondeterministic=False, max_episode_steps=None, order_enforce=True, autoreset=False, disable_env_checker=False, apply_api_compatibility=False, kwargs={'config': {'seed': 8864, 'sim_config': 'inputs/config/simulator/mean-10.yaml', 'network': 'inputs/networks/abilene_1-5in-1eg/abilene-in1-rand-cap0-2.graphml', 'services': 'inputs/services/abc-start_delay0.yaml', 'training_duration': 100000, 'test_mode': None, 'sim_seed': None, 'best': False}}, namespace=None, name='SprEnv', version=0, additional_wrappers=(), vector_entry_point=None)

Then the following error message occurs: 
```
env = gym.make("SprEnv-v0")
  File "/home/.conda/envs/ray/lib/python3.9/site-packages/gymnasium/envs/registration.py", line 741, in make
    env_spec = _find_spec(id)
  File "/home/.conda/envs/ray/lib/python3.9/site-packages/gymnasium/envs/registration.py", line 527, in _find_spec
    _check_version_exists(ns, name, version)
  File "/home/.conda/envs/ray/lib/python3.9/site-packages/gymnasium/envs/registration.py", line 393, in _check_version_exists
    _check_name_exists(ns, name)
  File "/home/.conda/envs/ray/lib/python3.9/site-packages/gymnasium/envs/registration.py", line 370, in _check_name_exists
    raise error.NameNotFound(
gymnasium.error.NameNotFound: Environment `SprEnv` doesn't exist.
```

### System info

Gym was installed using pip, version 0.29.1
Python 3.9

### Additional context

I don't know why or how this would cause an error, but:
from ray.rllib.env.multi_agent_env import MultiAgentEnv
class SprEnv(MultiAgentEnv):

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Running this code, I'm not able to replicate this issue.
I can't find the `spr_rl` module to install either, could you provide a more detail script to replicate the issue
