### ISSUE TITLE
[Proposal] Migrate from `setup.py` to `pyproject.toml`

### ISSUE THREAD

**Issue by kir0ul** [Farama-Foundation/Gymnasium#7]
### Proposal 

I'd like to propose to migrate from using `setup.py` to using `pyproject.toml`.

### Motivation

Probably not super urgent, but since `pyproject.toml` should be the new standard and `setup.py` is now considered legacy ([see `pip` documentation](https://pip.pypa.io/en/stable/reference/build-system/setup-py/#setup-py-legacy)), it could be good to migrate at some point.

### Pitch

- Migrate all the content of `setup.py` to `pyproject.toml`
- Have a single source of truth for all the dependencies in `pyproject.toml`, thus remove `requirements.txt` and `test_requirements.txt`

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by jkterry1** [comment]
I'd propose postponing this as long as we're able to without creating issues. Setup.py is crazy ubiquitously used right now and is useful for new contributors to be able to read.

**Comment by kir0ul** [comment]
And how about removing the duplication of dependencies which are listed both in `setup.py` and `requirements.txt`?
1. Apparently `test_requirements.txt` is not used anywhere and there is already a `testing` entry in `setup.py`.
2. `requirements.txt` seems to be used only to build the docs, so we could make a `docs` entry in `setup.py`.
