### ISSUE TITLE
[Question] ImportError: cannot import name 'rendering' from 'gym.envs.classic_control'

### ISSUE THREAD

**Issue by arshiarafiei** [Farama-Foundation/Gymnasium#712]
### Question

I have this error showing up. 

"from gym.envs.classic_control import rendering
ImportError: cannot import name 'rendering' from 'gym.envs.classic_control'"

Is there something that I can fix this.

**Comment by pseudo-rnd-thoughts** [comment]
You appear to be using code with gym v0.21 I believe which is no longer supported. 
What version of gym are you using?

**Comment by arshiarafiei** [comment]
> You appear to be using code with gym v0.21 I believe which is no longer supported. What version of gym are you using?

it is 0.26.2.

**Comment by pseudo-rnd-thoughts** [comment]
I can't remember exactly but gym 0.18 or 0.21 should probably work

**Comment by arshiarafiei** [comment]
> I can't remember exactly but gym 0.18 or 0.21 should probably work

I could not install the 0.21 version, I have this error.

```
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for gym
  Running setup.py clean for gym
Failed to build gym
ERROR: Could not build wheels for gym, which is required to install pyproject.toml-based projects

```

**Comment by pseudo-rnd-thoughts** [comment]
https://github.com/openai/gym/issues/3202
