### ISSUE TITLE
[Bug Report] TypeError when calling env.reset() on a NormalizeObservation wrapped env

### ISSUE THREAD

**Issue by SafetyMary** [Farama-Foundation/Gymnasium#713]
### Describe the bug

Calling .reset()  method on NormalizeObservation wrapped env will raise the following error

>TypeError                                 Traceback (most recent call last)
Cell In[17], line 1
----> 1 wrapped_env.reset()

>File ~/.local/lib/python3.10/site-packages/gymnasium/wrappers/normalize.py:95, in NormalizeObservation.reset(self, **kwargs)
     93     return self.normalize(obs), info
     94 else:
---> 95     return self.normalize(np.array([obs]))[0], info

>File ~/.local/lib/python3.10/site-packages/gymnasium/wrappers/normalize.py:99, in NormalizeObservation.normalize(self, obs)
     97 def normalize(self, obs):
     98     """Normalises the observation using the running mean and variance of the observations."""
---> 99     self.obs_rms.update(obs)
    100     return (obs - self.obs_rms.mean) / np.sqrt(self.obs_rms.var + self.epsilon)

>File ~/.local/lib/python3.10/site-packages/gymnasium/wrappers/normalize.py:19, in RunningMeanStd.update(self, x)
     17 def update(self, x):
     18     """Updates the mean, var and count from a batch of samples."""
---> 19     batch_mean = np.mean(x, axis=0)
     20     batch_var = np.var(x, axis=0)
     21     batch_count = x.shape[0]

>File <__array_function__ internals>:200, in mean(*args, **kwargs)

>File ~/anaconda3/envs/py3.10-persistent/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3464, in mean(a, axis, dtype, out, keepdims, where)
   3461     else:
   3462         return mean(axis=axis, dtype=dtype, out=out, **kwargs)
-> 3464 return _methods._mean(a, axis=axis, dtype=dtype,
   3465                       out=out, **kwargs)

>File ~/anaconda3/envs/py3.10-persistent/lib/python3.10/site-packages/numpy/core/_methods.py:194, in _mean(a, axis, dtype, out, keepdims, where)
    192         ret = ret.dtype.type(ret / rcount)
    193 else:
--> 194     ret = ret / rcount
    196 return ret

>TypeError: unsupported operand type(s) for /: 'dict' and 'int'

Wonder if NormalizeObservation wrapper supports spaces.Dict() as observation space with env class methods returning observation variable as a dictionary.

### Code example

```shell
To recreate the error:

Build environment according to 
https://gymnasium.farama.org/tutorials/gymnasium_basics/environment_creation/#sphx-glr-tutorials-gymnasium-basics-environment-creation-py

Then run the following,
from gymnasium.wrappers import NormalizeObservation

env = GridWorldEnv()
wrapped_env = NormalizeObservation(env)
wrapped_env.reset()
```

### System info

python version: 3.10.11
gymnasium version: 0.29.1

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
In short, the normalize observation wrapper only supports array-based observations. 
We are interested in adding this support but haven't done it yet

**Comment by SafetyMary** [comment]
Thanks a lot, that's good to know. I would propose to raise an Exception pointing out such functionality has not been immplemented when wrapping an env with space.Dict() as observation space. Otherwise, please consider this case closed.
