### ISSUE TITLE
[Proposal] Option to read/write frames to disk in VideoRecorder 

### ISSUE THREAD

**Issue by rk1a** [Farama-Foundation/Gymnasium#714]
### Proposal

Add option to `VideoRecorder` to write frames to disk instead of keeping them in memory before writing a video.
Frames are loaded on the fly by `moviepy` reducing the overall memory requirement.
Frames are deleted after the video has been created.

### Motivation

There are environments with large render images and long episodes. Creating videos with the `VideoRecorder` increases the memory requirements significantly due to every frame being kept in memory.
Adding the proposed option would enable users to choose whether to trade-off additional time required for writing and loading frames to and from disk against the additional memory requirements.

### Alternatives

An alternative would be to reduce the render image resolution and/or the episode length using additional environment wrappers.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Closing as #715 implements this
