### ISSUE TITLE
What should I do if I want to write my own environment under the gymnasium？

### ISSUE THREAD

**Issue by 623637719** [Farama-Foundation/Gymnasium#718]
### Question

What should I do if I want to write my own environment under the gymnasium？

I found registration.py and __init__.py in gymnasium/envs/. I think I should start here but I'm not sure what to do？
![image](https://github.com/Farama-Foundation/Gymnasium/assets/111236370/580719c3-0be8-48c0-bd07-104bd72937df)

Here are the details of my computer：
![image](https://github.com/Farama-Foundation/Gymnasium/assets/111236370/adf5f29d-1f74-4dcd-b690-3776aeaf1f24)

**Comment by pseudo-rnd-thoughts** [comment]
You don't want to include your environment within gymnasium
See https://gymnasium.farama.org/tutorials/gymnasium_basics/environment_creation/#registering-envs for how to register and make a custom environment
