### ISSUE TITLE
[Question] Issue with automatic program termination when creating environment with render_mode='human'

### ISSUE THREAD

**Issue by awecefil** [Farama-Foundation/Gymnasium#720]
### Question

Hi everyone, I am new in gymnasium and trying to figure out some problems when using gymnasium. The below is my question and hope for any probably solutions.

When executing the following code, I've noticed that if I create the environment with render_mode='human', such as gym.make('LunarLander-v2', render_mode='human'), and reach the env.reset() line, the program automatically terminates without allowing further execution. However, when I remove render_mode='human', everything proceeds smoothly.

I would like to understand the cause of this behavior and how to resolve it.

Code Snippet:
```python
import gymnasium as gym
env = gym.make("LunarLander-v2", render_mode="human")
observation, info = env.reset()

for _ in range(1000):
    action = env.action_space.sample()
    observation, reward, terminated, truncated, info = env.step(action)
    if terminated or truncated:
        observation, info = env.reset()
env.close()
```

By the way, when the program reach the gym.make(), the terminal show a RuntimeWarning about pygame:
```
<frozen importlib._bootstrap>:241: RuntimeWarning: Your system is avx2 capable but pygame was not built with support for it. The performance of some of your blits could be adversely affected. Consider enabling compile time detection with environment variables like PYGAME_DETECT_AVX2=1 if you are compiling without cross compilation.
```
I am not sure whether this warning is the reason that causes the above problem.

Environment & Package Versions:

PC: HP Elite x360 1040 14 inch G9 2-in-1 Notebook
CPU: Intel(R) Core(TM) i5-1245U
Operating System: Windows 10 Business 64-bits
Python Version: 3.11.5
Python Packages Version: 
   -  gymnasium 0.28.1
   -  pygame 2.5.2
   -  pybox2d 2.3.10
   -  numpy 1.26.0
   -  matplotlib 3.8.0
   -  seaborn 0.12.2

**Comment by pseudo-rnd-thoughts** [comment]
I'm a bit confused on what you are saying.
I will try to summary what the code does and could you explain what you understand differently or isn't working as explained.

`render_mode="human"` will open a window and show the environment rendering for the current state  
`env.reset` will restart the environment to a new initial state
`env.step` will take an action on the state 

Therefore, when the code reaches `if terminated or truncated:` we restart the environment and so the rendered observation changes

**Comment by awecefil** [comment]
Sorry, I may not have described the problem clearly.
The situation I am encountering now is that, as you said, `render_mode="human"` will open a window and render the current environment. However, when I execute the program and reach `gym.make("LunarLander-v2", render_mode="human")`, the window does not appear. And the program interrupts in `env.reset()` without any error, so it doesn't go into the for-loop.

I try to change the  `render_mode="human"` into  `render_mode="rgb_array"` which return the rgb array of current state. Then I use the rgb array with `imshow()` function in matplotlib and it works normally(open a window and show the env rendering for the current state).

I am not sure why `render_mode="human"` doesn't show the window and render the current state automatically and then causes the program stop at `env.reset()`?

**Comment by RedTachyon** [comment]
This is almost certainly some problem with your local setup leading to a crash when rendering. I'd probably blame Windows, we don't officially support it, and I don't know whether pygame does. I recommend using WSL if you're sticking with windows though.
