### ISSUE TITLE
[Question] Atari flicker

### ISSUE THREAD

**Issue by RexGLiu** [Farama-Foundation/Gymnasium#721]
### Question

Hi, I'm attempting to replicate the DQN results, and I'm trying to make sure I've implemented the preprocessing step correctly. I'm wondering whether Gymnasium's Atari games still include flicker (which the original DQN paper mentioned), as this will determine whether I should still be maxing over two successive frames or not.

When I look at the frames from e.g. env = gym.make("ALE/Breakout-v5", obs_type="grayscale", frameskip=1), I don't see any flickering. So has flickering been removed from these environments, or am I missing something?

**Comment by RedTachyon** [comment]
This is a question about ALE, not Gymnasium

**Comment by pseudo-rnd-thoughts** [comment]
Yes, this is an issue with ALE just not with every environment

**Comment by RexGLiu** [comment]
Thank you Mark! I was wondering whether Gymnasium's v5 environments got rid of it or not, but that answers my question.
