### ISSUE TITLE
How to render both RGB and depth at the same time?

### ISSUE THREAD

**Issue by JChunX** [Farama-Foundation/Gymnasium#727]
### Question

Hi, I am trying to setup an experiment where the agent receives both `rgb_array` and `depth_array` as input. However with the new rendering API, I can only set the rendering mode like this: `gym.make('FrankaKitchen-v1', tasks_to_complete=['microwave', 'kettle'], render_mode='rgb_array')`

Is there a way to switch rendering modes dynamically? Thanks.

**Comment by Kallinteris-Andreas** [comment]
That behavior is not supported by the Gymnasium API.
but you can hack it in
```
>>> import gymnasium
>>> env = gymnasium.make('Ant-v5')
>>> env = gymnasium.make('Ant-v5', render_mode="rgb_array")
>>> env.reset()
>>> env.render()
>>> env.unwrapped.render_mode = "depth_array"
>>> env.render()
```
This works for `Gymansium/MuJoCo` keep in mind `FrankaKitchen` uses a different render method

and this will likely not work on non-robotic environments

**Comment by pseudo-rnd-thoughts** [comment]
Good question, there is no way solution sadly. 
Like @Kallinteris-Andreas says, the easiest solution is probably to create two environments which you pass the different render modes and provide the reset seed and step actions
