### ISSUE TITLE
Wrapper that override type of VectorEnv's instances. 

### ISSUE THREAD

**Issue by rpanackal** [Farama-Foundation/Gymnasium#729]
https://github.com/Farama-Foundation/Gymnasium/blob/54d2ba79404e9937ba2a1d44449915ecb00f95ce/gymnasium/wrappers/record_episode_statistics.py#L11

Let's say I create a SyncVectorEnv instance, where `single_env` is a function that makes an environment with the `gymnasium.make` function and sets seed ´i´. Then I want to wrap it with `gymnasium.wrappers.RecordEpisodeStatistics` to record episode info.

```
envs = gymnasium.vector.SyncVectorEnv([lambda: single_env(i) for i in range(n_envs)])
envs = gymnasium.wrappers.RecordEpisodeStatistics(envs)
```

Then wrapping it with `gymnasium.wrappers.RecordEpisodeStatistics` will lead to the following assertion failing as the wrapped does not extend `gymnasium.vector.VectorEnvWrapper`

```assert isinstance(envs, gymz.vector.VectorEnv), "RecordEpisodeStatistics returns non vector env"```

When such wrappers are meant to handle vector and non-vector environments, shouldn't they extend the `gymnasium.Wrapper` and `gymnasium.vector.VectoEnvWrapper` conditionally? Or am I missing something here?

**Comment by RedTachyon** [comment]
This is one of the last relics of some of the old and questionable design choices in gym and will be resolved soon-ish with the 1.0.0 release
