### ISSUE TITLE
[Bug Report] UserWarning occurring after every call of the env. 

### ISSUE THREAD

**Issue by davidireland3** [Farama-Foundation/Gymnasium#733]
### Describe the bug

```
UserWarning: WARN: env.shape to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.shape` for environment variables or `env.get_wrapper_attr('shape')` that will search the reminding wrappers.
  logger.warn(
```

the above warning occurs as soon as initiating the environment for CartPole-v1 and Hopper-v4. Gymnasium version used is 0.29.1. 

### Code example

```shell
import gymnasium as gym

env = gym.make("CartPole-v1")
env.reset()
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
I can't replicate the issue, are you sure that the issue is arising from the code provided above? 
I suspect that you are trying to access `env.shape` somewhere which is causing the warning

**Comment by davidireland3** [comment]
I just tried to replicate the issue. From the command line the error only occurs when trying to use `env.shape`. However, in PyCharm which is where I was originally using the code, it happens as soon as the environment is made and any call to the environment made thereafter. Any idea why this would be?

**Comment by pseudo-rnd-thoughts** [comment]
Hi, sorry I forgot to respond to this problem
Is this still an issue? I will close in the meantime
