### ISSUE TITLE
[Bug Report] "Basic usage" documentation incorrect/incomplete

### ISSUE THREAD

**Issue by smarianimore** [Farama-Foundation/Gymnasium#735]
### Describe the bug

**Reproduce**:
1. Copy code [here](https://gymnasium.farama.org/content/basic_usage/#interacting-with-the-environment)
2. pip install gymnasium
3. execute code 

**Expectation**: see "lunar lander" screen appear and game playing randomly

**Actual**: error in missing dependency from box2d

_Weird fact 1_: error messages refer to "bipedal walker" env (unrelated to lunar lander from user perspective)

**Solution**:
1. pip install swig
2. pip install gymnasium[box2d]

_Weird fact 2_: I came up with solution 1 because trying to do 2 directly resulting in error "failed building wheel" and had to google search solution cause no error message pointed to missing dependency from swig package

**Suggestion**: either fix gymnasium check to avoid checking envs the user is not using or improve documentation [here](https://gymnasium.farama.org/content/basic_usage/#interacting-with-the-environment)

### Code example

```shell
import gymnasium as gym
env = gym.make("LunarLander-v2", render_mode="human")
observation, info = env.reset()

for _ in range(1000):
    action = env.action_space.sample()  # agent policy that uses the observation and info
    observation, reward, terminated, truncated, info = env.step(action)

    if terminated or truncated:
        observation, info = env.reset()

env.close()
```

### System info

- gymnasium version 0.29.1 installed via pip for Python 3.11
- OS: Ubuntu 22.04.2
- Python 3.11

### Additional context

Code example taken from official documentation, [here](https://gymnasium.farama.org/content/basic_usage/#interacting-with-the-environment)

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for pointing that out, I will see if we can update the basic usage page to make this more clear

**Comment by smarianimore** [comment]
feel free to ask for a pull request if that's the intended behaviour and thus updating the doc pages is all that's needed
