### ISSUE TITLE
[Bug Report] Taxi window freeze after rendering the environment

### ISSUE THREAD

**Issue by adielashrov** [Farama-Foundation/Gymnasium#739]
### Describe the bug

Hello,

I'm trying to wrap the Taxi environment with a Flask server on Python.
Here are the steps to reproduce.
1. Start the server (Run the attached Python file).
2. The Taxi environment appears rendered for 2 seconds
3. The window turns black and freezes.
4. You need to terminate the Python process for the windows to close.
![freeze_taxi_env](https://github.com/Farama-Foundation/Gymnasium/assets/5080734/dc8361f6-920d-408a-a585-fc077bedb2ee)

### Code example

```shell
import gymnasium as gym
from flask import Flask, request, jsonify
from time import sleep
from taxi_helper import action_to_word

app = Flask(__name__)
env = gym.make("Taxi-v3", render_mode="human")
initial_obs = env.reset()
print(f"initial observation: {initial_obs[0]}")

@app.route('/env_step', methods=['POST'])
def step():
    action = request.json['action']
    state, reward, terminated, truncated, info = env.step(action)
    print(f"state: {state}")
    print(f"terminated: {terminated}")
    env.render()
    sleep(0.1)
    ret_value = jsonify({
        'state': str(state),
        'terminated': str(terminated)
    })
    return ret_value

@app.route('/env_action', methods=['GET'])
def action():
    action = env.action_space.sample()
    action_word  = action_to_word(action)
    print("Action: ", action_word)
    ret_value = jsonify({
        'action': str(action)
    })
    return ret_value

@app.route('/get-example', methods=['GET'])
def get_request():
    # Your code to handle the "GET" request goes here
    return "This is a GET request response."

if __name__ == '__main__':
    app.run()
```

### System info

- Gymnasium  was installed using pip
- Version of gymnasium 0.28.1
- OS - Windows 10 - build 19045.3570
- Python version: 3.9

### Additional context

I have found several similar issues on Gym but did not find a solution.

[762 Environment working, but not render()](https://github.com/openai/gym/issues/762)

[741 Game window hangs up](https://github.com/openai/gym/issues/741)

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Try using without `render_mode="human"`

**Comment by adielashrov** [comment]
Thank you for your input.
I wish to see the Taxi environment visualization.
When I run with without `render_mode="human"` there is no rendering.

**Comment by pseudo-rnd-thoughts** [comment]
You can either use `render_mode="rgb_array"` then call `env.render()` to get the rendered frame but you will need to show it to the screen. Otherwise, I don't know how you will be able to use it with the window freezing up.
