### ISSUE TITLE
[Bug Report] Incompatible with mujoco 3.0.0

### ISSUE THREAD

**Issue by bennevans** [Farama-Foundation/Gymnasium#749]
### Describe the bug

When using mujoco 3.0.0 and gym version 0.29, human rendering crashes the code with the following error:

> AttributeError: 'mujoco._structs.MjData' object has no attribute 'solver_iter'

It has to do with the change in names described [here](https://github.com/google-deepmind/mujoco/releases/tag/3.0.0)

### Code example

```shell
import gymnasium as gym
env = gym.make("Hopper-v4", render_mode="human")

observation, info = env.reset(seed=42)
for _ in range(1000):
    action = env.action_space.sample()
    observation, reward, terminated, truncated, info = env.step(action)
    env.render()
    if terminated or truncated:
        observation, info = env.reset()
env.close()
```

### System info

Installed via pip version 0.29.1

Distro information
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

Python 3.11

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for reporting this.
@Kallinteris-Andreas or @rodrigodelazcano could you investigate?

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for reporting, a PR has already been opened to fix this, #735

**Comment by Kallinteris-Andreas** [comment]
downgrade to `2.3.*` in the meantime

**Comment by MohammedBadra** [comment]
Changing to solver_niter also works!

**Comment by pseudo-rnd-thoughts** [comment]
This has been solved in #746

**Comment by qlan3** [comment]
I saw a similar error when using Swimmer-v4:

```
>>> import gymnasium as gym
>>> env = gym.make("Swimmer-v4")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/python3.9/site-packages/gymnasium/envs/registration.py", line 802, in make
    env = env_creator(**env_spec_kwargs)
  File "~/python3.9/site-packages/gymnasium/envs/mujoco/swimmer_v4.py", line 170, in __init__
    MujocoEnv.__init__(
  File "~/python3.9/site-packages/gymnasium/envs/mujoco/mujoco_env.py", line 360, in __init__
    super().__init__(
  File "~/python3.9/site-packages/gymnasium/envs/mujoco/mujoco_env.py", line 72, in __init__
    self.model, self.data = self._initialize_simulation()
  File "~/python3.9/site-packages/gymnasium/envs/mujoco/mujoco_env.py", line 380, in _initialize_simulation
    model = mujoco.MjModel.from_xml_path(self.fullpath)
ValueError: XML Error: Schema violation: unrecognized attribute: 'collision'
```

Package versions:

```
gymnasium                0.29.1
mujoco                   3.0.0
mujoco-py                2.1.2.14
```

**Comment by pseudo-rnd-thoughts** [comment]
This was addressed in https://github.com/Farama-Foundation/Gymnasium/pull/746

**Comment by Kallinteris-Andreas** [comment]
@qlan3 
you can `pip install mujoco<3`  or wait for `gymansium==1.0.0`

**Comment by Kallinteris-Andreas** [comment]
@khoikhtn https://github.com/Farama-Foundation/Gymnasium/issues/749#issuecomment-1808355111

**Comment by MatthewGerber** [comment]
> @qlan3 you can `pip install mujoco<3` or wait for `gymansium==1.0.0` or use the git version of `gymnasium`

Thanks for clarifying the issue above! When do you anticipate releasing 1.0.0?

**Comment by pseudo-rnd-thoughts** [comment]
> > @qlan3 you can `pip install mujoco<3` or wait for `gymansium==1.0.0` or use the git version of `gymnasium`
> 
> Thanks for clarifying the issue above! When do you anticipate releasing 1.0.0?

Sorry, we have been wishing to release for a couple of weeks but due to everyone being volunteers and holiday and conference it could be at the end of January is my guess. Though main is very close to the final release most likely

**Comment by MatthewGerber** [comment]
> > > @qlan3 you can `pip install mujoco<3` or wait for `gymansium==1.0.0` or use the git version of `gymnasium`
> > 
> > 
> > Thanks for clarifying the issue above! When do you anticipate releasing 1.0.0?
> 
> Sorry, we have been wishing to release for a couple of weeks but due to everyone being volunteers and holiday and conference it could be at the end of January is my guess. Though main is very close to the final release most likely

No apology needed. I appreciate your help on this project and look forward to the new release. The workaround listed above is working for now.

**Comment by Nourine-Nadir** [comment]
> ### Describe the bug
> When using mujoco 3.0.0 and gym version 0.29, human rendering crashes the code with the following error:
> 
> > AttributeError: 'mujoco._structs.MjData' object has no attribute 'solver_iter'
> 
> It has to do with the change in names described [here](https://github.com/google-deepmind/mujoco/releases/tag/3.0.0)
> 
> ### Code example
> ```shell
> import gymnasium as gym
> env = gym.make("Hopper-v4", render_mode="human")
> 
> observation, info = env.reset(seed=42)
> for _ in range(1000):
>     action = env.action_space.sample()
>     observation, reward, terminated, truncated, info = env.step(action)
>     env.render()
>     if terminated or truncated:
>         observation, info = env.reset()
> env.close()
> ```
> 
> ### System info
> Installed via pip version 0.29.1
> 
> Distro information Distributor ID: Ubuntu Description: Ubuntu 22.04.3 LTS Release: 22.04 Codename: jammy
> 
> Python 3.11
> 
> ### Additional context
> _No response_
> 
> ### Checklist
> * [x]  I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

I tried this and it works,

 pip install mujoco==2.3.5
 then,
pip install gymnasium

This will automatically take care of compatibility. ✅
