### ISSUE TITLE
[Question] Truncated in CartPole-v1

### ISSUE THREAD

**Issue by Gaiejj** [Farama-Foundation/Gymnasium#751]
### Question

Thanks for your great work and it actually helps me a lot. However, when I use ``CartPole-v1``, I find that this environment never truncated. I checked the source and I found that the truncated is always False.
```python
    def step(self, action):
        # CartPole code here
        return np.array(self.state, dtype=np.float32), reward, terminated, False, {}
```
Your documents:
<img width="758" alt="image" src="https://github.com/Farama-Foundation/Gymnasium/assets/108712610/20e999b2-0197-4aaa-bdd2-870815394be5">

I think it is different from your documents and I really want to figure out what's going on. Thanks again for your time and great help !

**Comment by pseudo-rnd-thoughts** [comment]
Truncation is applied in make with the time limit wrapper. If you print the env you will all of the applied wrappers
Have you stripped the wrappers with unwrapped?

**Comment by Gaiejj** [comment]
My bad. Thanks a lot !

**Comment by pseudo-rnd-thoughts** [comment]
No worries, we should update the documentation to make this more clear
