### ISSUE TITLE
[Bug Report] LunarLander observations out of bounds

### ISSUE THREAD

**Issue by younik** [Farama-Foundation/Gymnasium#752]
### Describe the bug

LunarLander observations are not in the observation_space sometimes as they are out of bounds.

### Code example

```python
import gymnasium as gym

env = gym.make('LunarLander-v2')

env.reset()

for _ in range(1000):
    action = env.action_space.sample()
    obs, rew, terminated, truncated, info = env.step(action)
    assert env.observation_space.contains(obs), obs

    if terminated or truncated:
        env.reset()
```

fails with (second element is above 1.5):

```shell
AssertionError: [ 0.07156734  1.5057951   0.6199896   0.2828408  -0.07574554 -0.09089454
  0.          0.        ]
```

### System info

gymnasium 0.29.2

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by linminhtoo** [comment]
hi, how do you deal with this problem currently?

**Comment by younik** [comment]
> hi, how do you deal with this problem currently?

You can remove the assert or clip the observation

**Comment by pseudo-rnd-thoughts** [comment]
We should be able to modify the observation space to increase the second element, but this only happens when the agent moves straight up which isn't good for the policy

**Comment by Kallinteris-Andreas** [comment]
Can't we change that on version 3 since it's not released?

**Comment by pseudo-rnd-thoughts** [comment]
Good point, we can do that but this feels very minor and like it doesn't affect people.

**Comment by Kallinteris-Andreas** [comment]
working on it,
