### ISSUE TITLE
[Question] New gymnasium environment

### ISSUE THREAD

**Issue by bpiwowar** [Farama-Foundation/Gymnasium#753]
### Question

The discord link on https://gymnasium.farama.org/environments/third_party_environments/ is not working anymore.

So how can one report a new environment - I just created

https://github.com/bpiwowar/pystk2-gymnasium

which a SuperTuxKart environment

**Comment by Kallinteris-Andreas** [comment]
what do you mean it not working? the page renders on my browser, you can make a PR to add it to the list

**Comment by bpiwowar** [comment]
Sorry, the link 

```If you'd like to contribute an environment, please reach out on [Discord](https://discord.gg/nHg2JRN489).```

does not work (discord says the link has expired)

**Comment by Kallinteris-Andreas** [comment]
The readme has an invitation link

**Comment by bpiwowar** [comment]
Which readme?

**Comment by Kallinteris-Andreas** [comment]
https://github.com/Farama-Foundation/Gymnasium

**Comment by bpiwowar** [comment]
ah ok thanks; I submitted a pull request, tell me if this is enough (don't have a discord account but I can create one if needed)
