### ISSUE TITLE
[Bug Report] GLFWError when trying to render mujoco-v4 environment in gymnasium

### ISSUE THREAD

**Issue by elated-sawyer** [Farama-Foundation/Gymnasium#755]
### Describe the bug

I'm encountering an issue with the rendering of the "mujoco-v4" environment in gymnasium. For example, when I attempt to run "Humanoid-v4" environment and render it, I receive GLFW-related errors regarding **GLXFBConfigs** and an assertion failure in **glfwGetFramebufferSize**.
```
/home/kkk/.conda/envs/rl_lab/lib/python3.10/site-packages/glfw/__init__.py:916: GLFWError: (65542) b'GLX: No GLXFBConfigs returned'  warnings.warn(message, GLFWError)
/home/kkk/.conda/envs/rl_lab/lib/python3.10/site-packages/glfw/__init__.py:916: GLFWError: (65545) b'GLX: Failed to find a suitable GLXFBConfig'
  warnings.warn(message, GLFWError)
python: /builds/florianrhiem/pyGLFW/glfw-3.3.8/src/window.c:646: glfwGetFramebufferSize: Assertion 'window != ((void *)0)' failed.
Aborted (core dumped)
```

### Code example

```shell
import gymnasium as gym  
env = gym.make("Humanoid-v4", render_mode="human")
obs = env.reset()
env.render()
breakpoint()
```

### System info

Installation method: Installed via pip in a conda environment.
Gymnasium version: 0.29.1
Library Versions:

- glfw: 2.6.2
- gymnasium: 0.29.1
- imageio: 2.31.6
- importlib-resources: 6.1.0
- mujoco: 3.0.0
- PyOpenGL: 3.1.7

### Additional context

I'm unsure if the problem is related to specific versions of the libraries I'm using or some system configuration. Any insights or assistance with this issue would be greatly appreciated.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Hi how was this resolved for this future?

**Comment by elated-sawyer** [comment]
> Hi how was this resolved for this future?

Hi, The solution to this bug seems to be similar to issue #411 . However, I don't have the permissions to install anything on the server directly (I can only operate within a virtual environment), so I can't try further.

**Comment by alubawzk** [comment]
I used "export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6" then the issue can be solved.
