### ISSUE TITLE
[Question] Lunar Lander Trained Simulation Playback

### ISSUE THREAD

**Issue by girishkolli** [Farama-Foundation/Gymnasium#759]
### Question

So on the Gymnasium website, this code snippet is provided:

```
import gymnasium as gym
env = gym.make("LunarLander-v2", render_mode="human")
observation, info = env.reset(seed=42)
for _ in range(1000):
   action = env.action_space.sample()  # this is where you would insert your policy
   observation, reward, terminated, truncated, info = env.step(action)

   if terminated or truncated:
      observation, info = env.reset()

env.close()
```

How do I simulate my trained lander using the code above? I used the Stable Baselines3 library PPO algorithm to train the agent, but I'm not sure how to play the trained simulation. `action = env.action_space.sample()  # this is where you would insert your policy` tells us to insert the policy, but I can't figure out how to.

**Comment by pseudo-rnd-thoughts** [comment]
Hey, this is an SB3 question not a gymnasium question, could you look at their documentation on how to run the policy.
