### ISSUE TITLE
[Bug Report] Incorrect type annotation for Box

### ISSUE THREAD

**Issue by Jammf** [Farama-Foundation/Gymnasium#769]
### Describe the bug

`Box.__init__()`  is currently documented as having the following type annotation:

```python
class Box(...):
    def __init__(
        self,
        low: SupportsFloat | NDArray[Any],
        high: SupportsFloat | NDArray[Any],
        shape: Sequence[int] | None = None,
        dtype: type[np.floating[Any]] | type[np.integer[Any]] = np.float32,
        seed: int | np.random.Generator | None = None,
    ): ...
```

`SupportsFloat` seems to be incorrect here, since the implementation doesn't allow things like `low="5.0"` or custom classes that implement `__float__`. 

I don't have a good replacement annotation handy, but if you're willing to change the implementation to instead support `npt.ArrayLike`, and also willing to import a private type alias from numpy, something like this might work:

```python
from numpy._typing import _ArrayLikeFloat_co 
# Array-like objects that can be coerced into a float ndarray given the casting rules `same_kind`,
# including arrays and scalars of np.bool_, np.integer, np.floating, and their subclasses.

class Box(...):
    def __init__(
        self,
        low: _ArrayLikeFloat_co,
        high: _ArrayLikeFloat_co,
        shape: Sequence[int] | None = None,
        dtype: type[np.floating[Any]] | type[np.integer[Any]] = np.float32,
        seed: int | np.random.Generator | None = None,
    ): 
        low = np.array(low)
        high = np.array(high)
```

### System info

installed in a venv using pip
`gymnasium.__version__ == '0.29.1'`
macOS Ventura 13.5.2
Python 3.11.3 (main, May 24 2023, 14:40:18) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin

### Additional context

`box._broadcast()` and `box.get_precision()` also have `SupportsFloat`. An alternative for those might be `value: _ArrayLikeFloat_co` and `-> int | float`?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
This is a good point, it is more for IDE's doing type checking than anything else. 
The type should be anything that can be passed to `np.array` but we could make the type a bit more tight with `int | float | np.ndarray`

**Comment by Jammf** [comment]
What about accepting things like nested Sequences (like nested lists/tuples), torch Tensors, and jax Arrays? Otherwise, with that annotation (and with the current implementation) it'd only be accepting things that are already numpy arrays? 

In particular, accepting nested lists could also make things a bit cleaner for callers, since they could just write something like `Box(low=[0, 0, 1], high=[9, 9, 7])` rather than having to wrap everything in ndarrays like `Box(low=np.array([0, 0, 1]), high=np.array([9, 9, 7]))`

**Comment by pseudo-rnd-thoughts** [comment]
Looking at the code, we are going to limit the possible accepted low and high values to make it simpler to implement the necessary error checking
