### ISSUE TITLE
Incorrect observation range in Blackjack documentation

### ISSUE THREAD

**Issue by BigOzzie** [Farama-Foundation/Gymnasium#772]
https://github.com/Farama-Foundation/Gymnasium/blob/40f5c7bd425767598b43c1a1fa00acdf2a112f33/gymnasium/envs/toy_text/blackjack.py#L98

The Min/Max range of the "Dealer showing card value" observation is listed as 2 / 11.  Due to Aces showing a value of '1', this range is actually 1 / 10:

```
    | Dealer showing card value |  1   |  10  |
```

**Comment by goekce** [comment]
I can confirm this issue. In the following lines

https://github.com/Farama-Foundation/Gymnasium/blob/9a256e45319c5bb6ce24dff5cac86ffcc805743f/gymnasium/envs/toy_text/blackjack.py#L154-L155

`Discrete(11)`  should be changed to `Discrete(10, start=1)`. 

If a maintainer confirms this, I can create a PR.

**Comment by pseudo-rnd-thoughts** [comment]
@BigOzzie Sorry I forgot to reply to this
Yes, @goekce this is incorrect within the documentation. 

As the possible values sampled from the [desk](https://github.com/Farama-Foundation/Gymnasium/blob/40f5c7bd425767598b43c1a1fa00acdf2a112f33/gymnasium/envs/toy_text/blackjack.py#L16
) is 1-10 then the max range 

I'm a bit confused why the initial lower bound of the player is 4, I looks like it should be 2 to me

**Comment by goekce** [comment]
> I'm a bit confused why the initial lower bound of the player is 4, I looks like it should be 2 to me.

Let us find out the minimum of player's sum:

1. The player begins with at least two cards
1. If you have two aces, you can count them as 2 or 12. To ensure minimal number of states we choose 12, because we have to hit anyway if we count them as 2. We are only interested in observations where we can make a *meaningful* decision against a stochastic process (dealer's uncovered card). Sticking to the sum of 2 would *always* lose — therefore this is not a meaningful decision.
2. If you have one ace and 2, then you can count them as 3 or 13. Like above we choose 13
3. If you have 2 and 2, then we have 4.

I believe this is the rationale behind this limit in `Blackjack-v1`. However I believe the minimum should be 12, I explained this in the [related issue](https://github.com/Farama-Foundation/Gymnasium/issues/803#issuecomment-1832057893).

Maybe we should leave this issue for the dealer's sum and discuss the player's sum in #803 .

**Comment by goekce** [comment]
> Yes, @goekce this is incorrect within the documentation.

You mean we should change to 
```
| Dealer showing card value |  1   |  10  |
```

but leave `Discrete(11)` as is?

**Comment by goekce** [comment]
I was assuming that the player cannot win with a sum of <17, but this is not true, so I updated [my comment above](https://github.com/Farama-Foundation/Gymnasium/issues/772#issuecomment-1832093637).

In summary, I would change the docs to:

```
| Dealer showing card value |  1   |  10  |
```
and change the observation space to `Discrete(11, start=1)`.

@pseudo-rnd-thoughts what do you think?

**Comment by HyeAnn-Lee** [comment]
I want to add one more thing.

Is that the only incorrect information? I think the previous line (Player current sum) also should be changed too,

https://github.com/Farama-Foundation/Gymnasium/blob/40f5c7bd425767598b43c1a1fa00acdf2a112f33/gymnasium/envs/toy_text/blackjack.py#L97

as it can be simply checked by the code below (Gymnasium v0.28.1 , reproducible) .

    import gymnasium as gym
    env = gym.make("Blackjack-v1")
    s1, s2, s3 = set(), set(), set()
    
    for _ in range(10000):
        s, _ = env.reset()
        cur_sum, dealer, ace = s
        s1.add(cur_sum)
        s2.add(dealer)
        s3.add(ace)
 
 This results `s1` to be `{4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21}`. 

I think the line should be changed to 

    | Player current sum        |  4   |  21  |

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for looking at this again

I wrote the following script to check this empirically and the observation space more generally
Therefore, made #893 to fix this 

```python

import gymnasium as gym
import numpy as np

env = gym.make('Blackjack-v1')

# Checking the initial states
initial_states = []
for _ in range(100):
    initial_states.append(env.reset()[0])

initial_states = np.array(initial_states)
print('Possible initial starting values for')
print(f'\tplayer current sum: {np.unique(initial_states[:, 0])}')
print(f'\tdealer showing card value: {np.unique(initial_states[:, 1])}')
print(f'\tusable ace: {np.unique(initial_states[:, 2])}')

# assert observation space
for _ in range(1000):
    obs, _ = env.reset()
    assert obs in env.observation_space, obs
    terminated = False
    while not terminated:
        obs, _, terminated, _, _ = env.step(env.action_space.sample())
        assert obs in env.observation_space, obs
```
