### ISSUE TITLE
How "truncations" of Hopper Env get the True value?

### ISSUE THREAD

**Issue by sxzhuang** [Farama-Foundation/Gymnasium#773]
### Question

I have reviewed the code in the main branch "gymnasium/envs/mujoco/hopper_v4.py" file. I observed that in line 155 of the ```step``` function, the return statement is ```observation, reward, terminated, False, info```. However, during my testing of hopperv4 and after reaching 1000 steps, when I debugged at the line ```next_obs, rewards, terminations, truncations, infos = env.step()```, I noticed that the value of truncations is True. So I am confused about how truncations could acquire the value True?

**Comment by Kallinteris-Andreas** [comment]
it is wrapped by this:
https://gymnasium.farama.org/api/wrappers/misc_wrappers/#gymnasium.wrappers.TimeLimit
in `gymnasium.make()`

**Comment by sxzhuang** [comment]
> it is wrapped by this: https://gymnasium.farama.org/api/wrappers/misc_wrappers/#gymnasium.wrappers.TimeLimit in `gymnasium.make()`

Thanks a lot!!
