### ISSUE TITLE
[Proposal] Please crate a manual and example code for building custom Gymnasium

### ISSUE THREAD

**Issue by dmitryponv** [Farama-Foundation/Gymnasium#777]
### Proposal

The migration guide from 0.21 and 0.26 only has 20 lines of code. There are no examples anywhere on the website for making custom environments and using them with something like stable baselines 3, please provide thorough examples and guides for people to be able to use the new gym with changes

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Kallinteris-Andreas** [comment]
https://gymnasium.farama.org/main/tutorials/gymnasium_basics/environment_creation/

**Comment by pseudo-rnd-thoughts** [comment]
@dmitryponv We will be updated that tutorial and adding a more accessible page for users about this soon
