### ISSUE TITLE
[Proposal] `PlayPlot` is deprecated. The docs should warn this.

### ISSUE THREAD

**Issue by goekce** [Farama-Foundation/Gymnasium#799]
### Proposal

`PlayPlot` is deprecated:

https://github.com/Farama-Foundation/Gymnasium/blob/b09ce1a810e7c086fc61a9cf6b782e6d5dfc40d0/gymnasium/utils/play.py#L343-L344

[The docs](https://gymnasium.farama.org/api/utils/#gymnasium.utils.play.PlayPlot) does not contain a deprecation warning however.

Noting the deprecation of `PlayPlot` in the docs would save new users the time needlessly integrating `PlayPlot` in their code just to see that `PlayPlot` is actually deprecated.

I can create a PR if desired.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Apologies for that, yes, the easiest solution is to remove `PlayPlot` completely, https://github.com/Farama-Foundation/Gymnasium/pull/800
