### ISSUE TITLE
[Question] Can `utils.play.Play` be used for playing `Blackjack`?

### ISSUE THREAD

**Issue by goekce** [Farama-Foundation/Gymnasium#802]
### Question

I would like to use [`utils.play.Play`](https://gymnasium.farama.org/api/utils/#gymnasium.utils.play.play) to play `Blackjack`, however I failed.  `utils.play.Play` does not wait for keypresses and proceed with the next step using the `noop` key (default 0) if the user does not provide any input.

Can `utils.play.Play` be used for playing `Blackjack`? Or: Is `utils.play.Play` primarily implemented for high fps games like `CarRacing`?

If yes, I can happily open an enhancement request to note that in the docs.

**Comment by pseudo-rnd-thoughts** [comment]
I believe you will need to define the `keys_to_action` parameter that specifies keyboard presses to actions in the game

**Comment by goekce** [comment]
@pseudo-rnd-thoughts  you can try this example:

```
import gymnasium as gym
from gymnasium.utils.play import play

env = gym.make("Blackjack-v1", render_mode="rgb_array")
play(
    env,
    keys_to_action={
        "0": 0,
        "1": 1,
    },
    # noop=0, default is `0`
)
env.close()
```

`Play` automatically continues after each step to not interrupt the environment.

**Comment by goekce** [comment]
I don't have the capacity to improve `play` right now. At least a note in the docs could save time for the users.
