### ISSUE TITLE
[Bug Report] Blackjack player sum observation range should be `Discrete(18, start=4)`

### ISSUE THREAD

**Issue by goekce** [Farama-Foundation/Gymnasium#803]
### Describe the bug

Blackjack player sum observation range should be `Discrete(18, start=4)`, which corresponds to the range 4 .. 21 instead of:

https://github.com/Farama-Foundation/Gymnasium/blob/9a256e45319c5bb6ce24dff5cac86ffcc805743f/gymnasium/envs/toy_text/blackjack.py#L154-L155

I use the observation range to test if the agent has experienced every action. However the players sums > 21 are irrelevant, because the game ends anyway. I have to subtract the irrelevant observation numbers manually in my case. Would it not be better avoid irrelevant observations (i.e., player sum>21)?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

Related: https://github.com/Farama-Foundation/Gymnasium/issues/772

**Comment by goekce** [comment]
I believe it may be better to decrease the observation range to the range of `4..21` which corresponds to `Discrete(18, start=4)`. Two arguments that speak for this change:

1. player sums >21 are irrelevant. This information is already encoded in `terminated` flag.
2. the observation value of the dealer card also follows this approach. For example see the following episode:

```
new
(15, 9, 0)
(15, 9, 0) 0 -1.0 True
```
In this game the player loses because the dealer had a higher sum. However dealer's actual value is not provided — what matters is that we lost.

Can someone confirm this?

**Comment by pseudo-rnd-thoughts** [comment]
While you are technically right about the observation space and observations for losing
1. the observation space is not a strict definition (it is not the set of valid observations, it just describes the set of possible observations). 
2. I think it is more helpful for users debugging their code that the sum of cards is `X` rather than `min(X, 21)`

As these are not critical bugs and fixing would require a version change (`Blackjack-v2`), I'm going to close this as I don't view the bugs as required fixing but I'm happy to continue discussing and can reopen if we think they should be fixed

**Comment by goekce** [comment]
Dear Mark, my thoughts on your feedback:

> it just describes the set of possible observations
     
In current setting the observations for the player sum `0, .. ,3` are not possible. So your statement is incorrect. Maybe you wanted to say a *superset of the observations*. Then, however, I would question the advantage of providing the observation space at all, because it gives only a *rough* definition of the values that I can observe. This rough definition   does not help but distract IMHO.

>     it is more helpful for users debugging their code that the sum of cards is X rather than min(X, 21)

I concur. However after seeing that the same behavior does not happen with the dealer's sum, I was confused. This could happen also to other users. Then I would make the observation behavior of player's and dealer's sum consistent.

>  these are not critical bugs and fixing would require a version change

From the pedagogical view, I see this critical — many users will probably start learning RL with this environment. But from the technical/maintenance view you may be right. The middle way could be to collect a significant number of changes for `Blackjack-v2`.

---

After remark related to the player's sum:

This game imitates the example 5.1 from Sutton's RL book. After reading the example, I think the observation range should be even smaller. Excerpt:

> .... If the player holds an ace that he could count as 11 without going bust, then the ace is said to be usable. In this case it is always counted as 11 because counting it as 1 would make the sum 11 or less, in which case there is no decision to be made because, obviously, the player should always hit. Thus, the player makes decisions on the basis of three variables: his current sum (12–21), the dealer’s one showing card (ace–10), and whether or not he holds a usable ace. This makes for a total of 200 states.

If this example should be a followup to Sutton's example, the observation range should be `Discrete(10, start=12), Discrete(10, start=1), Discrete(2)`.
