### ISSUE TITLE
[Bug Report] `make_vec` ignores `EnvSpec.additional_wrappers`

### ISSUE THREAD

**Issue by pseudo-rnd-thoughts** [Farama-Foundation/Gymnasium#814]
### Describe the bug

Currently `make_vec` ignores the `EnvSpec.additional_wrappers` attribute which is complicated with the `make_vec(..., wrappers)` parameter that allows users to specify wrappers to apply to the environment. 

The implement need to consider this for custom and async/sync environments

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Kallinteris-Andreas** [comment]
@pseudo-rnd-thoughts hasn't this been fixed?

**Comment by pseudo-rnd-thoughts** [comment]
I don't believe so, I will try to fix today

**Comment by pseudo-rnd-thoughts** [comment]
For async and sync vector environments, this already works. However, I think it should be disabled for `vector_entry_point` such that vector wrappers should be applied similarly to standard environments

**Comment by pseudo-rnd-thoughts** [comment]
Fixed in #983
