### ISSUE TITLE
[Bug Report] [documentation] The LaTeX math is not rendering properly (`$$`)

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [Farama-Foundation/Gymnasium#820]
### Describe the bug

example:
https://gymnasium.farama.org/main/environments/mujoco/ant/#rewards
![image](https://github.com/Farama-Foundation/Gymnasium/assets/30759571/3d438444-56a3-4001-b3eb-84619e5d1f58)

### Additional context

There was a discord thread about that
https://discord.com/channels/961771112864313344/1007727212042129409/1133757126808969216

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Looking around the Box documentation has properly rendering maths [here](https://gymnasium.farama.org/main/api/spaces/fundamental/#gymnasium.spaces.Box) which uses "math:`equation`" style. 
However if I change the Ant documentation to use this style (regenerated the markdown) then build the website again locally and it doesn't apply mathjax, it is just "math:`equation`". 

I suspect that the difference is that sphinx autocode is adding the maths rendering while the markdown to HTML is not. 

I found this solution https://github.com/readthedocs/recommonmark/issues/133 but it didn't work either

@mgoulao Any ideas?

**Comment by Kallinteris-Andreas** [comment]
Here is a fun fact, I found there are 50+ flavors for Markdown
https://github.com/commonmark/commonmark-spec/wiki/Markdown-Flavors

This appears to work with python markdown:

{math} \`2^2 + 3 = 7\`

**Comment by mgoulao** [comment]
We use MyST as the Markdown parser. I think the problem is now fixed from the sphinx theme side (Celshast), so no need to merge #843 .

**Comment by Kallinteris-Andreas** [comment]
@mgoulao, but it is not working https://gymnasium.farama.org/main/environments/mujoco/ant/#rewards

**Comment by mgoulao** [comment]
I know, we need to wait for the next commit to see if the fix worked

**Comment by pseudo-rnd-thoughts** [comment]
Any update on this?

**Comment by Kallinteris-Andreas** [comment]
Appears to be fixed
https://gymnasium.farama.org/main/environments/mujoco/ant/#rewards

Thanks! @mgoulao
