### ISSUE TITLE
[Bug Report] [`MuJoCo`] Reacher And Pusher reward is calculated prior to transition

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [Farama-Foundation/Gymnasium#821]
### Describe the bug

In a normal RL environment's step:
1. execute the actions (change the state according to the state-action transition model)
2. generate a reward using current state and actions
3. and do other stuff

which is mean that they generate the reward as a function of the current state and current actions

but in `Pusher` & `Reacher`'s step:
```
1. generate a reward using current state and actions
2. execute the actions (change the state according to the state-action transition model)
3. do other stuff
```

which means that they generate the reward as a function of the previous state and current actions

## Learning impact analysis
TODO at some point (will likely do it after 2023)

## proposed solution
as I believe, the current `v5` MuJoCo environment to be done as is, 
and the environments are easily solvable as is anyway,
we should fix this in a future release (v6?) 

### Code example

https://github.com/Farama-Foundation/Gymnasium/blob/14def0759fa094e9a4a6fa0d7b4d66719a11007b/gymnasium/envs/mujoco/reacher_v5.py#L199-L207
lines 199 and 200 are in the opposite order

### Additional context
This has been an issue since `reacher` was introduced in the initial commit.
This issue was first reported in 2018, but never addressed.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Is it possible to change this in v5 before we make the release? 
I can run the code if you need

**Comment by Kallinteris-Andreas** [comment]
Quick analysis:
The agents were trained using the environment mentioned on the legend, but evaluated with fixed environment.

The performance is very similar (though slightly more consistent for the fixed reward case)

![Pusher](https://github.com/Farama-Foundation/Gymnasium/assets/30759571/356025c1-71d6-4be2-9948-99766f488a79)
![Reacher](https://github.com/Farama-Foundation/Gymnasium/assets/30759571/d68f149c-0170-4541-83c2-aa5678db06f0)

**Comment by pseudo-rnd-thoughts** [comment]
Amazing, could you make a PR to change the implementation to this?
