### ISSUE TITLE
render_mode Problem leads to kernel Dead

### ISSUE THREAD

**Issue by AasheeshLikePanner** [Farama-Foundation/Gymnasium#822]
### Describe the bug

When i run the code the pop window and then close, then kernel dead and automatically restart. If i didn't use render_mode then code runs fine. I also tested the code which given on the official website, but the code also not working of official website. I also tried to make the new kernel for Jupiter but still not working.
please help

### Code example

```shell
import gymnasium as gym
enviroment_name = 'CartPole-v1'
env = gym.make(enviroment_name,render_mode="human")
episodes = 5
for episode in range(1, episodes+1):
    state = env.reset()
    done = False
    score = 0 
    
    while not done:
        env.render()
        action = env.action_space.sample()
        n_state, reward, t, done, info = env.step(action)
        score+=reward
    print('Episode:{} Score:{}'.format(episode, score))
env.close()
```

### System info

I installed gymnasium with pip. The python version is 3.11 and I am using linux mint

### Additional context

I think it's all problem of gym if i disable all gym method then it works

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by AasheeshLikePanner** [comment]
So guys i figured it out the problem is jupyter notebook. When i run the same code in pycharm the code runs does anyone have solution for this

**Comment by pseudo-rnd-thoughts** [comment]
I wouldn't run your code with a render mode in jupyter notebook
