### ISSUE TITLE
[Bug Report] Bump Docs Version

### ISSUE THREAD

**Issue by kumikoda** [Farama-Foundation/Gymnasium#828]
### Describe the bug

In the example code for the [blackjack agent on the docs site](https://gymnasium.farama.org/tutorials/training_agents/blackjack_tutorial/#building-an-agent), the variable `epsilon_decay` is undefined, should be `self.epsilon_decay` instead. 
<img width="669" alt="image" src="https://github.com/Farama-Foundation/Gymnasium/assets/1307362/15a01da1-14e0-452e-953b-16fdf1b0398e">

This bug is actually already fixed in the [code for this tutorial](https://github.com/Farama-Foundation/Gymnasium/blob/main/docs/tutorials/training_agents/blackjack_tutorial.py#L240).
<img width="727" alt="image" src="https://github.com/Farama-Foundation/Gymnasium/assets/1307362/7eec37bc-2876-4a93-ad34-c097e257f059">

The `master (unstable)` branch of the docs also has this fixed. So maybe this just needs a docs version bump for fix?
<img width="265" alt="image" src="https://github.com/Farama-Foundation/Gymnasium/assets/1307362/0bd91dfd-43d3-4f28-a064-9ae6c849a7f4">

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for spotting that.
This was  actually fixed in #670
