### ISSUE TITLE
[Question] Does FrameStackObservation work as expected?

### ISSUE THREAD

**Issue by jamartinh** [Farama-Foundation/Gymnasium#829]
This is the current code of the reset function:

https://github.com/Farama-Foundation/Gymnasium/blob/ede2ed1af2146bd9d3a3129418eb929636c78d96/gymnasium/wrappers/stateful_observation.py#L396-L399

Should the code no be like this:
```python

        obs, info = super().reset(seed=seed, options=options)
        for _ in range(self.stack_size):
            self._stacked_obs.append(obs)  # <--- change here!
        
```

**Comment by pseudo-rnd-thoughts** [comment]
Could you create a test that shows an issue

**Comment by jamartinh** [comment]
```python
import numpy as np
import gymnasium as gym

env = gym.make("Hopper-v5")

obs, _ = env.reset()
print("Original env:")
print(np.around(obs,2))


env_stack = gym.wrappers.FrameStackObservation(env,5)
print()
print("Stacked env")
obs_stack, _ = env_stack.reset()
print(np.around(obs_stack,2))

```
```
Original env:
[ 1.25 -0.   -0.   -0.    0.   -0.    0.    0.   -0.   -0.    0.  ]

Stacked env
[[ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 1.25 -0.    0.    0.    0.    0.    0.   -0.   -0.    0.    0.  ]]


```



The output of the stacked env should be the initial observation repeated 5 times but it is filled with zeores.

**Comment by jamartinh** [comment]
Also, this line, IMHO has a mistake as well:
https://github.com/Farama-Foundation/Gymnasium/blob/ede2ed1af2146bd9d3a3129418eb929636c78d96/gymnasium/wrappers/stateful_observation.py#L396

It should be:
```python
obs, info = self.env.reset(seed=seed, options=options)


```

**Comment by jamartinh** [comment]
PR done for this.

**Comment by pseudo-rnd-thoughts** [comment]
> Also, this line, IMHO has a mistake as well:
> 
> https://github.com/Farama-Foundation/Gymnasium/blob/ede2ed1af2146bd9d3a3129418eb929636c78d96/gymnasium/wrappers/stateful_observation.py#L396
> 
> It should be:
> 
> ```python
> obs, info = self.env.reset(seed=seed, options=options)
> ```

If you look at the definition of `Wrapper.reset` then the two lines are equivalent

**Comment by jamartinh** [comment]
Supoose that you specialize the Framestack by inheritance.

Then this will call FrameStack step instead of self.env.step

So, what's the safer solution?

**Comment by pseudo-rnd-thoughts** [comment]
Fair that is a good point, Let update to use `self.env.step`
