### ISSUE TITLE
[Question] Removing deprecation warnings when having multiple "vN" versions of environment

### ISSUE THREAD

**Issue by Mayankm96** [Farama-Foundation/Gymnasium#850]
### Question

Hi, 

I am using the Gymnasium registry for our framework on Isaac Sim. We have many different tasks in there, with different observation and action spaces. Since these are still the same "task", we would like to keep the same environment name but rename the versions of it. Otherwise, this becomes hard to specify through CLI args.

Currently, if I make an environment "MyEnv-v0" and "MyEnv-v1", I get the following deprecation warning to use the"new" version of the environment, which is v1.

Is there a way around this?

**Comment by Kallinteris-Andreas** [comment]
I am not familiar with your library but if you have different editions of your environment then you should have different names, example:
https://robotics.farama.org/envs/shadow_dexterous_hand/
the `-v*` suffix of the name should be used exclusively for versioning

**Comment by Mayankm96** [comment]
Got it. We will see how to simplify the naming on our end then.

The library I'm talking about is this one: https://github.com/NVIDIA-Omniverse/Orbit
