### ISSUE TITLE
[Question] `FuncEnv` why is the `key` not argument for all member functions

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [Farama-Foundation/Gymnasium#851]
### Question

`FuncEnvs`'s
- initial
- transition
do have a `key` argument

but 
- observation
- reward
- terminal
do not have a `key` argument

which could be useful for environments with noisy observation and noisy rewards (while it is less common than initial and transition)

@RedTachyon

**Comment by RogerJL** [comment]
I see no reason for `terminal` to be noisy.

Having `key` in all methods will require generating a new one before **all** calls, and `split` takes time...
My thought was that `param` could be use to pass it for those that are in need, but then I guess `transition`(?) should be able to output a new modified `params`
