### ISSUE TITLE
[Question] Want some help in implementing sampling with masking for Box spaces?

### ISSUE THREAD

**Issue by fracapuano** [Farama-Foundation/Gymnasium#858]
### Question

I am willing to contribute to implementing masking in sampling for `gymnasium.spaces.Box` and was curious if this is something on the roadmap. Also, would very much appreciate any help/advice on how to tackle this.

**Comment by Kallinteris-Andreas** [comment]
No one is currently working on it,
please mention the motivation for adding this feature, and describe how you want it to work

**Comment by RedTachyon** [comment]
There were some discussions in the past about extending the `space.sample()` functionality, either here or back in Gym, but the general conclusion was that this is not something we're planning to add. It's not necessarily a definitive decision, but it would need a very solid argumentation and discussion, so closing this for now, and feel free to reopen/create a new issue if you strongly believe this should be added (and ideally find the old discussions on the topic)

**Comment by pseudo-rnd-thoughts** [comment]
The problem we discussed is that it is not obvious how to mask sampling for a uniform distribution (Box) compared to a discrete distribution of all the other spaces. 
If there an easy to use and efficient masking for uniform sampling then we could consider it
