### ISSUE TITLE
[Bug Report] toy_text/frozen_lake.py - Any size supported? Same length for both sides? Or only 4x4 and 8x8?

### ISSUE THREAD

**Issue by capiman** [Farama-Foundation/Gymnasium#859]
### Describe the bug

I tried to use frozen_lake with a 10x12 field. I seem to not have got an error, but it does not find a way from S to G.
I am missing documentation if only 4x4 and 8x8 is supported or other sizes are supported, and if, if length and width must be equal (only quadratic field?).

### Code example

```shell
import gymnasium

myfield=["SFFF",
         "FHFH",
         "FFFH",
         "HFFG"]

myfieldtest = [ "XXXXXXXXXXXX",
                "X   X     SX",
                "X X   XXXXXX",
                "X XOXOXXXXOX",
                "X   X  O   X",
                "XO  X    X X",
                "X  XX  O XGX",
                "XX X     XXX",
                "XX    OO   X",
                "XXXXXXXXXXXX"]

myfieldtestnew = [ "HHHHHHHHHHHH",
                   "HFFFHFFFFFSH",
                   "HFHFFFHHHHHH",
                   "HFHHHHHHHHHH",
                   "HFFFHFFHFFFH",
                   "HHFFHFFFFHFH",
                   "HFFHHFFHFHGH",
                   "HHFHFFFFFHHH",
                   "HHFFFFHHFFFH",
                   "HHHHHHHHHHHH"]

env = gymnasium.make('FrozenLake-v1', desc=myfieldtestnew)
env.action_space.seed(42)

observation, info = env.reset(seed=42)

for i in range(100000000):
    s = env.action_space.sample()

    observation, reward, terminated, truncated, info = env.step(s)

    print(i)
    print("s " + str(s))
    print("o " + str(observation))
    print("r " + str(reward))
    print(terminated)
    print(truncated)
    print(info)
    print("\n")

    if terminated or truncated:
        observation, info = env.reset()

    # if terminated:
    #     break

env.close()
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Kallinteris-Andreas** [comment]
I am confused, what is your problem? The test provided works fine on my computer,

I can see a problem: the environment is practically impossible if slippery, there is almost 0 margin for slipping and not falling in a hole. 
![image](https://github.com/Farama-Foundation/Gymnasium/assets/30759571/819fcbef-a2f3-4ccc-9f13-c91784d7c81f)

**Comment by capiman** [comment]
Ok, so any size (any length, any width) is supported? At least, with small numbers. This is good! Thanks for the clarification!

Can I just switch of slippery (is_slippery = False) and then it works and find a path?

**Comment by capiman** [comment]
I switched is_slippery off and restarted. It is now running over 25 minutes on a Raspberry Pi 5.
Memory seems to be enough, almost all free.
I am looking for a reward value higher than 0.0.
No solution yet.

**Comment by pseudo-rnd-thoughts** [comment]
As frozen lake is a sparse reward (only rewarded at the end of the episode), this means that it is a difficult to learn the environment
