### ISSUE TITLE
[Proposal]  Addition of a tactical milsim game called Ground Branch

### ISSUE THREAD

**Issue by lucifermorningstar1305** [Farama-Foundation/Gymnasium#864]
### Proposal

# Addition of a tactical milsim game called Ground Branch created by Blackfoot Studios.

Hi, is there a possibility of integrating a tactical milsim game such as Ground Branch into one of the Gymnasium environments? 

About the game: Ground Branch is a military simulation (milsim) tactical game that can be played as a Single player (PvE) and in Multiplayer (PvP) mode. 

### Motivation

We humans are pretty tactical in almost everything. The present environment in the gym/gymnasium includes some tactical gaming environments. Still, the dynamics are limited because an agent trained in such an environment only works in a simple environment. What happens if we train an agent in a severely complex environment such as the one showcased in the Ground Branch Game and see whether it's possible for an agent to devise more tactical policies that are far better than any human?

### Pitch

In an environment like the one showcased in the Ground Branch, an agent has to decide on proper strategies, such as stealth, speed of entry, angle, gravity, etc., before hitting the enemy and earning a reward. 

### Additional context

A demo of the game: [Ground Branch Gameplay - Glid Gaming](https://www.youtube.com/watch?v=Ib3mZerv5NU&list=PLV_dKJif_TsWN1lrrGsKZHy5sr1nyJn6D&index=14)

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Gym and Gymnasium are primarily an API (interface for describing most reinforcement learning environments) therefore, it should be possible for Ground Branch to be incorporated to have a Gymnasium based API to train agents. 
However, this can be more complex when interacting with external software, i.e., games.
