### ISSUE TITLE
[Question] Does the Pong game have speed in its actions?

### ISSUE THREAD

**Issue by gglsmm** [Farama-Foundation/Gymnasium#865]
### Question

The pong game has 6 basic actions. Noop, fire, right, rightfire, left, left fire. My question is do actions that have fire options (such as right fire) speed up the ball? 
According to the AtariAge page, the red button in the actual controller adds some speed. Did you add this feature to the gymnasium?

**Comment by Kallinteris-Andreas** [comment]
https://gymnasium.farama.org/environments/atari/pong/#actions

**Comment by pseudo-rnd-thoughts** [comment]
@gglsmm I would guess so and from playing the environment, I believe so, as all the atari environment is a wrapper over the stella emulator which should run the actual pong ROM so it should play identically to the real thing
