### ISSUE TITLE
[Bug Report] Various rendering issues in 'cartpole.py'

### ISSUE THREAD

**Issue by RogerJL** [Farama-Foundation/Gymnasium#872]
### Describe the bug

1. Accepts any string as 'render_mode' then assumes everything else than 'human' to be "rgb_array"
2. line 512-513: test that 'self.clocks' is None, then sets 'self.clock'...
3. line 525-526: transposes x but does not pick the to the environment corresponding data

### Code example

```shell
__init__


        if self.clocks is None:
            self.clock = [pygame.time.Clock() for _ in range(self.num_envs)]

        for state, screen, clock in zip(self.state, self.screens, self.clocks):
            x = self.state.T
```

### System info

Gymnasium installed from source
version 1.0.0rc1
Windows
Python 3.11

### Additional context

Issues corrected in the HumanVectorRenderingPR4

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Kallinteris-Andreas** [comment]
```py
>>> gymnasium.make("CartPole-v1", render_mode="NON_VALID")
/home/master-andreas/gym/Gymnasium/gymnasium/envs/registration.py:735: UserWarning: WARN: The environment is being initialised with render_mode='NON_VALID' that is not in the possible render_modes (['human', 'rgb_array']).
  logger.warn(
<TimeLimit<OrderEnforcing<PassiveEnvChecker<CartPoleEnv<CartPole-v1>>>>>
>>> gymnasium.make("Ant-v5", render_mode="NON_VALID")
/home/master-andreas/gym/Gymnasium/gymnasium/envs/registration.py:735: UserWarning: WARN: The environment is being initialised with render_mode='NON_VALID' that is not in the possible render_modes (['human', 'rgb_array', 'depth_array']).
  logger.warn(
<TimeLimit<OrderEnforcing<PassiveEnvChecker<AntEnv<Ant-v5>>>>>
```

**Comment by RogerJL** [comment]
OK, fixing

**Comment by RogerJL** [comment]
BTW noticed

registration.py:722
            logger.warn(
                "You are trying to use 'human' rendering for an environment that doesn't natively support it. "
                "The HumanRendering wrapper is being applied to your environment."
            )
Should that really be a warning? Feels like info level to me. Asking for "human", knowing of automatic HumanRendering, getting "human"...

**Comment by Kallinteris-Andreas** [comment]
In the case where the environment does not natively support "human" rendering, it should be made clear to the user in case of bug reports

**Comment by Kallinteris-Andreas** [comment]
Does 2. and 3.  cause any issues?

**Comment by RogerJL** [comment]
Yes, 
2. native vector rendering does not work properly
3. vector mode does not work at all

**Comment by RogerJL** [comment]
@pseudo-rnd-thoughts 
Finally got time to give my commits some time, noticed that the ChartPole and that vector HumanRenderer is also merged.

Note: the ChartPole vector part still contains human renderer (as used in my latest commit).
It should be removed if I understand the discussions here correctly.

**Comment by pseudo-rnd-thoughts** [comment]
@RogerJL Could you clarify where there is a difference in non-vector vs vector CartPole working differently? 
See https://github.com/Farama-Foundation/Gymnasium/blob/596bdcc94d068ad494ff4347612df25c6ebec62c/tests/envs/test_env_implementation.py#L259 for the current testing

Yes, we removed "human" rendering intentionally as it is too complex to maintain for each vector environment individually and would prefer if people used the `wrappers.vector.HumanRendering` instead
