### ISSUE TITLE
[Proposal] Vector environments can not currently be rendered

### ISSUE THREAD

**Issue by RogerJL** [Farama-Foundation/Gymnasium#873]
### Proposal

Add rendering for vector environments

rgb_array:
environment should be able to choose to return a single frame (itself selecting what parallel environment to render) or a list of frames

rgb_array_list:
environment should return a list of list of 'rgb_array' output

### Motivation

I need it for my project!

### Alternatives

Add native rendering in every vector project

### Additional context

HumanVectorRenderingPR5 implements this, related issue #233

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
With `wrappers.vector.HumanRendering`, all vector environments now support human rendering
