### ISSUE TITLE
[Proposal] Use GitHub Issue Forms

### ISSUE THREAD

**Issue by tobirohrer** [Farama-Foundation/Gymnasium#88]
### Proposal 

I propose to use [GitHub Issue Forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) when an issue is created in this repo

### Motivation

This facilitates the proper filling in of information when an issue is created. Information can be marked as required. 

### Alternatives

Stick with the current solution

### Additional context

Creating an issue could look like this (screenshot taken from [stable-baselines3 repo](https://github.com/DLR-RM/stable-baselines3):

<img width="945" alt="image" src="https://user-images.githubusercontent.com/17867382/198526648-296e879b-829a-4da2-8140-16a4065d2f19.png">

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo (**required**)

**Comment by pseudo-rnd-thoughts** [comment]
Yes, this seems like a very helpful feature. 
Would you be able to add it?
