### ISSUE TITLE
[Question] How to see the map of the frozen lake

### ISSUE THREAD

**Issue by VOCdevShy** [Farama-Foundation/Gymnasium#887]
### Question

Hi i try to learn text toy, and most particularly the game Frozen Lake.
My question is: Did someone could help me with the interface of the frozen lake game because actually i do my test of the movement in the void?

Here is my code:
(yes i know that their is a lot of French in it but i don’t think this near to the comprehension of the code for everyone)

```python 
import gymnasium
candy=0
x=0
env = gymnasium.make('FrozenLake-v1', desc=["SFFF", "FHFH", "FFFH", "HFFG"], map_name="4x4",  render_mode="rgb_array" ,  is_slippery=True)
state = env.reset()
while x < 100 :    
    env.render()    
    action_str = input('Entrez une action (0: haut, 1: bas, 2: gauche, 3: droite): ').encode('utf-8').decode('utf-8')
    if action_str.strip() != "":
      action = int(action_str)
    else:
        print("Veuillez entrer une action valide.")    
    next_state, reward, done, truncated, info = env.step(action)    
    state = next_state   
    x = x+1
    if done:
        candy = candy+1
        print("Partie Gagné")
        if x == 100:
          print("Toutes les parties ont été jouées")
          break
env.close() 
```

**Comment by VOCdevShy** [comment]
For a better view of the code i take some screen
![IMG_1444](https://github.com/Farama-Foundation/Gymnasium/assets/143907302/3842b90f-3618-4240-9691-8c93ff8c9487)
![IMG_1445](https://github.com/Farama-Foundation/Gymnasium/assets/143907302/294c0a15-8b45-42af-a607-940131c3b18d)

**Comment by pseudo-rnd-thoughts** [comment]
Use `render_mode="human"` for a pop up screen visualisation of the environment. 
I believe this should work with custom maps but I won't be surprised if it hasn't been tested. 

Otherwise, `render_mode="rgb_array"` will return the visualisation from `env.render()`

**Comment by VOCdevShy** [comment]
It works thank you for your help
