### ISSUE TITLE
new simple wrapper for external environment parameters

### ISSUE THREAD

**Issue by jamartinh** [Farama-Foundation/Gymnasium#90]
Situation: some times there are already done benchmarks using _environments_ in code that you don't want/can modify and you have a replacement new environment {env_name} }that requires some extra parameters for the _make_ function.

A simple (I guess convenient, as I am using it and I am happy) is just to write a .json config file (e.g.  {envname}_config.json or {envname}_params.json)

{envname}_config.json  in the 
```json
{
    "rollout_length": 1000,
    "strategy": "offline",
    "p_action": 0.0
}
```
Such that if your Env is called without arguments it reads it from the .json file.

e.g.
in the __init__ function of the wrapper if exception is raised:
`TypeError: f() missing 3 required positional arguments: 'a', 'b', and 'c'`

The init function of the wrapper reads it from the json

```python
with open(f"{envname}_config.json", "r") as f:
    env_data = json.load(f)

self.env = gym.make(env_name,**env_data)
```
This is just the idea, there should be many ways of implementing it.
I am just using the current path as the location of the {env_name}.json

**Comment by pseudo-rnd-thoughts** [comment]
I don't totally understand what you mean but you can register environments with kwargs 
You could do this with your configurations, i.e.
`gymnasium.register(f"{env_name}-config-v0", kwargs={....})`
This should allow you to `gymnasium.make(f'{env_name}-config-v0') with all of the parameters
