### ISSUE TITLE
[Bug Report] [WEB Documentation] `/tutorials/gymnasium_basics/load_quadruped_model/` does not show in the TOCtree

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [Farama-Foundation/Gymnasium#901]
### Describe the bug

The recently added load_quadruped_model tutorial does appear in the list of tutorials
https://github.com/Farama-Foundation/Gymnasium/blob/main/docs/tutorials/gymnasium_basics/load_quadruped_model.md
https://gymnasium.farama.org/main/tutorials/gymnasium_basics/load_quadruped_model/
![image](https://github.com/Farama-Foundation/Gymnasium/assets/30759571/1d6357ab-2469-45ab-81ed-6c501ddee1b7)

@mgoulao 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by mgoulao** [comment]
In `docs/index.md`, Update the tutorials toctree to:
```
```{toctree}
:hidden:
:glob:
:caption: Tutorials

tutorials/**/index
tutorials/**/*.md
tutorials/third-party-tutorials
Comet Tutorial <https://www.comet.com/docs/v2/integrations/ml-frameworks/gymnasium/?utm_source=gymnasium&utm_medium=partner&utm_campaign=partner_gymnasium_2023&utm_content=docs_gymnasium>
```
