### ISSUE TITLE
[Bug Report] Bug in docs or bug in implementation of HalfCheetah Mujoco Env

### ISSUE THREAD

**Issue by jamartinh** [Farama-Foundation/Gymnasium#906]
### Describe the bug

In the docs page of Cheetah:   (https://gymnasium.farama.org/environments/mujoco/half_cheetah/)

We have:

**excluded | x-coordinate of the front tip | -Inf | Inf | rootx | slide | position (m)**

And:

**8 | x-coordinate of the front tip | -Inf | Inf | rootx | slide | velocity (m/s)**

https://github.com/Farama-Foundation/Gymnasium/blob/b8991ece32048af342bc82324bd94d5f8e3fa901/gymnasium/envs/mujoco/half_cheetah_v5.py#L56-L75

And in the code of the env, we have:

https://github.com/Farama-Foundation/Gymnasium/blob/b8991ece32048af342bc82324bd94d5f8e3fa901/gymnasium/envs/mujoco/half_cheetah_v5.py#L278-L281

And also:

https://github.com/Farama-Foundation/Gymnasium/blob/b8991ece32048af342bc82324bd94d5f8e3fa901/gymnasium/envs/mujoco/half_cheetah_v5.py#L251-L259

Following the Hopper and Walker envs it makes sense to assume that the right excluded *qpos* values is at index 0.

But then the docs are wrong.

Can you please clarify this?

Thanks

### System info

Gymnasium 1.0.0a

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by jamartinh** [comment]
Also, in the xml file:

https://github.com/Farama-Foundation/Gymnasium/blob/b8991ece32048af342bc82324bd94d5f8e3fa901/gymnasium/envs/mujoco/assets/half_cheetah.xml#L3-L24

Hence, it seems that the description in the docs is the problem.

**Comment by Kallinteris-Andreas** [comment]
`qpos[0]` is indeed the position of the `rootx` body part


```py
8 | x-coordinate of the front tip | -Inf | Inf | rootx | slide | velocity (m/s)
```

Should be 
```py
8 | x-coordinate velocity of the front tip | -Inf | Inf | rootx | slide | velocity (m/s)
```


The "velocity" word is missing from the description, this happens in many cases in the MuJoCo environment Documentation

@jamartinh thanks for spotting it out, can you make a PR to fix this?
Thanks!

**Comment by jamartinh** [comment]
PR done
