### ISSUE TITLE
[Question] Problem with the reset method of gymnasium ... again

### ISSUE THREAD

**Issue by PBerit** [Farama-Foundation/Gymnasium#907]
### Question

Hi all,

the reset method of Gynasium is again making problems. So my actual code, which worked for gym (but not for gymansium) looks like this (taken from this tutorial for gym: https://www.youtube.com/watch?v=bD6V3rcr_54):
```
import gymnasium as gym
from gymnasium import Env
from gymnasium.spaces import Discrete, Box, Tuple, MultiDiscrete

import numpy as np
import pandas as pd
import random

from stable_baselines3 import A2C
import stable_baselines3 as sb3


class ShowerEnv (Env):
    def __init__(self):
        #Define action space
        self.action_space = Discrete(3)

        #Define state space: Temperature range of the water temperature
        self.observation_space = Box (low=np.array([0]), high=np.array([100]))

        #Set starting water temperature
        self.state = 38 + random.randint(-1, 1)

        #Set the shower length in number of time slots
        self.shower_length = 60

    def step(self, action):

        #Apply action
        #Action can have the 3 discrete values (0, 1, 2)
        # When action is 0 --> temperature reduced by 1, When action is 1 --> temperature is kept, When action is 2 --> temperature is increased
        self.state = self.state + action - 1

        #Calculate reward
        if self.state >=37 and self.state <=39:
            reward = 1
        else:
            reward = -1

        #Apply random noise to temperature
        self.state = self.state + random.randint(-1,1)

        #Set placeholder for the info
        info = {}


        #Count down time of shower
        self.shower_length = self.shower_length - 1


        #Chec if shower is finished
        terminated = False
        truncuated = False

        if self.shower_length <=0:
            terminated = True
            truncuated =  True

        #Define observation
        observation = self.state



        return observation, reward, terminated, truncuated, info

    def reset(self):

        #Call the super method
        #super().reset(**kwargs)

        self.state = 38
        self.shower_length = 60
        observation = self.state

        return observation

    def render(self):
        pass


#Create the environment
env = ShowerEnv()

'''
#Test the environment and interact with it
terminated = False
state = env.reset()
cumulative_reward = 0
while not terminated:
    action= random.choice([0,1, 2])
    state, reward, terminated, truncuated, info  = env.step(action)
    cumulative_reward = cumulative_reward + reward
    print(f"action: {action}")
    print(f"state: {state}")
    print(f"reward: {reward}")
    print(f"terminated: {terminated}")
    print("")

print(f"cumulative_reward: {cumulative_reward}")
'''

#Define the model
model = A2C('MlpPolicy', env, verbose=1, learning_rate=0.0003,ent_coef=0.01)


# train and save the model
number_of_time_steps = 1000
model.learn(total_timesteps=number_of_time_steps)
model.save('Trained_RL_Models/Shower_Agent')
```
When I run it, the reset method once again causes problems "TypeError: reset() got an unexpected keyword argument 'seed'"

So what I did is to modify the reset method, because I was told to do this here: https://github.com/Farama-Foundation/Gymnasium/issues/899
    def reset(self, **kwargs):
        
        #Call the super method
        super().reset(**kwargs)
        
        self.state = 38
        self.shower_length = 60
        observation = self.state

        return observation

So I added the `, **kwargs` in the defintion of the method and I call the super method `super().reset(**kwargs)`. However, now I get another error: "    obs, self.reset_infos[env_idx] = self.envs[env_idx].reset(seed=self._seeds[env_idx], **maybe_options)
TypeError: cannot unpack non-iterable int object"

There seems to be a basic difference in designing the reset method when you compare gymnasium to gym. In gym I never got any of those error messages regarding the reset method and I honestly don't understand why the design of the reset method seems to introduce additional complexity in gymnasium. Can anyone tell me some general advice about how to design the reset method, especially considering topics like: **kwargs, super method, random number inclusion (altough here there is no random number generator in the reset method).

**Comment by Kallinteris-Andreas** [comment]
`reset()` takes in a `seed argument` with the new API
https://gymnasium.farama.org/main/introduction/migration_guide/
https://gymnasium.farama.org/main/api/env/

**Comment by pseudo-rnd-thoughts** [comment]
```python

import numpy as np

from gymnasium import Env
from gymnasium.spaces import Discrete, Box
from gymnasium.utils.env_checker import check_env


class ShowerEnv(Env):
    def __init__(self):
        # Define action space
        self.action_space = Discrete(3)

        # Define state space: Temperature range of the water temperature
        self.observation_space = Box(low=np.array([0]), high=np.array([100]), dtype=np.int32)

        # Set starting water temperature
        self.state = np.zeros((1,))

        # Set the shower length in number of time slots
        self.shower_length = 60

    def step(self, action):
        # Apply action
        # Action can have the 3 discrete values (0, 1, 2)
        # When action is 0 --> temperature reduced by 1, When action is 1 --> temperature is kept, When action is 2 --> temperature is increased
        self.state = self.state + action - 1

        # Calculate reward
        if 37 <= self.state <= 39:
            reward = 1
        else:
            reward = -1

        # Apply random noise to temperature
        self.state = self.state + self.np_random.integers(-1, 2)

        # Count downtime of shower
        self.shower_length = self.shower_length - 1

        # Check if shower is finished
        truncated = self.shower_length <= 0

        return self.state, reward, False, truncated, {}

    def reset(self, *, seed=None, options=None):
        super().reset(seed=seed, options=options)

        self.state = np.array([38], dtype=np.int32) + self.np_random.integers(-1, 2)
        self.shower_length = 60

        return self.state, {}



check_env(ShowerEnv())
```

**Comment by PBerit** [comment]
@pseudo-rnd-thoughts  and @Kallinteris-Andreas : Thanks a lot for your answers. Actually when using `def reset(self, *, seed=None, options=None):` it works, but I don't understand, why in this case you can't use 
```
    def reset(self, **kwargs):
        # Call the super method
        super().reset(**kwargs)
```
as recommended here: https://github.com/Farama-Foundation/Gymnasium/issues/899

When can I use the first or the second approach for defining the reset() method? Is there even another approach?

**Comment by pseudo-rnd-thoughts** [comment]
Because the problem is actually with the return data, it should be a tuple of the observation and info not just observation

**Comment by PBerit** [comment]
@pseudo-rnd-thoughts : Thanks pseudo for your comment. So when shall I uses `def reset(self, **kwargs):
        # Call the super method
        super().reset(**kwargs)` and when `def reset(self, *, seed=None, options=None)`? Is there also a third option? Or is it always the first or second code that I can use for every custom environment?

**Comment by pseudo-rnd-thoughts** [comment]
Just use the second version

**Comment by Kallinteris-Andreas** [comment]
you must follow the API
`reset(*, seed: int | None = None, options: dict[str, Any] | None = None) → tuple[ObsType, dict[str, Any]]`

**Comment by PBerit** [comment]
@pseudo-rnd-thoughts and @Kallinteris-Andreas : Thanks for your answers and effort, I really appreciate it. But why was the recommendation here https://github.com/Farama-Foundation/Gymnasium/issues/899 to use the first option `def reset(self, **kwargs): # Call the super method super().reset(**kwargs)` and not the second one `def reset(self, *, seed=None, options=None)`? This is what I basically don't understand. When defining the reset method, how shall I approach this?

**Comment by pseudo-rnd-thoughts** [comment]
`**kwargs` and specifying the arguments function very similarly to each other therefore, as your question did not related to the reset function but the random number generator, I did not correct you at the time. 

There are several more bugs / problems in your code, please use my code above that fixes them to my knowledge.

**Comment by pseudo-rnd-thoughts** [comment]
You should always use the second, as the second is a sub-set of the first function so in practice the first will work but sometimes not correctly

**Comment by PBerit** [comment]
Okay, thanks a lot @pseudo-rnd-thoughts for your great help and effort. I really appreciate it.
