### ISSUE TITLE
[Proposal] Clean up the `gym.make` function

### ISSUE THREAD

**Issue by RedTachyon** [Farama-Foundation/Gymnasium#92]
### Proposal

Clean up `registration.py` HumanRendering/RenderCollection automatic wrapping

https://github.com/Farama-Foundation/Gymnasium/blob/6f94a2a0bf46b73f809236a150c5387a439741bc/gymnasium/envs/registration.py#L588-L629

This chunk has 5 levels of if-else indentation, with pretty opaque logic and seems to conflate two wrappers together. I don't have the bandwidth to do it right now, but it desperately needs a cleanup.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
In addition, the env spec has a number of parameters that I don't believed are used by anyone, `reward_range`, etc. 
I think we should slim down a lot of this, the problem is backward compatibility.
