### ISSUE TITLE
[Proposal] Cupy support and performance issue

### ISSUE THREAD

**Issue by tonyhsun** [Farama-Foundation/Gymnasium#942]
### Proposal

Support Cupy as an alternative backend while using vectorized environment.

Give me some insight of the performance discripency comparing with my own VecEnv.

### Motivation

Approximately one year ago, I embarked on developing my own AI framework as a personal side project, focusing on Evolutionary Algorithms. This endeavor required the simultaneous execution of thousands, if not hundreds of thousands, of gym environments. At that time, the capabilities provided by gym/sb3’s VecEnv were not sufficient for my needs. Consequently, I developed a solution akin to what is now recognized as Gymnasium's VectorEnv.

Recently, I migrated my project from gym to gymnasium, driven by curiosity and a desire to explore the advancements made in the library. To my delight, I discovered significant parallels between Gymnasium’s current direction and the solutions I had independently pursued. This revelation excites me for two primary reasons:
- It potentially absolves me of the need to independently develop additional VecEnvs, allowing me to concentrate on refining my model implementations.
- I was doing the right thing! The code looks so closed to yours. (Though I only implemented Cartpole and a few basic ones. Even LunarLander is too completated for me to feel like picking that up, not seeing that in your repo too ^.^)

Besides I'm exited, I got two question:
**1. Performance issue on dry run:**
I just ran some basic example from your get started docs. But I find even running with 100 num_env freeze my desktop.

With my implementation, I can run 200 thousand at FPS about 1. With some number that make sense, for example, 100k, this code block complete in 9 secs.
```
    num_envs = int(1e5)
    s = time.time()
    ac = Multivac(-1)  # -1 for CPU
    env = NdCartPoleV1(num_envs, ac.device)
    obs = env.reset()

    for i in range(int(1e3)):
        action = env.sample_actions()
        obs, rewards, dones, info = env.step(action)
    e = time.time()
    print(f"NdEnv Time: {e - s}")
```
Want to know is this expected? Are you only aming for supporting running like 20 environments instead of thousands? Or I did it incorrectly?

2. Cupy support
Since cupy have very similar with Numpy, I supported it as another backend with not much extra codes. The API looks like:
```
    num_envs = int(1e5)
    s = time.time()
    ac = Multivac(0)  # 0 for cuda:0
    env = NdCartPoleV1(num_envs, ac.device)

```
With this approach, I can run 10 millions of env without a problem. I know it might be an overkill to most of the people. But for EAs, larger population means better biodiversity and much larger search space.

I know the API may looks ugly to you. But it works. And it support multiple devices by simply
 ac = Multivac([0, 1, 2, ...], distribution_strategy="Benchmark")

Do you have plan to support this? Do you mind give me some insight so that I can make a PR for this?

### Pitch

- Insight about my questions.
- Your reason of not plan to implement this or suggestion of API design.
- Any guideline for making a PR.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by tonyhsun** [comment]
It's more like a bug. I followed [Vectorized Environments](https://www.gymlibrary.dev/content/vectorising/). But either ways calls `CartPoleEnv.__init__()` instead of `CartPoleVectorEnv.__init__()`. What's right way to create a vectorized environment backed by Numpy?

**Comment by tonyhsun** [comment]
Update: I just noticed that I should use `gymnasium.experimental.vector.SyncVectorEnv`  instead of `vector.SyncVectorEnv` for Numpy backed environment.

However, performance issue is still noticable with larger number of environments in following experiments:
```
if __name__ == '__main__':
    num_envs = int(1e1)
    print(f"Number of environments: {num_envs}")
    s = time.time()
    envs = SyncVectorEnv([lambda: gym.make('CartPole-v1')] * num_envs)
    envs.reset()

    for i in range(int(1e3)):
        actions = envs.action_space.sample()
        observations, rewards, dones, infos, _ = envs.step(actions)
    e = time.time()
    print(f"Gym Time: {e - s}")

    s = time.time()
    ac = Multivac(-1)  # -1 for CPU, >=0 for GPU, [int] for distributed devices
    env = NdCartPoleV1(num_envs, ac.device)
    obs = env.reset()

    for i in range(int(1e3)):
        action = env.sample_actions()
        obs, rewards, dones, info = env.step(action)
    e = time.time()
    print(f"NdEnv Time: {e - s}")
```
Observations:
```
Number of environments: 100
Gym Time: 0.549628496170044
NdEnv Time: 0.0476222038269043
```
```
Number of environments: 1000
Gym Time: 5.219935417175293
NdEnv Time: 0.08007240295410156
```
```
Number of environments: 10000
Gym Time: 53.72116470336914
NdEnv Time: 0.454970121383667
```
Then I excluded the time of env making, still similar result.

I know I shouldn't put a experiment functionality under such a rigorous testing. But still want to let you know.

**Comment by pseudo-rnd-thoughts** [comment]
Python is the wrong language for high-performance code, therefore, our Sync and Async vector environments will never be optimal.
We have added NumPy only CartPole vector environments in v1.0.0a1 that does have impressive scaling performance

For more general vector performance improvements, I would look at https://github.com/sail-sg/envpool
And for GPU based optimisations, I would look at Jax, see https://github.com/google/brax

**Comment by Kallinteris-Andreas** [comment]
We currently support `numpy` `pytorch` `tensorflow` `jax`, 

 `cupy` is not popular enough for us to support it

but there is nothing stopping you from making an environment using `cupy`

**Comment by tonyhsun** [comment]
> Python is the wrong language for high-performance code, therefore, our Sync and Async vector environments will never be optimal. We have added NumPy only CartPole vector environments in v1.0.0a1 that does have impressive scaling performance
> 
> For more general vector performance improvements, I would look at https://github.com/sail-sg/envpool written in C++ And for GPU based optimisations, see https://github.com/google/brax as an example written using Jax

Thank you for replying. I was referring to the experimental.vector package instead of vector. All the performance testings were on that basis.
`from gymnasium.experimental.vector import SyncVectorEnv, AsyncVectorEnv`

**Comment by pseudo-rnd-thoughts** [comment]
Closing as there is no plan for gymnasium to support cupy, those another repo could do this and the performance issues are not an issue with gymnasium itself, rather the limits of python vectorisation it is believed
