### ISSUE TITLE
spaces.Dict.contains can't return expected results

### ISSUE THREAD

**Issue by hyjocean** [Farama-Foundation/Gymnasium#949]
hello, I'm confused about the `spaces.Dict.contains` in the file of line as follow,
https://github.com/Farama-Foundation/Gymnasium/blob/876e6a267aa180db4457a2f3fa54fabc64728fcf/gymnasium/spaces/dict.py#L176

from my intuition, I feel the function of `spaces.Dict.contains` is detect whether the input array `x` is valid. so I think maybe there should be
`return all(self.spaces[key].contains(x[key) for key in self.spaces.keys())`?

I'm not sure, if I misunderstand, could you tell me how to comprehend the origin code `x[key] in self.spaces[key]`? I'm confused about it.

**Comment by pseudo-rnd-thoughts** [comment]
In the `Space.py`, the `__contains__` function was override such that `x in space` is equivalent to `space.contains(x)` so don't worry, you suggest is equivalent to the current code (though less clear admittly)
