### ISSUE TITLE
[Proposal] Randomize LunarLander wind generation at reset to gain statistical independence between episodes

### ISSUE THREAD

**Issue by TobiasKallehauge** [Farama-Foundation/Gymnasium#954]
### Proposal

In `gymnasium/envs/box2d/lunar_lander.py`, randomly draw a new `wind_idx` and `torque_idx` when the environment is reset through `reset()`. The cleanest fix would be to move the lines
```
        self.wind_idx = np.random.randint(-9999, 9999)
        self.torque_idx = np.random.randint(-9999, 9999)
```
From the `__init__()` method to the `reset()` method. This would ensure that the environment is statistically independent between episodes, which it is currently not. I believe it is important to have statistical independence between episodes since researchers are expecting this behavior, e.g., for Monte Carlo simulation.

### Motivation

When simulating the lunar lander environment with wind enabled, it seems that the variables `wind_idx` and `torque_idx`, which are only drawn randomly in the `__init__()` call, greatly affect the environment. Though the variables continuously increase with every step after initialization, some initial choices generally create an easier environment than others. I encountered this problem when evaluating landing/crashing performances for a trained reinforcement learning policy. In one example, I got the following statistics from 5000 episodes:
```
Landing rate: 81.62% +- 1.80%
Crash rate: 10.54% +- 1.43%
```
Where the `+-` indicates a 99.99% confidence interval. Now, in another example (where the environment was initialized again), the following statistics were obtained:
```
Landing rate 94.84% +- 1.03%
Crash rate 2.02% +- 0.65%
```
The only plausible explanation for this behavior is that **each episode is not statistically independent**. I tested changing the code to draw independent `wind_idx` and `torque_idx` each time the environment is reset (as described in the proposal), and **now I get the same landing and crash rate for every simulation**. My best explanation for this behavior is the fact that randomly drawing `wind_idx` and `torque_idx` permanently affects the phase offsets of the wind and torque variables `wind_mag` and `torque_mag`, which may or may not align favorably with the average length of each episode. 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
I believe your right, could you make a PR with the changes to review and the performance differences you observe?

**Comment by pseudo-rnd-thoughts** [comment]
I believe by default the wind is turned off as the result shouldn't be possible as the wind power uses `np.random` not `self.np_random`

**Comment by Kallinteris-Andreas** [comment]
using `enable_wind=True` does indeed fail the tests
```py
import gymnasium
from gymnasium.utils.env_match import check_environments_match

env_a = gymnasium.make("LunarLander-v2", enable_wind=True)
env_b = gymnasium.make("LunarLander-v2", enable_wind=True)

check_environments_match(env_a, env_b, num_steps=int(1e5))
```

**Comment by TobiasKallehauge** [comment]
Thanks, @pseudo-rnd-thoughts. I will make the pull request. @Kallinteris-Andreas, it's a bit more complicated than simple deterministic / non-deterministic behavior. It is a fact that when you initialize the environment, there are two `wind_idx` and `torque_idx` that are drawn **upon initialization** but not upon reset. These variables affect the wind, so essentially, the wind in the next episode is a continuation of the wind in the former episode. I am not sure why it has so much of an effect - but for sure, there is some dependency between episodes.
