### ISSUE TITLE
 error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

### ISSUE THREAD

**Issue by brucecui1998** [Farama-Foundation/Gymnasium#96]
### Question

Please help me look at this problem. It has been bothering me for several days.when I run the code "pip install gym_super_mario_bros==7.3.0 nes_py",I got this:

 error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

 I've tried all the solutions on stackoverflow. I have installed the build tools and Visual Studio. I even tried reboot my computer and upgrade pip.But it doesn"t work.

**Comment by RedTachyon** [comment]
Hi, we don't maintain neither `gym_super_mario_bros`, nor `nes_py`, nor do we fully support Windows. I recommend trying to get help from the maintainers of one of those libraries if solutions found online don't work.
