### ISSUE TITLE
[Bug Report] Quaternion order incorrect in Ant environment observation

### ISSUE THREAD

**Issue by ghost** [Farama-Foundation/Gymnasium#971]
### Describe the bug

In the documentation for the Ant environment, it is claimed that the quaternion representation of the torso orientation is returned in the (x, y, z, w) order. Upon inspection of a trajectory of the ant and comparing these values with the true behavior visually, it seems to me that the actual order is (w, x, y, z). These values seem to come directly from the `qpos` variable in Mujoco. I couldn't find any proper documentation of this variable, but the site https://mujoco.readthedocs.io/en/stable/overview.html states "For ball joints, the quaternion saved in mjModel.qpos0 is always (1,0,0,0) which corresponds to the null rotation", which corresponds to the (w, x, y, z) order.

This error might also persist in the documentations of other environments.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Kallinteris-Andreas** [comment]
Hello, I have tested it and it appears to be correct in the documentation.

qpos[0] Is the x coordinate
qpos[1] is the y coordinate

**Comment by onnoeberhardtest** [comment]
Thanks for the reply. `qpos[0:3]` indeed describe the x-, y- and z-position, respectively. I was talking about the orientation of the torso, which is described by the quaternion `qpos[3:7]`. Here, it seems that the first element (`qpos[3]`) is the real part (w), followed by the x, y, and z orientations. The documentation however states that the order of these elements is (x, y, z, w).

**Comment by onnoeberhard** [comment]
Commenting because I switched account (I opened this issue).

**Comment by Kallinteris-Andreas** [comment]
Hey, @onnoeberhard sorry for taking a while to respond, I had to study how Quaternions work :-)

all material on quaternions I could find denote them as $a + bi + cj + dk$ (and therefore the values are `a, b, c, d`), it is not clear to me how these map to `x, y, z, w` rotation

**Comment by onnoeberhard** [comment]
This is just a different convention, the real part is $w$, so that the quaternion is $w + xi + yj + zk$. See also the following paragraph from the MuJoCo documentation: https://mujoco.readthedocs.io/en/2.2.1/programming.html#:~:text=To%20represent%203D,quaternions%20in%20MJCF.

**Comment by Kallinteris-Andreas** [comment]
Here is the relevant documentation page in the latest version of MuJoCo Library (3.1.3) https://mujoco.readthedocs.io/en/3.1.3/programming/simulation.html#data-layout-and-buffer-allocation
you are correct, the order is `(w, x, y, z)`

The affected environment's documentation is 
`Ant`, `Humanoid` `HumanoidStandup`
besides the "Observation Space" section, the "Starting State" section also need to be updated

@onnoeberhard do you want to make a PR to fix this issue? Thanks!
