### ISSUE TITLE
[Bug Report] save_video crashes for `mujoco-py`

### ISSUE THREAD

**Issue by modanesh** [Farama-Foundation/Gymnasium#972]
### Describe the bug

I have installed the gymnasium for mujoco and everything works fine. Although it works fine for other envs like classical control, however, as soon as I call the `save_video` function for a mujoco environment, my ubuntu machine crashes. My screen goes blank and i have to uninstall nvidia drivers, reboot (to get display), and install drivers again (to have nvidia-smi) to make everything back to the original configuration. the code i use is taken from #882 .

### Code example

```shell
import gymnasium as gym
from gymnasium.utils.save_video import save_video

terminated = False
truncated = False

reward_eps = 0.0

env = gym.make('Ant-v3', render_mode='rgb_array_list')
env.reset()

while not (terminated or truncated):
    action = env.action_space.sample()
    observation, reward, terminated, truncated, info = env.step(action)

    reward_eps += reward

save_video(env.render(), "videos",
           fps=env.metadata['render_fps'],
           step_starting_index=0,
           episode_index=0)

env.close()
```

### System info

gymnasium==0.28.1 was installed with pip
ubuntu 20.04
python 3.9

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Kallinteris-Andreas** [comment]
Does this also happen for ant-v4?

**Comment by Kallinteris-Andreas** [comment]
rgb_array_list is not a valid render mode `rgb_array`

**Comment by pseudo-rnd-thoughts** [comment]
@Kallinteris-Andreas `rgb_array_list` is a valid render mode, as `make` will add an intermediate wrapper that saves `rgb_array` such that `render` returns a list of frames

**Comment by modanesh** [comment]
@pseudo-rnd-thoughts So there shouldn't be such crashes?

**Comment by Kallinteris-Andreas** [comment]
Of course it shouldn't be crashing, The fact that your Nvidia drivers are being corrupted

**Comment by pseudo-rnd-thoughts** [comment]
@modanesh Is this issue only using the `save_video` function or `VideoRecord` wrapper? 
If you sample the environment without a render mode are there any issues? 

This feels much more likely to be a strange mujoco bug than a Gymnasium issue.
What version of mujoco are you using?

**Comment by modanesh** [comment]
@Kallinteris-Andreas How can I check if Nvidia drivers are corrupted? These are the outputs I get for the corresponding commands:
```bash
mohamad@mohamad:~$ nvidia-smi
Wed Mar 20 08:07:22 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4070        Off | 00000000:01:00.0 Off |                  N/A |
| 31%   30C    P0              27W / 200W |      1MiB / 12282MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```
and:
```bash
mohamad@mohamad:~$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0

```

Also, with Ant v4 it works fine. The crash only happens when I use other than v4 envs (like v3 which I need)

**Comment by modanesh** [comment]
@pseudo-rnd-thoughts For mujoco version, I have the following: `mujoco_py 2.1.2.14` and `mujoco 3.0.1`.

Without the `render_mode`, if I use `v4`, I get this error: `AttributeError: Unexpected mode: None, expected modes: human, rgb_array, or depth_array` at line: `save_video(env.render(), "videos", ...`. And if I use `v3` I get this: `TypeError: 'NoneType' object is not subscriptable` at the same line.

**Comment by Kallinteris-Andreas** [comment]
Can you post whatever message you're getting With the code example from the opening post.

**Comment by modanesh** [comment]
The code I use is the one I posted above. The full errors are as following. 

With `v3`:
```sh
ERROR: Expected a list of frames, got a <class 'NoneType'> instead.
Traceback (most recent call last):
  File "/home/mohamad/Research/Safe-Robotics/TBD/offline_rl/tmp.py", line 18, in <module>
    save_video(env.render(), "videos",
  File "/home/mohamad/Research/Safe-Robotics/Gymnasium/gymnasium/utils/save_video.py", line 96, in save_video
    clip = ImageSequenceClip(frames[:video_length], **kwargs)
TypeError: 'NoneType' object is not subscriptable
```

With `v4`:
```sh
Traceback (most recent call last):
  File "/home/mohamad/Research/Safe-Robotics/TBD/offline_rl/tmp.py", line 18, in <module>
    save_video(env.render(), "videos",
  File "/home/mohamad/Research/Safe-Robotics/Gymnasium/gymnasium/core.py", line 418, in render
    return self.env.render()
  File "/home/mohamad/Research/Safe-Robotics/Gymnasium/gymnasium/wrappers/order_enforcing.py", line 70, in render
    return self.env.render(*args, **kwargs)
  File "/home/mohamad/Research/Safe-Robotics/Gymnasium/gymnasium/wrappers/env_checker.py", line 63, in render
    return env_render_passive_checker(self.env, *args, **kwargs)
  File "/home/mohamad/Research/Safe-Robotics/Gymnasium/gymnasium/utils/passive_env_checker.py", line 391, in env_render_passive_checker
    result = env.render()
  File "/home/mohamad/Research/Safe-Robotics/Gymnasium/gymnasium/envs/mujoco/mujoco_env.py", line 379, in render
    return self.mujoco_renderer.render(
  File "/home/mohamad/Research/Safe-Robotics/Gymnasium/gymnasium/envs/mujoco/mujoco_rendering.py", line 646, in render
    viewer = self._get_viewer(render_mode=render_mode)
  File "/home/mohamad/Research/Safe-Robotics/Gymnasium/gymnasium/envs/mujoco/mujoco_rendering.py", line 688, in _get_viewer
    raise AttributeError(
AttributeError: Unexpected mode: None, expected modes: human, rgb_array, or depth_array
```

**Comment by pseudo-rnd-thoughts** [comment]
Why are you are not using the video recorder wrapper?

**Comment by modanesh** [comment]
Same happens. Only when I uninstall the Nvidia driver (`sudo /usr/bin/nvidia-uninstall`) it works fine. For the record, the Nvidia driver's version is 535.

Also, to add, the environment variable in `bashrc` contains this line: `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/mohamad/.mujoco/mujoco210/bin`. When I changed it to this: `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/mohamad/.mujoco/mujoco-3.0.1/bin` I got the error mentioning that I need to have the environment variable pointing to `mujoco210`.

**Comment by modanesh** [comment]
Code I used for the video recorder wrapper:

```python
import gymnasium as gym

env = gym.make("HalfCheetah-v3", render_mode="rgb_array_list")

env = gym.wrappers.RecordVideo(env, 'videos')

env.reset()
for t in range(200):
    action = env.action_space.sample()
    observation, reward, _, _, info = env.step(action)

env.close()
```

**Comment by Kallinteris-Andreas** [comment]
Does calling `env.render()` without `RecordVideo` or anything similar give the expected result?

**Comment by modanesh** [comment]
Yes, `env.render()` works fine with no issues.

**Comment by pseudo-rnd-thoughts** [comment]
Is there an issue recording an video for `CartPole-v1`? 
There might be an issue with ffmpeg, if there isn't an issue with recording a cartpole environment then I'm confused again

**Comment by modanesh** [comment]
Both `save_video` and `RecordVideo` wrapper work fine with `CartPole-v1`. Super confusing!
For now, I decided to switch to `v4` as this one doesn't require `mujoco_py` and video recording works fine with that.

**Comment by Kallinteris-Andreas** [comment]
The code example in the OP works on my computer

**Comment by pseudo-rnd-thoughts** [comment]
@modanesh That is probably the best plan as mujoco is a maintained project while mujoco-py (v2 and v3) is not
