### ISSUE TITLE
I use mac to install environment issues

### ISSUE THREAD

**Issue by ChengJunJunJun** [Farama-Foundation/Gymnasium#987]
### Question

<img width="564" alt="image" src="https://github.com/Farama-Foundation/Gymnasium/assets/127819698/2f4a5466-7e5f-4ef2-9406-016053efd08d">
Why can't it ever fit

**Comment by Kallinteris-Andreas** [comment]
`pip installed "gymnasium[...]"`

There's a bug with `zsh`

**Comment by pseudo-rnd-thoughts** [comment]
Yeah, on mac you need to use quotemarks around python options
