### ISSUE TITLE
Installation library problems

### ISSUE THREAD

**Issue by ChengJunJunJun** [Farama-Foundation/Gymnasium#988]
### Question

<img width="825" alt="image" src="https://github.com/Farama-Foundation/Gymnasium/assets/127819698/28618628-9a31-4201-bb3a-1899b62847e6">
I use the command "`pip install gymnasium[box2d]`",I kept getting errors after that；

**Comment by pseudo-rnd-thoughts** [comment]
You need to install swig, either with python or as a separate executable

**Comment by ChengJunJunJun** [comment]
you should use ` pip install "gymnasium[all]"` if with zsh

**Comment by ChengJunJunJun** [comment]
<img width="383" alt="image" src="https://github.com/Farama-Foundation/Gymnasium/assets/127819698/f9436a34-cd3b-43c2-b63b-9953fd984b7d">

**Comment by David-Lemon** [comment]
Thanks for the update. I successfully installed [all]. But it seems that "[box2d-py]" is again problematic when trying to run the example code in documentation.
`pip install "gymnasium[box2d]"`

> Requirement already satisfied: gymnasium[box2d] in [/Users/chongchong/Desktop/](https://file+.vscode-resource.vscode-cdn.net/Users/chongchong/Desktop/)学习/大三/大三下/Reinforcement Learning/.venv/lib/python3.10/site-packages (0.29.1)
> Requirement already satisfied: numpy>=1.21.0 in [/Users/chongchong/Desktop/](https://file+.vscode-resource.vscode-cdn.net/Users/chongchong/Desktop/)学习/大三/大三下/Reinforcement Learning/.venv/lib/python3.10/site-packages (from gymnasium[box2d]) (1.26.4)
> Requirement already satisfied: cloudpickle>=1.2.0 in [/Users/chongchong/Desktop/](https://file+.vscode-resource.vscode-cdn.net/Users/chongchong/Desktop/)学习/大三/大三下/Reinforcement Learning/.venv/lib/python3.10/site-packages (from gymnasium[box2d]) (3.0.0)
> Requirement already satisfied: typing-extensions>=4.3.0 in [/Users/chongchong/Desktop/](https://file+.vscode-resource.vscode-cdn.net/Users/chongchong/Desktop/)学习/大三/大三下/Reinforcement Learning/.venv/lib/python3.10/site-packages (from gymnasium[box2d]) (4.10.0)
> Requirement already satisfied: farama-notifications>=0.0.1 in [/Users/chongchong/Desktop/](https://file+.vscode-resource.vscode-cdn.net/Users/chongchong/Desktop/)学习/大三/大三下/Reinforcement Learning/.venv/lib/python3.10/site-packages (from gymnasium[box2d]) (0.0.4)
> Collecting box2d-py==2.3.5 (from gymnasium[box2d])
>   Using cached box2d-py-2.3.5.tar.gz (374 kB)
>   Installing build dependencies ...   Getting requirements to build wheel ...   Installing backend dependencies ...   Preparing metadata (pyproject.toml) ... Requirement already satisfied: pygame>=2.1.3 in [/Users/chongchong/Desktop/](https://file+.vscode-resource.vscode-cdn.net/Users/chongchong/Desktop/)学习/大三/大三下/Reinforcement Learning/.venv/lib/python3.10/site-packages (from gymnasium[box2d]) (2.5.2)
> Requirement already satisfied: swig==4.* in [/Users/chongchong/Desktop/](https://file+.vscode-resource.vscode-cdn.net/Users/chongchong/Desktop/)学习/大三/大三下/Reinforcement Learning/.venv/lib/python3.10/site-packages (from gymnasium[box2d]) (4.2.1)
> Building wheels for collected packages: box2d-py
>   Building wheel for box2d-py (pyproject.toml) ... error: subprocess-exited-with-error
>   
>   × Building wheel for box2d-py (pyproject.toml) did not run successfully.
>   │ exit code: 1
>   ╰─> [20 lines of output]
>       Using setuptools (version 69.2.0).
>       running bdist_wheel
>       running build
>       running build_py
>       creating build
>       creating build/lib.macosx-10.9-universal2-cpython-310
>       creating build/lib.macosx-10.9-universal2-cpython-310/Box2D
>       copying library/Box2D/Box2D.py -> build/lib.macosx-10.9-universal2-cpython-310/Box2D
>       copying library/Box2D/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/Box2D
>       creating build/lib.macosx-10.9-universal2-cpython-310/Box2D/b2
>       copying library/Box2D/b2/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/Box2D/b2
>       running build_ext
>       building 'Box2D._Box2D' extension
>       swigging Box2D/Box2D.i to Box2D/Box2D_wrap.cpp
>       swig -python -c++ -IBox2D -small -O -includeall -ignoremissing -w201 -globals b2Globals -outdir library/Box2D -keyword -w511 -D_SWIG_KWARGS -o Box2D/Box2D_wrap.cpp Box2D/Box2D.i
>       Traceback (most recent call last):
>         File "/Users/chongchong/Desktop/学习/大三/大三下/Reinforcement Learning/.venv/bin/swig", line 7, in <module>
>           from swig import swig
>       ModuleNotFoundError: No module named 'swig'
>       error: command '/Users/chongchong/Desktop/学习/大三/大三下/Reinforcement Learning/.venv/bin/swig' failed with exit code 1
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for box2d-py
> Failed to build box2d-py
> ERROR: Could not build wheels for box2d-py, which is required to install pyproject.toml-based projects
> Note: you may need to restart the kernel to use updated packages.

**Comment by David-Lemon** [comment]
When I tried installing "gymnasium[box2d]", it is problematic again:

> Requirement already satisfied: gymnasium[box2d] in [/Users/chongchong/Desktop/](https://file+.vscode-resource.vscode-cdn.net/Users/chongchong/Desktop/)学习/大三/大三下/Reinforcement Learning/.venv/lib/python3.10/site-packages (0.29.1)
> Requirement already satisfied: numpy>=1.21.0 in [/Users/chongchong/Desktop/](https://file+.vscode-resource.vscode-cdn.net/Users/chongchong/Desktop/)学习/大三/大三下/Reinforcement Learning/.venv/lib/python3.10/site-packages (from gymnasium[box2d]) (1.26.4)
> Requirement already satisfied: cloudpickle>=1.2.0 in [/Users/chongchong/Desktop/](https://file+.vscode-resource.vscode-cdn.net/Users/chongchong/Desktop/)学习/大三/大三下/Reinforcement Learning/.venv/lib/python3.10/site-packages (from gymnasium[box2d]) (3.0.0)
> Requirement already satisfied: typing-extensions>=4.3.0 in [/Users/chongchong/Desktop/](https://file+.vscode-resource.vscode-cdn.net/Users/chongchong/Desktop/)学习/大三/大三下/Reinforcement Learning/.venv/lib/python3.10/site-packages (from gymnasium[box2d]) (4.10.0)
> Requirement already satisfied: farama-notifications>=0.0.1 in [/Users/chongchong/Desktop/](https://file+.vscode-resource.vscode-cdn.net/Users/chongchong/Desktop/)学习/大三/大三下/Reinforcement Learning/.venv/lib/python3.10/site-packages (from gymnasium[box2d]) (0.0.4)
> Collecting box2d-py==2.3.5 (from gymnasium[box2d])
>   Using cached box2d-py-2.3.5.tar.gz (374 kB)
>   Installing build dependencies ...   Getting requirements to build wheel ...   Installing backend dependencies ...   Preparing metadata (pyproject.toml) ... Requirement already satisfied: pygame>=2.1.3 in [/Users/chongchong/Desktop/](https://file+.vscode-resource.vscode-cdn.net/Users/chongchong/Desktop/)学习/大三/大三下/Reinforcement Learning/.venv/lib/python3.10/site-packages (from gymnasium[box2d]) (2.5.2)
> Requirement already satisfied: swig==4.* in [/Users/chongchong/Desktop/](https://file+.vscode-resource.vscode-cdn.net/Users/chongchong/Desktop/)学习/大三/大三下/Reinforcement Learning/.venv/lib/python3.10/site-packages (from gymnasium[box2d]) (4.2.1)
> Building wheels for collected packages: box2d-py
>   Building wheel for box2d-py (pyproject.toml) ... error: subprocess-exited-with-error
>   
>   × Building wheel for box2d-py (pyproject.toml) did not run successfully.
>   │ exit code: 1
>   ╰─> [20 lines of output]
>       Using setuptools (version 69.2.0).
>       running bdist_wheel
>       running build
>       running build_py
>       creating build
>       creating build/lib.macosx-10.9-universal2-cpython-310
>       creating build/lib.macosx-10.9-universal2-cpython-310/Box2D
>       copying library/Box2D/Box2D.py -> build/lib.macosx-10.9-universal2-cpython-310/Box2D
>       copying library/Box2D/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/Box2D
>       creating build/lib.macosx-10.9-universal2-cpython-310/Box2D/b2
>       copying library/Box2D/b2/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/Box2D/b2
>       running build_ext
>       building 'Box2D._Box2D' extension
>       swigging Box2D/Box2D.i to Box2D/Box2D_wrap.cpp
>       swig -python -c++ -IBox2D -small -O -includeall -ignoremissing -w201 -globals b2Globals -outdir library/Box2D -keyword -w511 -D_SWIG_KWARGS -o Box2D/Box2D_wrap.cpp Box2D/Box2D.i
>       Traceback (most recent call last):
>         File "/Users/chongchong/Desktop/学习/大三/大三下/Reinforcement Learning/.venv/bin/swig", line 7, in <module>
>           from swig import swig
>       ModuleNotFoundError: No module named 'swig'
>       error: command '/Users/chongchong/Desktop/学习/大三/大三下/Reinforcement Learning/.venv/bin/swig' failed with exit code 1
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for box2d-py
> Failed to build box2d-py
> ERROR: Could not build wheels for box2d-py, which is required to install pyproject.toml-based projects
> Note: you may need to restart the kernel to use updated packages.

Looked like I have installed swig, but I didn't.

**Comment by pseudo-rnd-thoughts** [comment]
Jupyter notebooks, I believe you will need to restart the kernel to get swig working. Otherwise, I would just download swig as a normal executable
