### ISSUE TITLE
RecordVideo not recording any videos anymore in 0.26.x

### ISSUE THREAD

**Issue by SebastianHurubaru** [Farama-Foundation/Gymnasium#99]
### Describe the bug

Hello,

since the change in 0.26.0 of the render_mode flag, the gym.wrappers.RecordVideo does not work anymore.

When recording the video we are getting the following log message:
```
.../lib/python3.8/site-packages/gym/wrappers/monitoring/video_recorder.py:59: UserWarning: WARN: Disabling video recorder because environment <OrderEnforcing<PassiveEnvChecker<AtariEnv<ALE/Pong-v5>>>> was not initialized with any compatible video mode between rgb_array and rgb_array_list
```

We are setting the render_mode when creating the environment, as showed in the [blog](https://younis.dev/blog/render-api/) for the 0.26.0 release, but the render_mode flag no longer gets set, leading to the warning and videos not being recorded.

Here is a code sample that can help with the issue replication:

### Code example

```python
import gym

env = gym.make("ALE/Pong-v5", render_mode="rgb_array")

env = gym.wrappers.RecordVideo(
  env,
  video_folder='video',
  step_trigger=lambda x: x % 100 == 0
)

env.reset()
for t in range(100):
  action = env.action_space.sample()
  observation, reward, terminated, truncated, info = env.step(action)

env.close()
```

### System info

Gym 0.26.2, Python 3.8.10.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by SebastianHurubaru** [comment]
After further investigation, this seems to be an issue with the ALE, where in the AtariEnv, the `self.render_mode` is set to None, as the class uses another variable `self._render_mode` instead. Should this be addressed in the ALE repo?

**Comment by pseudo-rnd-thoughts** [comment]
Yes, I think ALE store the `render_mode` in `self._render_mode` as atari made the change before gym.
Could you make an issue on the ALE-py repo
In the meantime, I would set the render_mode after, `env.render_mode = "rgb_array"`

**Comment by SebastianHurubaru** [comment]
Thanks @pseudo-rnd-thoughts ! Reported the issue there. 

Unfortunately the workaround you suggested does not work, as `render_mode` is a read-only property for the gym  wrappers, which are used to wrap the `AtariEnv` object.

**Comment by pseudo-rnd-thoughts** [comment]
Ahh, what about `env.unwrapped.render_mode = "rgb_array"`?

**Comment by SebastianHurubaru** [comment]
Thanks @pseudo-rnd-thoughts, that indeed worked! Closing this issue!
