### ISSUE TITLE
[Proposal] Add a new extra named "except-mujoco-py"

### ISSUE THREAD

**Issue by evan0greenup** [Farama-Foundation/Gymnasium#991]
### Proposal

Related to previous proposal: <https://github.com/Farama-Foundation/Gymnasium/issues/921>. When user want `cython>=3.0.0` but also an almost full features of `gymnasium` .

Provide a new extra named `except-mujoco-py` would make user a lot easier than manually include all the feature except for `mujoco-py`.

### Motivation

`mujoco-py` is a legacy and deprecated stuff. All newly created project will rarely need it. Adding a new extra option `except-mujoco-py` would save user a lot of time from manually include every extra option except for `mujoco-py`.

### Pitch

`pip install gymnasium[except-mujoco-py]` will install every extra dependencies except `mujoco-py` (which required `cython < 3`).
 

### Alternatives

An alternative would remove the support of `mujoco-py` support. 

### Additional context

- <https://github.com/Farama-Foundation/Gymnasium/issues/921>

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Kallinteris-Andreas** [comment]
It will likely be removed at some point.

For now You can just not use `gymnasium[all]` And only use the ones you need

**Comment by pseudo-rnd-thoughts** [comment]
I don't think this is a good idea and as @Kallinteris-Andreas notes, we will more likely remove it from the repo in the future. 

In the meantime, I would recommend just doing `pip install "gymnasium[atari, accept-rom-license, ...]"` for all the options you want
