### ISSUE TITLE
[Question] Custom dtype in observation space

### ISSUE THREAD

**Issue by dicksimon** [Farama-Foundation/Gymnasium#992]
### How to make use of custom data types in observation spaces?

Hey there I am quite new to Reinforcement Learning.

I defined a custom numpy data type like this: 
`dtype_page = np.dtype([
    ('in_use', np.bool_)])`

I want to use a box space with this custom type to define my observation space:
`self.observation_space = spaces.Dict({
'pages': spaces.Box(low=0, high=1, shape=(57,), dtype=dtype_page),
...
})`

However, when I run my environment the following errors occur

>   File "/../.venv/lib/python3.11/site-packages/gymnasium/envs/registration.py", line 802, in make
    env = env_creator(**env_spec_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/../gym_yos/envs/yos_env.py", line 75, in __init__
    'pages': spaces.Box(low=0, high=1, shape=(57,), dtype=dtype_page),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/../.venv/lib/python3.11/site-packages/gymnasium/spaces/box.py", line 125, in __init__
    if np.any(low > high):
              ^^^^^^^^^^
numpy.core._exceptions._UFuncNoLoopError: ufunc 'greater' did not contain a loop with signature matching types (<class 'numpy.dtypes.VoidDType'>, <class 'numpy.dtypes.VoidDType'>) -> None
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/../gym_yos/env_handler.py", line 10, in <module>
    env = gym.make('YOS-v0');
          ^^^^^^^^^^^^^^^^^^
  File "/../.venv/lib/python3.11/site-packages/gymnasium/envs/registration.py", line 814, in make
    raise type(e)(
          ^^^^^^^^
TypeError: _UFuncNoLoopError.__init__() missing 1 required positional argument: 'dtypes'

Can I use custom data types like this or am I missing something other essential? Any hint is highly appreciated.

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for the question, I'm a bit confused by your dtype. 
Why do you need a custom dtype when it is just a boolean? 
If so, you should be able to use `MultiBinary` or Box with integer dtype and low=0 and upper=1 without the need for a custom dtype

**Comment by dicksimon** [comment]
> Why do you need a custom dtype when it is just a boolean?

I reduced my example to minimize the complexity. The custom dtype I want to use is more complex.
I need an array of a data structure that contains a few booleans and some integers. 
Is this possible at all?

As far as I understand alternatively I could use nested dicts like this 
```
        Dict(  
            {
                "data_structure_1": Dict(
                {
                    "in_use": Discrete(4),
                    "number": Discrete(2)
                }),
                "data_structure_2": Dict({
                    "in_use":...,
                    "number": Discrete(4)
                }),
                .......
                "data_structure_n": Dict({
                    "in_use": Discrete(2),
                    "number": Discrete(4)
                })
            }
        )
```
But that does not feel like the ideal solution due to its verbosity.

**Comment by Kallinteris-Andreas** [comment]
Yes nested Dictionaries is the proper solution, it is a standard implementation that training algorithms understand

**Comment by pseudo-rnd-thoughts** [comment]
As you have a fix number of data structures, it would probably be more optimal to do have a `MultiDiscrete` for all of the numbers (`MultiDiscrete([4, 4, ..., ])`) and a `MultiBinary` for all the in use (`MultiBinary((N,))`)

**Comment by dicksimon** [comment]
> As you have a fix number of data structures, it would probably be more optimal to do have a `MultiDiscrete` for all of the numbers (`MultiDiscrete([4, 4, ..., ])`) and a `MultiBinary` for all the in use (`MultiBinary((N,))`)

Thank you guys for guiding me through this. Your help is highly appreciated.

So, your recommendation is to transform my n data structures (57 at all)

```
"data_structure_n": Dict({
    "exists": Discrete(2),
    "pid": Discrete(57),
    "unstarve_time": Discrete(5),
    "starvation_level": Discrete(6),
    "in_use": Discrete(2),
    "waiting_for_page": Discrete(2),
    "has_ended": Discrete(2),
    "pages": Dict({
        "page_0": Dict({
            "exists": Discrete(2),
            "in_use": Discrete(2),
            "in_swap": Discrete(2) 
        }),
        "page_1": Dict({
            "exists": Discrete(2),
            "in_use": Discrete(2),
            "in_swap": Discrete(2) 
        }),
        "page_2": Dict({
            "exists": Discrete(2),
            "in_use": Discrete(2),
            "in_swap": Discrete(2) 
        }),
        "page_3": Dict({
            "exists": Discrete(2),
            "in_use": Discrete(2),
            "in_swap": Discrete(2) 
        })
    })
})
```
to one merged structure like this?

```
"data_structure_all_in_one": Dict({
    "exists": MultiBinary(57,),
    "unstarve_time": Multi_Discrete(5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5),
    "starvation_level": Multi_Discrete(6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6),
    "in_use": Multi_Binary(57,),
    "waiting_for_page": Multi_Binary(57,),
    "has_ended": Multi_Binary(57,),
    "pages": Dict({
        "page_0": Dict({
            "exists": Multi_Binary(57,),
            "in_use": Multi_Binary(57,),
            "in_swap": Multi_Binary(57,) 
        }),
        "page_1": Dict({
            "exists": Multi_Binary(57,),
            "in_use": Multi_Binary(57,),
            "in_swap": Multi_Binary(57,) 
        }),
        "page_2": Dict({
            "exists": Multi_Binary(57,),
            "in_use": Multi_Binary(57,),
            "in_swap": Multi_Binary(57,) 
        }),
        "page_3": Dict({
            "exists": Multi_Binary(57,),
            "in_use": Multi_Binary(57,),
            "in_swap": Multi_Binary(57,) 
        })
    })
})
```

Note: The key "pid" from n_data_structure was supposed to distinguish between the data structures, so there is no need for this in the merged one

**Comment by pseudo-rnd-thoughts** [comment]
You can merge the pages info into a single space again. 

```
"data_structure_all_in_one": Dict({
    "exists": MultiBinary(57,),
    "unstarve_time": MultiDiscrete([5 for _ in range(57)]),
    "starvation_level": MultiDiscrete([6 for _ in range(57)]),
    "in_use": MultiBinary(57,),
    "waiting_for_page": MultiBinary(57,),
    "has_ended": MultiBinary(57,),
    "pages": Dict({
        "exists": MultiBinary([57, 57, 57]),
        "in_use": MultiBinary([57, 57, 57]),
        "in_swap": MultiBinary([57, 57, 57]) 
    })
})
```

It is not so much that it is "wrong" the way you were doing it, this just compresses the data more effectively, limiting the number of dictionaries required
