### ISSUE TITLE
[Proposal] Uniform API for Getting the Current State (and maybe setting it as well?) for Environments

### ISSUE THREAD

**Issue by Delta-Sigma** [Farama-Foundation/Gymnasium#995]
### Proposal

Uniform API for all environments for something like `.get_state()` and `.set_state(state)` or maybe `.get_last_obs()` or something like an Env instance attribute: `Env.state`

### Motivation

All environments compute the state already and return it when you do reset or step. Getting the current state can be very neat e.g. when you want to have a wrapper to an environment that does something non-standard in some specific states e.g. only one tile in FrozenLake is slippery.

Sorry if this has been addressed already, I tried searching to the best of my ability whether this was already proposed or not.

And then, in the future, setting a state can also be very useful?

### Alternatives

Alternatives that I can think of would not be so neat e.g. the wrapper is passed the last state every time some special needs to be taken, and user's code keeps track of last observation/state etc.

Another alternative would be that people needing such functionality modify the code of the environments themselves, which again I think is not so neat and requires needless diving into the internal workings of environments.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Kallinteris-Andreas** [comment]
see https://github.com/Farama-Foundation/Gymnasium/issues/842, this will be worked on after 1.0 release

**Comment by Delta-Sigma** [comment]
Thank you for your reply.

Just to be clear I am also interested in getting the last/current observation, not just the state e.g. in cases when internal state and observations are not the same and/or do not contain the same information.

Looking forward to 1.0

**Comment by Kallinteris-Andreas** [comment]
Observation is already returned by step()
